Repository cloudflare/workers-sdk, pull requests merged in 2022-05, with the labels that each got.

#891 Interactive pages publish prompts
  .changeset/ten-rules-destroy.md
  packages/wrangler/src/__tests__/config-cache.test.ts
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/config-cache.ts
  packages/wrangler/src/dialogs.tsx
  packages/wrangler/src/pages.tsx
  packages/wrangler/src/user.tsx
Labels: pages

#852 non-TTY required variables checks
  .changeset/eighty-yaks-jump.md
  packages/wrangler/src/__tests__/helpers/mock-istty.ts
  packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/__tests__/whoami.test.tsx
  packages/wrangler/src/index.tsx
  packages/wrangler/src/pages.tsx
  packages/wrangler/src/reporting.ts
  packages/wrangler/src/user.tsx
Labels: polish

#904 Add 'assets:' loader for Pages Functions
  .changeset/olive-oranges-bathe.md
  examples/pages-functions-app/.gitignore
  examples/pages-functions-app/functions/static/_middleware.ts
  examples/pages-functions-app/static-assets/index.html
  examples/pages-functions-app/tests/index.test.ts
  examples/pages-plugin-example/functions/static.ts
  examples/pages-plugin-example/package.json
  examples/pages-plugin-example/public/index.html
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/pages/functions/buildPlugin.ts
  packages/wrangler/pages/functions/buildWorker.ts
  packages/wrangler/src/pages.tsx
Labels: enhancement, pages

#934 Suppress beta warning when operating in Pages' CI environment
  .changeset/weak-mangos-admire.md
  packages/wrangler/src/pages.tsx
Labels: pages, polish

#930 Default to creating new project when no existing available for 'wrangler pages publish'
  .changeset/stupid-wombats-know.md
  packages/wrangler/src/pages.tsx
Labels: pages, polish

#947 Fix 'pages publish' defaults
  .changeset/chatty-wolves-bathe.md
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages.tsx
Labels: bug, pages, polish

#957 refactor: Moving `--legacy-env` out of global
  .changeset/hungry-bugs-marry.md
  package-lock.json
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/index.tsx
Labels: cleanup

#977 chore: setup the workflows to cache
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/experimental-wasm-release.yml
  .github/workflows/prereleases.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
Labels: type: maintenance

#1032 Windows caching fix in GH Workflows
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/prereleases.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
Labels: bug

#1044 fix: secret input trailing spaces
  .changeset/grumpy-dolphins-explain.md
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/index.tsx
Labels: bug

#1093 Pages Functions Tests
  examples/pages-functions-app/tests/index.test.ts
Labels: maintenance

#1051 feat: implement proxy support
  .changeset/calm-oranges-walk.md
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/src/index.tsx
Labels: blocked

#1028 Use new bulk upload API for 'pages publish'
  .changeset/unlucky-rocks-obey.md
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/pages.tsx
Labels: pages

#1139 chore: add issue triage docs
  .vscode/settings.json
  ISSUE_TRIAGE.md
Labels: documentation, discussion

#1157 fix: Ignore .git dir during pages publish
  .changeset/empty-news-jog.md
  packages/wrangler/src/pages.tsx
Labels: pages
