Repository cloudflare/workers-sdk, pull requests merged in 2022-06, with the labels that each got.

#1210 Deltas for 'wrangler pages publish'
  .changeset/clean-jokes-travel.md
  packages/wrangler/src/pages.tsx
Labels: enhancement, pages

#1272 feat: Bundle Reporter
  .changeset/breezy-scissors-tie.md
  packages/wrangler/src/__tests__/helpers/mock-console.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/bundle-reporter.tsx
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/publish.ts
Labels: enhancement

#1311 feat: text decoder
  .changeset/hungry-wombats-fail.md
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/index.tsx
Labels: enhancement

#1327 feat: working directory pathing
  .changeset/large-lizards-enjoy.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/sites.tsx
Labels: enhancement

#1325 fix: Ensure Response is mutable in Pages functions
  .changeset/dull-bottles-teach.md
  packages/wrangler/templates/pages-template-worker.ts
Labels: pages

#1335 feat: resolve cli arg relative to current working directory
  .changeset/lemon-olives-sip.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/sites.tsx
Labels: enhancement, polish

#1337 polish: bundle reporter was not printing during publish errors
  .changeset/forty-doors-argue.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/publish.ts
Labels: polish

#1278 throw error if config is specified in pages
  .changeset/rotten-radios-wink.md
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages/dev.tsx
  packages/wrangler/src/pages/publish.tsx
Labels: pages

#1353 Updating `actions/checkout`
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/experimental-wasm-release.yml
  .github/workflows/prereleases.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
Labels: maintenance

#1274 loading .dev.vars support for pages
  .changeset/wise-pens-shake.md
  fixtures/pages-functions-app/.dev.vars
  fixtures/pages-functions-app/tests/index.test.ts
  packages/wrangler/src/pages/dev.tsx
Labels: pages

#1354 README badges
  packages/wrangler/README.md
Labels: documentation, discussion

#1359 Removed comment artifact from previous updates
  packages/wrangler/src/config/validation.ts
Labels: maintenance

#1297 feat: implement `config.define`
  .changeset/swift-bobcats-joke.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/bundle.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/preview.tsx
  packages/wrangler/src/publish.ts
Labels: enhancement

#1363 fix: email from env & error messaging
  .changeset/small-needles-wash.md
  packages/wrangler/src/__tests__/whoami.test.tsx
  packages/wrangler/src/whoami.tsx
Labels: bug
