Repository cloudflare/workers-sdk, pull requests merged in 2022-07, with the labels that each got.

#1375 polish: Compliance with the XDG Base Directory Specification
  .changeset/old-timers-smash.md
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
  packages/wrangler/src/__tests__/https-options.test.ts
  packages/wrangler/src/__tests__/jest.setup.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/global-wrangler-config-path.ts
  packages/wrangler/src/https-options.ts
  packages/wrangler/src/user/user.tsx
Labels: polish

#1541 chore: test coverage
  .github/workflows/pullrequests.yml
  fixtures/local-mode-tests/package.json
  fixtures/node-app-pages/package.json
  fixtures/pages-functions-app/package.json
  fixtures/remix-pages-app/package.json
  package.json
  packages/wrangler/package.json
Labels: maintenance

#1542 chore: CodeCov Main branch context
  .github/workflows/codecov-context.yml
Labels: maintenance

#1553 chore: CodeCov non-blocking
  codecov.yml
Labels: maintenance

#1564 chore: Documentation Links in README.md
  .changeset/quick-monkeys-exercise.md
  packages/wrangler/README.md
Labels: documentation, maintenance

#1569 chore: fix patch block CI
  codecov.yml
Labels: maintenance

#1575 feat: legacy kv-namespace not supported
  .changeset/green-queens-fry.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
Labels: maintenance, polish

#1574 fix: Retry check-missing call to make wrangler pages publish more reliable
  .changeset/soft-seahorses-cough.md
  packages/wrangler/src/pages/constants.ts
  packages/wrangler/src/pages/upload.tsx
Labels: pages

#1552 fix: Invalid regular expression error
  .changeset/fifty-schools-check.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/module-collection.ts
Labels: pages
