Repository cloudflare/workers-sdk, pull requests merged in 2022-10, with the labels that each got.

#1965 chore: remove hidden on --from-dash
  .changeset/wet-deers-bow.md
  packages/wrangler/src/init.ts
Labels: maintenance, blocked

#1978 chore: Undici 5.11.0 multipart/form-data support
  .changeset/yellow-boats-join.md
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/src/cfetch/internal.ts
Labels: maintenance

#1986 Explicit MSW usage
  packages/wrangler/src/__tests__/helpers/msw/handlers/index.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/namespaces.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/oauth.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/user.ts
  packages/wrangler/src/__tests__/helpers/msw/index.ts
  packages/wrangler/src/__tests__/jest.setup.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/whoami.test.tsx
  packages/wrangler/src/__tests__/worker-namespace.test.ts
Labels: maintenance

#2074 Generate DTS `wrangler-overrides.d.ts` from config
  .changeset/long-buttons-retire.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/entry.ts
  packages/wrangler/src/index.tsx
  packages/wrangler/src/type-generation.ts
Labels: enhancement

#2088 chore: remove empty code block
  packages/wrangler/README.md
Labels: documentation
