Repository cloudflare/workers-sdk, pull requests merged in 2022-02, with the labels that each got.

#279 Adhoc NPM Release GitHub Action
  .github/workflows/create-pullrequest-prerelease.yml
  .gitignore
  .prettierignore
  package-lock.json
  package.json
  packages/prerelease-registry/functions/runs/[[path]].ts
  packages/prerelease-registry/package.json
  packages/prerelease-registry/tsconfig.json
  packages/prerelease-registry/wrangler.toml
  packages/wrangler/package.json
  packages/wrangler/tsconfig.json
  tsconfig.json
Labels: maintenance

#402 polish: Added Wrangler TOML fields
  .changeset/silly-students-add.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/index.tsx
Labels: polish

#403 polish: `package.json` tweaks
  .changeset/orange-hats-yell.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/index.tsx
Labels: polish

#227 Sentry Integration
  .changeset/sixty-dragons-grab.md
  .github/sourcemap-url.js
  .github/workflows/release.yml
  package-lock.json
  package.json
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/jest.setup.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/cli.ts
  packages/wrangler/src/index.tsx
  packages/wrangler/src/reporting.ts
Labels: enhancement

#438 feat: Add support for "json" bindings
  .changeset/green-carrots-scream.md
  .vscode/settings.json
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/api/form_data.ts
  packages/wrangler/src/api/worker.ts
  packages/wrangler/src/config.ts
  packages/wrangler/src/index.tsx
Labels: feature

#442 chore: remove trailing whitespace from snapshot tests
  .vscode/settings.json
  packages/wrangler/src/__tests__/helpers/mock-console.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/user.tsx
Labels: maintenance

#448 add `--yes` flag to `wrangler init`
  .changeset/olive-maps-promise.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/index.tsx
Labels: polish

#472 Fix: TypeError localWebsocket.destroy is not a function
  .changeset/few-cherries-compare.md
  packages/wrangler/src/proxy.ts
Labels: bug

#504 PR Aliases for Prerelease Registry
  .github/workflows/write-prerelease-comment.yml
  packages/prerelease-registry/functions/routes/prs/[[path]].ts
  packages/prerelease-registry/functions/routes/runs/[[path]].ts
  packages/prerelease-registry/functions/utils/getArtifactForWorkflowRun.ts
  packages/prerelease-registry/functions/utils/gitHubFetch.ts
  packages/prerelease-registry/package.json
Labels: cleanup

#419 refactor: use esbuild's message formatting for cleaner error messages
  .changeset/poor-beers-deny.md
  packages/wrangler/src/__tests__/parse.test.ts
  packages/wrangler/src/cfetch/index.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/index.tsx
  packages/wrangler/src/parse.ts
Labels: polish
