Repository cloudflare/workers-sdk, pull requests merged in 2022-09, with the labels that each got.

#1789 fix: getMonth compatibility date
  .changeset/rude-seas-impress.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/publish.ts
Labels: bug

#1781 feat: Publish Origin Messaging
  .changeset/tender-pianos-kick.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/dialogs.tsx
  packages/wrangler/src/init.ts
  packages/wrangler/src/publish.ts
Labels: enhancement

#1790 chore: add npmrc to webpack-plugin
  packages/wranglerjs-compat-webpack-plugin/.npmrc
Labels: maintenance

#1694 feat: don't require command when proxy port provided
  .changeset/sixty-pigs-camp.md
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages/dev.tsx
Labels: pages

#1799 feat: Bulk Secret Upload
  .changeset/forty-phones-punch.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/index.tsx
Labels: enhancement

#1768 Mock Service Worker Conversion - Initial Setup
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/index.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/namespaces.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/oauth.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/user.ts
  packages/wrangler/src/__tests__/helpers/msw/index.ts
  packages/wrangler/src/__tests__/jest.setup.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/whoami.test.tsx
Labels: maintenance

#1827 fix: Publish error when no upstream Worker existed
  .changeset/cyan-cherries-stare.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/publish.ts
Labels: bug

#1865 polish: loglevel flag
  .changeset/gorgeous-moose-whisper.md
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/pages/dev.tsx
Labels: polish

#1898 chore: convert namespaces tests to MSW
  packages/wrangler/src/__tests__/worker-namespace.test.ts
Labels: maintenance

#1937 fix: fails to publish due to empty migrations
  .changeset/blue-pots-thank.md
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/init.ts
Labels: bug

#1964 chore: Emoji space in help description
  .changeset/strange-clouds-judge.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/index.tsx
Labels: maintenance
