Repository cloudflare/workers-sdk, pull requests merged in 2022-11, with the labels that each got.

#2111 Add a `passThroughOnException()` handler to Pages Functions
  .changeset/dirty-gifts-breathe.md
  fixtures/pages-functions-app/functions/passThroughOnException/_middleware.ts
  fixtures/pages-functions-app/functions/passThroughOnException/nested.ts
  fixtures/pages-functions-app/functions/passThroughOnExceptionClosed.ts
  fixtures/pages-functions-app/functions/passThroughOnExceptionOpen.ts
  fixtures/pages-functions-app/functions/passThroughOnExceptionWithCapture/_middleware.ts
  fixtures/pages-functions-app/functions/passThroughOnExceptionWithCapture/nested.ts
  fixtures/pages-functions-app/tests/index.test.ts
  packages/wrangler/templates/pages-template-plugin.ts
  packages/wrangler/templates/pages-template-worker.ts
Labels: pages

#1417 fix(upload): add helper to check for expired JWT
  packages/wrangler/src/pages/upload.tsx
Labels: pages

#2124 fix: `--from-dash` `vars` incorrect fields
  .changeset/tidy-lobsters-agree.md
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/init.ts
Labels: bug

#2127 Fix: Missing Worker name using `--from-dash`
  .changeset/large-dingos-try.md
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/init.ts
Labels: bug

#2119 chore: Update naming conventions
  packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
  packages/wrangler/src/index.tsx
Labels: maintenance

#2096 new metadata binding type
  .changeset/rich-bears-press.md
  packages/wrangler/src/__tests__/api-dev.test.ts
  packages/wrangler/src/__tests__/api-devregistry.test.js
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/create-worker-upload-form.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/publish/publish.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/worker.ts
Labels: enhancement

#2156 Revert "new metadata binding type"
  .changeset/rich-bears-press.md
  packages/wrangler/src/__tests__/api-devregistry.test.js
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/create-worker-upload-form.ts
  packages/wrangler/src/deployments.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/publish/publish.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/worker.ts
Labels: maintenance, discussion, internal

#2165 [Fix] `vars` string type
  .changeset/yellow-files-argue.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/type-generation.ts
Labels: bug

#2178 Queues Type Generation
  .changeset/honest-countries-swim.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/index.tsx
  packages/wrangler/src/type-generation.ts
Labels: enhancement

#2077 feat: Tails for Pages
  .changeset/pink-lies-dress.md
  packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/metrics/send-event.ts
  packages/wrangler/src/pages/build.tsx
  packages/wrangler/src/pages/deployment-tails.tsx
  packages/wrangler/src/pages/deployments.tsx
  packages/wrangler/src/pages/dev.tsx
  packages/wrangler/src/pages/functions.tsx
  packages/wrangler/src/pages/index.tsx
  packages/wrangler/src/pages/prompt-select-project.tsx
  packages/wrangler/src/pages/publish.tsx
  packages/wrangler/src/pages/types.ts
  packages/wrangler/src/pages/upload.tsx
  packages/wrangler/src/pages/utils.ts
  packages/wrangler/src/tail/createTail.ts
  packages/wrangler/src/yargs-types.ts
Labels: pages

#2204 fix: Upload filepath-routing configuration in wrangler pages publish
  .changeset/wicked-rules-run.md
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages/publish.tsx
Labels: pages

#2210 Miniflare options transform rename
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/start-server.ts
Labels: maintenance, quick win

#2209 XDG compliant metrics directory
  .changeset/brown-beers-cheat.md
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/metrics/metrics-config.ts
Labels: maintenance, bug

#2224 Dependency libc++
  CONTRIBUTING.md
Labels: documentation

#2259 chore: split migration commands into their own modules
  packages/wrangler/src/d1/migrations.tsx
  packages/wrangler/src/d1/migrations/apply.tsx
  packages/wrangler/src/d1/migrations/create.tsx
  packages/wrangler/src/d1/migrations/helpers.ts
  packages/wrangler/src/d1/migrations/index.tsx
  packages/wrangler/src/d1/migrations/list.tsx
Labels: d1

#2239 Convert `user.test.ts` to MSW
  packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/oauth.ts
  packages/wrangler/src/__tests__/logout.test.ts
  packages/wrangler/src/__tests__/user.test.ts
Labels: maintenance, polish
