Repository cloudflare/workers-sdk, pull requests merged in 2022-04, with the labels that each got.

#732 Abort signalling
  .changeset/wet-tables-pretend.md
  packages/wrangler/src/create-worker-preview.ts
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/inspect.ts
  packages/wrangler/src/proxy.ts
Labels: bug

#757 feat: Add wrangler pages project list
  .changeset/lucky-paws-report.md
  package-lock.json
  package.json
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/index.tsx
  packages/wrangler/src/pages.tsx
  packages/wrangler/src/user.tsx
Labels: pages

#758 feat: Add wrangler pages deployment list
  .changeset/thin-paws-dance.md
  package-lock.json
  package.json
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages.tsx
Labels: pages

#769 Inconsistent mock types `fetchKVGetValue`
  packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
Labels: maintenance

#763 update check
  .changeset/hungry-carrots-run.md
  package-lock.json
  packages/wrangler/package.json
  packages/wrangler/src/index.tsx
  packages/wrangler/src/update-check.ts
Labels: polish

#768 refactor to `parseTOML`
  packages/wrangler/src/index.tsx
  packages/wrangler/src/parse.ts
  packages/wrangler/src/reporting.ts
  packages/wrangler/src/user.tsx
Labels: polish

#783 Jest cleanup fix
  packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
Labels: maintenance

#772 Improve Sentry Error Filtering
  .changeset/breezy-steaks-visit.md
  packages/wrangler/src/reporting.ts
Labels: maintenance

#782 Create Pages project command
  .changeset/afraid-crabs-care.md
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages.tsx
Labels: pages

#811 `--minify`/`config.minify` for scripts
  .changeset/young-bulldogs-sell.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/bundle.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/index.tsx
  packages/wrangler/src/publish.ts
Labels: enhancement

#796 Mutable headers for next() responses in Pages Functions
  .changeset/large-beans-accept.md
  examples/pages-functions-app/functions/_middleware.ts
  examples/pages-functions-app/tests/index.test.ts
  packages/wrangler/pages/functions/template-worker.ts
Labels: pages

#798 Fix `next()` parameters in Pages Functions
  .changeset/fifty-fireants-add.md
  examples/pages-functions-app/functions/next.ts
  examples/pages-functions-app/public/some-asset.html
  examples/pages-functions-app/tests/index.test.ts
  packages/wrangler/pages/functions/template-worker.ts
Labels: pages

#822 Add Pages commands to help menu
  .changeset/tender-tables-yawn.md
  packages/wrangler/src/__tests__/pages.test.ts
  packages/wrangler/src/pages.tsx
Labels: pages, polish

#794 Improve login error handling
  .changeset/early-ducks-travel.md
  packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/user.tsx
Labels: bug

#829 Add validation to the `name` field in configuration.
  .changeset/mean-owls-own.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/config/validation-helpers.ts
  packages/wrangler/src/config/validation.ts
Labels: enhancement
