Repository cloudflare/workers-sdk, pull requests merged in 2023-09, with the labels that each got.

#3885 [📦 Monorepo] Turbo R2 Archive
  package-lock.json
  package.json
  packages/turbo-r2-archive/.eslintrc.js
  packages/turbo-r2-archive/.gitignore
  packages/turbo-r2-archive/README.md
  packages/turbo-r2-archive/package.json
  packages/turbo-r2-archive/src/autoCacheBust.ts
  packages/turbo-r2-archive/src/index.ts
  packages/turbo-r2-archive/src/routes.ts
  packages/turbo-r2-archive/tsconfig.json
  packages/turbo-r2-archive/turbo.json
  packages/turbo-r2-archive/worker-configuration.d.ts
  packages/turbo-r2-archive/wrangler.json
  turbo.json
Labels: maintenance

#3935 fix: remove unused env variable from sveltekit template
  .changeset/modern-needles-develop.md
  packages/create-cloudflare/src/frameworks/svelte/index.ts
Labels: c3

#3940 TurboRepo CodeGen for New Packages
  .prettierignore
  package.json
  pnpm-lock.yaml
  turbo/generators/config.ts
  turbo/generators/templates/.eslintrc.js.hbs
  turbo/generators/templates/package.json.hbs
  turbo/generators/templates/tsconfig.json.hbs
Labels: maintenance

#3976 Upgrading Testing Deps
  fixtures/pages-functions-app/package.json
  fixtures/pages-plugin-mounted-on-root-app/package.json
  package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
  templates/pages-image-sharing/package.json
Labels: maintenance

#3974 Upgrade ESLint & TurboRepo
  package.json
  packages/eslint-config-worker/package.json
  packages/wrangler/src/dev/miniflare.ts
  pnpm-lock.yaml
Labels: maintenance

#3733 Default local dev server to `*`
  .changeset/shiny-rats-hide.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/validation.ts
Labels: miniflare

#4005 Upgrade XDG package
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: maintenance

#4013 wrangler: some additions
  .changeset/good-ads-fold.md
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/mtls-certificates.test.ts
  packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
  packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/index.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/vectorize/client.ts
  packages/wrangler/src/vectorize/common.ts
  packages/wrangler/src/vectorize/create.tsx
  packages/wrangler/src/vectorize/delete.ts
  packages/wrangler/src/vectorize/get.ts
  packages/wrangler/src/vectorize/index.ts
  packages/wrangler/src/vectorize/insert.ts
  packages/wrangler/src/vectorize/list.ts
  packages/wrangler/src/vectorize/query.ts
  pnpm-lock.yaml
Labels: e2e

#4036 [playground] Fix dark mode in Chrome
  packages/workers-playground/src/QuickEditor/PreviewTab/useRefreshableIframe.tsx
Labels: preview:workers-playground

#4046 [workers-playground] TopBar fixes
  packages/workers-playground/src/QuickEditor/TopBar.tsx
Labels: preview:workers-playground

#3695 Fix(pages): pages dev crash leaving port open
  .changeset/smooth-elephants-divide.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/errors.ts
  packages/wrangler/src/pages/functions/filepath-routing.ts
Labels: pages, awaiting dev response
