Repository cloudflare/workers-sdk, pull requests merged in 2023-02, with the labels that each got.

#2567 Add api, commands, and binding support for mTLS certificates
  .changeset/clean-jokes-tan.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/mtls-certificates.test.ts
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/api/index.ts
  packages/wrangler/src/api/mtls-certificate.ts
  packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/create-worker-upload-form.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/index.ts
  packages/wrangler/src/mtls-certificate/cli.ts
  packages/wrangler/src/publish/publish.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/user/user.ts
  packages/wrangler/src/worker.ts
Labels: enhancement

#2726 [Templates] Remove Beta Message D1
  templates/worker-d1/README.md
Labels: maintenance, templates

#2720 [Wrangler] Build target ES2022
  .changeset/perfect-knives-lie.md
  packages/wrangler/src/__tests__/publish.test.ts
  packages/wrangler/src/bundle.ts
  packages/wrangler/src/entry.ts
Labels: maintenance

#2785 [Wrangler] Add ESLint no .only
  .eslintrc.js
  package-lock.json
  package.json
Labels: maintenance, Wrangler
