Repository cloudflare/workers-sdk, pull requests merged in 2023-06, with the labels that each got.

#3415 pages: remove beta warning
  package-lock.json
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/deploy.tsx
  packages/wrangler/src/pages/deployments.tsx
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions.ts
  packages/wrangler/src/pages/index.ts
  packages/wrangler/src/pages/projects.tsx
  packages/wrangler/src/pages/upload.tsx
  packages/wrangler/src/pages/utils.ts
Labels: pages

#3444 ESLint Import Order
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/constellation/createProject.tsx
  packages/wrangler/src/constellation/deleteProjectModel.ts
  packages/wrangler/src/constellation/listModel.tsx
  packages/wrangler/src/constellation/uploadModel.tsx
  packages/wrangler/src/constellation/utils.ts
  packages/wrangler/src/d1/backups.tsx
  packages/wrangler/src/d1/create.tsx
  packages/wrangler/src/d1/delete.ts
  packages/wrangler/src/d1/execute.tsx
  packages/wrangler/src/d1/info.tsx
  packages/wrangler/src/d1/list.tsx
  packages/wrangler/src/d1/utils.ts
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/pages/buildFunctions.ts
  packages/wrangler/src/pages/deploy.tsx
  packages/wrangler/src/pages/deployment-tails.ts
  packages/wrangler/src/pages/deployments.tsx
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions/filepath-routing.test.ts
  packages/wrangler/src/pages/functions/filepath-routing.ts
  packages/wrangler/src/pages/projects.tsx
  packages/wrangler/src/pages/upload.tsx
  packages/wrangler/src/tail/index.ts
Labels: maintenance

#3456 [Templates] Fix Failing Test
  templates/worker-typescript/src/index.test.ts
Labels: maintenance

#3474 c3: add new Queues and Cron Triggers templates
  .changeset/rare-mirrors-fly.md
  package-lock.json
  packages/create-cloudflare/e2e-tests/workers.test.ts
  packages/create-cloudflare/src/cli.ts
  packages/create-cloudflare/templates/queues/js/.editorconfig
  packages/create-cloudflare/templates/queues/js/.gitignore
  packages/create-cloudflare/templates/queues/js/.prettierrc
  packages/create-cloudflare/templates/queues/js/package.json
  packages/create-cloudflare/templates/queues/js/src/worker.js
  packages/create-cloudflare/templates/queues/js/wrangler.toml
  packages/create-cloudflare/templates/queues/ts/.editorconfig
  packages/create-cloudflare/templates/queues/ts/.gitignore
  packages/create-cloudflare/templates/queues/ts/.prettierrc
  packages/create-cloudflare/templates/queues/ts/package.json
  packages/create-cloudflare/templates/queues/ts/src/worker.ts
  packages/create-cloudflare/templates/queues/ts/tsconfig.json
  packages/create-cloudflare/templates/queues/ts/wrangler.toml
  packages/create-cloudflare/templates/scheduled/js/.editorconfig
  packages/create-cloudflare/templates/scheduled/js/.gitignore
  packages/create-cloudflare/templates/scheduled/js/.prettierrc
  packages/create-cloudflare/templates/scheduled/js/package.json
  packages/create-cloudflare/templates/scheduled/js/src/worker.js
  packages/create-cloudflare/templates/scheduled/js/wrangler.toml
  packages/create-cloudflare/templates/scheduled/ts/.editorconfig
  packages/create-cloudflare/templates/scheduled/ts/.gitignore
  packages/create-cloudflare/templates/scheduled/ts/.prettierrc
  packages/create-cloudflare/templates/scheduled/ts/package.json
  packages/create-cloudflare/templates/scheduled/ts/src/worker.ts
  packages/create-cloudflare/templates/scheduled/ts/tsconfig.json
  packages/create-cloudflare/templates/scheduled/ts/wrangler.toml
Labels: c3

#3491 Bump e2e timeout
  packages/wrangler/package.json
Labels: e2e

#3496 C3-name-validation-fix
  .changeset/nasty-cows-talk.md
  packages/create-cloudflare/package-lock.json
  packages/create-cloudflare/src/cli.ts
Labels: c3

#3499 Add e2e fixes for release
  packages/wrangler/e2e/deploy.test.ts
  packages/wrangler/e2e/deployments.test.ts
Labels: e2e

#3497 Refactor checkFetch from a separate method to a proxy around fetch
  .changeset/selfish-files-flow.md
  packages/wrangler/src/bundle.ts
  packages/wrangler/templates/checked-fetch.js
Labels: e2e

#3545 Convert Pages Shared to Vitest
  packages/pages-shared/__tests__/asset-server/handler.test.ts
  packages/pages-shared/__tests__/asset-server/responses.test.ts
  packages/pages-shared/__tests__/asset-server/rulesEngine.test.ts
  packages/pages-shared/__tests__/metadata-generator/createMetadataObject.test.ts
  packages/pages-shared/__tests__/metadata-generator/parseHeaders.invalid.test.ts
  packages/pages-shared/__tests__/metadata-generator/parseHeaders.valid.test.ts
  packages/pages-shared/__tests__/metadata-generator/parseRedirects.invalid.test.ts
  packages/pages-shared/__tests__/metadata-generator/parseRedirects.valid.test.ts
  packages/pages-shared/package.json
  packages/pages-shared/tsconfig.json
  packages/pages-shared/vite.config.ts
  packages/pages-shared/vite.setup.ts
Labels: maintenance

#3542 chore: retry the e2e tests once if they fail
  .github/workflows/e2e.yml
Labels: e2e

#3511 Upgrade rimraf from v3 to v5
  .changeset/yellow-cameras-swim.md
  package-lock.json
  package.json
  packages/wranglerjs-compat-webpack-plugin/package.json
  packages/wranglerjs-compat-webpack-plugin/src/index.ts
Labels: maintenance
