Repository cloudflare/workers-sdk, pull requests merged in 2023-10, with the labels that each got.

#4105 fix usage of shell-quote.parse on windows
  packages/create-cloudflare/src/helpers/shell-quote.ts
  packages/wrangler/src/utils/shell-quote.ts
Labels: e2e

#3726 Add `find_additional_modules` option to support partial bundling with externals
  .changeset/blue-donkeys-pretend.md
  .changeset/clever-turkeys-leave.md
  .changeset/hot-deers-return.md
  .prettierignore
  fixtures/additional-modules/package.json
  fixtures/additional-modules/src/common.cjs
  fixtures/additional-modules/src/dep.ts
  fixtures/additional-modules/src/dynamic.js
  fixtures/additional-modules/src/index.ts
  fixtures/additional-modules/src/lang/en.js
  fixtures/additional-modules/src/lang/fr.js
  fixtures/additional-modules/src/text.d.ts
  fixtures/additional-modules/src/text.txt
  fixtures/additional-modules/test/index.test.ts
  fixtures/additional-modules/test/tsconfig.json
  fixtures/additional-modules/tsconfig.json
  fixtures/additional-modules/wrangler.toml
  fixtures/no-bundle-import/src/index.test.ts
  fixtures/no-bundle-import/wrangler.toml
  fixtures/shared/package.json
  fixtures/shared/src/run-wrangler-long-lived.ts
  packages/workers-playground/src/QuickEditor/module-collection.ts
  packages/wrangler/src/__tests__/d1/timeTravel.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/find-additional-modules.test.ts
  packages/wrangler/src/api/pages/deploy.tsx
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/apply-middleware.ts
  packages/wrangler/src/deployment-bundle/build-failures.ts
  packages/wrangler/src/deployment-bundle/bundle-type.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/dedupe-modules.ts
  packages/wrangler/src/deployment-bundle/find-additional-modules.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/deployment-bundle/rules.ts
  packages/wrangler/src/deployment-bundle/traverse-module-graph.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/inspect.ts
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/proxy.ts
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/buildFunctions.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/whoami.ts
  packages/wrangler/templates/modules-watch-stub.js
  pnpm-lock.yaml
Labels: e2e

#4086 Update DevTools frontend
  packages/wrangler-devtools/Makefile
  packages/wrangler-devtools/patches/0001-Add-README-detailing-the-setup-process.patch
  packages/wrangler-devtools/patches/0001-Support-viewing-files-over-the-network.patch
  packages/wrangler-devtools/patches/0002-Show-fallback-image-on-Safari.patch
  packages/wrangler-devtools/patches/0003-Support-previewing-subrequest-responses.patch
  packages/wrangler-devtools/patches/0004-Better-Firefox-support-for-network-tab.patch
  packages/wrangler-devtools/patches/0005-Remove-unsupported-network-UI.patch
  packages/wrangler-devtools/patches/0006-Remove-unsupported-profiler-UI.patch
  packages/wrangler-devtools/patches/0007-Support-theme-url-parameter-for-forcing-the-theme-fr.patch
  packages/wrangler-devtools/patches/0008-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
  packages/wrangler-devtools/patches/0008-Show-an-overlay-on-the-memory-tab-in-Firefox.patch
  packages/wrangler-devtools/patches/0009-Fallback-to-location-for-domain.patch
  packages/wrangler-devtools/patches/0010-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
  packages/wrangler-devtools/patches/0010-Hide-unsupported-settings-UI.patch
  packages/wrangler-devtools/patches/0011-Add-ping-to-improve-connection-stability.patch
  packages/wrangler-devtools/patches/0012-Support-sourcemaps.patch
  packages/wrangler-devtools/patches/0013-DEVX-380-Hide-debugger-sidebar-and-disable-breakpoin.patch
  packages/wrangler-devtools/patches/0013-Enable-debugger-when-query-parameter-debugger-is-tru.patch
  packages/wrangler-devtools/patches/0014-Show-Profiling-panel.patch
  packages/wrangler-devtools/patches/0015-Basic-support-for-Safari.patch
  packages/wrangler/src/dev/inspect.ts
Labels: preview:wrangler-devtools

#2397 Support Queue events in tail
  .changeset/warm-queens-taste.md
  packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
  packages/wrangler/src/__tests__/tail.test.ts
  packages/wrangler/src/tail/createTail.ts
  packages/wrangler/src/tail/printing.ts
Labels: awaiting Cloudflare response, queues

#4096 C3: Better e2e quarantine dx
  .github/actions/run-c3-e2e/action.yml
  .github/workflows/c3-checks.yml
  .github/workflows/c3-e2e-dependabot.yml
  .github/workflows/c3-e2e-project-cleanup.yml
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/test-c3.yml
  packages/create-cloudflare/e2e-tests/frameworkToTest.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/e2e-tests/pages.test.ts
Labels: e2e

#3590 Bail early on middleware format mismatch
  .changeset/itchy-experts-sniff.md
  packages/wrangler/src/deployment-bundle/apply-middleware.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
Labels: needs clarification

#4116 C3: Add angular e2e coverage
  .changeset/purple-penguins-tie.md
  packages/create-cloudflare/e2e-tests/pages.test.ts
  packages/create-cloudflare/src/frameworks/angular/index.ts
Labels: e2e

#4170 Use `unstable_dev` and add e2e tests for service bindings
  fixtures/service-bindings-app/tests/index.test.ts
  packages/wrangler/e2e/dev.test.ts
Labels: e2e

#2162 Service bindings in Pages
  .changeset/three-dolphins-float.md
  fixtures/external-service-bindings-app/module-worker-a/index.ts
  fixtures/external-service-bindings-app/module-worker-a/wrangler.toml
  fixtures/external-service-bindings-app/module-worker-b/index.ts
  fixtures/external-service-bindings-app/module-worker-b/wrangler.toml
  fixtures/external-service-bindings-app/module-worker-c/index.ts
  fixtures/external-service-bindings-app/module-worker-c/wrangler.toml
  fixtures/external-service-bindings-app/module-worker-d/index.ts
  fixtures/external-service-bindings-app/module-worker-d/wrangler.toml
  fixtures/external-service-bindings-app/package.json
  fixtures/external-service-bindings-app/pages-functions-app/functions/env.ts
  fixtures/external-service-bindings-app/pages-functions-app/functions/index.ts
  fixtures/external-service-bindings-app/pages-functions-app/package.json
  fixtures/external-service-bindings-app/pages-functions-app/public/index.html
  fixtures/external-service-bindings-app/service-worker-a/index.ts
  fixtures/external-service-bindings-app/service-worker-a/wrangler.toml
  fixtures/external-service-bindings-app/tests/index.test.ts
  fixtures/external-service-bindings-app/tsconfig.json
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/pages/dev.ts
  pnpm-lock.yaml
Labels: pages, e2e

#4215 use `shell-quote.quote(args)` instead of `args.join(" ")`
  .changeset/cold-parrots-deliver.md
  packages/create-cloudflare/src/cli.ts
  packages/create-cloudflare/src/helpers/shell-quote.ts
  packages/create-cloudflare/src/pages.ts
  packages/wrangler/src/__tests__/generate.test.ts
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/utils/shell-quote.ts
Labels: e2e

#4189 Wrangler and C3: Move the cli folder of C3 into @cloudflare/cli and make Wrangler and C3 depend on it
  .changeset/itchy-ducks-listen.md
  packages/cli/.eslintrc.js
  packages/cli/README.md
  packages/cli/__tests__/cli.test.ts
  packages/cli/colors.ts
  packages/cli/index.ts
  packages/cli/interactive.ts
  packages/cli/package.json
  packages/cli/tsconfig.json
  packages/cli/turbo.json
  packages/cli/vite.config.ts
  packages/cli/vite.setup.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/package.json
  packages/create-cloudflare/src/cli.ts
  packages/create-cloudflare/src/common.ts
  packages/create-cloudflare/src/frameworks/angular/index.ts
  packages/create-cloudflare/src/frameworks/astro/index.ts
  packages/create-cloudflare/src/frameworks/gatsby/index.ts
  packages/create-cloudflare/src/frameworks/hono/index.ts
  packages/create-cloudflare/src/frameworks/index.ts
  packages/create-cloudflare/src/frameworks/next/index.ts
  packages/create-cloudflare/src/frameworks/nuxt/index.ts
  packages/create-cloudflare/src/frameworks/qwik/index.ts
  packages/create-cloudflare/src/frameworks/react/index.ts
  packages/create-cloudflare/src/frameworks/remix/index.ts
  packages/create-cloudflare/src/frameworks/solid/index.ts
  packages/create-cloudflare/src/frameworks/svelte/index.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/helpers/cli.ts
  packages/create-cloudflare/src/helpers/codemod.ts
  packages/create-cloudflare/src/helpers/command.ts
  packages/create-cloudflare/src/helpers/files.ts
  packages/create-cloudflare/src/helpers/poll.ts
  packages/create-cloudflare/src/pages.ts
  packages/create-cloudflare/src/workers.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/jest.setup.ts
  pnpm-lock.yaml
Labels: awaiting Cloudflare response

#4135 feat: support npm resolution for file imports
  .changeset/long-starfishes-mate.md
  fixtures/import-wasm-example/.gitignore
  fixtures/import-wasm-example/README.md
  fixtures/import-wasm-example/package.json
  fixtures/import-wasm-example/src/index.js
  fixtures/import-wasm-example/tests/index.test.ts
  fixtures/import-wasm-example/tests/tsconfig.json
  fixtures/import-wasm-example/tsconfig.json
  fixtures/import-wasm-example/wrangler.toml
  fixtures/import-wasm-static/README.md
  fixtures/import-wasm-static/package.json
  fixtures/import-wasm-static/wasm/multiply.wasm
  fixtures/import-wasm-static/wasm/multiply.wat
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/module-collection.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  pnpm-lock.yaml
Labels: awaiting Cloudflare response

#4279 fix: use a valid compatibility date for worker templates
  .changeset/wise-pears-fry.md
  packages/create-cloudflare/templates/scheduled/ts/wrangler.toml
Labels: c3
