Repository cloudflare/workers-sdk, pull requests merged in 2024-09, with the labels that each got.

#6623 Remove some missed --x-versions and move deploy to existing util function
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.view.test.ts
  packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
  packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
  packages/wrangler/src/__tests__/versions/secrets/put.test.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/versions/deployments/view.ts
  packages/wrangler/src/versions/secrets/bulk.ts
  packages/wrangler/src/versions/secrets/delete.ts
  packages/wrangler/src/versions/secrets/put.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#6603 [wrangler] log version preview url when previews exist
  .changeset/funny-comics-lick.md
  .changeset/modern-scissors-relax.md
  packages/wrangler/e2e/README.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#6615 avoid potential double-install of create-cloudflare
  .changeset/friendly-brooms-brush.md
  packages/wrangler/src/__tests__/generate.test.ts
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
Labels: e2e

#6633 fix: ensure console methods are bound to instance
  .changeset/real-cooks-argue.md
  packages/vitest-pool-workers/src/worker/lib/node/console.ts
  packages/vitest-pool-workers/test/console.test.ts
Labels: e2e

#6606 Add new_sqlite_classes migration for Durable Objects
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/worker.ts
Labels: caretaking

#6639 Add note on wrangler v2 support
  packages/wrangler/README.md
Labels: caretaking

#6620 fix: don't warn about `node:async_hooks` if `nodejs_als` is set
  .changeset/silly-ways-brake.md
  fixtures/nodejs-als-app/package.json
  fixtures/nodejs-als-app/src/index.ts
  fixtures/nodejs-als-app/tests/index.test.ts
  fixtures/nodejs-als-app/tests/tsconfig.json
  fixtures/nodejs-als-app/tsconfig.json
  fixtures/nodejs-als-app/turbo.json
  fixtures/nodejs-als-app/vitest.config.mts
  fixtures/nodejs-als-app/wrangler.toml
  packages/workers-shared/package.json
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts
  packages/wrangler/src/deployment-bundle/node-compat.ts
  pnpm-lock.yaml
Labels: e2e

#6126 Add cloudchamber curl command
  .changeset/new-dragons-bow.md
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/cloudchamber/curl.ts
  packages/wrangler/src/cloudchamber/index.ts
Labels: awaiting Cloudflare response

#6612 enable hyperdrive bindings in `getPlatformProxy`
  .changeset/gold-maps-itch.md
  .changeset/slimy-waves-dance.md
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler.toml
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/d1/index.ts
  packages/miniflare/src/plugins/do/index.ts
  packages/miniflare/src/plugins/hyperdrive/index.ts
  packages/miniflare/src/plugins/kv/index.ts
  packages/miniflare/src/plugins/kv/sites.ts
  packages/miniflare/src/plugins/queues/index.ts
  packages/miniflare/src/plugins/r2/index.ts
  packages/miniflare/src/plugins/ratelimit/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/test/plugins/hyperdrive/index.spec.ts
  packages/wrangler/e2e/get-platform-proxy.test.ts
Labels: e2e

#6640 feat: experimental workers assets can be ignored by adding a .assetsignore file
  .changeset/nasty-hats-rhyme.md
  .vscode/settings.json
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/experimental-assets.ts
  packages/wrangler/src/sites.ts
  packages/wrangler/src/utils/filesystem.ts
Labels: e2e

#6621 fix(wrangler): validate routes in dev and deploy
  .changeset/lazy-poems-mate.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/triggers/index.ts
Labels: e2e

#6674 Add pipeline binding to wrangler.toml
  .changeset/angry-keys-dance.md
  .prettierignore
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#6628 Improve asset uploading messaging
  .changeset/sixty-suns-act.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/experimental-assets.ts
Labels: e2e

#6671 Not including detail id in wrangler output from R2 event notifications
  .changeset/smooth-bananas-obey.md
  packages/wrangler/src/r2/helpers.ts
Labels: caretaking

#6679 Adding argument to specify rule to delete if don't want to delete every rule in config
  .changeset/lazy-jeans-kick.md
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/r2/helpers.ts
  packages/wrangler/src/r2/notification.ts
Labels: caretaking

#6624 chore(quick-edit): run setup and custom-build script before deploy
  .changeset/bright-radios-fail.md
  .github/workflows/deploy-pages-previews.yml
  packages/quick-edit-extension/scripts/bundle.ts
  packages/quick-edit/README.md
  packages/quick-edit/build.sh
  packages/quick-edit/package.json
  packages/quick-edit/setup.sh
Labels: preview:quick-edit

#6703 remove outdated config options
  fixtures/workers-with-assets-only/wrangler.toml
Labels: skip-pr-validation

#6696 Support `WRANGLER_CI_MATCH_TAG` environment variable
  .changeset/quiet-impalas-sniff.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/match-tag.test.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
  packages/wrangler/src/match-tag.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: internal, e2e

#6232 Upgrade `@cloudflare/vitest-pool-workers` to Vitest v2+
  .changeset/soft-beans-explode.md
  fixtures/asset-config/package.json
  fixtures/asset-config/vitest.config.ts
  fixtures/local-mode-tests/tests/logging.test.ts
  fixtures/vitest-pool-workers-examples/package.json
  fixtures/vitest-pool-workers-examples/vitest.workers.config.ts
  package.json
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/miniflare/src/index.ts
  packages/vitest-pool-workers/package.json
  packages/vitest-pool-workers/src/config/index.ts
  packages/vitest-pool-workers/src/pool/config.ts
  packages/vitest-pool-workers/src/pool/index.ts
  packages/vitest-pool-workers/src/pool/module-fallback.ts
  packages/vitest-pool-workers/src/worker/lib/cloudflare/test-runner.ts
  packages/vitest-pool-workers/src/worker/lib/node/fs.ts
  packages/vitest-pool-workers/test/console.test.ts
  packages/vitest-pool-workers/test/global-setup.ts
  packages/workers-shared/package.json
  packages/workers.new/package.json
  packages/workers.new/tests/vitest.config.mts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/vitest.setup.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tools/dependabot/__tests__/generate-dependabot-pr-changesets.test.ts
Labels: caretaking, skip-pr-validation

#6707 Bump `pnpm` 9.1.3 -> 9.10.0 to support catalogs
  .github/actions/install-dependencies/action.yml
  .github/workflows/c3-e2e-dependabot.yml
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  package.json
Labels: skip-pr-validation

#6694 Version Packages
  .changeset/angry-socks-pretend.md
  .changeset/bright-radios-fail.md
  .changeset/fifty-students-prove.md
  .changeset/gold-toys-smell.md
  .changeset/lovely-experts-double.md
  .changeset/lovely-pigs-bow.md
  .changeset/popular-snakes-report.md
  .changeset/quiet-impalas-sniff.md
  .changeset/sixty-bottles-care.md
  .changeset/soft-beans-explode.md
  .changeset/sour-jeans-bake.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-validation

#6709 Add missing config params to router-worker and asset-worker
  .changeset/stupid-dogs-hear.md
  package.json
  packages/workers-shared/asset-worker/wrangler.toml
  packages/workers-shared/router-worker/wrangler.toml
  pnpm-lock.yaml
Labels: skip-pr-validation

#6710 Version Packages
  .changeset/curvy-donuts-study.md
  .changeset/healthy-swans-impress.md
  .changeset/stupid-dogs-hear.md
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-validation

#6712 Use D&C token
  .changeset/thick-grapes-joke.md
  packages/workers-shared/package.json
Labels: skip-pr-validation

#6713 Version Packages
  .changeset/thick-grapes-joke.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-validation

#6686 Bump path-to-regexp to 6.3.0
  .changeset/gorgeous-eagles-matter.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-validation

#6329 Add header + caching to runtime type generation
  .changeset/perfect-pens-work.md
  packages/wrangler/e2e/types.test.ts
  packages/wrangler/src/type-generation/index.ts
  packages/wrangler/src/type-generation/runtime/index.ts
  packages/wrangler/src/workerd.d.ts
Labels: e2e, skip-pr-validation

#6727 Version Packages
  .changeset/big-dogs-whistle.md
  .changeset/gorgeous-eagles-matter.md
  .changeset/nervous-days-greet.md
  .changeset/perfect-pens-work.md
  .changeset/pink-meals-walk.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/package.json
  packages/create-cloudflare/src/__tests__/deploy.test.ts
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
  packages/create-cloudflare/templates/hello-world/js/package.json
  packages/create-cloudflare/templates/hello-world/ts/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-validation

#6734 chore: improve c3 tests
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/src/__tests__/deploy.test.ts
Labels: e2e

#6705 fix: upload compat date for static-asset only projects
  .changeset/tame-ties-smash.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
Labels: e2e

#6733 Version Packages
  .changeset/blue-bags-walk.md
  .changeset/empty-pots-fetch.md
  .changeset/ninety-icons-live.md
  .changeset/tall-needles-marry.md
  .changeset/tame-ties-smash.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-editor-shared/CHANGELOG.md
  packages/workers-editor-shared/package.json
  packages/workers-playground/CHANGELOG.md
  packages/workers-playground/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-validation

#6514 fix(miniflare): Fix regression introduced in #5570
  .changeset/cool-beans-applaud.md
  packages/miniflare/src/index.ts
  packages/miniflare/test/plugins/queues/index.spec.ts
Labels: awaiting Cloudflare response, queues, skip-pr-validation

#6749 fix: Throw error when attempting to configure Workers with assets and tail consumers
  .changeset/fresh-ravens-pull.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/experimental-assets.ts
  packages/wrangler/src/versions/index.ts
Labels: e2e

#6739 Version Packages
  .changeset/cool-beans-applaud.md
  .changeset/famous-knives-battle.md
  .changeset/fresh-ravens-pull.md
  .changeset/moody-kangaroos-allow.md
  .changeset/polite-sheep-sip.md
  .changeset/six-buses-matter.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-validation

#6755 C3: bump qwik to `1.9.0`
  .changeset/few-feet-appear.md
  .changeset/spotty-snails-design.md
  packages/create-cloudflare/src/frameworks/package.json
  packages/create-cloudflare/templates-experimental/qwik/c3.ts
  packages/create-cloudflare/templates/qwik/c3.ts
  packages/create-cloudflare/templates/qwik/templates/wrangler.toml
Labels: e2e

#6743 fix: support non-default build conditions via the WRANGLER_BUILD_CONDITIONS flag
  .changeset/eight-bikes-nail.md
  fixtures/isomorphic-random-example/package.json
  fixtures/isomorphic-random-example/src/default.js
  fixtures/isomorphic-random-example/src/other.js
  fixtures/worker-app/src/index.js
  fixtures/worker-app/tests/env-vars.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
Labels: skip-pr-validation, skip-pr-description-validation

#6765 Version Packages
  .changeset/c3-frameworks-update-6536.md
  .changeset/c3-frameworks-update-6766.md
  .changeset/eight-bikes-nail.md
  .changeset/eight-squids-collect.md
  .changeset/few-feet-appear.md
  .changeset/old-mugs-begin.md
  .changeset/spotty-snails-design.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6782 chore: update unenv dependency version
  .changeset/lucky-doors-jam.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#6775 fix(wrangler): Support switching between static and dynamic Workers
  .changeset/bright-guests-destroy.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/experimental-assets.ts
Labels: e2e

#6783 Version Packages
  .changeset/bright-guests-destroy.md
  .changeset/fresh-worms-knock.md
  .changeset/hot-poems-march.md
  .changeset/lucky-doors-jam.md
  .changeset/quiet-dolphins-compete.md
  .changeset/serious-houses-film.md
  .changeset/spotty-colts-peel.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6484 feat(create-cloudflare): telemetry collection
  .changeset/eighty-guests-join.md
  packages/cli/error.ts
  packages/cli/interactive.ts
  packages/create-cloudflare/package.json
  packages/create-cloudflare/scripts/build.ts
  packages/create-cloudflare/src/__tests__/deploy.test.ts
  packages/create-cloudflare/src/__tests__/dialog.test.ts
  packages/create-cloudflare/src/__tests__/git.test.ts
  packages/create-cloudflare/src/__tests__/metrics.test.ts
  packages/create-cloudflare/src/__tests__/templates.test.ts
  packages/create-cloudflare/src/cli.ts
  packages/create-cloudflare/src/deploy.ts
  packages/create-cloudflare/src/dialog.ts
  packages/create-cloudflare/src/event.ts
  packages/create-cloudflare/src/frameworks/index.ts
  packages/create-cloudflare/src/git.ts
  packages/create-cloudflare/src/help.ts
  packages/create-cloudflare/src/helpers/__tests__/args.test.ts
  packages/create-cloudflare/src/helpers/__tests__/command.test.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/helpers/codemod.ts
  packages/create-cloudflare/src/helpers/command.ts
  packages/create-cloudflare/src/helpers/files.ts
  packages/create-cloudflare/src/helpers/global-wrangler-config-path.ts
  packages/create-cloudflare/src/helpers/metrics-config.ts
  packages/create-cloudflare/src/helpers/sparrow.ts
  packages/create-cloudflare/src/metrics.ts
  packages/create-cloudflare/src/pages.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/src/wrangler/__tests__/accounts.test.ts
  packages/create-cloudflare/src/wrangler/accounts.ts
  packages/create-cloudflare/telemetry.md
  packages/create-cloudflare/templates/next/c3.ts
  packages/create-cloudflare/templates/pre-existing/c3.ts
  packages/create-cloudflare/templates/qwik/c3.ts
  packages/create-cloudflare/templates/react/c3.ts
  packages/create-cloudflare/turbo.json
  pnpm-lock.yaml
Labels: e2e

#6806 Revert "fix(quick-edit): disable autosave"
  .changeset/sour-jars-dance.md
  packages/quick-edit/functions/_middleware.ts
Labels: skip-pr-description-validation

#6799 Version Packages
  .changeset/eighty-guests-join.md
  .changeset/fast-rocks-know.md
  .changeset/pink-months-promise.md
  .changeset/proud-hats-notice.md
  .changeset/shaggy-peas-notice.md
  .changeset/silly-birds-shout.md
  .changeset/sour-jars-dance.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6813 Version Packages
  .changeset/brown-shoes-tease.md
  .changeset/eight-emus-compete.md
  .changeset/gentle-goats-greet.md
  .changeset/light-insects-drive.md
  .changeset/many-years-nail.md
  .changeset/perfect-bikes-type.md
  .changeset/witty-eggs-reply.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6824 Fix nodejs compat v2 upgrade
  .changeset/early-tigers-buy.md
  .changeset/tender-items-exercise.md
  fixtures/nodejs-hybrid-app/wrangler.toml
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/core/modules.ts
  packages/miniflare/src/plugins/core/node-compat.ts
  packages/miniflare/src/plugins/index.ts
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-console.ts
  packages/wrangler/src/__tests__/helpers/normalize.ts
  packages/wrangler/src/__tests__/helpers/run-wrangler.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/api/pages/deploy.tsx
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/build-failures.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/log-build-output.ts
  packages/wrangler/src/deployment-bundle/node-compat.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/buildFunctions.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/type-generation/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#6828 Version Packages
  .changeset/dependabot-update-6826.md
  .changeset/early-tigers-buy.md
  .changeset/tender-items-exercise.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6833 fix version preview url snapshot
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/versions.test.ts
Labels: e2e, skip-pr-description-validation

#6803 chore: add workers + assets e2es
  packages/wrangler/e2e/deployments.test.ts
Labels: e2e

#6819 fix(wrangler): Validate routes on config file changes
  .changeset/friendly-papayas-provide.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/dev.tsx
Labels: e2e

#6829 Version Packages
  .changeset/chilled-clocks-add.md
  .changeset/friendly-papayas-provide.md
  .changeset/green-fishes-rest.md
  .changeset/quiet-eels-rest.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6840 Queues is now GA so don't say it's in beta in warning messages
  .changeset/pretty-birds-scream.md
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/dev/dev.tsx
Labels: skip-pr-description-validation

#6849 Version Packages
  .changeset/pretty-birds-scream.md
  .changeset/twelve-years-search.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#6850 Update workers-types in Quick Edit
  .changeset/poor-deers-develop.md
Labels: preview:quick-edit

#6851 Version Packages
  .changeset/poor-deers-develop.md
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
Labels: skip-pr-description-validation
