Repository cloudflare/workers-sdk, pull requests merged in 2024-07, with the labels that each got.

#6164 fix: use account id for listing zones
  .changeset/grumpy-bikes-prove.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/rollback.test.ts
  packages/wrangler/src/__tests__/zones.test.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/tail/index.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/versions/rollback/index.ts
  packages/wrangler/src/zones.ts
Labels: e2e

#6022 fix(wrangler): Watch for external dependencies changes in `pages dev`
  .changeset/gorgeous-oranges-brake.md
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/pages/utils.ts
Labels: e2e

#6149 React-free hotkeys implementation
  .changeset/few-days-tap.md
  fixtures/interactive-dev-tests/tests/index.test.ts
  packages/miniflare/src/shared/log.ts
  packages/wrangler/src/__tests__/cli-hotkeys.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/cli-hotkeys.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/dev/hotkeys.ts
  packages/wrangler/src/dev/inspect.ts
  packages/wrangler/src/dev/proxy.ts
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/dialogs.ts
  packages/wrangler/src/is-interactive.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/utils/isAbortError.ts
  packages/wrangler/src/utils/onKeyPress.ts
Labels: e2e

#6150 fix(wrangler): Fix `pages dev` watch mode [_worker.js]
  .changeset/poor-ads-poke.md
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#6201 Granular e2e caching
  .github/workflows/e2e.yml
  package.json
  tools/e2e/runIndividualE2EFiles.ts
  turbo.json
Labels: maintenance, e2e

#6209 fixup: Add `--only` to e2e script
  tools/e2e/runIndividualE2EFiles.ts
Labels: e2e

#4398 Improved tsconfig.json files in examples directory
  .changeset/many-lies-boil.md
  packages/wrangler/templates/tsconfig.init.json
  templates/worker-turso-ts/tsconfig.json
  templates/worker-typescript/tsconfig.json
Labels: blocked

#6263 fix: use cli script-name arg when deploying a worker with queue consumers
  .changeset/stupid-beans-joke.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/triggers/deploy.ts
Labels: e2e

#6255 [D1] teach init --from-dash about d1
  .changeset/green-sloths-collect.md
  packages/wrangler/src/deployments.ts
  packages/wrangler/src/init.ts
Labels: e2e

#6247 Updated D1 export progress to use spinnerWhile
  packages/wrangler/src/d1/export.ts
Labels: e2e

#6123 Minor copy change in rollback
  packages/wrangler/src/__tests__/rollback.test.ts
  packages/wrangler/src/versions/rollback/index.ts
Labels: e2e

#6276 feat(wrangler): Add support for `wrangler.jsonc`
  .changeset/rare-forks-fly.md
  packages/wrangler/src/__tests__/d1/execute.test.ts
  packages/wrangler/src/__tests__/d1/export.test.ts
  packages/wrangler/src/__tests__/d1/info.test.ts
  packages/wrangler/src/__tests__/d1/migrate.test.ts
  packages/wrangler/src/__tests__/d1/timeTravel.test.ts
  packages/wrangler/src/__tests__/delete.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/__tests__/helpers/write-wrangler-toml.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
  packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
  packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
  packages/wrangler/src/__tests__/versions/secrets/list.test.ts
  packages/wrangler/src/__tests__/versions/secrets/put.test.ts
  packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.list.test.ts
  packages/wrangler/src/__tests__/versions/versions.view.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/config/index.ts
Labels: e2e

#6314 Use the same workerName for all of the tests in e2e/dev-with-resources
  packages/wrangler/e2e/c3-integration.test.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/command.ts
  packages/wrangler/e2e/helpers/read-until.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/e2e/vitest.config.mts
Labels: e2e

#6336 fix(wrangler): Rename more `legacy-assets` things
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/__tests__/validate-dev-props.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/dev/validate-dev-props.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/sites.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#6330 Add --x-dev-env to fixtures tests
  .changeset/late-bikes-promise.md
  fixtures/additional-modules/package.json
  fixtures/d1-worker-app/package.json
  fixtures/external-durable-objects-app/package.json
  fixtures/external-durable-objects-app/tests/index.test.ts
  fixtures/external-service-bindings-app/package.json
  fixtures/external-service-bindings-app/tests/index.test.ts
  fixtures/get-bindings-proxy/tests/get-bindings-proxy.bindings.test.ts
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/local-mode-tests/tests/logging.test.ts
  fixtures/local-mode-tests/tests/module.test.ts
  fixtures/local-mode-tests/tests/ports.test.ts
  fixtures/local-mode-tests/tests/specified-port.test.ts
  fixtures/local-mode-tests/tests/sw.test.ts
  fixtures/local-mode-tests/vitest.config.mts
  fixtures/no-bundle-import/package.json
  fixtures/no-bundle-import/src/index.test.ts
  fixtures/nodejs-hybrid-app/package.json
  fixtures/service-bindings-app/package.json
  fixtures/service-bindings-app/tests/index.test.ts
  fixtures/shared/src/run-wrangler-long-lived.ts
  fixtures/worker-ts/package.json
  package.json
  packages/wrangler/e2e/helpers/command.ts
  packages/wrangler/package.json
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/templates/startDevWorker/ProxyWorker.ts
  pnpm-lock.yaml
Labels: e2e

#6361 remove get-bindings-proxy fixture
  fixtures/get-bindings-proxy/.dev.vars
  fixtures/get-bindings-proxy/custom-toml/path/.dev.vars
  fixtures/get-bindings-proxy/custom-toml/path/test-toml
  fixtures/get-bindings-proxy/package.json
  fixtures/get-bindings-proxy/tests/get-bindings-proxy.bindings.test.ts
  fixtures/get-bindings-proxy/tests/get-bindings-proxy.caches.test.ts
  fixtures/get-bindings-proxy/tests/get-bindings-proxy.cf.test.ts
  fixtures/get-bindings-proxy/tests/get-bindings-proxy.ctx.test.ts
  fixtures/get-bindings-proxy/tests/shared.ts
  fixtures/get-bindings-proxy/tsconfig.json
  fixtures/get-bindings-proxy/vitest.config.mts
  fixtures/get-bindings-proxy/workers/do-worker-a/index.ts
  fixtures/get-bindings-proxy/workers/do-worker-a/wrangler.toml
  fixtures/get-bindings-proxy/workers/do-worker-b/index.ts
  fixtures/get-bindings-proxy/workers/do-worker-b/wrangler.toml
  fixtures/get-bindings-proxy/workers/hello-worker-a/index.ts
  fixtures/get-bindings-proxy/workers/hello-worker-a/wrangler.toml
  fixtures/get-bindings-proxy/workers/hello-worker-b/index.ts
  fixtures/get-bindings-proxy/workers/hello-worker-b/wrangler.toml
  fixtures/get-bindings-proxy/wrangler.json
  fixtures/get-bindings-proxy/wrangler.toml
Labels: e2e

#6097 Support --x-dev-env for Pages
  .changeset/young-doors-think.md
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#6362 fix: ensure that mocked fetch responses have a valid URL property
  .changeset/proud-chefs-count.md
  fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
  packages/vitest-pool-workers/src/worker/fetch-mock.ts
Labels: e2e

#6301 fix: allow `getPlatformProxy` to handle RPC calls returning objects
  .changeset/polite-dodos-happen.md
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/workers/rpc-worker/index.ts
  packages/miniflare/src/workers/core/proxy.worker.ts
  packages/miniflare/test/index.spec.ts
Labels: e2e

#6379 Clearer error message when trying to use Workers Sites with `wrangler versions upload`
  .changeset/chatty-pans-grow.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/experimental-assets.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#6390 Update Workers Sites/Legacy Assets error message in versions commands
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/secrets/index.ts
Labels: e2e
