Repository cloudflare/workers-sdk, pull requests merged in 2024-05, with the labels that each got.

#5746 fix: suggest trying to update Wrangler if there is a newer one available after an unexpected error
  .changeset/stale-parrots-explode.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/index.ts
Labels: e2e

#5754 fix: custom build noop causes esbuild to skip bundling
  .changeset/sixty-pans-nail.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/use-esbuild.ts
Labels: e2e

#5820 Node 18
  .github/workflows/c3-dependabot-versioning-prs.yml
  .github/workflows/changesets.yml
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/d1.yml
  .github/workflows/miniflare-dependabot-versioning-prs.yml
  .github/workflows/prereleases.yml
  .github/workflows/test-and-check.yml
  .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
  .prettierignore
  fixtures/get-bindings-proxy/tests/get-bindings-proxy.bindings.test.ts
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/local-mode-tests/tests/logging.test.ts
  fixtures/local-mode-tests/tests/module.test.ts
  fixtures/local-mode-tests/tests/ports.test.ts
  fixtures/local-mode-tests/tests/specified-port.test.ts
  fixtures/local-mode-tests/tests/sw.test.ts
  fixtures/no-bundle-import/src/index.test.ts
  fixtures/pages-dev-proxy-with-script/tests/index.test.ts
  fixtures/pages-proxy-app/tests/index.test.ts
  fixtures/shared/src/run-wrangler-long-lived.ts
  package.json
  packages/edge-preview-authenticated-proxy/tests/index.test.ts
  packages/workers.new/tests/index.test.ts
  packages/wrangler/src/__tests__/api-dev.test.ts
  packages/wrangler/src/__tests__/api-devregistry.test.ts
  packages/wrangler/src/__tests__/cfetch-utils.test.ts
  packages/wrangler/src/__tests__/custom-build.test.ts
  packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
  packages/wrangler/src/__tests__/middleware.scheduled.test.ts
  packages/wrangler/src/__tests__/middleware.test.ts
  packages/wrangler/src/__tests__/pages/dev.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.view.test.ts
  packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.list.test.ts
  packages/wrangler/src/__tests__/versions/versions.view.test.ts
  packages/wrangler/turbo.json
  templates/pages-example-forum-app/README.md
Labels: e2e

#5855 chore: bump undici to 5.28.4
  .changeset/wet-bugs-burn.md
  packages/cli/package.json
  packages/create-cloudflare/package.json
  pnpm-lock.yaml
Labels: e2e

#5868 refactor: move tests from `vitest-pool-workers` into `misc` fixture
  fixtures/vitest-pool-workers-examples/README.md
  fixtures/vitest-pool-workers-examples/durable-objects/test/direct-access.test.ts
  fixtures/vitest-pool-workers-examples/misc/README.md
  fixtures/vitest-pool-workers-examples/misc/src/other-worker.mjs
  fixtures/vitest-pool-workers-examples/misc/test/defines.test.ts
  fixtures/vitest-pool-workers-examples/misc/test/durable-objects.test.ts
  fixtures/vitest-pool-workers-examples/misc/test/env.d.ts
  fixtures/vitest-pool-workers-examples/misc/test/fake-timers.test.ts
  fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
  fixtures/vitest-pool-workers-examples/misc/test/global.d.ts
  fixtures/vitest-pool-workers-examples/misc/test/module-mocking.test.ts
  fixtures/vitest-pool-workers-examples/misc/test/tsconfig.json
  fixtures/vitest-pool-workers-examples/misc/tsconfig.json
  fixtures/vitest-pool-workers-examples/misc/vitest.config.ts
  fixtures/vitest-pool-workers-examples/misc/wrangler.toml
  fixtures/vitest-pool-workers-examples/vitest.workers.config.ts
  packages/vitest-pool-workers/.eslintrc.js
  packages/vitest-pool-workers/package.json
  packages/vitest-pool-workers/test/basic/env.d.ts
  packages/vitest-pool-workers/test/basic/fake-timer.test.ts
  packages/vitest-pool-workers/test/basic/maths.test.ts
  packages/vitest-pool-workers/test/basic/mocking.test.ts
  packages/vitest-pool-workers/test/basic/setup/global-setup.ts
  packages/vitest-pool-workers/test/basic/setup/setup.ts
  packages/vitest-pool-workers/test/basic/strings.test.ts
  packages/vitest-pool-workers/test/basic/vitest.config.ts
  packages/vitest-pool-workers/test/kv/__snapshots__/store.test.ts.snap
  packages/vitest-pool-workers/test/kv/env.d.ts
  packages/vitest-pool-workers/test/kv/global.d.ts
  packages/vitest-pool-workers/test/kv/other-worker.mjs
  packages/vitest-pool-workers/test/kv/seed.txt
  packages/vitest-pool-workers/test/kv/store.test.ts
  packages/vitest-pool-workers/test/kv/worker.ts
  packages/vitest-pool-workers/test/kv/wrangler.toml
  packages/vitest-pool-workers/test/stacked/stacked.test.ts
  packages/vitest-pool-workers/test/stacked/vitest.config.ts
  packages/vitest-pool-workers/tsconfig.json
  packages/vitest-pool-workers/types/cloudflare-test.d.ts
  packages/vitest-pool-workers/types/tsconfig.json
  packages/vitest-pool-workers/vitest.workers.config.ts
  packages/vitest-pool-workers/vitest.workspace.ts
Labels: e2e

#5875 Don't cache 404s from the asset-server
  .changeset/unlucky-radios-fold.md
  packages/pages-shared/__tests__/asset-server/handler.test.ts
  packages/pages-shared/asset-server/handler.ts
Labels: pages

#5869 Implement vitest pool e2e meta tests
  packages/vitest-pool-workers/package.json
  packages/vitest-pool-workers/src/pool/index.ts
  packages/vitest-pool-workers/src/worker/index.ts
  packages/vitest-pool-workers/test/README.md
  packages/vitest-pool-workers/test/chunking.test.ts
  packages/vitest-pool-workers/test/console.test.ts
  packages/vitest-pool-workers/test/env.d.ts
  packages/vitest-pool-workers/test/global-setup.ts
  packages/vitest-pool-workers/test/helpers.ts
  packages/vitest-pool-workers/test/isolation.test.ts
  packages/vitest-pool-workers/test/snapshots.test.ts
  packages/vitest-pool-workers/test/validation.test.ts
  packages/vitest-pool-workers/test/watch.test.ts
  packages/vitest-pool-workers/tsconfig.json
  packages/vitest-pool-workers/vitest.config.ts
  pnpm-lock.yaml
Labels: e2e

#5905 Remove WARP cert
  .changeset/dirty-spies-dress.md
  packages/wrangler/Cloudflare_CA.pem
  packages/wrangler/bin/wrangler.js
  packages/wrangler/package.json
Labels: e2e

#5900 feature: add support for testing Pages Functions
  .changeset/tame-melons-promise.md
  fixtures/vitest-pool-workers-examples/README.md
  fixtures/vitest-pool-workers-examples/misc/test/env.d.ts
  fixtures/vitest-pool-workers-examples/misc/test/pages-functions.test.ts
  fixtures/vitest-pool-workers-examples/misc/vitest.config.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/.gitignore
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/README.md
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/functions/api/_middleware.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/functions/api/kv/[key].ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/functions/api/ping.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/functions/env.d.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/functions/tsconfig.json
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/global-setup.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/public/404.html
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/public/_headers
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/public/_redirects
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/public/index.html
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/public/secure.html
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/test/env.d.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/test/integration-self.test.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/test/tsconfig.json
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/test/unit.test.ts
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/tsconfig.json
  fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/vitest.config.ts
  packages/vitest-pool-workers/src/config/d1.ts
  packages/vitest-pool-workers/src/config/index.ts
  packages/vitest-pool-workers/src/config/pages.ts
  packages/vitest-pool-workers/src/worker/events.ts
  packages/vitest-pool-workers/src/worker/lib/cloudflare/test.ts
  packages/vitest-pool-workers/types/cloudflare-test.d.ts
  packages/wrangler/src/cli.ts
Labels: e2e

#5703 Check if middleware is an array
  .changeset/funny-drinks-destroy.md
  packages/wrangler/src/__tests__/middleware.test.ts
  packages/wrangler/src/deployment-bundle/apply-middleware.ts
  packages/wrangler/templates/facade.d.ts
  packages/wrangler/templates/middleware/loader-modules.ts
Labels: awaiting Cloudflare response

#5917 Partially fix #3160 by properly handling resultsFormat query
  .changeset/little-jars-train.md
  packages/miniflare/src/workers/d1/database.worker.ts
  packages/miniflare/test/plugins/d1/suite.ts
  packages/miniflare/test/plugins/d1/test.ts
Labels: d1
