Repository cloudflare/workers-sdk, pull requests merged in 2024-06, with the labels that each got.

#5960 fix: avoid injecting esbuild watch stubs into production Worker code
  .changeset/popular-ravens-add.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
Labels: e2e

#5250 c3: update DO example
  .changeset/gold-squids-give.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/hello-world-durable-object/c3.ts
Labels: c3

#5939 Remote runtime controller
  .changeset/flat-days-punch.md
  fixtures/dev-env/tests/index.test.ts
  fixtures/unstable_dev/package.json
  fixtures/unstable_dev/src/index.js
  fixtures/unstable_dev/src/wrangler-dev.mjs
  packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
  packages/wrangler/e2e/dev-env.test.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/wrangler.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/events.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/errors.ts
  pnpm-lock.yaml
Labels: e2e

#5823 Cleanup: Remove builtin-wasm-modules from autogates passed to workerd
  packages/miniflare/src/index.ts
Labels: e2e

#5961 chore: bump workerd and workers-types deps
  .changeset/friendly-students-fly.md
  fixtures/additional-modules/package.json
  fixtures/external-durable-objects-app/package.json
  fixtures/external-service-bindings-app/package.json
  fixtures/get-bindings-proxy/package.json
  fixtures/get-platform-proxy/package.json
  fixtures/local-mode-tests/package.json
  fixtures/node-app-pages/package.json
  fixtures/pages-dev-proxy-with-script/package.json
  fixtures/pages-functions-app/package.json
  fixtures/pages-functions-with-routes-app/package.json
  fixtures/pages-plugin-mounted-on-root-app/package.json
  fixtures/pages-simple-assets/package.json
  fixtures/remix-pages-app/package.json
  fixtures/vitest-pool-workers-examples/package.json
  fixtures/worker-ts/package.json
  package.json
  packages/create-cloudflare/package.json
  packages/edge-preview-authenticated-proxy/package.json
  packages/format-errors/package.json
  packages/kv-asset-handler/package.json
  packages/miniflare/package.json
  packages/pages-shared/package.json
  packages/playground-preview-worker/package.json
  packages/prerelease-registry/package.json
  packages/quick-edit-extension/package.json
  packages/vitest-pool-workers/package.json
  packages/workers.new/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#5878 feat: second-cut of using unenv to create a hybrid node.js compatibility setting (via inject)
  .changeset/calm-ducks-happen.md
  fixtures/nodejs-hybrid-app/package.json
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  fixtures/nodejs-hybrid-app/tests/tsconfig.json
  fixtures/nodejs-hybrid-app/tsconfig.json
  fixtures/nodejs-hybrid-app/turbo.json
  fixtures/nodejs-hybrid-app/vitest.config.ts
  fixtures/nodejs-hybrid-app/worker-configuration.d.ts
  fixtures/nodejs-hybrid-app/wrangler.toml
  package.json
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/api/pages/deploy.tsx
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/node-compat.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/dev/validate-dev-props.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/buildFunctions.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/upload.ts
  patches/pg@8.11.3.patch
  pnpm-lock.yaml
Labels: e2e

#5990 update e2e kv command usage
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
Labels: e2e

#5957 Bundle controller
  fixtures/dev-env/tests/index.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/events.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/run-custom-build.ts
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/routes.ts
  packages/wrangler/src/user/user.ts
  packages/wrangler/vitest.config.ts
Labels: e2e

#5307 feat(wrangler-d1): Teach wrangler d1 insights about more timePeriods
  .changeset/large-seals-kiss.md
  packages/wrangler/src/__tests__/d1/insights.test.ts
  packages/wrangler/src/d1/insights.ts
Labels: enhancement

#6010 test: add checks of uploads of very large number of Pages assets
  packages/wrangler/src/__tests__/pages/project-upload.test.ts
Labels: contribution

#6025 fix(wrangler): avoid path collisions between performance and Performance polyfills
  .changeset/lazy-cycles-pull.md
  fixtures/nodejs-hybrid-app/src/index.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Labels: e2e

#6024 chore: update workerd and workers-types
  .changeset/dependabot-update-6024.md
  fixtures/nodejs-hybrid-app/package.json
  packages/miniflare/package.json
  pnpm-lock.yaml
Labels: e2e

#6039 fix: hybrid nodejs compat now supports requiring the default export of a CJS module
  .changeset/afraid-mails-kneel.md
  fixtures/nodejs-hybrid-app/src/dep.cjs
  fixtures/nodejs-hybrid-app/src/index.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Labels: e2e

#6040 Update Github Action dependency versions
  .github/actions/create-c3-docs-pr/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/c3-dependabot-versioning-prs.yml
  .github/workflows/c3-e2e-dependabot.yml
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/changesets.yml
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/d1.yml
  .github/workflows/deploy-pages-previews.yml
  .github/workflows/e2e-project-cleanup.yml
  .github/workflows/e2e.yml
  .github/workflows/miniflare-dependabot-versioning-prs.yml
  .github/workflows/prereleases.yml
  .github/workflows/test-and-check.yml
  .github/workflows/test-old-node-error.yml
  .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
  .github/workflows/write-prerelease-comment.yml
Labels: e2e

#5995 Allow do migrations in environments
  .changeset/smooth-pumpkins-breathe.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/pages/functions/tsconfig.json
Labels: e2e

#6046 Normalize more dependencies.
  .changeset/moody-bees-end.md
  .prettierignore
  fixtures/no-bundle-import/package.json
  package.json
  packages/cli/package.json
  packages/create-cloudflare/package.json
  packages/edge-preview-authenticated-proxy/package.json
  packages/edge-preview-authenticated-proxy/src/index.ts
  packages/eslint-config-worker/package.json
  packages/format-errors/package.json
  packages/playground-preview-worker/package.json
  packages/quick-edit-extension/package.json
  packages/turbo-r2-archive/package.json
  packages/workers-playground/package.json
  packages/wrangler/package.json
  patches/toucan-js@3.2.2.patch
  pnpm-lock.yaml
  templates/pages-example-forum-app/package.json
  templates/pages-functions-cors/package.json
  templates/pages-image-sharing/package.json
  templates/pages-plugin-static-forms/package.json
  templates/worker-d1-api/package.json
  templates/worker-d1/package.json
  templates/worker-example-request-scheduler/package.json
  templates/worker-example-wordle/package.json
  templates/worker-mysql/package.json
  templates/worker-openapi/package.json
  templates/worker-postgres/package.json
  templates/worker-prospector/package.json
  templates/worker-r2/package.json
  templates/worker-speedtest/package.json
  templates/worker-turso-ts/package.json
  templates/worker-typescript/package.json
  templates/worker-websocket-durable-objects/package.json
  templates/worker-websocket/package.json
  templates/worker-worktop/package.json
  tools/package.json
  turbo/generators/templates/package.json.hbs
Labels: e2e

#6063 tweak instructions for running e2e tests
  packages/wrangler/e2e/README.md
Labels: e2e

#6048 fix: node compat v2 handle $ in inject preset
  packages/wrangler/src/__tests__/hybrid-nodejs-compat.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Labels: e2e

#6050 Normalize more deps
  .changeset/fifty-waves-fry.md
  fixtures/ai-app/package.json
  fixtures/dev-env/package.json
  fixtures/entrypoints-rpc-tests/package.json
  fixtures/external-durable-objects-app/package.json
  fixtures/external-service-bindings-app/package.json
  fixtures/get-bindings-proxy/package.json
  fixtures/get-platform-proxy/package.json
  fixtures/import-wasm-example/package.json
  fixtures/pages-functions-wasm-app/package.json
  fixtures/pages-workerjs-app/package.json
  fixtures/pages-workerjs-directory/package.json
  fixtures/pages-workerjs-wasm-app/package.json
  fixtures/pages-workerjs-with-config-file-app/package.json
  fixtures/pages-workerjs-with-routes-app/package.json
  fixtures/pages-ws-app/package.json
  fixtures/ratelimit-app/package.json
  packages/eslint-config-worker/package.json
  packages/miniflare/package.json
  packages/miniflare/test/setup.mjs
  packages/pages-shared/package.json
  packages/playground-preview-worker/package.json
  packages/vitest-pool-workers/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
  tools/package.json
Labels: e2e

#5889 [wrangler] Made D1 BEGIN and CASE regex case insensitive
  packages/wrangler/src/__tests__/d1/splitter.test.ts
  packages/wrangler/src/d1/splitter.ts
Labels: awaiting reporter response

#6076 c3: use latest dependencies for hello-world templates
  .changeset/tough-poets-deliver.md
  packages/create-cloudflare/templates/common/js/package.json
  packages/create-cloudflare/templates/common/ts/package.json
  packages/create-cloudflare/templates/hello-world-durable-object/js/package.json
  packages/create-cloudflare/templates/hello-world-durable-object/ts/package.json
  packages/create-cloudflare/templates/hello-world-python/py/package.json
  packages/create-cloudflare/templates/hello-world/js/package.json
  packages/create-cloudflare/templates/hello-world/ts/package.json
  packages/create-cloudflare/templates/openapi/ts/package.json
  packages/create-cloudflare/templates/pre-existing/js/package.json
  packages/create-cloudflare/templates/queues/js/package.json
  packages/create-cloudflare/templates/queues/ts/package.json
  packages/create-cloudflare/templates/scheduled/js/package.json
  packages/create-cloudflare/templates/scheduled/ts/package.json
Labels: e2e

#6108 fix(wrangler): fix failing `versions` e2e tests
  packages/wrangler/e2e/versions.test.ts
Labels: e2e

#6121 fix(wrangler): fix failing versions e2e tests
  packages/wrangler/e2e/versions.test.ts
Labels: e2e

#6116 fix: onBundleStart dependency array
  packages/wrangler/src/dev/dev.tsx
Labels: e2e

#6136 ConfigController defaults
  fixtures/dev-env/tests/index.test.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  pnpm-lock.yaml
Labels: e2e

#6077 test: improve Windows reliability of e2e tests
  .markdownlint.json
  packages/wrangler/e2e/README.md
  packages/wrangler/e2e/c3-integration.test.ts
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/dev-env.test.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/get-platform-proxy.test.ts
  packages/wrangler/e2e/helpers/command.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/helpers/setup.ts
  packages/wrangler/e2e/helpers/wrangler.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/e2e/r2.test.ts
  packages/wrangler/e2e/tsconfig.json
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/e2e/vitest.config.mts
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#6124 startWorker tests
  .changeset/little-dolphins-breathe.md
  fixtures/dev-env/.gitignore
  fixtures/dev-env/package.json
  fixtures/dev-env/tests/index.test.ts
  fixtures/dev-env/tests/tsconfig.json
  fixtures/dev-env/vitest.config.mts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/startWorker.test.ts
  packages/wrangler/e2e/tsconfig.json
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/events.ts
  packages/wrangler/src/api/startDevWorker/index.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  pnpm-lock.yaml
Labels: e2e

#6147 React free dev registry
  .changeset/moody-lies-rest.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/fetch-text.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/dev-registry.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/start-server.ts
  pnpm-lock.yaml
Labels: e2e

#6161 Chain `React`ion
  packages/wrangler/e2e/dev-env.test.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/startWorker.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/helpers/seed.ts
  packages/wrangler/src/__tests__/helpers/teardown.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/index.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/cli.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/experimental-flags.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/tail/index.ts
  packages/wrangler/src/utils/collectKeyValues.ts
  packages/wrangler/src/utils/memoizeGetPort.ts
  packages/wrangler/src/versions/secrets/index.ts
  packages/wrangler/src/versions/upload.ts
  pnpm-lock.yaml
Labels: e2e
