Repository cloudflare/workers-sdk, pull requests merged in 2024-03, with the labels that each got.

#5130 Deploy non-npm packages via changesets
  .changeset/config.json
  .github/workflows/README.md
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/changesets.yml
  .github/workflows/deploy-pages-previews.yml
  .github/workflows/deploy-pages-project.yml
  .github/workflows/deploy-pages-projects.yml
  .github/workflows/prereleases.yml
  .github/workflows/worker-deploy-edge-preview-authenticated-proxy.yml
  .github/workflows/worker-format-errors-deploy.yml
  .github/workflows/worker-playground-preview-deploy-production.yml
  .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
  CONTRIBUTING.md
  packages/prerelease-registry/package.json
  packages/quick-edit/README.md
  packages/workers-playground/README.md
  packages/workers-playground/package.json
  packages/wrangler-devtools/README.md
  packages/wrangler-devtools/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tools/.eslintrc.js
  tools/README.md
  tools/deployments/__tests__/deploy-non-npm-packages.test.ts
  tools/deployments/deploy-non-npm-packages.ts
  tools/package.json
  tools/tsconfig.json
  tools/turbo.json
  tools/vitest.config.ts
  vitest.workspace.ts
Labels: maintenance, e2e

#3099 🧹 chore: move links to old templates repo to point here
  templates/README.md
  templates/examples/cryptocurrency-slack-bot/index.js
  templates/experimental/worker-cobol/README.md
  templates/experimental/worker-emscripten/README.md
  templates/experimental/worker-rust/README.md
  templates/pages-example-forum-app/README.md
  templates/pages-functions-cors/README.md
  templates/pages-image-sharing/README.md
  templates/pages-plugin-static-forms/README.md
  templates/stream/auth/stripe/README.md
  templates/stream/playback/dash-js/README.md
  templates/stream/playback/hls-js/README.md
  templates/stream/playback/shaka-player/README.md
  templates/stream/playback/stream-player/README.md
  templates/stream/playback/video-js/README.md
  templates/stream/playback/vidstack/README.md
  templates/stream/upload/direct-creator-uploads-tus/README.md
  templates/stream/upload/direct-creator-uploads/README.md
  templates/stream/webrtc/README.md
  templates/worker-aws/README.md
  templates/worker-d1-api/README.md
  templates/worker-d1/README.md
  templates/worker-durable-objects/README.md
  templates/worker-example-request-scheduler/README.md
  templates/worker-example-wordle/README.md
  templates/worker-mysql/README.md
  templates/worker-openapi/README.md
  templates/worker-postgres/README.md
  templates/worker-prospector/readme.md
  templates/worker-r2/README.md
  templates/worker-router/README.md
  templates/worker-sites-react/README.md
  templates/worker-sites/README.md
  templates/worker-speedtest/README.md
  templates/worker-typescript/README.md
  templates/worker-websocket-durable-objects/README.md
  templates/worker-websocket/README.md
  templates/worker-worktop/README.md
  templates/worker/README.md
Labels: awaiting Cloudflare response, templates

#5100 Handle multiple set cookie headers
  .changeset/tall-wombats-reply.md
  packages/edge-preview-authenticated-proxy/src/index.ts
  packages/edge-preview-authenticated-proxy/tests/index.test.ts
  packages/playground-preview-worker/src/index.ts
  packages/playground-preview-worker/tests/index.test.ts
Labels: preview:workers-playground, playground-worker

#5007 [KV] Remove `worker-` prefix from kv:namespace create when using wrangler in a pages project or without a `name` property
  .changeset/tall-planets-pull.md
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/kv/helpers.ts
  packages/wrangler/src/kv/index.ts
Labels: breaking change

#5043 Python playground support
  .changeset/famous-phones-type.md
  .github/workflows/deploy-pages-previews.yml
  packages/playground-preview-worker/src/index.ts
  packages/playground-preview-worker/src/user.do.ts
  packages/playground-preview-worker/tests/index.test.ts
  packages/workers-playground/functions/playground/[[route]].ts
  packages/workers-playground/functions/playground/api/[[route]].ts
  packages/workers-playground/generate-default-hash.ts
  packages/workers-playground/generate-default-hashes.ts
  packages/workers-playground/package.json
  packages/workers-playground/src/QuickEditor/QuickEditor.tsx
  packages/workers-playground/src/QuickEditor/defaultHash.ts
  packages/workers-playground/src/QuickEditor/defaultHashes.ts
  packages/workers-playground/src/QuickEditor/getPlaygroundWorker.ts
  packages/workers-playground/src/QuickEditor/module-collection.ts
  packages/workers-playground/src/QuickEditor/useDraftWorker.ts
  packages/workers-playground/welcome/index.py
  packages/workers-playground/welcome/requirements.txt
  packages/workers.new/src/index.ts
  packages/workers.new/tests/index.test.ts
Labels: preview:workers-playground, playground-worker, python

#5059 perf(worker-rust): Add `dev` env for faster local build times
  templates/experimental/worker-rust/Cargo.toml
  templates/experimental/worker-rust/package.json
  templates/experimental/worker-rust/wrangler.toml
Labels: awaiting Cloudflare response

#4930 [D1] default `wrangler d1 execute` to local mode first.
  .changeset/hungry-cougars-tie.md
  packages/wrangler/src/__tests__/d1/execute.test.ts
  packages/wrangler/src/__tests__/d1/migrate.test.ts
  packages/wrangler/src/__tests__/d1/utils.test.ts
  packages/wrangler/src/d1/execute.tsx
  packages/wrangler/src/d1/migrations/apply.tsx
  packages/wrangler/src/d1/migrations/create.tsx
  packages/wrangler/src/d1/migrations/helpers.ts
  packages/wrangler/src/d1/migrations/list.tsx
  packages/wrangler/src/d1/migrations/options.ts
Labels: breaking change

#5035 wrangler: cleanup standard pricing check after legacy usage model deprecation
  packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
  packages/wrangler/src/__tests__/standard-pricing.test.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/versions/index.ts
Labels: blocked, internal

#5227 [C3] Fix bad changeset
  .changeset/friendly-jobs-serve.md
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
Labels: c3

#5209 refactor: use `esbuild-plugins-node-modules-polyfill`
  .changeset/hungry-ladybugs-smash.md
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  pnpm-lock.yaml
  templates/worker-aws/package.json
  templates/worker-aws/worktop.config.js
Labels: e2e

#5099 feat: cli flag to disable interactive dev session
  .changeset/tender-buckets-confess.md
  packages/wrangler/src/__tests__/dev.test.tsx
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/pages/dev.ts
Labels: awaiting reporter response

#5317 Deprecate pages dev's proxy features
  .changeset/tidy-dodos-pull.md
  fixtures/pages-dev-proxy-with-script/tests/index.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#5329 Add e2e tests for Versions
  CONTRIBUTING.md
  packages/cli/interactive.ts
  packages/wrangler/e2e/versions.test.ts
Labels: e2e

#5231 wrangler support Queues http-pull consumer config and cli
  .changeset/fuzzy-mangos-sparkle.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/queues.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/queues/cli/commands/consumer/http-pull/add.ts
  packages/wrangler/src/queues/cli/commands/consumer/http-pull/index.ts
  packages/wrangler/src/queues/cli/commands/consumer/http-pull/remove.ts
  packages/wrangler/src/queues/cli/commands/consumer/index.ts
  packages/wrangler/src/queues/cli/commands/consumer/worker/add.ts
  packages/wrangler/src/queues/cli/commands/consumer/worker/index.ts
  packages/wrangler/src/queues/cli/commands/consumer/worker/remove.ts
  packages/wrangler/src/queues/cli/commands/index.ts
  packages/wrangler/src/queues/client.ts
Labels: blocked, internal

#5330 chore(wrangler): Add `pages dev` tests
  .github/workflows/e2e.yml
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/pages/dev.test.ts
Labels: e2e

#5310 [wrangler] Watch the entire module root + watch requirements.txt
  .changeset/green-jokes-decide.md
  .changeset/thin-penguins-drum.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/setup.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/dev/use-esbuild.ts
Labels: e2e

#5353 [pages] Update `pages functions build` to include config
  .changeset/swift-pears-carry.md
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
  packages/wrangler/src/api/pages/deploy.tsx
  packages/wrangler/src/pages/build.ts
Labels: ldw-exempt

#5284 Config file support in `pages dev`
  .changeset/silly-countries-notice.md
  fixtures/pages-functions-with-config-file-app/README.md
  fixtures/pages-functions-with-config-file-app/functions/celebrate.ts
  fixtures/pages-functions-with-config-file-app/functions/holiday.ts
  fixtures/pages-functions-with-config-file-app/package.json
  fixtures/pages-functions-with-config-file-app/public/_routes.json
  fixtures/pages-functions-with-config-file-app/public/index.html
  fixtures/pages-functions-with-config-file-app/tests/index.test.ts
  fixtures/pages-functions-with-config-file-app/tests/tsconfig.json
  fixtures/pages-functions-with-config-file-app/tsconfig.json
  fixtures/pages-functions-with-config-file-app/vitest.config.ts
  fixtures/pages-functions-with-config-file-app/wrangler.toml
  fixtures/pages-workerjs-with-config-file-app/README.md
  fixtures/pages-workerjs-with-config-file-app/package.json
  fixtures/pages-workerjs-with-config-file-app/public/_routes.json
  fixtures/pages-workerjs-with-config-file-app/public/_worker.js
  fixtures/pages-workerjs-with-config-file-app/public/index.html
  fixtures/pages-workerjs-with-config-file-app/tests/index.test.ts
  fixtures/pages-workerjs-with-config-file-app/tests/tsconfig.json
  fixtures/pages-workerjs-with-config-file-app/tsconfig.json
  fixtures/pages-workerjs-with-config-file-app/vitest.config.ts
  fixtures/pages-workerjs-with-config-file-app/wrangler.toml
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/config-validation-pages.test.ts
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/__tests__/pages/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/config/validation-pages.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/utils/mergeWithOverride.ts
  pnpm-lock.yaml
Labels: e2e, ldw-exempt

#5401 update e2e snapshots for versions commands
  packages/wrangler/e2e/versions.test.ts
Labels: e2e

#5404 Update CONTRIBUTING.md communicate type
  CONTRIBUTING.md
Labels: ldw-exempt

#5369 Use queue name for event notification config
  .changeset/rich-oranges-attack.md
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/r2/helpers.ts
  packages/wrangler/src/r2/index.ts
Labels: ldw-exempt

#5416 Improvements to R2 notification commands
  .changeset/yellow-wolves-talk.md
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/r2/helpers.ts
  packages/wrangler/src/r2/index.ts
Labels: ldw-exempt

#5258 wrangler: Try to URL decode hyperdrive connection string components before sending them to API
  .changeset/twenty-laws-mix.md
  packages/miniflare/src/plugins/hyperdrive/index.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/hyperdrive.test.ts
  packages/wrangler/src/hyperdrive/create.ts
  packages/wrangler/src/hyperdrive/update.ts
Labels: ldw-exempt

#4932 Add private host option for private networks support in hyperdrive
  .changeset/bright-planets-unite.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/hyperdrive.test.ts
  packages/wrangler/src/hyperdrive/client.ts
  packages/wrangler/src/hyperdrive/create.ts
  packages/wrangler/src/hyperdrive/update.ts
Labels: ldw-exempt

#5427 update e2e snapshots
  packages/wrangler/e2e/c3-integration.test.ts
  packages/wrangler/e2e/deployments.test.ts
Labels: e2e

#5410 C3: Adapt Astro c3 flow to their v10 Cloudflare adapter
  .changeset/large-rice-bow.md
  packages/create-cloudflare/templates/astro/c3.ts
  packages/create-cloudflare/templates/astro/snippets/runtimeDeclaration.ts
Labels: ldw-exempt

#5425 [D1] initial `wrangler d1 export`
  .changeset/wicked-balloons-compare.md
  packages/wrangler/src/__tests__/d1/d1.test.ts
  packages/wrangler/src/d1/export.ts
  packages/wrangler/src/d1/index.ts
Labels: ldw-exempt
