Repository cloudflare/workers-sdk, pull requests merged in 2024-12, with the labels that each got.

#7228 Remove v2 warning
  packages/wrangler/README.md
Labels: breaking change

#6884 chore: update esbuild
  .changeset/proud-otters-bow.md
  .github/workflows/test-and-check.yml
  fixtures/pages-workerjs-directory/public/_worker.js/index.js
  fixtures/wildcard-modules/package.json
  fixtures/wildcard-modules/src/common.cjs
  fixtures/wildcard-modules/src/dep.ts
  fixtures/wildcard-modules/src/dynamic.js
  fixtures/wildcard-modules/src/index.ts
  fixtures/wildcard-modules/src/lang/en.js
  fixtures/wildcard-modules/src/lang/fr.js
  fixtures/wildcard-modules/src/text.d.ts
  fixtures/wildcard-modules/src/text.txt
  fixtures/wildcard-modules/test/index.test.ts
  fixtures/wildcard-modules/test/tsconfig.json
  fixtures/wildcard-modules/tsconfig.json
  fixtures/wildcard-modules/turbo.json
  fixtures/wildcard-modules/vitest.config.mts
  fixtures/wildcard-modules/wrangler.toml
  package.json
  packages/cli/package.json
  packages/create-cloudflare/package.json
  packages/miniflare/package.json
  packages/quick-edit-extension/package.json
  packages/vitest-pool-workers/package.json
  packages/workers-shared/package.json
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/middleware.test.ts
  packages/wrangler/src/deployment-bundle/apply-middleware.ts
  pnpm-lock.yaml
Labels: breaking change, e2e

#7352 Remove deprecated commands & config
  .changeset/major-remove-args-config.md
  .changeset/major-remove-generate.md
  .changeset/major-remove-init.md
  .changeset/major-remove-legacy-assets.md
  .changeset/major-remove-publish.md
  .changeset/major-remove-version.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/config-validation-pages.test.ts
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/core/command-registration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/generate.test.ts
  packages/wrangler/src/__tests__/guess-worker-format.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/__tests__/kv.local.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/middleware.test.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/__tests__/package-manager.test.ts
  packages/wrangler/src/__tests__/route.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/__tests__/version.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/guess-worker-format.ts
  packages/wrangler/src/deprecated/index.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/dev.ts
  packages/wrangler/src/dev/remote.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/generate/index.ts
  packages/wrangler/src/git-client.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/package-manager.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/sites.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/templates/middleware/middleware-serve-static-assets.d.ts
  packages/wrangler/templates/middleware/middleware-serve-static-assets.ts
Labels: breaking change, e2e

#7415 refactor: move projectRoot computation to config validation
  fixtures/import-npm/package-lock.json
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/find-additional-modules.test.ts
  packages/wrangler/src/__tests__/get-entry.test.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/validation-pages.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/d1/execute.ts
  packages/wrangler/src/d1/migrations/helpers.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/find-additional-modules.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/deployment-bundle/resolve-entry.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-pr-description-validation

#7358 Version Packages
  .changeset/c3-frameworks-update-7359.md
  .changeset/cuddly-chicken-visit.md
  .changeset/dependabot-update-7418.md
  .changeset/four-zebras-deliver.md
  .changeset/gold-pandas-yell.md
  .changeset/gorgeous-paws-compare.md
  .changeset/hip-penguins-kiss.md
  .changeset/little-suns-bathe.md
  .changeset/lucky-carrots-sparkle.md
  .changeset/purple-coats-lick.md
  .changeset/seven-eels-reflect.md
  .changeset/shy-cups-grin.md
  .changeset/silly-news-compete.md
  .changeset/six-coats-rule.md
  .changeset/sour-pugs-agree.md
  .changeset/witty-dolphins-appear.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7420 ci: don't watch for changes on the workers-shared test:ci job
  packages/workers-shared/package.json
Labels: skip-pr-description-validation

#7421 refactor: remove missed redundant computation of `projectRoot`
  fixtures/workflow-multiple/package.json
  fixtures/workflow/package.json
  packages/wrangler/src/__tests__/get-entry.test.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/deployment-bundle/entry.ts
Labels: skip-pr-description-validation

#7385 feat(wrangler): add inherit bindings support
  .changeset/tall-flowers-move.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#7343 fix: C3 experimental template for Solid now uses correct preset
  .changeset/quick-bananas-refuse.md
  packages/create-cloudflare/templates-experimental/solid/c3.ts
  packages/create-cloudflare/templates-experimental/solid/templates/wrangler.toml
Labels: e2e

#7426 fix: allow the asset directory to be omitted in Wrangler config for commands that don't need it
  .changeset/forty-gifts-grab.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation-helpers.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/triggers/index.ts
  packages/wrangler/src/versions/index.ts
Labels: e2e

#7332 fix: C3 experimental template for Nuxt now uses correct preset
  .changeset/stale-poets-deny.md
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/templates-experimental/nuxt/c3.ts
  packages/create-cloudflare/templates-experimental/nuxt/templates/cloudflare-preset/nitro.config.ts
  packages/create-cloudflare/templates-experimental/nuxt/templates/wrangler.toml
Labels: e2e

#7437 chore: convert versions and versions secret to createCommand
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/versions/deploy.ts
  packages/wrangler/src/versions/deployments/list.ts
  packages/wrangler/src/versions/deployments/status.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/list.ts
  packages/wrangler/src/versions/rollback/index.ts
  packages/wrangler/src/versions/secrets/bulk.ts
  packages/wrangler/src/versions/secrets/delete.ts
  packages/wrangler/src/versions/secrets/index.ts
  packages/wrangler/src/versions/secrets/list.ts
  packages/wrangler/src/versions/secrets/put.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/src/versions/utils/config.ts
  packages/wrangler/src/versions/view.ts
Labels: e2e, no-changeset-required

#7431 chore(wrangler): update unenv dependency version
  .changeset/curly-queens-breathe.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#7446 Pbd/revert-project-root-refactoring
  .changeset/proud-toes-travel.md
  fixtures/import-npm/package-lock.json
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/find-additional-modules.test.ts
  packages/wrangler/src/__tests__/get-entry.test.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/validation-pages.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/d1/execute.ts
  packages/wrangler/src/d1/migrations/helpers.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/find-additional-modules.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/deployment-bundle/resolve-entry.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#7450 fix: ensure that version secrets commands do not write wrangler config warnings
  .changeset/yellow-cooks-battle.md
  packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
  packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
  packages/wrangler/src/__tests__/versions/secrets/list.test.ts
  packages/wrangler/src/__tests__/versions/secrets/put.test.ts
  packages/wrangler/src/__tests__/versions/secrets/utils.ts
  packages/wrangler/src/api/pages/deploy.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/pages/build-env.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/deploy.ts
  packages/wrangler/src/pages/secret/index.ts
  packages/wrangler/src/versions/secrets/bulk.ts
  packages/wrangler/src/versions/secrets/delete.ts
  packages/wrangler/src/versions/secrets/list.ts
  packages/wrangler/src/versions/secrets/put.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/src/versions/utils/config.ts
Labels: e2e

#7445 Wranger dev support with serve_directly
  .changeset/strong-kings-visit.md
  fixtures/workers-with-assets-serve-directly/README.md
  fixtures/workers-with-assets-serve-directly/package.json
  fixtures/workers-with-assets-serve-directly/public/index.html
  fixtures/workers-with-assets-serve-directly/src/index.ts
  fixtures/workers-with-assets-serve-directly/tests/index.test.ts
  fixtures/workers-with-assets-serve-directly/tests/tsconfig.json
  fixtures/workers-with-assets-serve-directly/tsconfig.json
  fixtures/workers-with-assets-serve-directly/wrangler.toml
  packages/workers-shared/router-worker/tests/index.test.ts
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/src/assets.ts
  pnpm-lock.yaml
Labels: e2e

#7454 refactor: Ensure that unstable type exports are all prefixed with `Unstable_` rather than just `Unstable`
  .changeset/breezy-cats-matter.md
  .changeset/lemon-panthers-arrive.md
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/local-mode-tests/tests/module.test.ts
  fixtures/local-mode-tests/tests/ports.test.ts
  fixtures/local-mode-tests/tests/specified-port.test.ts
  fixtures/local-mode-tests/tests/sw.test.ts
  fixtures/no-bundle-import/src/index.test.ts
  packages/edge-preview-authenticated-proxy/tests/index.test.ts
  packages/vitest-pool-workers/src/config/pages.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/index.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/cli.ts
  packages/wrangler/templates/init-tests/test-vitest-new-worker.ts
Labels: e2e

#7453 fix: remove an unnecessary await for metrics.sendMetricsEvent
  packages/wrangler/src/versions/upload.ts
Labels: no-changeset-required

#7463 Mark `wrangler versions` as stable
  .changeset/thick-nails-switch.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/versions/deploy.ts
  packages/wrangler/src/versions/list.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/src/versions/view.ts
Labels: e2e

#7448 WfP Assets support
  .changeset/smart-plants-wash.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#7473 ci: extend the timeout on BundleController.test.ts "custom build" test to reduce CI flakiness
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
Labels: skip-pr-description-validation, no-changeset-required

#7439 Version Packages
  .changeset/breezy-cats-matter.md
  .changeset/curly-queens-breathe.md
  .changeset/dependabot-update-7464.md
  .changeset/eighty-lies-sort.md
  .changeset/forty-gifts-grab.md
  .changeset/lemon-panthers-arrive.md
  .changeset/lovely-kiwis-grab.md
  .changeset/metal-feet-carry.md
  .changeset/perfect-cougars-lie.md
  .changeset/proud-toes-travel.md
  .changeset/quick-bananas-refuse.md
  .changeset/smart-plants-wash.md
  .changeset/stale-poets-deny.md
  .changeset/strong-kings-visit.md
  .changeset/tall-flowers-move.md
  .changeset/thick-nails-switch.md
  .changeset/unlucky-teachers-call.md
  .changeset/yellow-cooks-battle.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7472 chore: split readConfig and readPages config to simplify and lower responsibilities
  packages/wrangler/src/api/pages/deploy.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/pages/build-env.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/deploy.ts
  packages/wrangler/src/pages/secret/index.ts
Labels: e2e, no-changeset-required

#7392 `--local` by default for `wrangler kv` & `wrangler r2`
  .changeset/funny-pets-punch.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/r2.test.ts
  packages/wrangler/src/__tests__/kv.local.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/r2.local.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/r2/object.ts
Labels: breaking change, e2e

#7483 Version Packages
  .changeset/angry-apricots-swim.md
  .changeset/c3-frameworks-update-7257.md
  .changeset/c3-frameworks-update-7419.md
  .changeset/c3-frameworks-update-7489.md
  .changeset/fifty-dots-end.md
  .changeset/funny-impalas-run.md
  .changeset/old-garlics-judge.md
  .changeset/thirty-turkeys-turn.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/versions/versions.list.test.ts
  packages/wrangler/src/__tests__/versions/versions.view.test.ts
Labels: skip-pr-description-validation

#7502 chore(create-cloudflare): Make assertions in config tests more exhaustive
  packages/create-cloudflare/src/wrangler/__tests__/config.test.ts
Labels: no-changeset-required

#7506 feat: notify users when they are running C3 in experimental mode
  .changeset/smooth-vans-share.md
  packages/create-cloudflare/src/__tests__/dialog.test.ts
  packages/create-cloudflare/src/cli.ts
  packages/create-cloudflare/src/dialog.ts
Labels: awaiting reporter response, c3, e2e

#7494 chore: remove unnecessary svelteKit C3 variants
  packages/create-cloudflare/templates-experimental/svelte/c3.ts
  packages/create-cloudflare/templates-experimental/svelte/templates/static/.assetsignore
  packages/create-cloudflare/templates-experimental/svelte/templates/wrangler.toml
  packages/create-cloudflare/templates-experimental/svelte/ts/static/.assetsignore
  packages/create-cloudflare/templates-experimental/svelte/ts/wrangler.toml
  packages/create-cloudflare/templates/svelte/c3.ts
  packages/create-cloudflare/templates/svelte/templates/wrangler.toml
  packages/create-cloudflare/templates/svelte/ts/wrangler.toml
Labels: c3, e2e, no-changeset-required

#7500 Version Packages
  .changeset/c3-frameworks-update-7248.md
  .changeset/c3-frameworks-update-7503.md
  .changeset/c3-frameworks-update-7505.md
  .changeset/five-dryers-swim.md
  .changeset/large-mails-relax.md
  .changeset/smooth-vans-share.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7501 chore: delete test helper worker scripts
  packages/wrangler/src/__tests__/api-dev.test.ts
  packages/wrangler/src/__tests__/helpers/worker-scripts/hello-world-worker.js
  packages/wrangler/src/__tests__/helpers/worker-scripts/hello-world-wrangler.toml
Labels: no-changeset-required

#7526 Update create-remix
  .changeset/new-shoes-deny.md
  packages/create-cloudflare/src/frameworks/package.json
Labels: e2e

#7527 Increase dependabot PR limit to 10
  .github/dependabot.yml
Labels: skip-pr-description-validation

#7478 fix: ensure that non-inherited fields are not removed when using an inferred named environment
  .changeset/khaki-steaks-sniff.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/config/validation-helpers.ts
  packages/wrangler/src/config/validation.ts
Labels: e2e

#7517 ci: skip Miniflare browser CA certificate tests during local testing
  packages/miniflare/test/index.spec.ts
Labels: skip-pr-description-validation, no-changeset-required

#7515 test: try harder to delete Workers Sites KV store in e2e tests
  packages/wrangler/e2e/dev-with-resources.test.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required

#7485 Don't require Hyperdrive local connection string when using wrangler dev --remote
  .changeset/nervous-jeans-obey.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/dev.ts
Labels: e2e

#7427 feat(wrangler): identify draft and inherit bindings and provision draft ones
  .changeset/swift-bulldogs-repeat.md
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-kv.ts
  packages/wrangler/src/__tests__/provision.test.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/d1/create.ts
  packages/wrangler/src/d1/list.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/kv/helpers.ts
Labels: e2e

#7523 cloudchamber/create: always print deployment and placement ID
  packages/wrangler/src/cloudchamber/cli/deployments.ts
  packages/wrangler/src/cloudchamber/cli/index.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/create.ts
Labels: no-changeset-required

#7545 Revert "Don't require Hyperdrive local connection string when using wrangler dev --remote"
  .changeset/nervous-jeans-obey.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/dev.ts
Labels: e2e, skip-pr-description-validation

#7559 Add test command for the extension
  .vscode/launch.json
  packages/cloudflare-workers-bindings-extension/package.json
  packages/cloudflare-workers-bindings-extension/src/extension.ts
Labels: skip-pr-description-validation

#7514 Version Packages
  .changeset/c3-frameworks-update-7504.md
  .changeset/c3-frameworks-update-7512.md
  .changeset/c3-frameworks-update-7513.md
  .changeset/c3-frameworks-update-7530.md
  .changeset/c3-frameworks-update-7531.md
  .changeset/clean-peas-exist.md
  .changeset/fluffy-rules-listen.md
  .changeset/happy-ears-cough.md
  .changeset/heavy-boxes-fly.md
  .changeset/hot-ads-return.md
  .changeset/khaki-steaks-sniff.md
  .changeset/late-phones-stare.md
  .changeset/lazy-files-sneeze.md
  .changeset/lovely-fireants-roll.md
  .changeset/new-shoes-deny.md
  .changeset/shy-waves-prove.md
  .changeset/swift-bulldogs-repeat.md
  packages/cloudflare-workers-bindings-extension/CHANGELOG.md
  packages/cloudflare-workers-bindings-extension/package.json
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7486 Limit status bot repos
  .changeset/afraid-cooks-switch.md
  packages/devprod-status-bot/src/index.ts
Labels: skip-pr-description-validation

#7541 chore(wrangler): update unenv dependency version
  .changeset/chilled-needles-notice.md
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  pnpm-lock.yaml
Labels: e2e

#7499 chore: convert deployments to createCommand
  packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/versions/deployments/index.ts
  packages/wrangler/src/versions/deployments/list.ts
  packages/wrangler/src/versions/deployments/status.ts
  packages/wrangler/src/versions/deployments/view.ts
Labels: e2e, no-changeset-required

#7565 update the astro experimental template not to unnecessarily specify `v2` for `nodejs_compat`
  .changeset/stale-bananas-sort.md
  packages/create-cloudflare/templates-experimental/astro/templates/ts/wrangler.toml
Labels: e2e

#7370 import unenv-preset
  package.json
  packages/unenv-preset/.eslintrc.js
  packages/unenv-preset/LICENSE-APACHE
  packages/unenv-preset/LICENSE-MIT
  packages/unenv-preset/README.md
  packages/unenv-preset/build.config.ts
  packages/unenv-preset/package.json
  packages/unenv-preset/src/index.ts
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/async_hooks/index.ts
  packages/unenv-preset/src/runtime/node/console/index.ts
  packages/unenv-preset/src/runtime/node/crypto/index.ts
  packages/unenv-preset/src/runtime/node/module/index.ts
  packages/unenv-preset/src/runtime/node/perf_hooks/index.ts
  packages/unenv-preset/src/runtime/node/process/index.ts
  packages/unenv-preset/src/runtime/node/timers/index.ts
  packages/unenv-preset/src/runtime/node/util/index.ts
  packages/unenv-preset/tsconfig.json
  packages/unenv-preset/turbo.json
  pnpm-lock.yaml
  tools/deployments/__tests__/validate-changesets.test.ts
Labels: e2e, no-changeset-required

#7498 chore: convert rollback to createCommand
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/versions/rollback/index.ts
Labels: e2e, no-changeset-required

#7522 feat: add support for custom unenv resolve path
  .changeset/fluffy-eggs-film.md
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
Labels: e2e

#7567 Version Packages
  .changeset/afraid-cooks-switch.md
  .changeset/c3-frameworks-update-7511.md
  .changeset/c3-frameworks-update-7557.md
  .changeset/chilled-needles-notice.md
  .changeset/fluffy-eggs-film.md
  .changeset/green-socks-trade.md
  .changeset/polite-dragons-compete.md
  .changeset/poor-chefs-kneel.md
  .changeset/sour-scissors-teach.md
  .changeset/stale-bananas-sort.md
  .changeset/wise-pens-walk.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/devprod-status-bot/CHANGELOG.md
  packages/devprod-status-bot/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7380 feat(wrangler): Add remote mode support for Workers + Assets
  .changeset/strange-tips-lick.md
  packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/dev/remote.ts
Labels: e2e

#7585 chore(wrangler): Fix failing e2e tests
  packages/wrangler/e2e/dev.test.ts
Labels: e2e, no-changeset-required

#7583 Revert "feat: add support for custom unenv resolve path"
  .changeset/thick-ties-glow.md
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#7574 Version Packages
  .changeset/blue-laws-bathe.md
  .changeset/early-baboons-fly.md
  .changeset/selfish-yaks-hope.md
  .changeset/strange-tips-lick.md
  .changeset/thick-ties-glow.md
  .changeset/thirty-windows-prove.md
  packages/cloudflare-workers-bindings-extension/CHANGELOG.md
  packages/cloudflare-workers-bindings-extension/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7580 cleanup(fixtures): add missing dependencies to packages.json
  fixtures/additional-modules/package.json
  fixtures/ai-app/package.json
  fixtures/asset-config/package.json
  fixtures/durable-objects-app/package.json
  fixtures/entrypoints-rpc-tests/package.json
  fixtures/get-platform-proxy/package.json
  fixtures/import-wasm-example/package.json
  fixtures/interactive-dev-tests/package.json
  fixtures/local-mode-tests/package.json
  fixtures/no-bundle-import/package.json
  fixtures/node-app-pages/package.json
  fixtures/nodejs-als-app/package.json
  fixtures/nodejs-hybrid-app/package.json
  fixtures/pages-d1-shim/package.json
  fixtures/pages-dev-proxy-with-script/package.json
  fixtures/pages-functions-app/package.json
  fixtures/pages-functions-wasm-app/package.json
  fixtures/pages-functions-with-config-file-app/package.json
  fixtures/pages-functions-with-routes-app/package.json
  fixtures/pages-nodejs-v2-compat/package.json
  fixtures/pages-plugin-mounted-on-root-app/package.json
  fixtures/pages-proxy-app/package.json
  fixtures/pages-simple-assets/package.json
  fixtures/pages-workerjs-and-functions-app/package.json
  fixtures/pages-workerjs-app/package.json
  fixtures/pages-workerjs-directory/package.json
  fixtures/pages-workerjs-wasm-app/package.json
  fixtures/pages-workerjs-with-config-file-app/package.json
  fixtures/pages-workerjs-with-routes-app/package.json
  fixtures/pages-ws-app/package.json
  fixtures/ratelimit-app/package.json
  fixtures/type-generation/package.json
  fixtures/worker-app/package.json
  fixtures/workers-with-assets-only/package.json
  fixtures/workers-with-assets-serve-directly/package.json
  fixtures/workers-with-assets/package.json
  fixtures/workflow-multiple/package.json
  fixtures/workflow/package.json
  pnpm-lock.yaml
Labels: e2e, no-changeset-required

#7537 Provide validation around experimental_serve_directly usage
  .changeset/swift-zebras-guess.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/assets.ts
Labels: e2e

#7425 feat(wrangler): DX optimisations in `wrangler dev --remote`
  .changeset/quick-wombats-battle.md
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
Labels: e2e

#7568 Add warning for smart placement w/assets
  .changeset/tidy-kiwis-arrive.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/assets.ts
Labels: e2e

#7575 Make workflow `instance.status()` return output equal to production workflows
  .changeset/great-flowers-compete.md
  fixtures/workflow-multiple/src/index.ts
  fixtures/workflow-multiple/tests/index.test.ts
  fixtures/workflow/src/index.ts
  fixtures/workflow/tests/index.test.ts
  packages/miniflare/test/plugins/workflows/index.spec.ts
  packages/workflows-shared/src/binding.ts
  packages/workflows-shared/src/engine.ts
Labels: e2e

#7599 Update slimy-dots-hope.md
  .changeset/slimy-dots-hope.md
Labels: skip-pr-description-validation, no-changeset-required

#7601 Version Packages
  .changeset/five-poems-own.md
  .changeset/tender-cats-hammer.md
  .changeset/tough-tables-sleep.md
  .github/workflows/changesets.yml
  packages/cloudflare-workers-bindings-extension/CHANGELOG.md
  packages/cloudflare-workers-bindings-extension/package.json
  tools/deployments/__tests__/deploy-non-npm-packages.test.ts
Labels: skip-pr-description-validation

#7604 feat(wrangler): Capture Workers with static assets in the telemetry data
  .changeset/long-houses-mate.md
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/metrics/metrics-config.ts
  packages/wrangler/src/metrics/metrics-dispatcher.ts
  packages/wrangler/src/metrics/types.ts
Labels: e2e

#7581 Update unenv preset
  .changeset/chilled-mugs-fail.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/src/unenv-preset.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/unenv-preset/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#7610 fix: bug issue template
  .github/ISSUE_TEMPLATE/bug-template.yaml
Labels: no-changeset-required

#7614 chore(wrangler): update unenv dependency version
  .changeset/nice-pandas-wait.md
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/unenv/unenv.test.ts
  pnpm-lock.yaml
Labels: e2e

#7616 chore: pin `@opennextjs/cloudflare` to 0.2.x
  packages/create-cloudflare/templates-experimental/next/c3.ts
Labels: e2e, no-changeset-required

#7638 fix and update experimental Next.js template to work on `@opennextjs/cloudflare@0.3.x`
  .changeset/gorgeous-kids-protect.md
  packages/create-cloudflare/.gitignore
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/templates-experimental/next/c3.ts
  packages/create-cloudflare/templates-experimental/next/templates/.dev.vars
  packages/create-cloudflare/templates-experimental/next/templates/.gitignore
  packages/create-cloudflare/templates-experimental/next/templates/open-next.config.ts
  packages/create-cloudflare/templates-experimental/next/templates/wrangler.toml
Labels: e2e

#7649 chore: update workflow default node version
  .github/actions/install-dependencies/action.yml
Labels: e2e, no-changeset-required
