Repository cloudflare/workers-sdk, pull requests merged in 2024-11, with the labels that each got.

#7134 Change Pipelines to use name instead of id
  .changeset/friendly-ears-breathe.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/init.ts
Labels: e2e

#7020 chore: move printWranglerBanner for secret delete into handler
  .changeset/giant-bottles-trade.md
  packages/wrangler/src/secret/index.ts
Labels: skip-pr-description-validation

#7165 chore: mark pipeline bindings e2e test should fail
  packages/wrangler/e2e/dev-with-resources.test.ts
Labels: e2e, no-changeset-required

#7164 Fix `--test-scheduled` with custom builds & `--x-dev-env`
  .changeset/sweet-toes-check.md
  packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e, start-dev-worker

#7147 Version Packages
  .changeset/c3-frameworks-update-6973.md
  .changeset/c3-frameworks-update-7146.md
  .changeset/c3-frameworks-update-7148.md
  .changeset/c3-frameworks-update-7161.md
  .changeset/c3-frameworks-update-7167.md
  .changeset/c3-frameworks-update-7177.md
  .changeset/famous-chairs-sin.md
  .changeset/friendly-ears-breathe.md
  .changeset/giant-bottles-trade.md
  .changeset/good-eggs-lay.md
  .changeset/little-lamps-provide.md
  .changeset/selfish-readers-exercise.md
  .changeset/sweet-toes-check.md
  .changeset/tame-dryers-end.md
  .changeset/tricky-schools-heal.md
  .changeset/violet-zoos-obey.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#7162 chore: add ability to use DevTools preview with Playground Preview
  .github/workflows/deploy-pages-previews.yml
  packages/workers-playground/src/QuickEditor/DevtoolsIframe.tsx
  packages/workers-playground/turbo.json
  packages/wrangler-devtools/Makefile
  packages/wrangler-devtools/package.json
Labels: preview:workers-playground, preview:wrangler-devtools, no-changeset-required

#7182 Handle new D1 workerd behaviour in Miniflare's tests
  packages/miniflare/test/plugins/d1/suite.ts
Labels: no-changeset-required

#7172 Cleanup dev registry messaging
  .changeset/large-otters-search.md
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/dev-registry.test.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/logger.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/versions/deploy.ts
  packages/wrangler/src/versions/index.ts
Labels: e2e

#7109 Rename the framework name
  .changeset/happy-items-buy.md
  packages/create-cloudflare/templates-experimental/svelte/c3.ts
  packages/create-cloudflare/templates/svelte/c3.ts
Labels: e2e

#7169 Remove special handling for 'Failed to start ProxyWorker or InspectorProxyWorker'
  .changeset/famous-keys-walk.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/command.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
Labels: e2e

#7137 feat: update devtools patches and show performance tab
  .changeset/famous-birds-remain.md
  .gitignore
  .prettierignore
  packages/wrangler-devtools/Makefile
  packages/wrangler-devtools/patches/0001-Expand-Browser-support-make-it-work-in-Firefox-Safar.patch
  packages/wrangler-devtools/patches/0001-Support-viewing-files-over-the-network.patch
  packages/wrangler-devtools/patches/0002-Setup-Cloudflare-devtools-target-type.patch
  packages/wrangler-devtools/patches/0002-Show-fallback-image-on-Safari.patch
  packages/wrangler-devtools/patches/0003-Add-ping-to-improve-connection-stability.-Without-th.patch
  packages/wrangler-devtools/patches/0003-Support-previewing-subrequest-responses.patch
  packages/wrangler-devtools/patches/0004-Better-Firefox-support-for-network-tab.patch
  packages/wrangler-devtools/patches/0004-Support-viewing-source-files-over-the-network.-This-.patch
  packages/wrangler-devtools/patches/0005-Remove-unsupported-network-UI.patch
  packages/wrangler-devtools/patches/0005-Support-forcing-the-devtools-theme-via-a-query-param.patch
  packages/wrangler-devtools/patches/0006-All-about-the-network-tab.patch
  packages/wrangler-devtools/patches/0006-Remove-unsupported-profiler-UI.patch
  packages/wrangler-devtools/patches/0007-Limit-heap-profiling-modes-available.patch
  packages/wrangler-devtools/patches/0007-Support-theme-url-parameter-for-forcing-the-theme-fr.patch
  packages/wrangler-devtools/patches/0008-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
  packages/wrangler-devtools/patches/0008-Use-the-worker-name-as-the-title-for-the-Javascript-.patch
  packages/wrangler-devtools/patches/0009-Fallback-to-location-for-domain.patch
  packages/wrangler-devtools/patches/0010-Hide-unsupported-settings-UI.patch
  packages/wrangler-devtools/patches/0012-Support-sourcemaps.patch
  packages/wrangler-devtools/patches/0013-Enable-debugger-when-query-parameter-debugger-is-tru.patch
  packages/wrangler-devtools/patches/0014-Show-Profiling-panel.patch
Labels: preview:workers-playground, preview:wrangler-devtools

#7192 chore: add more useful information in the PR coment for previews
  .github/workflows/deploy-pages-previews.yml
Labels: preview:workers-playground, preview:wrangler-devtools, no-changeset-required

#7198 Update team bot
  packages/devprod-status-bot/src/index.ts
Labels: no-changeset-required

#7203 fix(wrangler): fix failing R2 e2e test
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/r2.test.ts
Labels: e2e, no-changeset-required

#7224 Version Packages
  .changeset/late-guests-end.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7111 chore: use upload-artifact@v4 for C3 e2e tests
  .github/actions/run-c3-e2e/action.yml
  .github/workflows/c3-e2e-dependabot.yml
  .github/workflows/c3-e2e-experimental.yml
  .github/workflows/c3-e2e.yml
  packages/create-cloudflare/turbo.json
Labels: no-changeset-required

#7222 Update issues.yml
  .github/workflows/issues.yml
Labels: no-changeset-required

#6569 Run deploy interactively in C3
  .changeset/smart-drinks-joke.md
  packages/create-cloudflare/src/__tests__/deploy.test.ts
  packages/create-cloudflare/src/deploy.ts
Labels: skip-pr-description-validation

#7239 Revert "Open devtools in default browser"
  .changeset/hungry-hornets-taste.md
  packages/wrangler/src/dev/inspect.ts
Labels: skip-pr-description-validation

#7234 Version Packages
  .changeset/c3-frameworks-update-7217.md
  .changeset/c3-frameworks-update-7218.md
  .changeset/c3-frameworks-update-7219.md
  .changeset/smart-drinks-joke.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
Labels: skip-pr-description-validation

#7201 Add support for Tail Consumers with Assets
  .changeset/nice-chefs-hang.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/assets.ts
Labels: e2e

#7245 docs: better wording on DevTools readme
  packages/wrangler-devtools/README.md
Labels: no-changeset-required

#7246 chore: use defineCommand in `wrangler docs`
  packages/wrangler/src/docs/index.ts
  packages/wrangler/src/index.ts
Labels: no-changeset-required

#7133 spinner: do not print escape sequences to non-tty output
  .changeset/wild-falcons-talk.md
  packages/cli/index.ts
  packages/cli/interactive.ts
  packages/wrangler/src/__tests__/cli.test.ts
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/config-cache.ts
  packages/wrangler/src/d1/migrations/apply.ts
  packages/wrangler/src/d1/migrations/helpers.ts
  packages/wrangler/src/is-interactive.ts
  packages/wrangler/src/metrics/metrics-config.ts
  packages/wrangler/src/user/user.ts
  packages/wrangler/src/versions/deploy.ts
Labels: e2e

#7242 Version Packages
  .changeset/clean-tigers-breathe.md
  .changeset/new-adults-float.md
  .changeset/nice-chefs-hang.md
  .changeset/stale-phones-bathe.md
  .changeset/tame-bobcats-suffer.md
  .changeset/wild-falcons-talk.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7173 WO-250 add workers-observability logs configuration
  .changeset/clever-grapes-sparkle.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation-helpers.ts
  packages/wrangler/src/config/validation.ts
Labels: e2e

#7249 chore: defineCommand refactor for `wrangler dev`
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/index.ts
Labels: e2e, no-changeset-required

#7081 Default `--x-registry` to on
  .changeset/tricky-bottles-bow.md
  packages/wrangler/e2e/dev-registry.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/dev-registry/file-registry.ts
  packages/wrangler/src/dev.ts
Labels: e2e

#7038 fix: only show fetch warning if on old compatibility_date
  .changeset/shaggy-monkeys-visit.md
  packages/wrangler/src/__tests__/check-fetch.test.ts
  packages/wrangler/src/api/pages/deploy.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/buildFunctions.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
Labels: e2e, skip-pr-description-validation

#7284 feat: add `wrangler metrics` as an alias for `wrangler telemetry`
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/metrics/commands.ts
Labels: no-changeset-required

#7243 Include Version Preview URL in Wrangler output file
  .changeset/mighty-beds-grab.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/output.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#7216 chore(wrangler): update unenv dependency version
  .changeset/shy-seas-wave.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#7278 fix: ensure Vitest Pool Workers doesn't error with nodejs_compat_v2 flag
  .changeset/hot-dolphins-obey.md
  packages/vitest-pool-workers/src/pool/compatibility-flag-assertions.ts
  packages/vitest-pool-workers/src/pool/index.ts
  packages/vitest-pool-workers/test/compatibility-flag-assertions.test.ts
  packages/vitest-pool-workers/test/validation.test.ts
Labels: e2e

#7261 Version Packages
  .changeset/clever-grapes-sparkle.md
  .changeset/four-mayflies-smash.md
  .changeset/hip-cycles-explain.md
  .changeset/hot-dolphins-obey.md
  .changeset/mighty-beds-grab.md
  .changeset/nasty-monkeys-heal.md
  .changeset/shaggy-monkeys-visit.md
  .changeset/shy-seas-wave.md
  .changeset/tricky-bottles-bow.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7285 Fix relative project root
  .changeset/sixty-news-relax.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/find-additional-modules.test.ts
  packages/wrangler/src/__tests__/get-entry.test.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/find-additional-modules.ts
  packages/wrangler/src/deployment-bundle/resolve-entry.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/index.ts
Labels: e2e, regression

#7286 Fix multiple workflows and add proper engine persistance
  .changeset/cyan-geese-smell.md
  fixtures/workflow-multiple/package.json
  fixtures/workflow-multiple/src/index.ts
  fixtures/workflow-multiple/tests/index.test.ts
  fixtures/workflow-multiple/tests/tsconfig.json
  fixtures/workflow-multiple/tsconfig.json
  fixtures/workflow-multiple/vitest.config.mts
  fixtures/workflow-multiple/wrangler.toml
  fixtures/workflow/tests/index.test.ts
  fixtures/workflow/worker-configuration.d.ts
  packages/miniflare/src/plugins/workflows/index.ts
  packages/miniflare/test/plugins/workflows/index.spec.ts
  packages/workflows-shared/src/engine.ts
  pnpm-lock.yaml
Labels: e2e

#7302 feat: add banner to indicate when telemetry is on
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/metrics/metrics-config.ts
  packages/wrangler/src/metrics/metrics-dispatcher.ts
Labels: no-changeset-required

#6960 feat: Update Angular template to version 19
  .changeset/cool-experts-punch.md
  packages/create-cloudflare/src/frameworks/package.json
  packages/create-cloudflare/templates/angular/c3.ts
  packages/create-cloudflare/templates/angular/templates/server.ts
  packages/create-cloudflare/templates/angular/templates/src/server.ts
  packages/create-cloudflare/templates/angular/templates/tools/alter-polyfills.mjs
  packages/create-cloudflare/templates/angular/templates/tools/copy-files.mjs
  packages/create-cloudflare/templates/angular/templates/tools/paths.mjs
Labels: skip-pr-description-validation

#7311 refactor: migrate r2 commands to new command registration setup
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/r2/bucket.ts
  packages/wrangler/src/r2/create.ts
  packages/wrangler/src/r2/domain.ts
  packages/wrangler/src/r2/helpers.ts
  packages/wrangler/src/r2/index.ts
  packages/wrangler/src/r2/info.ts
  packages/wrangler/src/r2/lifecycle.ts
  packages/wrangler/src/r2/list.ts
  packages/wrangler/src/r2/notification.ts
  packages/wrangler/src/r2/object.ts
  packages/wrangler/src/r2/public-dev-url.ts
  packages/wrangler/src/r2/sippy.ts
Labels: e2e, no-changeset-required

#7317 test: fix system locale override
  packages/wrangler/src/__tests__/vitest.global.ts
  packages/wrangler/src/__tests__/vitest.setup.ts
  packages/wrangler/vitest.config.mts
Labels: no-changeset-required

#7320 feat: add some more properties to telemetry events
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/metrics/metrics-config.ts
  packages/wrangler/src/metrics/metrics-dispatcher.ts
  packages/wrangler/src/metrics/send-event.ts
Labels: no-changeset-required

#7318 Normalize workers assets path
  .changeset/cyan-laws-mate.md
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  packages/workers-shared/asset-worker/src/handler.ts
Labels: skip-pr-description-validation

#7321 Version Packages
  .changeset/cool-experts-punch.md
  .changeset/cyan-laws-mate.md
  .changeset/stupid-moons-juggle.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7319 chore(wrangler): update unenv dependency version
  .changeset/fluffy-ravens-draw.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#7327 fix: missing unenv version in lockfile
  pnpm-lock.yaml
Labels: e2e, no-changeset-required

#6410 Fix the included file in tests for the hello world template
  .changeset/lemon-badgers-rest.md
  packages/create-cloudflare/templates/hello-world/ts/test/tsconfig.json
Labels: skip-pr-description-validation

#7176 Remove incorrect logic in Asset Worker
  .changeset/metal-flies-cross.md
  packages/workers-shared/asset-worker/src/index.ts
Labels: e2e

#7331 chore(workers-shared): use version range instead of tag to avoid issues with changesets CI
  packages/workers-shared/package.json
  pnpm-lock.yaml
Labels: no-changeset-required

#7335 chore: restrict changeset version bump to workspace protocol only
  .changeset/config.json
Labels: no-changeset-required

#7351 Revert "Add serve_directly option to assets configuration (#7316)"
  .changeset/six-coats-rule.md
  fixtures/asset-config/html-handling.test.ts
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
  packages/workers-shared/utils/types.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
Labels: skip-pr-description-validation, no-changeset-required

#7353 update changeset #7303
  .changeset/funny-dingos-guess.md
Labels: skip-pr-description-validation, no-changeset-required

#7325 Version Packages
  .changeset/brave-paws-build.md
  .changeset/c3-frameworks-update-7235.md
  .changeset/famous-dragons-retire.md
  .changeset/famous-mayflies-knock.md
  .changeset/fluffy-ravens-draw.md
  .changeset/funny-dingos-guess.md
  .changeset/lemon-badgers-rest.md
  .changeset/metal-flies-cross.md
  .changeset/six-apes-pull.md
  .changeset/swift-bikes-doubt.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7355 Unrevert "Add serve_directly option to assets configuration (#7316)"
  .changeset/six-coats-rule.md
  fixtures/asset-config/html-handling.test.ts
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
  packages/workers-shared/utils/types.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
Labels: skip-pr-description-validation

#7032 vitest-pool-workers: Support AbortSignal in fetch-mock
  .changeset/hip-penguins-kiss.md
  fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
  packages/vitest-pool-workers/src/worker/fetch-mock.ts
Labels: e2e, caretaking, skip-pr-description-validation

#7363 refactor: remove duplicate PagesConfigFields interface
  packages/wrangler/src/config/config.ts
Labels: no-changeset-required

#7368 Use `workers-devprod` service account for external E2E CI
  .github/workflows/run-ci-for-external-forks.yml
Labels: skip-pr-description-validation

#7361 chore: add clarifying comment to pr template
  .github/pull_request_template.md
Labels: no-changeset-required

#7375 Refactor login to expose a direct function to retrieve an Oauth token
  packages/wrangler/src/user/user.ts
Labels: no-changeset-required

#7251 Support multiple workers in a single Miniflare instance
  .changeset/gold-pandas-yell.md
  fixtures/interactive-dev-tests/src/worker-a.mjs
  fixtures/interactive-dev-tests/src/worker-b.mjs
  fixtures/interactive-dev-tests/tests/index.test.ts
  fixtures/interactive-dev-tests/wrangler.a.toml
  fixtures/interactive-dev-tests/wrangler.b.toml
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/command.ts
  packages/wrangler/e2e/helpers/workerd-processes.ts
  packages/wrangler/e2e/multiworker-dev.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/NoOpProxyController.ts
  packages/wrangler/src/api/startDevWorker/events.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/core/define-command.ts
  packages/wrangler/src/core/helpers.ts
  packages/wrangler/src/core/register-commands.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/experimental-flags.ts
  packages/wrangler/src/index.ts
  packages/wrangler/templates/middleware/middleware-patch-console-prefix.d.ts
  packages/wrangler/templates/middleware/middleware-patch-console-prefix.ts
Labels: e2e

#7360 fix: allow `wrangler types` when expected entrypoint doesn't exist
  .changeset/silly-news-compete.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e

#7381 Turn on `--x-registry` for Pages by default
  .changeset/seven-eels-reflect.md
  packages/wrangler/e2e/dev-registry.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#7357 chore: refactor defineCommand to use named imports
  packages/wrangler/CONTRIBUTING.md
  packages/wrangler/src/__tests__/core/command-registration.test.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/__tests__/vitest.global.ts
  packages/wrangler/src/core/CommandRegistry.ts
  packages/wrangler/src/core/create-command.ts
  packages/wrangler/src/core/helpers.ts
  packages/wrangler/src/core/index.ts
  packages/wrangler/src/core/register-commands.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/core/types.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/docs/index.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/r2/bucket.ts
  packages/wrangler/src/r2/domain.ts
  packages/wrangler/src/r2/index.ts
  packages/wrangler/src/r2/lifecycle.ts
  packages/wrangler/src/r2/notification.ts
  packages/wrangler/src/r2/object.ts
  packages/wrangler/src/r2/public-dev-url.ts
  packages/wrangler/src/r2/sippy.ts
  packages/wrangler/src/user/commands.ts
  packages/wrangler/src/workflows/commands/delete.ts
  packages/wrangler/src/workflows/commands/describe.ts
  packages/wrangler/src/workflows/commands/instances/describe.ts
  packages/wrangler/src/workflows/commands/instances/list.ts
  packages/wrangler/src/workflows/commands/instances/pause.ts
  packages/wrangler/src/workflows/commands/instances/resume.ts
  packages/wrangler/src/workflows/commands/instances/terminate.ts
  packages/wrangler/src/workflows/commands/list.ts
  packages/wrangler/src/workflows/commands/trigger.ts
  packages/wrangler/src/workflows/index.ts
  packages/wrangler/turbo.json
Labels: e2e, no-changeset-required

#7389 test: fix timezone for tests
  fixtures/vitest-pool-workers-examples/vitest.global.ts
  fixtures/vitest-pool-workers-examples/vitest.workers.config.ts
Labels: e2e, no-changeset-required

#7377 feat(wrangler): make resources identifier optional if x-provision flag is enabled
  .changeset/lucky-carrots-sparkle.md
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/d1/utils.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/kv/index.ts
Labels: e2e

#7338 Require Node v18 in Wrangler v4
  .changeset/slimy-pumpkins-tickle.md
  .github/workflows/test-and-check.yml
  .github/workflows/test-old-node-error.yml
  fixtures/node-app-pages/package.json
  fixtures/pages-d1-shim/package.json
  fixtures/pages-dev-proxy-with-script/package.json
  fixtures/pages-functions-app/package.json
  fixtures/pages-functions-wasm-app/package.json
  fixtures/pages-functions-with-config-file-app/package.json
  fixtures/pages-functions-with-routes-app/package.json
  fixtures/pages-nodejs-v2-compat/package.json
  fixtures/pages-plugin-mounted-on-root-app/package.json
  fixtures/pages-simple-assets/package.json
  fixtures/pages-workerjs-and-functions-app/package.json
  fixtures/pages-workerjs-app/package.json
  fixtures/pages-workerjs-directory/package.json
  fixtures/pages-workerjs-wasm-app/package.json
  fixtures/pages-workerjs-with-config-file-app/package.json
  fixtures/pages-workerjs-with-routes-app/package.json
  packages/kv-asset-handler/package.json
  packages/miniflare/package.json
  packages/workers-shared/package.json
  packages/workflows-shared/package.json
  packages/wrangler/bin/wrangler.js
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/msw.d.ts
  packages/wrangler/src/__tests__/test-old-node-version.js
  pnpm-lock.yaml
Labels: breaking change, e2e

#7336 Remove `node_compat` in Wrangler & Miniflare v4
  .changeset/node-compat-v4.md
  fixtures/node-app-pages/tests/index.test.ts
  packages/miniflare/src/plugins/core/node-compat.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/config-validation-pages.test.ts
  packages/wrangler/src/__tests__/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/pages/deploy.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/build-failures.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/log-build-output.ts
  packages/wrangler/src/deployment-bundle/node-compat.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/type-generation/index.ts
  packages/wrangler/src/versions/index.ts
  packages/wrangler/src/versions/upload.ts
  pnpm-lock.yaml
Labels: breaking change, e2e

#7391 chore(wrangler): fix type errors with experimental flags
  packages/wrangler/src/__tests__/configuration.test.ts
Labels: no-changeset-required

#7387 refactor(wrangler): Explicitely pick node compat plugins for each mode
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
Labels: e2e, no-changeset-required
