Repository cloudflare/workers-sdk, pull requests merged in 2024-10, with the labels that each got.

#6868 Version Packages
  .changeset/chilled-trainers-switch.md
  .changeset/fuzzy-cows-camp.md
  .changeset/thin-shirts-fail.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6408 on by default: –x-dev-env
  .changeset/eleven-planes-promise.md
  packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/dev-registry.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/remote.tsx
  packages/wrangler/src/index.ts
Labels: e2e

#6872 fix: render a helpful build error if a Service Worker mode Worker has imports
  .changeset/perfect-experts-draw.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/cloudflare-internal.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
Labels: e2e

#6838 Improve static asset upload messaging
  .changeset/rude-steaks-sip.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/assets.ts
Labels: e2e, skip-pr-description-validation

#6881 fix assets + custom build = infinite loop
  .changeset/happy-balloons-work.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
Labels: e2e

#6891 chore: use wrangler.js as entrypoint
  .github/workflows/e2e.yml
  packages/wrangler/e2e/dev.test.ts
Labels: e2e, skip-pr-description-validation

#6875 Version Packages
  .changeset/bright-deers-rescue.md
  .changeset/c3-frameworks-update-6848.md
  .changeset/cool-wombats-marry.md
  .changeset/curly-forks-allow.md
  .changeset/eleven-planes-promise.md
  .changeset/happy-balloons-work.md
  .changeset/perfect-experts-draw.md
  .changeset/popular-horses-hide.md
  .changeset/rude-steaks-sip.md
  .changeset/tasty-bears-behave.md
  .changeset/yellow-ears-kick.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6902 fix: enable esbuild's keepNames: true to set .name on functions/classes
  .changeset/fluffy-colts-give.md
  packages/wrangler/src/__tests__/middleware.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  pnpm-lock.yaml
Labels: e2e

#6903 fix: ensure that `alias` config gets passed through to the bundler when using new `--x-dev-env`
  .changeset/grumpy-apples-juggle.md
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
Labels: e2e

#6835 add workers assets to vitest integration
  .changeset/brave-needles-refuse.md
  .changeset/breezy-tips-sparkle.md
  fixtures/vitest-pool-workers-examples/workers-assets-only/README.md
  fixtures/vitest-pool-workers-examples/workers-assets-only/public/index.html
  fixtures/vitest-pool-workers-examples/workers-assets-only/test/assets-only.test.ts
  fixtures/vitest-pool-workers-examples/workers-assets-only/test/tsconfig.json
  fixtures/vitest-pool-workers-examples/workers-assets-only/tsconfig.json
  fixtures/vitest-pool-workers-examples/workers-assets-only/vitest.config.ts
  fixtures/vitest-pool-workers-examples/workers-assets-only/wrangler.toml
  fixtures/vitest-pool-workers-examples/workers-assets/README.md
  fixtures/vitest-pool-workers-examples/workers-assets/public/binding.html
  fixtures/vitest-pool-workers-examples/workers-assets/public/index.html
  fixtures/vitest-pool-workers-examples/workers-assets/src/env.d.ts
  fixtures/vitest-pool-workers-examples/workers-assets/src/index.ts
  fixtures/vitest-pool-workers-examples/workers-assets/src/tsconfig.json
  fixtures/vitest-pool-workers-examples/workers-assets/test/assets.test.ts
  fixtures/vitest-pool-workers-examples/workers-assets/test/env.d.ts
  fixtures/vitest-pool-workers-examples/workers-assets/test/tsconfig.json
  fixtures/vitest-pool-workers-examples/workers-assets/tsconfig.json
  fixtures/vitest-pool-workers-examples/workers-assets/vitest.config.ts
  fixtures/vitest-pool-workers-examples/workers-assets/wrangler.toml
  packages/miniflare/README.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/assets/schema.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/vitest-pool-workers/src/pool/config.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/dev/miniflare.ts
  pnpm-lock.yaml
Labels: e2e

#6909 Fix dev-env logging
  .changeset/gentle-apricots-kiss.md
  .prettierignore
  fixtures/interactive-dev-tests/src/startup-error.ts
  fixtures/interactive-dev-tests/tests/index.test.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/deployment-bundle/guess-worker-format.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/hotkeys.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/utils/log-file.ts
Labels: e2e

#6907 Version Packages
  .changeset/big-waves-hammer.md
  .changeset/brave-needles-refuse.md
  .changeset/breezy-tips-sparkle.md
  .changeset/fluffy-colts-give.md
  .changeset/gentle-apricots-kiss.md
  .changeset/grumpy-apples-juggle.md
  .changeset/pretty-cherries-relate.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6923 Fix test
  .changeset/blue-lies-juggle.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e

#6921 chore: Drop the "Fixes" check in CI
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: skip-pr-description-validation

#6794 chore: create semgrep.yml
  .github/workflows/semgrep.yml
Labels: caretaking

#6932 fix: allow `require`ing alias modules
  .changeset/nasty-melons-camp.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  pnpm-lock.yaml
Labels: e2e

#6926 [Refactor] Separate server registry from file-based registry
  .changeset/fluffy-seals-vanish.md
  packages/wrangler/src/dev-registry.ts
  packages/wrangler/src/dev-registry/file-registry.ts
  packages/wrangler/src/dev-registry/index.ts
  packages/wrangler/src/dev-registry/server-registry.ts
  packages/wrangler/src/dev-registry/types.ts
  packages/wrangler/src/dev.tsx
Labels: e2e

#6940 remove duplicate of cuddly-waves-pump.md
  .changeset/warm-games-brush.md
Labels: skip-pr-description-validation

#6894 fix: improve the rendering of build errors when bundling
  .changeset/famous-camels-leave.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deployment-bundle/build-failures.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/alias-external.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/cloudflare-internal.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/config-provider.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/log-build-output.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/standard-url.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/logger.ts
Labels: e2e

#6942 update changesets
  .changeset/cuddly-waves-pump.md
  .changeset/fluffy-seals-vanish.md
  .changeset/nasty-melons-camp.md
Labels: skip-pr-description-validation

#6934 Version Packages
  .changeset/cuddly-waves-pump.md
  .changeset/famous-camels-leave.md
  .changeset/heavy-ties-shop.md
  .changeset/nasty-melons-camp.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6941 WC-2695 Add better visibility for router-worker
  .changeset/poor-shoes-tickle.md
  packages/workers-shared/router-worker/src/analytics.ts
  packages/workers-shared/router-worker/src/index.ts
  packages/workers-shared/router-worker/src/performance.ts
  packages/workers-shared/router-worker/src/types.ts
  packages/workers-shared/router-worker/wrangler.toml
Labels: e2e

#6946 Version Packages
  .changeset/cyan-cycles-occur.md
  .changeset/dependabot-update-6949.md
  .changeset/poor-shoes-tickle.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e, skip-pr-description-validation

#6957 refactor: simplify tsconfig templates
  .changeset/twenty-grapes-taste.md
  packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/ts/tsconfig.json
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/tsconfig.json
  packages/create-cloudflare/templates/common/ts/tsconfig.json
  packages/create-cloudflare/templates/hello-world-durable-object/ts/tsconfig.json
  packages/create-cloudflare/templates/hello-world/ts/tsconfig.json
  packages/create-cloudflare/templates/queues/ts/tsconfig.json
  packages/create-cloudflare/templates/scheduled/ts/tsconfig.json
Labels: e2e, skip-pr-description-validation

#6964 fix: relax PR description validation
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: e2e

#6962 feat(worker-playground): delay preview environment setup
  .changeset/curly-jars-kick.md
  .changeset/tasty-chefs-watch.md
  packages/quick-edit/functions/_middleware.ts
  packages/workers-playground/package.json
  packages/workers-playground/src/QuickEditor/EditorPane.tsx
  packages/workers-playground/src/QuickEditor/HTTPTab/HTTPTab.tsx
  packages/workers-playground/src/QuickEditor/PreviewTab/PreviewTab.tsx
  packages/workers-playground/src/QuickEditor/PreviewTab/UrlBar.tsx
  packages/workers-playground/src/QuickEditor/QuickEditor.tsx
  packages/workers-playground/src/QuickEditor/useDraftWorker.ts
  pnpm-lock.yaml
Labels: preview:workers-playground

#6995 fix: quarantine C3 analog e2e tests
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
Labels: e2e

#6969 Version Packages
  .changeset/c3-frameworks-update-6880.md
  .changeset/c3-frameworks-update-6977.md
  .changeset/c3-frameworks-update-6978.md
  .changeset/curly-jars-kick.md
  .changeset/dependabot-update-6961.md
  .changeset/light-wasps-promise.md
  .changeset/tasty-chefs-watch.md
  .changeset/twenty-grapes-taste.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-playground/CHANGELOG.md
  packages/workers-playground/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#6971 chore: fix entrypoint logic and refactor
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/resolve-entry.ts
Labels: e2e

#6984 Relax changeset format docs
  CONTRIBUTING.md
  tools/deployments/__tests__/validate-changesets.test.ts
  tools/deployments/validate-changesets.ts
Labels: skip-pr-description-validation

#6526 defineCommand util
  packages/wrangler/CONTRIBUTING.md
  packages/wrangler/src/__tests__/core/command-registration.test.ts
  packages/wrangler/src/core/define-command.ts
  packages/wrangler/src/core/index.ts
  packages/wrangler/src/core/register-commands.ts
  packages/wrangler/src/core/teams.d.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/yargs-types.ts
Labels: e2e

#6997 Version Packages
  .changeset/brave-readers-promise.md
  .changeset/c3-frameworks-update-6993.md
  .changeset/c3-frameworks-update-6994.md
  .changeset/c3-frameworks-update-7006.md
  .changeset/c3-frameworks-update-7007.md
  .changeset/early-kangaroos-guess.md
  .changeset/kind-tomatoes-smile.md
  .changeset/little-cheetahs-arrive.md
  .changeset/nine-cougars-repeat.md
  .changeset/poor-phones-fail.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7010 chore(wrangler): update unenv dependency version
  .changeset/few-coats-count.md
  fixtures/pages-nodejs-v2-compat/tests/index.test.ts
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#6985 Simplify pull_request_template.md
  .github/pull_request_template.md
  .github/workflows/validate-pr-description.yml
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: no-changeset-required

#6972 Add ` (local)` indicator to bindings using local data
  .changeset/wet-dryers-pretend.md
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/paths.ts
Labels: e2e

#7039 Only show dev registry connection status in local dev
  .changeset/heavy-taxis-happen.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/config/index.ts
Labels: e2e

#7044 Fix head check for PR validation
  .github/workflows/validate-pr-description.yml
Labels: no-changeset-required

#7034 fix: ensure logged in when choosing account during pre-existing worker C3 flow
  .changeset/sixty-pants-attend.md
  packages/create-cloudflare/src/__tests__/pre-existing.test.ts
  packages/create-cloudflare/templates/pre-existing/c3.ts
Labels: e2e

#7018 fix: log successful execution of D1 commands locally
  .changeset/quiet-days-eat.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/src/d1/execute.tsx
Labels: e2e, skip-pr-description-validation

#7043 chore: stop uploading c3 diff
  .github/actions/create-c3-docs-pr/action.yml
  .github/actions/run-c3-e2e/action.yml
  .github/workflows/c3-e2e-dependabot.yml
  .github/workflows/c3-e2e-experimental.yml
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/changesets.yml
  packages/create-cloudflare/.env.example
  packages/create-cloudflare/.gitignore
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/src/frameworks/index.ts
  packages/create-cloudflare/turbo.json
Labels: e2e, no-changeset-required

#7005 fix(wrangler): enforce single value on non-array arguments
  .changeset/sour-buses-develop.md
  packages/wrangler/src/__tests__/core/command-registration.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/core/helpers.ts
  packages/wrangler/src/core/index.ts
  packages/wrangler/src/core/register-commands.ts
  packages/wrangler/src/errors.ts
  packages/wrangler/src/generate/index.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/pubsub/pubsub-commands.ts
  packages/wrangler/src/queues/cli/commands/consumer/http-pull/add.ts
  packages/wrangler/src/queues/cli/commands/consumer/worker/add.ts
  packages/wrangler/src/queues/cli/commands/create.ts
  packages/wrangler/src/r2/index.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e

#5737 Validate duplicate bindings across all binding types
  .changeset/fair-fishes-do.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/validation-helpers.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-pr-description-validation

#7054 fix: update changesets
  .changeset/green-parrots-lick.md
  .changeset/moody-seals-smash.md
  .changeset/serious-gifts-thank.md
Labels: skip-pr-description-validation, no-changeset-required

#7019 Version Packages
  .changeset/c3-frameworks-update-7016.md
  .changeset/c3-frameworks-update-7052.md
  .changeset/dependabot-update-7035.md
  .changeset/fair-fishes-do.md
  .changeset/few-coats-count.md
  .changeset/green-parrots-lick.md
  .changeset/heavy-taxis-happen.md
  .changeset/hungry-news-own.md
  .changeset/moody-seals-smash.md
  .changeset/odd-months-bake.md
  .changeset/pink-geckos-peel.md
  .changeset/quiet-days-eat.md
  .changeset/serious-gifts-thank.md
  .changeset/sixty-pants-attend.md
  .changeset/sour-buses-develop.md
  .changeset/tasty-jeans-train.md
  .changeset/violet-ducks-brush.md
  .changeset/wet-dryers-pretend.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/quick-edit/CHANGELOG.md
  packages/quick-edit/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#7057 Adds D&C as owners of workers-shared
  CODEOWNERS
Labels: skip-pr-description-validation

#7065 Rip out react from all non-dev flows
  .changeset/rotten-apples-happen.md
  packages/wrangler/src/__tests__/d1/create.test.ts
  packages/wrangler/src/ai/createFinetune.ts
  packages/wrangler/src/ai/listCatalog.ts
  packages/wrangler/src/ai/listFinetune.ts
  packages/wrangler/src/api/pages/deploy.ts
  packages/wrangler/src/d1/backups.ts
  packages/wrangler/src/d1/create.ts
  packages/wrangler/src/d1/execute.ts
  packages/wrangler/src/d1/info.ts
  packages/wrangler/src/d1/list.ts
  packages/wrangler/src/d1/migrations/apply.ts
  packages/wrangler/src/d1/migrations/create.ts
  packages/wrangler/src/d1/migrations/list.ts
  packages/wrangler/src/pages/deploy.ts
  packages/wrangler/src/pages/deployments.ts
  packages/wrangler/src/pages/projects.ts
  packages/wrangler/src/pages/prompt-select-project.ts
  packages/wrangler/src/pages/prompt-select-project.tsx
  packages/wrangler/src/pages/upload.ts
  packages/wrangler/src/pages/validate.ts
  packages/wrangler/src/user/choose-account.ts
  packages/wrangler/src/vectorize/create.ts
Labels: e2e

#7067 feat: change trigger command to comply with new endpoint
  .changeset/grumpy-eggs-rest.md
  packages/wrangler/src/workflows/commands/trigger.ts
Labels: skip-pr-description-validation

#7062 Version Packages
  .changeset/dependabot-update-7066.md
  .changeset/eleven-rats-press.md
  .changeset/gold-moose-dream.md
  .changeset/grumpy-eggs-rest.md
  .changeset/healthy-dogs-exist.md
  .changeset/plenty-garlics-jump.md
  .changeset/polite-numbers-warn.md
  .changeset/rare-planes-warn.md
  .changeset/rotten-apples-happen.md
  .changeset/smooth-kiwis-clean.md
  .changeset/sour-frogs-jam.md
  .changeset/tasty-kangaroos-bake.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#7086 Add test for custom build with `unstable_dev()`
  fixtures/unstable_dev/src/wrangler-dev.mjs
  fixtures/unstable_dev/wrangler.toml
Labels: no-changeset-required

#7080 chore(wrangler): update unenv dependency version
  .changeset/lucky-ants-call.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#6916 VS-286 Support mixed-mode local bindings for Vectorize in Miniflare
  .changeset/empty-lamps-turn.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/dev.tsx
  packages/wrangler/src/dev/dev.tsx
  packages/wrangler/src/dev/local.tsx
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/start-server.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/vectorize/fetcher.ts
Labels: e2e, caretaking

#7076 Upgrade to turbo v2
  fixtures/additional-modules/turbo.json
  fixtures/nodejs-als-app/turbo.json
  fixtures/nodejs-hybrid-app/turbo.json
  fixtures/pages-plugin-example/turbo.json
  fixtures/pages-proxy-app/turbo.json
  fixtures/pages-ws-app/turbo.json
  lint-turbo.mjs
  package.json
  packages/cli/turbo.json
  packages/create-cloudflare/turbo.json
  packages/format-errors/turbo.json
  packages/kv-asset-handler/turbo.json
  packages/miniflare/turbo.json
  packages/prerelease-registry/turbo.json
  packages/turbo-r2-archive/turbo.json
  packages/vitest-pool-workers/turbo.json
  packages/workers-editor-shared/turbo.json
  packages/workers-playground/turbo.json
  packages/workers-shared/turbo.json
  packages/workflows-shared/turbo.json
  packages/wrangler/turbo.json
  pnpm-lock.yaml
  tools/turbo.json
  turbo.json
Labels: no-changeset-required

#7008 chore: update devtools patches (2nd attempt)
  .changeset/famous-birds-remain.md
  .gitignore
  .prettierignore
  packages/wrangler-devtools/Makefile
  packages/wrangler-devtools/patches/0001-Expand-Browser-support-make-it-work-in-Firefox-Safar.patch
  packages/wrangler-devtools/patches/0001-Support-viewing-files-over-the-network.patch
  packages/wrangler-devtools/patches/0002-Setup-Cloudflare-devtools-target-type.patch
  packages/wrangler-devtools/patches/0002-Show-fallback-image-on-Safari.patch
  packages/wrangler-devtools/patches/0003-Add-ping-to-improve-connection-stability.-Without-th.patch
  packages/wrangler-devtools/patches/0003-Support-previewing-subrequest-responses.patch
  packages/wrangler-devtools/patches/0004-Better-Firefox-support-for-network-tab.patch
  packages/wrangler-devtools/patches/0004-Support-viewing-source-files-over-the-network.-This-.patch
  packages/wrangler-devtools/patches/0005-Remove-unsupported-network-UI.patch
  packages/wrangler-devtools/patches/0005-Support-forcing-the-devtools-theme-via-a-query-param.patch
  packages/wrangler-devtools/patches/0006-All-about-the-network-tab.patch
  packages/wrangler-devtools/patches/0006-Remove-unsupported-profiler-UI.patch
  packages/wrangler-devtools/patches/0007-Limit-heap-profiling-modes-available.patch
  packages/wrangler-devtools/patches/0007-Support-theme-url-parameter-for-forcing-the-theme-fr.patch
  packages/wrangler-devtools/patches/0008-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
  packages/wrangler-devtools/patches/0008-Use-the-worker-name-as-the-title-for-the-Javascript-.patch
  packages/wrangler-devtools/patches/0009-Fallback-to-location-for-domain.patch
  packages/wrangler-devtools/patches/0010-Hide-unsupported-settings-UI.patch
  packages/wrangler-devtools/patches/0012-Support-sourcemaps.patch
  packages/wrangler-devtools/patches/0013-Enable-debugger-when-query-parameter-debugger-is-tru.patch
  packages/wrangler-devtools/patches/0014-Show-Profiling-panel.patch
Labels: preview:wrangler-devtools

#7102 Restore turbo loose mode
  .github/actions/install-dependencies/action.yml
Labels: e2e, no-changeset-required

#7117 chore: fixup #7024
  packages/wrangler/src/hyperdrive/index.ts
Labels: skip-pr-description-validation, no-changeset-required

#7091 Synchronize observability settings during versions deploy
  .changeset/chilled-apes-repeat.md
  packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
  packages/wrangler/src/versions/deploy.ts
Labels: e2e, skip-pr-description-validation

#7119 chore: update r2 e2e snapshot
  packages/wrangler/e2e/r2.test.ts
Labels: e2e, no-changeset-required

#7131 Revert "chore: update devtools patches (2nd attempt)"
  .changeset/famous-birds-remain.md
  .gitignore
  .prettierignore
  packages/wrangler-devtools/Makefile
  packages/wrangler-devtools/patches/0001-Support-viewing-files-over-the-network.patch
  packages/wrangler-devtools/patches/0002-Setup-Cloudflare-devtools-target-type.patch
  packages/wrangler-devtools/patches/0002-Show-fallback-image-on-Safari.patch
  packages/wrangler-devtools/patches/0003-Support-previewing-subrequest-responses.patch
  packages/wrangler-devtools/patches/0004-Better-Firefox-support-for-network-tab.patch
  packages/wrangler-devtools/patches/0004-Support-viewing-source-files-over-the-network.-This-.patch
  packages/wrangler-devtools/patches/0005-Remove-unsupported-network-UI.patch
  packages/wrangler-devtools/patches/0005-Support-forcing-the-devtools-theme-via-a-query-param.patch
  packages/wrangler-devtools/patches/0006-All-about-the-network-tab.patch
  packages/wrangler-devtools/patches/0006-Remove-unsupported-profiler-UI.patch
  packages/wrangler-devtools/patches/0007-Limit-heap-profiling-modes-available.patch
  packages/wrangler-devtools/patches/0007-Support-theme-url-parameter-for-forcing-the-theme-fr.patch
  packages/wrangler-devtools/patches/0008-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
  packages/wrangler-devtools/patches/0008-Use-the-worker-name-as-the-title-for-the-Javascript-.patch
  packages/wrangler-devtools/patches/0009-Fallback-to-location-for-domain.patch
  packages/wrangler-devtools/patches/0010-Hide-unsupported-settings-UI.patch
  packages/wrangler-devtools/patches/0011-Add-ping-to-improve-connection-stability.patch
  packages/wrangler-devtools/patches/0012-Support-sourcemaps.patch
  packages/wrangler-devtools/patches/0013-Enable-debugger-when-query-parameter-debugger-is-tru.patch
  packages/wrangler-devtools/patches/0014-Show-Profiling-panel.patch
  packages/wrangler-devtools/patches/0015-Basic-support-for-Safari.patch
Labels: skip-pr-description-validation, no-changeset-required

#7089 Version Packages
  .changeset/c3-frameworks-update-7085.md
  .changeset/c3-frameworks-update-7126.md
  .changeset/chilled-apes-repeat.md
  .changeset/early-parents-run.md
  .changeset/empty-lamps-turn.md
  .changeset/happy-scissors-deliver.md
  .changeset/hip-actors-thank.md
  .changeset/lucky-ants-call.md
  .changeset/metal-ladybugs-teach.md
  .changeset/mighty-carrots-report.md
  .changeset/shiny-files-jog.md
  .changeset/tasty-elephants-develop.md
  .changeset/tender-pens-change.md
  .changeset/wrangler-hyperdrive-create-params-fix.md
  .changeset/wrangler-hyperdrive-create-update-refactor.md
  .changeset/wrangler-hyperdrive-update-support-conn-string.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#7070 chore: pin runner image of non test related workflows to ubuntu-22.04
  .github/workflows/c3-dependabot-versioning-prs.yml
  .github/workflows/changesets.yml
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/d1.yml
  .github/workflows/deploy-pages-previews.yml
  .github/workflows/e2e-project-cleanup.yml
  .github/workflows/holopin.yml
  .github/workflows/miniflare-dependabot-versioning-prs.yml
  .github/workflows/prerelease-workflows.yml
  .github/workflows/prereleases.yml
  .github/workflows/validate-pr-description.yml
  .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
  .github/workflows/write-prerelease-comment.yml
Labels: no-changeset-required

#7143 chore: enable observability for infra bots + devprod status bot
  .changeset/cool-dragons-brush.md
  packages/devprod-status-bot/wrangler.toml
  packages/edge-preview-authenticated-proxy/wrangler.toml
  packages/format-errors/wrangler.toml
  packages/playground-preview-worker/wrangler.json
Labels: no-changeset-required

#7140 Version Packages
  .changeset/c3-frameworks-update-7139.md
  .changeset/cool-dragons-brush.md
  .changeset/eleven-cobras-repeat.md
  .changeset/odd-lions-warn.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/devprod-status-bot/CHANGELOG.md
  packages/devprod-status-bot/package.json
  packages/edge-preview-authenticated-proxy/CHANGELOG.md
  packages/edge-preview-authenticated-proxy/package.json
  packages/format-errors/CHANGELOG.md
  packages/format-errors/package.json
  packages/playground-preview-worker/CHANGELOG.md
  packages/playground-preview-worker/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation
