Repository cloudflare/workers-sdk, pull requests merged in 2025-07, with the labels that each got.

#9779 Version Packages
  .changeset/olive-rabbits-tell.md
  .changeset/six-lizards-retire.md
  .changeset/warm-masks-chew.md
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
Labels: e2e, c3-e2e

#9804 Revert "temporarily remove all codeowners besides wrangler so that all PRs need the wrangler's team approval to land (#9749)"
  CODEOWNERS
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9806 Run E2Es on `merge_group` events
  .github/workflows/e2e.yml
Labels: skip-pr-description-validation

#9808 Improve GH Actions docs & remove obsolete PR labelling
  .github/pr-labeler.config.yml
  .github/workflows/README.md
  .github/workflows/pr-labeler.yml
Labels: skip-pr-description-validation

#9776 Cap the number of errors and warnings for bulk KV put
  .changeset/shaggy-frogs-tap.md
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/kv/helpers.ts
  packages/wrangler/src/kv/index.ts
Labels: wrangler, skip-pr-description-validation, v3-backport

#9746 add permissions to github workflows
  .github/workflows/c3-dependabot-versioning-prs.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/changesets.yml
  .github/workflows/deploy-pages-previews.yml
  .github/workflows/e2e-project-cleanup.yml
  .github/workflows/e2e.yml
  .github/workflows/holopin.yml
  .github/workflows/hotfix-release.yml
  .github/workflows/issues.yml
  .github/workflows/miniflare-dependabot-versioning-prs.yml
  .github/workflows/open-v3-maintenance-prs.yml
  .github/workflows/prerelease.yml
  .github/workflows/run-ci-for-external-forks.yml
  .github/workflows/semgrep.yml
  .github/workflows/test-and-check.yml
  .github/workflows/validate-pr-description.yml
  .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
  .github/workflows/workers-shared-deploy-production.yml
  .github/workflows/workers-shared-deploy-staging.yml
Labels: no-changeset-required, skip-v3-pr

#9823 Remove more workers in E2E cleanup
  fixtures/get-platform-proxy-remote-bindings-node-test/index.test.js
  fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
  tools/e2e/__tests__/common.test.ts
  tools/e2e/common.ts
Labels: skip-pr-description-validation

#9535 Initial support for VSCode Javascript Debug Terminals
  .changeset/perfect-plants-compete.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/runtime/index.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/wrangler/e2e/startWorker.test.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/dev/hotkeys.ts
  turbo.json
Labels: e2e, skip-v3-pr

#9824 Allow "plain text" images when blocking vulnerable non-image responses
  .changeset/fluffy-comics-study.md
  packages/workers-shared/router-worker/src/worker.ts
  packages/workers-shared/router-worker/tests/index.test.ts
Labels: e2e, c3-e2e, skip-v3-pr, every-os

#9838 bump the VS code JS debug terminal support PR to minor
  .changeset/perfect-plants-compete.md
  .github/workflows/c3-e2e.yml
Labels: skip-pr-description-validation, skip-v3-pr

#9805 Version Packages
  .changeset/fluffy-comics-study.md
  .changeset/lemon-bobcats-lose.md
  .changeset/perfect-plants-compete.md
  .changeset/ripe-forks-shop.md
  .changeset/shaggy-frogs-tap.md
  .changeset/tangy-ghosts-rule.md
  .changeset/thin-grapes-rescue.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9815 Remove --json arg from cloudchamber and containers commands
  .changeset/tender-cups-grin.md
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/create.test.ts
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/__tests__/cloudchamber/delete.test.ts
  packages/wrangler/src/__tests__/cloudchamber/images.test.ts
  packages/wrangler/src/__tests__/cloudchamber/list.test.ts
  packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
  packages/wrangler/src/__tests__/containers/delete.test.ts
  packages/wrangler/src/__tests__/containers/info.test.ts
  packages/wrangler/src/__tests__/containers/list.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/create.ts
  packages/wrangler/src/cloudchamber/curl.ts
  packages/wrangler/src/cloudchamber/delete.ts
  packages/wrangler/src/cloudchamber/deploy.ts
  packages/wrangler/src/cloudchamber/images/images.ts
  packages/wrangler/src/cloudchamber/images/list.ts
  packages/wrangler/src/cloudchamber/index.ts
  packages/wrangler/src/cloudchamber/list.ts
  packages/wrangler/src/cloudchamber/modify.ts
  packages/wrangler/src/cloudchamber/ssh/ssh.ts
  packages/wrangler/src/containers/containers.ts
  packages/wrangler/src/containers/index.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/yargs-types.ts
Labels: e2e

#9734 Make Wrangler warn more loudly if you're missing auth scopes
  .changeset/thick-meals-cheat.md
  packages/wrangler/src/__tests__/whoami.test.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/user/whoami.ts
Labels: skip-v3-pr

#9826 Skip remote E2E tests when no auth available
  .github/workflows/e2e.yml
  CONTRIBUTING.md
  packages/wrangler/e2e/cert.test.ts
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/dev-env.test.ts
  packages/wrangler/e2e/dev-remote-bindings.test.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/get-platform-proxy.test.ts
  packages/wrangler/e2e/helpers/wrangler.ts
  packages/wrangler/e2e/miniflare-remote-resources.test.ts
  packages/wrangler/e2e/pages-deploy.test.ts
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/e2e/r2.test.ts
  packages/wrangler/e2e/secrets-store.test.ts
  packages/wrangler/e2e/start-worker-remote-bindings.test.ts
  packages/wrangler/e2e/startWorker.test.ts
  packages/wrangler/e2e/validate-environment.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/e2e/wrangler-remote-resources.test.ts
  tools/e2e/runIndividualE2EFiles.ts
Labels: no-changeset-required

#9821 Require generated aliases to meet stricter naming requirements
  .changeset/heavy-wasps-switch.md
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-v3-pr

#9813 Support image name without account ID
  .changeset/fruity-pillows-peel.md
  packages/wrangler/e2e/containers.dev.test.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/cloudchamber/utils.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
Labels: skip-v3-pr

#9796 Browser Rendering local mode
  .changeset/cute-terms-sin.md
  .github/workflows/test-and-check.yml
  fixtures/browser-rendering/package.json
  fixtures/browser-rendering/src/index.ts
  fixtures/browser-rendering/test/index.spec.ts
  fixtures/browser-rendering/test/tsconfig.json
  fixtures/browser-rendering/tsconfig.json
  fixtures/browser-rendering/vitest.config.mts
  fixtures/browser-rendering/worker-configuration.d.ts
  fixtures/browser-rendering/wrangler.jsonc
  packages/miniflare/README.md
  packages/miniflare/package.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/browser-rendering/constants.ts
  packages/miniflare/src/plugins/browser-rendering/index.ts
  packages/miniflare/src/workers/browser-rendering/binding.worker.ts
  packages/miniflare/test/plugins/browser/index.spec.ts
  packages/wrangler/e2e/miniflare-remote-resources.test.ts
  packages/wrangler/e2e/wrangler-remote-resources.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/dev/miniflare.ts
  pnpm-lock.yaml
Labels: e2e

#9801 Containers: Ensure updating only the image URI updates app config
  .changeset/metal-aliens-tell.md
  packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
  packages/wrangler/src/cloudchamber/deploy.ts
Labels: skip-v3-pr

#9857 fix e2e tests on forks
  packages/wrangler/e2e/cert.test.ts
  packages/wrangler/e2e/r2.test.ts
  packages/wrangler/e2e/secrets-store.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9844 update wrangler's `pnpm dev` to also watch the containers-shared src directory
  packages/wrangler/package.json
Labels: no-changeset-required, skip-v3-pr

#9856 Set the Wrangler peer dependency to the same version as the direct dependency
  .changeset/brown-ends-wink.md
  packages/vite-plugin-cloudflare/package.json
Labels: vite-plugin

#9811 wrangler containers images delete should prefix the account id by default
  .changeset/four-needles-rule.md
  packages/containers-shared/src/images.ts
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/__tests__/cloudchamber/images.test.ts
  packages/wrangler/src/__tests__/containers/delete.test.ts
  packages/wrangler/src/__tests__/containers/info.test.ts
  packages/wrangler/src/__tests__/containers/list.test.ts
  packages/wrangler/src/cloudchamber/images/images.ts
  packages/wrangler/src/cloudchamber/images/list.ts
  packages/wrangler/src/cloudchamber/images/registries.ts
  packages/wrangler/src/cloudchamber/index.ts
  packages/wrangler/src/containers/index.ts
Labels: skip-v3-pr

#9729 Spawn docker build relative to the Dockerfile
  .changeset/clever-regions-build.md
  packages/containers-shared/src/build.ts
  packages/containers-shared/src/types.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/deploy.ts
Labels: e2e, skip-pr-description-validation, skip-v3-pr

#9845 remove extraneous double spaces from help output
  .changeset/cool-toes-repair.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/mtls-certificates.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/mtls-certificate/cli.ts
  packages/wrangler/src/versions/index.ts
Labels: skip-v3-pr

#9872 fix dockerfile path resolution
  .changeset/smooth-cooks-refuse.md
  packages/containers-shared/src/build.ts
  packages/containers-shared/src/images.ts
  packages/containers-shared/src/utils.ts
  packages/containers-shared/tests/utils.test.ts
  packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-legacy-script.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/cloudchamber/deploy.ts
  packages/wrangler/src/deploy/deploy.ts
Labels: skip-v3-pr

#9807 V3 backport for #9799
  .changeset/thin-grapes-rescue.md
  packages/wrangler/src/__tests__/cfetch-utils.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/sentry.test.ts
  packages/wrangler/src/__tests__/whoami.test.ts
  packages/wrangler/src/user/whoami.ts
Labels: e2e, skip-pr-description-validation, c3-e2e, v3-backport

#9685 [v3] WC-2965 Prevent selecting in-progress deployments when tailing
  .changeset/bumpy-otters-kiss.md
  packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
  packages/wrangler/src/pages/deployment-tails.ts
Labels: e2e, v3-backport

#9888 Containers-shared: Remove undici dependency
  .changeset/green-stars-fold.md
  packages/containers-shared/package.json
  packages/containers-shared/src/client/core/OpenAPI.ts
  packages/containers-shared/src/client/core/request.ts
  packages/containers-shared/tsconfig.json
  pnpm-lock.yaml
Labels: skip-v3-pr

#9902 clean up the vite e2e remote mode tests to avoid flakes
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/auxiliary-worker/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/entry-worker/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker-alt/index.js
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker-alt/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker/index.js
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9917 fix: assets only versions upload should include tag and message
  .changeset/long-ants-start.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/versions/types.ts
  packages/wrangler/src/versions/view.ts
Labels: skip-v3-pr

#9932 Improve our CI and local failures
  .github/workflows/c3-e2e.yml
  fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
  fixtures/get-platform-proxy-remote-bindings/turbo.json
  fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
  fixtures/vitest-pool-workers-remote-bindings/turbo.json
  fixtures/worker-app/tests/index.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9936 remove call to close the playwright browser in fixture tests as this can cause tests to hang
  fixtures/workers-with-assets-static-routing/test/index.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9854 fix incorrect bindings remote deduplication logic
  .changeset/cruel-owls-watch.md
  packages/miniflare/src/plugins/ai/index.ts
  packages/miniflare/src/plugins/browser-rendering/index.ts
  packages/miniflare/src/plugins/d1/index.ts
  packages/miniflare/src/plugins/dispatch-namespace/index.ts
  packages/miniflare/src/plugins/email/index.ts
  packages/miniflare/src/plugins/images/index.ts
  packages/miniflare/src/plugins/kv/index.ts
  packages/miniflare/src/plugins/mtls/index.ts
  packages/miniflare/src/plugins/r2/index.ts
  packages/miniflare/src/plugins/secret-store/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/src/plugins/vectorize/index.ts
  packages/miniflare/src/plugins/workflows/index.ts
  packages/wrangler/e2e/seed-files/remote-binding-workers/mixed-kvs.js
  packages/wrangler/e2e/wrangler-remote-resources.test.ts
Labels: e2e

#9918 chore: remove deprecated dependabot reviewers field
  .github/dependabot.yml
Labels: skip-pr-description-validation

#9959 Make it easier to run wrangler e2e locally
  packages/wrangler/e2e/README.md
  packages/wrangler/e2e/helpers/wrangler.ts
  packages/wrangler/e2e/validate-environment.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9969 Further updates to e2e test running helpers and instructions
  CONTRIBUTING.md
  packages/wrangler/e2e/README.md
  packages/wrangler/e2e/helpers/wrangler.ts
  packages/wrangler/e2e/validate-environment.ts
  tools/e2e/runIndividualE2EFiles.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9954 Support Images binding in `getPlatformProxy()`
  .changeset/red-wombats-chew.md
  fixtures/get-platform-proxy/package.json
  fixtures/get-platform-proxy/tests/__image_snapshots__/get-platform-proxy-env-test-ts-get-platform-proxy-env-correctly-obtains-functioning-image-bindings-2-snap.png
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler.jsonc
  packages/miniflare/src/plugins/core/proxy/client.ts
  packages/miniflare/src/workers/core/constants.ts
  packages/miniflare/src/workers/core/proxy.worker.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  pnpm-lock.yaml
Labels: skip-v3-pr

#9974 Pass worker name & compliance region through correctly
  .changeset/wicked-beans-nail.md
  fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
  fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
  packages/wrangler/e2e/wrangler-remote-resources.test.ts
  packages/wrangler/src/api/remoteBindings/index.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
Labels: skip-v3-pr

#9847 Bump undici & TS
  .changeset/thin-ideas-stay.md
  fixtures/wildcard-modules/package.json
  packages/miniflare/src/http/fetch.ts
  packages/miniflare/src/http/index.ts
  packages/miniflare/src/plugins/core/proxy/types.ts
  packages/miniflare/test/http/fetch.spec.ts
  packages/miniflare/test/plugins/core/proxy/client.spec.ts
  packages/vitest-pool-workers/scripts/bundle.mjs
  packages/vitest-pool-workers/src/mock-agent/client.cjs
  packages/vitest-pool-workers/src/mock-agent/index.cjs
  packages/vitest-pool-workers/src/worker/fetch-mock.ts
  packages/vitest-pool-workers/src/worker/index.ts
  packages/wrangler/src/__tests__/ai.local.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/__tests__/versions/secrets/put.test.ts
  packages/wrangler/src/__tests__/versions/secrets/utils.ts
  packages/wrangler/src/api/pages/deploy.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/pages/deploy.ts
  packages/wrangler/src/vectorize/insert.ts
  packages/wrangler/src/vectorize/upsert.ts
  packages/wrangler/src/versions/secrets/index.ts
  packages/wrangler/src/versions/upload.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: skip-v3-pr

#9980 Update changesets
  .changeset/dull-signs-smash.md
Labels: skip-pr-description-validation, skip-v3-pr

#9982 avoid a major bump to vite-plugin when its peer dependency (wrangler) gets a minor bump
  .changeset/config.json
  package.json
  packages/vite-plugin-cloudflare/package.json
  patches/@changesets__assemble-release-plan.patch
  pnpm-lock.yaml
Labels: no-changeset-required, skip-v3-pr

#9931 refactor: move compare to the tests
  packages/workers-shared/asset-worker/src/assets-manifest.ts
  packages/workers-shared/asset-worker/tests/assets-manifest.test.ts
Labels: no-changeset-required

#9934 add more validation to containers config
  .changeset/clean-colts-vanish.md
  packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-v3-pr

#9978 Bump `tar-fs` where possible
  .vscode/launch.json
  packages/cloudflare-workers-bindings-extension/.eslintrc.json
  packages/cloudflare-workers-bindings-extension/.vscode/launch.json
  packages/cloudflare-workers-bindings-extension/.vscodeignore
  packages/cloudflare-workers-bindings-extension/CHANGELOG.md
  packages/cloudflare-workers-bindings-extension/LICENSE
  packages/cloudflare-workers-bindings-extension/LICENSE-APACHE
  packages/cloudflare-workers-bindings-extension/README.md
  packages/cloudflare-workers-bindings-extension/esbuild.js
  packages/cloudflare-workers-bindings-extension/media/cf-workers-logo.png
  packages/cloudflare-workers-bindings-extension/media/cf-workers-logo.svg
  packages/cloudflare-workers-bindings-extension/media/cloudflare-workers-outline.svg
  packages/cloudflare-workers-bindings-extension/media/main.css
  packages/cloudflare-workers-bindings-extension/media/main.js
  packages/cloudflare-workers-bindings-extension/media/reset.css
  packages/cloudflare-workers-bindings-extension/package.json
  packages/cloudflare-workers-bindings-extension/resources/icons/ai.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/analytics_engine_datasets.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/assets.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/browser.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/d1_databases.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/dispatch_namespaces.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/durable_objects.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/hyperdrive.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/kv_namespaces.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/logfwdr.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/mtls_certificates.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/pipelines.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/queues.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/r2_buckets.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/send_email.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/services.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/tail_consumers.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/unsafe.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/vars.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/vectorize.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/version_metadata.svg
  packages/cloudflare-workers-bindings-extension/resources/icons/workflows.svg
  packages/cloudflare-workers-bindings-extension/src/add-binding.ts
  packages/cloudflare-workers-bindings-extension/src/extension.ts
  packages/cloudflare-workers-bindings-extension/src/home.ts
  packages/cloudflare-workers-bindings-extension/src/show-bindings.ts
  packages/cloudflare-workers-bindings-extension/src/test/runTest.ts
  packages/cloudflare-workers-bindings-extension/src/test/suite/extension.test.ts
  packages/cloudflare-workers-bindings-extension/src/test/suite/index.ts
  packages/cloudflare-workers-bindings-extension/src/wrangler.ts
  packages/cloudflare-workers-bindings-extension/tsconfig.json
  packages/cloudflare-workers-bindings-extension/turbo.json
  pnpm-lock.yaml
  tools/deployments/__tests__/deploy-non-npm-packages.test.ts
  tools/deployments/__tests__/validate-changesets.test.ts
Labels: no-changeset-required

#9994 Add boolean env var factory
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/metrics/commands.ts
  packages/wrangler/src/metrics/metrics-config.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10000 add more (sanitised) user errors to telemetry
  .changeset/gold-shirts-wash.md
  packages/wrangler/src/assets.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/package-manager.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: skip-v3-pr

#9960 Add some basic smoke tests to check that workers with multiple containers work as expected
  fixtures/interactive-dev-tests/multi-containers-app/DockerfileA
  fixtures/interactive-dev-tests/multi-containers-app/DockerfileB
  fixtures/interactive-dev-tests/multi-containers-app/src/index.ts
  fixtures/interactive-dev-tests/multi-containers-app/src/tsconfig.json
  fixtures/interactive-dev-tests/multi-containers-app/src/worker-configuration.d.ts
  fixtures/interactive-dev-tests/multi-containers-app/wrangler.jsonc
  fixtures/interactive-dev-tests/tests/index.test.ts
  packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
Labels: no-changeset-required, skip-v3-pr

#10010 reduce flakes on interactive-dev fixture tests
  fixtures/interactive-dev-tests/tests/index.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10017 refactor asynchronous code
  packages/wrangler/e2e/helpers/setup.ts
Labels: no-changeset-required

#10001 Inject HMR code in Worker entry file
  .changeset/orange-donkeys-check.md
  packages/vite-plugin-cloudflare/playground/worker/__tests__/worker.spec.ts
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#10039 group remote bind tests e2e in a single folder
  packages/wrangler/.eslintrc.js
  packages/wrangler/e2e/remote-binding/dev-remote-bindings.test.ts
  packages/wrangler/e2e/remote-binding/miniflare-remote-resources.test.ts
  packages/wrangler/e2e/remote-binding/start-worker-remote-bindings.test.ts
  packages/wrangler/e2e/remote-binding/workers/ai.js
  packages/wrangler/e2e/remote-binding/workers/alt-remote-worker.js
  packages/wrangler/e2e/remote-binding/workers/browser.js
  packages/wrangler/e2e/remote-binding/workers/d1.js
  packages/wrangler/e2e/remote-binding/workers/dispatch-namespace.js
  packages/wrangler/e2e/remote-binding/workers/images.js
  packages/wrangler/e2e/remote-binding/workers/kv.js
  packages/wrangler/e2e/remote-binding/workers/local-and-remote-service-bindings.js
  packages/wrangler/e2e/remote-binding/workers/local-service-binding-and-remote-ai.js
  packages/wrangler/e2e/remote-binding/workers/mixed-kvs.js
  packages/wrangler/e2e/remote-binding/workers/mtls.js
  packages/wrangler/e2e/remote-binding/workers/r2.js
  packages/wrangler/e2e/remote-binding/workers/remote-worker.js
  packages/wrangler/e2e/remote-binding/workers/service-binding.js
  packages/wrangler/e2e/remote-binding/workers/simple-service-binding.js
  packages/wrangler/e2e/remote-binding/workers/vectorize.js
  packages/wrangler/e2e/remote-binding/wrangler-remote-resources.test.ts
  packages/wrangler/e2e/tsconfig.json
Labels: no-changeset-required

#9992 Add `npx envinfo` to issue template
  .github/ISSUE_TEMPLATE/bug-template.yaml
Labels: skip-pr-description-validation

#9961 refactor containers config handling
  packages/containers-shared/.eslintrc.js
  packages/containers-shared/.eslintrc.json
  packages/containers-shared/src/build.ts
  packages/containers-shared/src/images.ts
  packages/containers-shared/src/types.ts
  packages/containers-shared/src/utils.ts
  packages/containers-shared/tests/utils.test.ts
  packages/containers-shared/tsconfig.json
  packages/vite-plugin-cloudflare/src/index.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/containers/apply.test.ts
  packages/wrangler/src/__tests__/containers/config.test.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/helpers/normalize.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/deploy.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/containers/config.ts
  packages/wrangler/src/containers/deploy.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/dev/miniflare.ts
  turbo.json
Labels: no-changeset-required

#10056 Quarantine next on pages c3 tests
  packages/create-cloudflare/e2e/tests/frameworks/test-config.ts
Labels: no-changeset-required

#10019 [v3-maintenance] chore: update workerd dependency to latest
  .changeset/blue-clubs-bake.md
  packages/miniflare/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation, skip-v3-pr

#10054 add `worker` to Vite plugin default conditions
  .changeset/social-geckos-leave.md
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Labels: vite-plugin

#10003 v3 backport: more error telemetry
  .changeset/gold-shirts-wash.md
  packages/wrangler/src/assets.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/package-manager.ts
Labels: skip-pr-description-validation, skip-v3-pr

#10048 pass the compatibility date and flags to the unenv preset
  .changeset/gentle-mice-create.md
  .prettierignore
  packages/unenv-preset/.eslintrc.cjs
  packages/unenv-preset/package.json
  packages/unenv-preset/src/index.ts
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/async_hooks.ts
  packages/unenv-preset/src/runtime/node/console.ts
  packages/unenv-preset/src/runtime/node/crypto.ts
  packages/unenv-preset/src/runtime/node/process.ts
  packages/unenv-preset/src/runtime/node/tls.ts
  packages/unenv-preset/src/runtime/polyfill/performance.ts
  packages/unenv-preset/tsconfig.json
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-v3-pr

#10093 import debug instead of the alias
  packages/wrangler/e2e/unenv-preset/worker/index.ts
Labels: no-changeset-required

#10109 chore: update dependencies of "create-cloudflare" package
  .changeset/c3-frameworks-update-9431.md
  packages/create-cloudflare/src/frameworks/package.json
  packages/create-cloudflare/templates/angular/pages/c3.ts
  packages/create-cloudflare/templates/angular/workers/c3.ts
Labels: skip-v3-pr

#10137 refactor: remove abort controller from vite-plugin
  packages/vite-plugin-cloudflare/src/index.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10138 refactor: remove redundant watcher.close() from vite-plugin
  packages/vite-plugin-cloudflare/src/index.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10004 fix wrangler dev logs being logged on the incorrect level in some cases
  .changeset/deep-lizards-move.md
  .changeset/full-areas-lick.md
  fixtures/shared/src/run-wrangler-long-lived.ts
  fixtures/worker-logs/package.json
  fixtures/worker-logs/src/module.js
  fixtures/worker-logs/src/service.js
  fixtures/worker-logs/tests/index.test.ts
  fixtures/worker-logs/tsconfig.json
  fixtures/worker-logs/wrangler.module.jsonc
  fixtures/worker-logs/wrangler.service.jsonc
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/runtime/config/generated.ts
  packages/miniflare/src/runtime/config/workerd.ts
  packages/miniflare/test/index.spec.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/dev/miniflare/index.ts
  packages/wrangler/src/dev/miniflare/stdio.ts
  pnpm-lock.yaml
Labels: skip-v3-pr

#10015 V3 Backport [#10004]: fix wrangler dev logs being logged on the incorrect level in some cases
  .changeset/deep-lizards-move.md
  .changeset/full-areas-lick.md
  fixtures/shared/src/run-wrangler-long-lived.ts
  fixtures/worker-logs/package.json
  fixtures/worker-logs/src/module.js
  fixtures/worker-logs/src/service.js
  fixtures/worker-logs/tests/index.test.ts
  fixtures/worker-logs/tsconfig.json
  fixtures/worker-logs/wrangler.module.jsonc
  fixtures/worker-logs/wrangler.service.jsonc
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/runtime/config/generated.ts
  packages/miniflare/src/runtime/config/workerd.ts
  packages/miniflare/test/index.spec.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/dev/miniflare/index.ts
  packages/wrangler/src/dev/miniflare/stdio.ts
  pnpm-lock.yaml
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#10099 Clean up containers started by local dev during process exit hook instead
  .changeset/great-terms-roll.md
  fixtures/interactive-dev-tests/tests/index.test.ts
  packages/containers-shared/src/utils.ts
  packages/vite-plugin-cloudflare/src/containers.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/wrangler/e2e/containers.dev.test.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
  packages/wrangler/src/dev/hotkeys.ts
Labels: skip-v3-pr

#10151 reduce vite-plugin remote-bindings e2e flakes
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts
Labels: no-changeset-required, skip-v3-pr
