Repository cloudflare/workers-sdk, pull requests merged in 2025-04, with the labels that each got.

#8680 [vite-plugin] improve inspector port handling
  .changeset/hip-parents-shave.md
  .changeset/warm-mammals-invent.md
  packages/vite-plugin-cloudflare/README.md
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/vite-plugin-cloudflare/src/utils.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8713 V3 Backport #8697: prevent `getPlatformProxy` from crashing with internal DOs
  .changeset/shiny-ghosts-flash.md
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler_external_do.jsonc
  fixtures/get-platform-proxy/wrangler_internal_do.jsonc
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/deployment-bundle/entry.ts
Labels: e2e, skip-pr-description-validation, skip-v3-pr

#8748 Update node compat warnings test
  packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts
Labels: no-changeset-required, vite-plugin

#8738 fix: remove stray main field in Hono Pages template
  .changeset/wide-ideas-work.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/templates/hono/pages/c3.ts
  packages/create-cloudflare/templates/hono/pages/templates/wrangler.jsonc
Labels: c3-e2e

#8741 graduate next + assets template
  .changeset/stale-snakes-boil.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/next/c3.ts
  packages/create-cloudflare/templates/next/pages/README.md
  packages/create-cloudflare/templates/next/pages/app/js/app/api/hello/route.js
  packages/create-cloudflare/templates/next/pages/app/js/app/not-found.js
  packages/create-cloudflare/templates/next/pages/app/ts/app/api/hello/route.ts
  packages/create-cloudflare/templates/next/pages/app/ts/app/not-found.tsx
  packages/create-cloudflare/templates/next/pages/c3.ts
  packages/create-cloudflare/templates/next/pages/env.d.ts
  packages/create-cloudflare/templates/next/pages/pages/js/pages/api/hello.js
  packages/create-cloudflare/templates/next/pages/pages/ts/pages/api/hello.ts
  packages/create-cloudflare/templates/next/pages/wrangler.jsonc
  packages/create-cloudflare/templates/next/workers/c3.ts
  packages/create-cloudflare/templates/next/workers/templates/.dev.vars
  packages/create-cloudflare/templates/next/workers/templates/.gitignore
  packages/create-cloudflare/templates/next/workers/templates/cloudflare-env.d.ts
  packages/create-cloudflare/templates/next/workers/templates/open-next.config.ts
  packages/create-cloudflare/templates/next/workers/templates/wrangler.jsonc
Labels: c3-e2e

#8737 fix: General improvements for the R2 catalog commands
  .changeset/tangy-badgers-grow.md
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/r2/catalog.ts
  packages/wrangler/src/r2/helpers.ts
Labels: e2e, skip-v3-pr

#8752 fix missing Vite capitalization in vite-pluging e2e test
  packages/vite-plugin-cloudflare/e2e/invalid-worker-env-configs.test.ts
Labels: e2e, no-changeset-required, skip-v3-pr

#8754 improve turbo settings and vite e2e test config
  packages/vite-plugin-cloudflare/e2e/vitest.config.ts
  packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts
  packages/wrangler/package.json
  packages/wrangler/turbo.json
  turbo.json
Labels: e2e, skip-pr-description-validation, no-changeset-required, skip-v3-pr

#8730 Version Packages
  .changeset/c3-frameworks-update-8731.md
  .changeset/c3-frameworks-update-8732.md
  .changeset/c3-frameworks-update-8734.md
  .changeset/every-wolves-roll.md
  .changeset/five-camels-cheer.md
  .changeset/hip-parents-shave.md
  .changeset/resource-name-from-binding-8719.md
  .changeset/sharp-dogs-love.md
  .changeset/shiny-ghosts-flash.md
  .changeset/stale-snakes-boil.md
  .changeset/tangy-badgers-grow.md
  .changeset/twenty-ads-follow.md
  .changeset/warm-mammals-invent.md
  .changeset/wide-ideas-work.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8612 chore(fixtures): Add fixture tests for Workers + Assets and WebSockets
  fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/workerWS.util.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/wrangler.toml
  fixtures/workers-with-assets-and-service-bindings/workerWS/public/busy-bee.html
  fixtures/workers-with-assets-and-service-bindings/workerWS/public/index.html
  fixtures/workers-with-assets-and-service-bindings/workerWS/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerWS/wrangler.toml
Labels: no-changeset-required

#8750 include documentation_url in api errors
  .changeset/lovely-lemons-count.md
  packages/wrangler/src/__tests__/cfetch-utils.test.ts
  packages/wrangler/src/cfetch/errors.ts
  packages/wrangler/src/cfetch/index.ts
Labels: e2e

#8758 backport #8757
  .changeset/easy-pens-lie.md
  packages/wrangler/src/__tests__/pages/secret.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/pages/secret/index.ts
  packages/wrangler/src/secret/index.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8260 unskip c3 + template test
  packages/create-cloudflare/e2e-tests/cli.test.ts
Labels: no-changeset-required, c3-e2e, skip-v3-pr

#8766 update pnpm lock
  pnpm-lock.yaml
Labels: skip-pr-description-validation, no-changeset-required

#8696 v3 Maintenance Release
  .changeset/easy-pens-lie.md
  .changeset/good-taxis-repeat.md
  .changeset/lovely-lemons-count.md
  .changeset/shiny-ghosts-flash.md
  .changeset/violet-ravens-draw.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8746 Log whether a command is operating on a local or remote resource
  .changeset/better-laws-follow.md
  packages/create-cloudflare/templates/astro/workers/templates/ts/wrangler.jsonc
  packages/wrangler/e2e/r2.test.ts
  packages/wrangler/src/__tests__/__snapshots__/kv.test.ts.snap
  packages/wrangler/src/__tests__/kv.local.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/r2.local.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/core/types.ts
  packages/wrangler/src/kv/index.ts
  packages/wrangler/src/r2/object.ts
  packages/wrangler/src/utils/is-local.ts
Labels: e2e, c3-e2e, skip-v3-pr

#8768 No longer warn if the user sets `upload_source_maps` in the Worker config.
  .changeset/old-guests-smile.md
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/wrangler-with-fields-to-ignore.toml
  packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/vite-plugin-cloudflare/src/utils.ts
  packages/vite-plugin-cloudflare/src/workers-configs.ts
Labels: vite-plugin

#8767 Fix inspector port change being logged on server restarts
  .changeset/plain-lies-retire.md
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#8759 fix: Minor refactor for the R2 catalog commands
  .changeset/tricky-eagles-peel.md
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/r2/catalog.ts
Labels: skip-v3-pr

#8762 Version Packages
  .changeset/better-laws-follow.md
  .changeset/bumpy-owls-fry.md
  .changeset/easy-pens-lie.md
  .changeset/lovely-lemons-count.md
  .changeset/old-guests-smile.md
  .changeset/plain-lies-retire.md
  .changeset/tricky-eagles-peel.md
  .changeset/wet-memes-mix.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/turbo.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8769 🫧 update for SPA mode in c3 templates
  .changeset/shiny-facts-cross.md
  packages/create-cloudflare/templates/react/workers/js/src/App.jsx
  packages/create-cloudflare/templates/react/workers/js/worker/index.js
  packages/create-cloudflare/templates/react/workers/js/wrangler.jsonc
  packages/create-cloudflare/templates/react/workers/ts/src/App.tsx
  packages/create-cloudflare/templates/react/workers/ts/tsconfig.worker.json
  packages/create-cloudflare/templates/react/workers/ts/worker/index.ts
  packages/create-cloudflare/templates/react/workers/ts/wrangler.jsonc
  packages/create-cloudflare/templates/vue/workers/js/server/index.js
  packages/create-cloudflare/templates/vue/workers/js/wrangler.jsonc
  packages/create-cloudflare/templates/vue/workers/ts/server/index.ts
  packages/create-cloudflare/templates/vue/workers/ts/wrangler.jsonc
Labels: c3-e2e

#8774 Remove sourcemaps from NPM release
  .github/workflows/changesets.yml
  packages/create-cloudflare/package.json
  packages/wrangler/package.json
  packages/wrangler/scripts/bundle.ts
Labels: no-changeset-required, c3-e2e

#7894 Write fetch handler so that `npm run start` works
  .changeset/tall-donkeys-pull.md
  packages/create-cloudflare/templates/scheduled/ts/src/index.ts
Labels: c3, c3-e2e

#8778 V3 backport (youch update) #8449
  .changeset/bumpy-owls-fry.md
  packages/miniflare/package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#8747 [miniflare] fix: make sure that `miniflare#setOptions` allows the update of inspector ports
  .changeset/sweet-doors-notice.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/inspector-proxy/inspector-proxy-controller.ts
  packages/miniflare/test/plugins/core/inspector-proxy/index.spec.ts
Labels: miniflare, e2e

#8779 astro template fixup
  packages/create-cloudflare/templates/astro/workers/templates/ts/wrangler.jsonc
Labels: skip-pr-description-validation, c3-e2e

#8787 Bump version to 1.0 and update README.
  .changeset/whole-candles-burn.md
  packages/vite-plugin-cloudflare/README.md
Labels: vite-plugin

#8789 fix types Wrangler e2e test
  packages/wrangler/e2e/types.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#8781 Version Packages
  .changeset/c3-frameworks-update-8070.md
  .changeset/c3-frameworks-update-8733.md
  .changeset/dependabot-update-8712.md
  .changeset/fine-cameras-nail.md
  .changeset/sharp-bottles-agree.md
  .changeset/shiny-facts-cross.md
  .changeset/sweet-doors-notice.md
  .changeset/tall-donkeys-pull.md
  .changeset/tender-geckos-dig.md
  .changeset/whole-candles-burn.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8793 Add GitHub issue types to issue templates
  .github/ISSUE_TEMPLATE/bug-template.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: skip-pr-description-validation

#8208 fix: make vitest-pool-workers not crash with scripts that have Workflows
  .changeset/vast-stars-dig.md
  fixtures/vitest-pool-workers-examples/workflows/README.md
  fixtures/vitest-pool-workers-examples/workflows/src/env.d.ts
  fixtures/vitest-pool-workers-examples/workflows/src/index.ts
  fixtures/vitest-pool-workers-examples/workflows/src/tsconfig.json
  fixtures/vitest-pool-workers-examples/workflows/test/env.d.ts
  fixtures/vitest-pool-workers-examples/workflows/test/integration-self.test.ts
  fixtures/vitest-pool-workers-examples/workflows/test/tsconfig.json
  fixtures/vitest-pool-workers-examples/workflows/tsconfig.json
  fixtures/vitest-pool-workers-examples/workflows/vitest.config.ts
  fixtures/vitest-pool-workers-examples/workflows/wrangler.toml
  packages/vitest-pool-workers/src/pool/index.ts
  packages/vitest-pool-workers/src/pool/loopback.ts
  packages/vitest-pool-workers/src/worker/entrypoints.ts
Labels: e2e

#8698 remove BETA label from Workers+Assets templates and hide Pages templates
  .changeset/clever-squids-unite.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/angular/pages/c3.ts
  packages/create-cloudflare/templates/astro/pages/c3.ts
  packages/create-cloudflare/templates/docusaurus/pages/c3.ts
  packages/create-cloudflare/templates/gatsby/pages/c3.ts
  packages/create-cloudflare/templates/hono/pages/c3.ts
  packages/create-cloudflare/templates/next/pages/c3.ts
  packages/create-cloudflare/templates/nuxt/pages/c3.ts
  packages/create-cloudflare/templates/qwik/pages/c3.ts
  packages/create-cloudflare/templates/react/pages/c3.ts
  packages/create-cloudflare/templates/remix/pages/c3.ts
  packages/create-cloudflare/templates/svelte/pages/c3.ts
  packages/create-cloudflare/templates/vue/pages/c3.ts
Labels: c3-e2e

#8780 Pipelines CLI Improvements
  .changeset/busy-chairs-happen.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/pipelines/cli/create.ts
  packages/wrangler/src/pipelines/cli/get.ts
  packages/wrangler/src/pipelines/cli/show.ts
  packages/wrangler/src/pipelines/cli/update.ts
  packages/wrangler/src/pipelines/index.ts
Labels: e2e, skip-v3-pr

#7260 Fix `fromVitest` conditional
  .changeset/lemon-deers-speak.md
  packages/vitest-pool-workers/src/worker/index.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8596 [wrangler] add validation to redirected configs in regards to environments
  .changeset/sour-things-run.md
  .prettierignore
  fixtures/redirected-config-worker-with-environments/.gitignore
  fixtures/redirected-config-worker-with-environments/package.json
  fixtures/redirected-config-worker-with-environments/src/index.js
  fixtures/redirected-config-worker-with-environments/tests/index.test.ts
  fixtures/redirected-config-worker-with-environments/tools/build.ts
  fixtures/redirected-config-worker-with-environments/tsconfig.json
  fixtures/redirected-config-worker-with-environments/turbo.json
  fixtures/redirected-config-worker-with-environments/vitest.config.mts
  fixtures/redirected-config-worker-with-environments/wrangler.toml
  fixtures/redirected-config-worker/tests/index.test.ts
  fixtures/shared/src/run-wrangler-long-lived.ts
  packages/wrangler/src/config/validation.ts
  pnpm-lock.yaml
Labels: e2e

#8394 Secrets Store Secret binding local dev
  .changeset/calm-grapes-eat.md
  fixtures/secrets-store/package.json
  fixtures/secrets-store/src/index.ts
  fixtures/secrets-store/tsconfig.json
  fixtures/secrets-store/wrangler.jsonc
  fixtures/worker-ts/wrangler.toml
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/plugins/secret-store/index.ts
  packages/miniflare/src/workers/secrets-store/constants.ts
  packages/miniflare/src/workers/secrets-store/secret.worker.ts
  packages/miniflare/test/plugins/secret-store/index.spec.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/secrets-store.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/secrets-store/commands.ts
  packages/wrangler/src/type-generation/index.ts
  packages/wrangler/src/utils/print-bindings.ts
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#8806 Replace assertion in node-js compat transform hook with early return
  .changeset/big-trees-drum.md
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#8812 update changeset to patch
  .changeset/tiny-ideas-nail.md
Labels: skip-pr-description-validation, skip-v3-pr

#8821 chore: run dependabot updates outside of busy times
  .github/dependabot.yml
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#8375 Email Workers local dev and send_email binding
  .changeset/neat-planes-call.md
  fixtures/email-worker/package.json
  fixtures/email-worker/src/index.ts
  fixtures/email-worker/tsconfig.json
  fixtures/email-worker/worker-configuration.d.ts
  fixtures/email-worker/wrangler.toml
  package.json
  packages/miniflare/package.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/email/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/workers/core/constants.ts
  packages/miniflare/src/workers/core/email.ts
  packages/miniflare/src/workers/core/entry.worker.ts
  packages/miniflare/src/workers/core/scheduled.ts
  packages/miniflare/src/workers/email/constants.ts
  packages/miniflare/src/workers/email/email.worker.ts
  packages/miniflare/src/workers/email/send_email.worker.ts
  packages/miniflare/src/workers/email/validate.ts
  packages/miniflare/src/workers/tsconfig.json
  packages/miniflare/test/index.spec.ts
  packages/miniflare/test/plugins/email/index.spec.ts
  packages/miniflare/test/plugins/secret-store/index.spec.ts
  packages/miniflare/tsconfig.json
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/utils/print-bindings.ts
  patches/postal-mime.patch
  pnpm-lock.yaml
Labels: e2e

#8836 add `preventAssignment` to `replace` call (to prevent terminal warning)
  packages/vite-plugin-cloudflare/src/index.ts
Labels: e2e, no-changeset-required, vite-plugin

#8809 Improve error message displayed when a redirected config includes multiple environments
  .changeset/silent-keys-bake.md
  fixtures/redirected-config-worker-with-environments/tests/index.test.ts
  fixtures/redirected-config-worker-with-environments/tools/build.ts
  fixtures/redirected-config-worker/tests/index.test.ts
  packages/wrangler/src/config/validation.ts
Labels: e2e, skip-v3-pr

#8829 Add options to update pipelines to remove CORS
  .changeset/slow-roses-create.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/pipelines/cli/create.ts
  packages/wrangler/src/pipelines/cli/delete.ts
  packages/wrangler/src/pipelines/cli/get.ts
  packages/wrangler/src/pipelines/cli/update.ts
  packages/wrangler/src/pipelines/index.ts
  packages/wrangler/src/pipelines/validate.ts
Labels: e2e, skip-v3-pr

#8854 Version Packages
  .changeset/dependabot-update-8810.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8846 use latest version of wrangler when using c3 to init from dash
  .changeset/eager-dragons-stand.md
  packages/create-cloudflare/templates/pre-existing/c3.ts
Labels: c3-e2e

#8862 Fix Node.js externals usage causing dev server to crash
  .changeset/true-wings-arrive.md
  packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-resolve-externals/resolve-externals.spec.ts
  packages/vite-plugin-cloudflare/playground/node-compat/package.json
  packages/vite-plugin-cloudflare/playground/node-compat/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-resolve-externals.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-resolve-externals/index.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-resolve-externals/wrangler.jsonc
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
Labels: vite-plugin

#8861 Version Packages
  .changeset/eager-dragons-stand.md
  .changeset/true-wings-arrive.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
Labels: e2e, c3-e2e

#8785 v3 Maintenance Release
  .changeset/bumpy-owls-fry.md
  .changeset/dependabot-update-8810.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8865 chore: open v3 backport PR only if the current PR targets main
  .github/workflows/open-v3-maintenance-prs.yml
Labels: no-changeset-required

#8600 V3 Backport (add validation to redirected configs in regards to environments #8596)
  .changeset/sour-things-run.md
  .prettierignore
  fixtures/redirected-config-worker-with-environments/.gitignore
  fixtures/redirected-config-worker-with-environments/package.json
  fixtures/redirected-config-worker-with-environments/src/index.js
  fixtures/redirected-config-worker-with-environments/tests/index.test.ts
  fixtures/redirected-config-worker-with-environments/tools/build.ts
  fixtures/redirected-config-worker-with-environments/tsconfig.json
  fixtures/redirected-config-worker-with-environments/turbo.json
  fixtures/redirected-config-worker-with-environments/vitest.config.mts
  fixtures/redirected-config-worker-with-environments/wrangler.toml
  fixtures/redirected-config-worker/tests/index.test.ts
  fixtures/shared/src/run-wrangler-long-lived.ts
  packages/wrangler/src/config/validation.ts
  pnpm-lock.yaml
Labels: skip-pr-description-validation, skip-v3-pr

#8842 fix a comment in wrangler API
  packages/wrangler/src/api/integrations/platform/index.ts
Labels: no-changeset-required

#8845 Refactor Turbo + CI jobs
  .github/pr-labeler.config.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/e2e.yml
  .github/workflows/test-and-check.yml
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/turbo.json
  packages/miniflare/package.json
  packages/miniflare/test/index.spec.ts
  packages/miniflare/turbo.json
  packages/turbo-r2-archive/turbo.json
  packages/vite-plugin-cloudflare/turbo.json
  packages/workers-shared/turbo.json
  packages/workflows-shared/turbo.json
  packages/wrangler/turbo.json
  turbo.json
Labels: e2e, no-changeset-required, c3-e2e

#8874 rename c3 options
  .changeset/breezy-cats-trade.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/templates/hello-world-assets-only/c3.ts
  packages/create-cloudflare/templates/hello-world-with-assets/c3.ts
Labels: c3-e2e

#8877 chore: re-run v3 backport on label changes
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/open-v3-pr.ts
Labels: no-changeset-required, skip-v3-pr

#8685 [vite-plugin] make sure that `.dev.vars` files trigger a full reload
  .changeset/blue-hats-accept.md
  packages/vite-plugin-cloudflare/playground/config-changes/.dev.vars
  packages/vite-plugin-cloudflare/playground/config-changes/.gitignore
  packages/vite-plugin-cloudflare/playground/config-changes/__tests__/config-changes.spec.ts
  packages/vite-plugin-cloudflare/playground/config-changes/src/index.ts
  packages/vite-plugin-cloudflare/playground/config-changes/vite.config.with-cloudflare-env.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/__tests__/vars-changes.spec.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/__tests__/with-specified-env/vars-changes.spec.ts
  packages/vite-plugin-cloudflare/src/asset-config.ts
  packages/vite-plugin-cloudflare/src/index.ts
Labels: e2e, vite-plugin

#8875 Add label to run on multiple OSs
  .github/workflows/c3-e2e.yml
  .github/workflows/e2e.yml
  .github/workflows/test-and-check.yml
Labels: e2e, no-changeset-required, c3-e2e, every-os

#8807 feat: promote Workflow commands to stable
  .changeset/nine-weeks-hug.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/workflows/commands/delete.ts
  packages/wrangler/src/workflows/commands/describe.ts
  packages/wrangler/src/workflows/commands/instances/describe.ts
  packages/wrangler/src/workflows/commands/instances/list.ts
  packages/wrangler/src/workflows/commands/instances/pause.ts
  packages/wrangler/src/workflows/commands/instances/resume.ts
  packages/wrangler/src/workflows/commands/instances/terminate-all.ts
  packages/wrangler/src/workflows/commands/instances/terminate.ts
  packages/wrangler/src/workflows/commands/list.ts
  packages/wrangler/src/workflows/commands/trigger.ts
  packages/wrangler/src/workflows/index.ts
Labels: e2e, skip-v3-pr

#8882 chore: update changeset
  .changeset/nine-weeks-hug.md
Labels: skip-pr-description-validation

#8783 V3 backport (add hint when no permission to show membership info #8341)
  .changeset/sharp-bottles-agree.md
  packages/wrangler/src/__tests__/whoami.test.ts
  packages/wrangler/src/user/whoami.ts
Labels: e2e, skip-pr-description-validation, c3-e2e

#8813 V3 backport (Unhide 'wrangler pages functions build' #8795)
  .changeset/tiny-ideas-nail.md
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/index.ts
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: skip-pr-description-validation

#8883 Fix multiple request logging
  .changeset/sour-islands-watch.md
  packages/miniflare/src/workers/core/entry.worker.ts
  packages/wrangler/e2e/dev.test.ts
Labels: e2e, regression, skip-v3-pr

#8864 Version Packages
  .changeset/blue-hats-accept.md
  .changeset/breezy-cats-trade.md
  .changeset/dependabot-update-8859.md
  .changeset/nine-weeks-hug.md
  .changeset/sour-islands-watch.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8866 V3 Backport (Improve error message displayed when a redirected config includes multiple environments #8809)
  .changeset/silent-keys-bake.md
  fixtures/redirected-config-worker-with-environments/tests/index.test.ts
  fixtures/redirected-config-worker-with-environments/tools/build.ts
  fixtures/redirected-config-worker/tests/index.test.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-pr-description-validation

#8885 fix(wrangler): Disambiguate the "No files to upload. Proceeding with deployment..." message
  .changeset/mean-badgers-battle.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/src/assets.ts
Labels: e2e, skip-v3-pr

#8878 vite-plugin: add support for Node.js ALS compat mode
  .changeset/nasty-mice-dance.md
  packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-als/als.spec.ts
  packages/vite-plugin-cloudflare/playground/node-compat/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-als.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-als/wrangler.jsonc
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  packages/vite-plugin-cloudflare/src/worker-environments-validation.ts
Labels: e2e, vite-plugin

#8910 Revert "V3 backport (Unhide 'wrangler pages functions build' #8795)"
  .changeset/tiny-ideas-nail.md
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/pages/build.ts
  packages/wrangler/src/pages/index.ts
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: skip-pr-description-validation

#8890 Update wrangler esbuild version
  .changeset/brave-gifts-occur.md
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/alias-external.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: e2e, c3-e2e, skip-v3-pr, every-os

#8888 Improve PR comments
  .github/extract-runtime-versions.mjs
  .github/prereleases/3-comment.mjs
  .github/workflows/create-pullrequest-prerelease.yml
  .github/workflows/open-v3-maintenance-prs.yml
  .github/workflows/write-prerelease-comment.yml
  .gitignore
Labels: no-changeset-required

#8799 docs: fix worker compat URL in docstring
  packages/wrangler/src/config/environment.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#8244 feat(wrangler): Add debug logs to capture assets upload status
  .changeset/thin-bears-smile.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/assets.ts
Labels: e2e, skip-v3-pr, every-os

#8929 Add " in v3 backport script
  tools/deployments/open-v3-pr.ts
Labels: skip-pr-description-validation, no-changeset-required

#7802 Add fixtures using startWorker() and Miniflare directly
  fixtures/miniflare-node-test/package.json
  fixtures/miniflare-node-test/src/index-build.test.js
  fixtures/miniflare-node-test/src/index-with-bindings.test.js
  fixtures/miniflare-node-test/src/index-with-imports.js
  fixtures/miniflare-node-test/src/index-with-imports.test.js
  fixtures/miniflare-node-test/src/index.js
  fixtures/miniflare-node-test/src/index.test.js
  fixtures/miniflare-node-test/src/index.ts
  fixtures/miniflare-node-test/src/say-hello.js
  fixtures/miniflare-node-test/tsconfig.json
  fixtures/miniflare-node-test/wrangler-build.json
  fixtures/miniflare-node-test/wrangler.toml
  fixtures/start-worker-node-test/package.json
  fixtures/start-worker-node-test/src/index.test.js
  fixtures/start-worker-node-test/src/index.ts
  fixtures/start-worker-node-test/src/say-hello.ts
  fixtures/start-worker-node-test/tsconfig.json
  fixtures/start-worker-node-test/wrangler.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#8930 chore: comment on v3 backport status only if it has wrangler patch
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/open-v3-pr.ts
Labels: no-changeset-required

#8925 ci timeout in e2e tests
  .github/workflows/e2e.yml
Labels: no-changeset-required

#8928 V3 Backport for #8924
  .changeset/odd-steaks-cheat.md
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-pr-description-validation

#8900 Version Packages
  .changeset/brave-gifts-occur.md
  .changeset/c3-frameworks-update-8814.md
  .changeset/c3-frameworks-update-8815.md
  .changeset/c3-frameworks-update-8816.md
  .changeset/c3-frameworks-update-8818.md
  .changeset/c3-frameworks-update-8820.md
  .changeset/c3-frameworks-update-8834.md
  .changeset/c3-frameworks-update-8835.md
  .changeset/dependabot-update-8873.md
  .changeset/mean-badgers-battle.md
  .changeset/nasty-mice-dance.md
  .changeset/odd-steaks-cheat.md
  .changeset/shy-cooks-flow.md
  .changeset/sweet-rocks-clean.md
  .changeset/thin-bears-smile.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8933 chore: run e2e on every os when updating workerd version
  .github/dependabot.yml
Labels: no-changeset-required

#8708 Add --template-mode to create-cloudflare
  .changeset/solid-needles-deny.md
  packages/create-cloudflare/src/__tests__/templates.test.ts
  packages/create-cloudflare/src/helpers/__tests__/args.test.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/src/types.ts
Labels: c3-e2e, post-devweek

#8952 fix(create-cloudflare): update help test snapshot
  packages/create-cloudflare/e2e-tests/cli.test.ts
Labels: no-changeset-required, c3-e2e, every-os

#8961 chore: update changset
  .changeset/cute-carpets-sneeze.md
Labels: skip-pr-description-validation

#8945 Version Packages
  .changeset/cold-pumas-shout.md
  .changeset/cuddly-news-double.md
  .changeset/cute-carpets-sneeze.md
  .changeset/solid-needles-deny.md
  .changeset/wild-books-melt.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8889 Add warning to Wrangler if using the Bun runtime and an error is encountered
  .changeset/cold-donuts-fetch.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/utils/logPossibleBugMessage.ts
Labels: skip-pr-description-validation

#8804 Add support for Vitest 3.1.x
  .changeset/stupid-goats-share.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/src/__tests__/d1/insights.test.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: e2e, vitest, c3-e2e, post-devweek

#8949 bump create-next-app to 15.3.0 for the Workers template
  .changeset/tough-friends-share.md
  packages/create-cloudflare/templates/next/workers/c3.ts
Labels: c3-e2e

#8955 V3 Backport [#8889]: Add warning to Wrangler if using the Bun runtime and an error is encountered
  .changeset/cold-donuts-fetch.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/utils/logPossibleBugMessage.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8316 feat: :sparkles: introduce ip param for wrangler login command, fixes [5937]
  .changeset/salty-ties-find.md
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/user/commands.ts
  packages/wrangler/src/user/user.ts
Labels: skip-pr-description-validation, post-devweek

#8936 chore: cleanup e2e test certs
  packages/wrangler/e2e/cert.test.ts
  tools/e2e/common.ts
  tools/e2e/e2eCleanup.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required

#8991 fix changesets
  .changeset/c3-frameworks-update-8919.md
  .changeset/c3-frameworks-update-8948.md
  .changeset/huge-kings-switch.md
  .changeset/stupid-goats-share.md
Labels: skip-pr-description-validation, skip-v3-pr

#8965 Version Packages
  .changeset/c3-frameworks-update-8919.md
  .changeset/c3-frameworks-update-8946.md
  .changeset/c3-frameworks-update-8947.md
  .changeset/c3-frameworks-update-8948.md
  .changeset/cold-donuts-fetch.md
  .changeset/dependabot-update-8927.md
  .changeset/huge-kings-switch.md
  .changeset/salty-ties-find.md
  .changeset/stupid-goats-share.md
  .changeset/tough-friends-share.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8978 fix(create-cloudflare): keep the default _headers and _redirects files in the qwik workers template
  .changeset/fancy-cobras-rhyme.md
  packages/create-cloudflare/templates/qwik/workers/c3.ts
Labels: c3-e2e

#8935 Move local analytics engine from Wrangler to Miniflare
  .changeset/tough-dodos-guess.md
  packages/miniflare/src/plugins/analytics-engine/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/workers/analytics-engine/analytics-engine.worker.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/templates/middleware/middleware-mock-analytics-engine.d.ts
  packages/wrangler/templates/middleware/middleware-mock-analytics-engine.ts
Labels: e2e, skip-v3-pr

#9025 fix changeset
  .changeset/tough-dodos-guess.md
Labels: skip-v3-pr

#8996 Version Packages
  .changeset/c3-frameworks-update-9012.md
  .changeset/c3-frameworks-update-9013.md
  .changeset/c3-frameworks-update-9014.md
  .changeset/c3-frameworks-update-9015.md
  .changeset/c3-frameworks-update-9016.md
  .changeset/c3-frameworks-update-9017.md
  .changeset/dependabot-update-8993.md
  .changeset/fancy-cobras-rhyme.md
  .changeset/tough-dodos-guess.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8943 v3 Maintenance Release
  .changeset/cold-donuts-fetch.md
  .changeset/odd-steaks-cheat.md
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8640 Implement support for ctx.props.
  .changeset/curly-groups-scream.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/core/services.ts
  packages/miniflare/src/runtime/config/workerd.ts
  packages/wrangler/e2e/multiworker-dev.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/miniflare.ts
Labels: e2e

#9024 Add undefined/null checks to containers list
  .changeset/cold-aliens-learn.md
  packages/wrangler/src/containers/containers.ts
Labels: skip-v3-pr

#7796 feat(create-cloudflare): Update openapi template to include better ts types and lint command
  .changeset/perfect-geckos-tell.md
  packages/create-cloudflare/templates/openapi/ts/.gitignore
  packages/create-cloudflare/templates/openapi/ts/package.json
  packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskCreate.ts
  packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskDelete.ts
  packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskFetch.ts
  packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskList.ts
  packages/create-cloudflare/templates/openapi/ts/src/index.ts
  packages/create-cloudflare/templates/openapi/ts/src/types.ts
  packages/create-cloudflare/templates/openapi/ts/tsconfig.json
Labels: c3-e2e

#8771 feat: add `config.keep_names` option
  .changeset/long-mugs-pull.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/dev/use-esbuild.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e, post-devweek

#9028 Version Packages
  .changeset/cold-aliens-learn.md
  .changeset/curly-groups-scream.md
  .changeset/dependabot-update-9030.md
  .changeset/long-mugs-pull.md
  .changeset/perfect-geckos-tell.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8860 KV: improve error messages for 400 errors
  .changeset/tender-bushes-move.md
  packages/miniflare/src/workers/kv/namespace.worker.ts
  packages/miniflare/test/plugins/kv/index.spec.ts
Labels: e2e

#9031 feat(create-cloudflare): update react template to fix type errors
  .changeset/fluffy-mice-attack.md
  packages/create-cloudflare/templates/react/workers/c3.ts
  packages/create-cloudflare/templates/react/workers/ts/tsconfig.worker.json
Labels: c3-e2e

#8990 fix version metadata binding type in when generating env type
  .changeset/plenty-beans-enjoy.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e

#9037 V3 backport[#8990]: Fix version metadata binding type in when generating env type
  .changeset/plenty-beans-enjoy.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/type-generation/index.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8962 chore: add workflow to check v3 patch status
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/__tests__/check-v3-patch-status.test.ts
  tools/deployments/check-v3-patch-status.ts
Labels: no-changeset-required

#8983 Removes open-beta disclaimer from workflows commands
  .changeset/eighty-knives-reply.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/versions/deploy.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e, skip-v3-pr

#8941 Fix e2e hyperdrive cleanup + logging
  tools/e2e/common.ts
  tools/e2e/e2eCleanup.ts
Labels: no-changeset-required

#9034 Version Packages
  .changeset/blue-suns-battle.md
  .changeset/dependabot-update-9041.md
  .changeset/eighty-knives-reply.md
  .changeset/fluffy-mice-attack.md
  .changeset/old-ghosts-grin.md
  .changeset/plenty-beans-enjoy.md
  .changeset/tame-views-learn.md
  .changeset/tender-bushes-move.md
  .changeset/thirty-apples-invite.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9049 Version Packages
  .changeset/seven-humans-scream.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/devprod-status-bot/CHANGELOG.md
  packages/devprod-status-bot/package.json
  packages/edge-preview-authenticated-proxy/CHANGELOG.md
  packages/edge-preview-authenticated-proxy/package.json
  packages/format-errors/CHANGELOG.md
  packages/format-errors/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/prerelease-registry/CHANGELOG.md
  packages/prerelease-registry/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/workers.new/CHANGELOG.md
  packages/workers.new/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9061 chore: cleanup unused workflow job
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/__tests__/check-v3-patch-status.test.ts
  tools/deployments/check-v3-patch-status.ts
Labels: no-changeset-required

#8975 Adds missing waiting status
  .changeset/loose-results-think.md
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/workflows/types.ts
  packages/wrangler/src/workflows/utils.ts
Labels: e2e

#9060 chore: add v3 maintenance workflow
  .github/workflows/check-v3-backport-status.yml
  tools/deployments/__tests__/check-v3-backport-status.test.ts
  tools/deployments/check-v3-backport-status.ts
Labels: no-changeset-required

#9084 chore: skip checking backport status on v3 version release
  .github/workflows/check-v3-backport-status.yml
Labels: no-changeset-required

#8981 Adds support for `waitForEvent` step type
  .changeset/swift-hairs-run.md
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/workflows/commands/instances/describe.ts
  packages/wrangler/src/workflows/types.ts
  packages/wrangler/src/workflows/utils.ts
Labels: e2e

#8994 Install `@opennextjs/cloudflare` as regular dependency
  .changeset/heavy-sides-shake.md
  packages/create-cloudflare/templates/next/workers/c3.ts
Labels: c3-e2e

#9083 Support Tail Workers in local dev
  .changeset/wild-boxes-invite.md
  fixtures/worker-app/src/index.js
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/runtime/config/workerd.ts
  packages/miniflare/test/index.spec.ts
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/dev-registry.test.ts
  packages/wrangler/e2e/multiworker-dev.test.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/provision.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/dev-registry/index.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/utils/print-bindings.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#9048 fix: Validate input file for Vectorize inserts
  .changeset/stupid-paws-slide.md
  packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
  packages/wrangler/src/__tests__/vectorize/vectorize.upsert.test.ts
  packages/wrangler/src/vectorize/common.ts
  packages/wrangler/src/vectorize/create.ts
  packages/wrangler/src/vectorize/deleteByIds.ts
  packages/wrangler/src/vectorize/getByIds.ts
  packages/wrangler/src/vectorize/insert.ts
  packages/wrangler/src/vectorize/query.ts
  packages/wrangler/src/vectorize/upsert.ts
Labels: e2e

#9087 Add `global_fetch_strictly_public` to the Next template for workers
  .changeset/kind-dolls-swim.md
  packages/create-cloudflare/templates/next/workers/templates/wrangler.jsonc
Labels: c3-e2e

#9097 chore: add tests for new python DO templates
  packages/create-cloudflare/e2e-tests/workers.test.ts
Labels: no-changeset-required, c3-e2e

#9058 Version Packages
  .changeset/bitter-walls-cough.md
  .changeset/c3-frameworks-update-9070.md
  .changeset/c3-frameworks-update-9071.md
  .changeset/c3-frameworks-update-9072.md
  .changeset/c3-frameworks-update-9073.md
  .changeset/c3-frameworks-update-9074.md
  .changeset/cyan-ends-melt.md
  .changeset/dependabot-update-9081.md
  .changeset/heavy-sides-shake.md
  .changeset/kind-dolls-swim.md
  .changeset/loose-results-think.md
  .changeset/stupid-paws-slide.md
  .changeset/swift-hairs-run.md
  .changeset/wild-boxes-invite.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/e2e/dev-registry.test.ts
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9085 Do not include .wrangler and Wrangler config files in additional modules
  .changeset/eager-bobcats-agree.md
  packages/vite-plugin-cloudflare/playground/multi-worker/__tests__/multi-worker.spec.ts
  packages/vite-plugin-cloudflare/playground/multi-worker/package.json
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/find-additional-modules.test.ts
  packages/wrangler/src/__tests__/navigator-user-agent.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deployment-bundle/entry.ts
  packages/wrangler/src/deployment-bundle/find-additional-modules.ts
  packages/wrangler/src/pages/functions/buildPlugin.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  packages/wrangler/src/paths.ts
Labels: e2e, skip-v3-pr

#9095 wrangler login put custom callback host and port into the auth URL
  .changeset/tough-bats-live.md
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/user/user.ts
Labels: skip-v3-pr
