Repository cloudflare/workers-sdk, pull requests merged in 2025-01, with the labels that each got.

#7658 cleanup unnecessary nullish coalescing operation
  packages/create-cloudflare/src/helpers/compatDate.ts
Labels: no-changeset-required

#7628 test(nodejs-hybrid-app): factor test setup
  fixtures/nodejs-hybrid-app/tests/index.test.ts
Labels: no-changeset-required

#7675 chore: fix broken e2e tests from merge error
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
Labels: e2e, no-changeset-required

#7625 feat(wrangler): use unenv bulitin dependency resolution
  .changeset/chilled-needles-notice.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Labels: e2e

#7682 chore(vitest-pool-workers): test intercepting fetch with different query pattern
  fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
Labels: no-changeset-required

#7681 chore: add d1 and kv to e2e cleanup job
  tools/e2e/__tests__/common.test.ts
  tools/e2e/common.ts
  tools/e2e/e2eCleanup.ts
Labels: no-changeset-required

#7608 Version Packages
  .changeset/c3-frameworks-update-7617.md
  .changeset/c3-frameworks-update-7618.md
  .changeset/c3-frameworks-update-7619.md
  .changeset/c3-frameworks-update-7620.md
  .changeset/c3-frameworks-update-7621.md
  .changeset/c3-frameworks-update-7622.md
  .changeset/c3-frameworks-update-7623.md
  .changeset/c3-frameworks-update-7624.md
  .changeset/c3-frameworks-update-7643.md
  .changeset/c3-frameworks-update-7644.md
  .changeset/c3-frameworks-update-7645.md
  .changeset/c3-frameworks-update-7646.md
  .changeset/c3-frameworks-update-7647.md
  .changeset/c3-frameworks-update-7673.md
  .changeset/chilled-mugs-fail.md
  .changeset/chilled-needles-notice.md
  .changeset/dependabot-update-7652.md
  .changeset/empty-cars-provide.md
  .changeset/gorgeous-kids-protect.md
  .changeset/long-houses-mate.md
  .changeset/moody-bikes-cross.md
  .changeset/moody-suns-chew.md
  .changeset/nice-pandas-wait.md
  .changeset/quick-years-run.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7685 test(wrangler): allow overriding the unenv preset
  .changeset/twelve-fireants-hunt.md
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
Labels: e2e

#7683 chore(unenv-preset): publish beta pre-release
  .github/workflows/prereleases.yml
  packages/unenv-preset/package.json
Labels: no-changeset-required

#7456 Remove --experimental-versions (and related flags) as it is now GA
  .changeset/bright-keys-march.md
  packages/wrangler/CONTRIBUTING.md
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/__tests__/rollback.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
  packages/wrangler/src/__tests__/versions/deployments/deployments.view.test.ts
  packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
  packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
  packages/wrangler/src/__tests__/versions/secrets/list.test.ts
  packages/wrangler/src/__tests__/versions/secrets/put.test.ts
  packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/__tests__/versions/versions.list.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/__tests__/versions/versions.view.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deprecated/index.ts
  packages/wrangler/src/generate/index.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/triggers/index.ts
  packages/wrangler/src/yargs-types.ts
Labels: e2e

#7684 refactor(CI): explicitly set encoding when reading package.json
  .github/version-script.js
Labels: no-changeset-required

#7698 test: ensure that the sub-packages of npm-import fixture are also initialised
  fixtures/import-npm/package.json
Labels: skip-pr-description-validation

#7388 Remove node_compat flag from C3 templates that use Vitest Pool Workers
  .changeset/healthy-bags-cry.md
  .changeset/polite-goats-behave.md
  fixtures/vitest-pool-workers-examples/basics-integration-auxiliary/wrangler.toml
  fixtures/vitest-pool-workers-examples/basics-unit-integration-self/wrangler.toml
  fixtures/vitest-pool-workers-examples/d1/wrangler.toml
  fixtures/vitest-pool-workers-examples/durable-objects/wrangler.toml
  fixtures/vitest-pool-workers-examples/external-package-resolution/wrangler.toml
  fixtures/vitest-pool-workers-examples/hyperdrive/wrangler.toml
  fixtures/vitest-pool-workers-examples/internal-module-resolution/wrangler.toml
  fixtures/vitest-pool-workers-examples/kv-r2-caches/wrangler.toml
  fixtures/vitest-pool-workers-examples/misc/wrangler.toml
  fixtures/vitest-pool-workers-examples/multiple-workers/api-service/wrangler.toml
  fixtures/vitest-pool-workers-examples/multiple-workers/auth-service/wrangler.toml
  fixtures/vitest-pool-workers-examples/multiple-workers/database-service/wrangler.toml
  fixtures/vitest-pool-workers-examples/pages-with-config/wrangler.toml
  fixtures/vitest-pool-workers-examples/queues/wrangler.toml
  fixtures/vitest-pool-workers-examples/request-mocking/wrangler.toml
  fixtures/vitest-pool-workers-examples/rpc/wrangler.toml
  fixtures/vitest-pool-workers-examples/web-assembly/wrangler.toml
  fixtures/vitest-pool-workers-examples/workers-assets-only/wrangler.toml
  fixtures/vitest-pool-workers-examples/workers-assets/wrangler.toml
  packages/create-cloudflare/templates/hello-world/js/wrangler.toml
  packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
  packages/vitest-pool-workers/src/pool/index.ts
Labels: e2e

#7705 ensure that the import-npm fixture's node_modules are cached by turbo
  fixtures/import-npm/turbo.json
Labels: skip-pr-description-validation, no-changeset-required

#7709 test: add missing await
  fixtures/pages-workerjs-with-config-file-app/tests/index.test.ts
Labels: no-changeset-required

#7708 chore: delete more orphaned e2e resources
  tools/e2e/__tests__/common.test.ts
  tools/e2e/common.ts
Labels: no-changeset-required

#7700 test(unenv-preset): move tests from nodejs-hybrid-app
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/unenv-preset/package.json
  packages/unenv-preset/tests/index.test.ts
  packages/unenv-preset/tests/worker/index.ts
  packages/unenv-preset/tests/worker/wrangler.json
  pnpm-lock.yaml
Labels: no-changeset-required

#7534 feat: Use OAuth flow to generate R2 tokens for Pipelines
  .changeset/odd-ducks-attack.md
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/pipelines/client.ts
  packages/wrangler/src/pipelines/index.ts
  pnpm-lock.yaml
Labels: caretaking

#7712 Remove CF-Connecting-IP for requests to the edge preview
  .changeset/honest-pillows-tease.md
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
Labels: e2e

#7692 Version Packages
  .changeset/bright-keys-march.md
  .changeset/fuzzy-nails-invent.md
  .changeset/green-dodos-push.md
  .changeset/green-socks-trade.md
  .changeset/healthy-bags-cry.md
  .changeset/honest-pillows-tease.md
  .changeset/hungry-llamas-repair.md
  .changeset/nervous-scissors-suffer.md
  .changeset/odd-ducks-attack.md
  .changeset/polite-goats-behave.md
  .changeset/proud-rules-try.md
  .changeset/red-lamps-obey.md
  .changeset/red-pillows-provide.md
  .changeset/silver-plums-brake.md
  .changeset/thin-pots-camp.md
  .changeset/three-chefs-bathe.md
  .changeset/twelve-fireants-hunt.md
  .changeset/young-icons-rescue.md
  packages/chrome-devtools-patches/CHANGELOG.md
  packages/chrome-devtools-patches/package.json
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7706 Remove express-based dev registry
  .changeset/ten-eyes-tease.md
  .gitignore
  fixtures/get-platform-proxy/tests/shared.ts
  fixtures/shared/src/run-wrangler-long-lived.ts
  packages/pages-shared/package.json
  packages/wrangler/e2e/dev-registry.test.ts
  packages/wrangler/e2e/get-platform-proxy.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/bundle.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/__tests__/unstableDev.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/cli.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/dev-registry/index.ts
  packages/wrangler/src/dev-registry/server-registry.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/experimental-flags.ts
  packages/wrangler/src/pages/dev.ts
  pnpm-lock.yaml
Labels: e2e

#7719 chore: consolidate to a single rimraf version
  package.json
  packages/miniflare/package.json
  packages/workers-shared/package.json
  packages/workflows-shared/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: no-changeset-required

#7724 ci: add package name to the PR artifacts
  .github/prereleases/3-comment.mjs
Labels: no-changeset-required

#7745 test: fix c3 integration test
  packages/wrangler/e2e/c3-integration.test.ts
Labels: e2e, no-changeset-required

#7630 fix(playground-preview-worker,edge-preview-authenticated-proxy): allow overriding raw request method with the X-CF-Http-Method header
  .changeset/dull-coins-scream.md
  packages/edge-preview-authenticated-proxy/src/index.ts
  packages/edge-preview-authenticated-proxy/tests/index.test.ts
  packages/playground-preview-worker/src/index.ts
  packages/playground-preview-worker/tests/index.test.ts
Labels: e2e, preview:workers-playground, preview:quick-edit

#7734 Pull out all exported functions from Wrangler's index
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/d1/create.ts
  packages/wrangler/src/d1/delete.ts
  packages/wrangler/src/d1/execute.ts
  packages/wrangler/src/d1/export.ts
  packages/wrangler/src/d1/info.ts
  packages/wrangler/src/d1/insights.ts
  packages/wrangler/src/d1/list.ts
  packages/wrangler/src/d1/migrations/apply.ts
  packages/wrangler/src/d1/migrations/create.ts
  packages/wrangler/src/d1/migrations/list.ts
  packages/wrangler/src/d1/timeTravel/info.ts
  packages/wrangler/src/d1/timeTravel/restore.ts
  packages/wrangler/src/delete.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployments.ts
  packages/wrangler/src/dispatch-namespace.ts
  packages/wrangler/src/generate/index.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/deployment-tails.ts
  packages/wrangler/src/pages/secret/index.ts
  packages/wrangler/src/pipelines/index.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/tail/createTail.ts
  packages/wrangler/src/tail/index.ts
  packages/wrangler/src/triggers/index.ts
  packages/wrangler/src/utils/constants.ts
  packages/wrangler/src/utils/getDevCompatibilityDate.ts
  packages/wrangler/src/utils/getLegacyScriptName.ts
  packages/wrangler/src/utils/getRules.ts
  packages/wrangler/src/utils/getScriptName.ts
  packages/wrangler/src/utils/isLegacyEnv.ts
  packages/wrangler/src/utils/logPossibleBugMessage.ts
  packages/wrangler/src/versions/secrets/bulk.ts
  packages/wrangler/src/versions/secrets/delete.ts
  packages/wrangler/src/versions/secrets/list.ts
  packages/wrangler/src/versions/secrets/put.ts
  packages/wrangler/src/versions/upload.ts
Labels: no-changeset-required

#7738 Use TEXT bindings for plain text values in Miniflare
  .changeset/dry-numbers-doubt.md
  packages/miniflare/src/plugins/core/index.ts
Labels: e2e

#7737 Bundle & pin Wrangler dependencies
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/pages/functions/buildWorker.ts
  pnpm-lock.yaml
Labels: e2e, no-changeset-required

#7716 Version Packages
  .changeset/angry-ants-call.md
  .changeset/c3-frameworks-update-7746.md
  .changeset/c3-frameworks-update-7747.md
  .changeset/c3-frameworks-update-7748.md
  .changeset/c3-frameworks-update-7749.md
  .changeset/dry-numbers-doubt.md
  .changeset/dull-coins-scream.md
  .changeset/eleven-dingos-scream.md
  .changeset/lemon-years-sniff.md
  .changeset/many-boats-glow.md
  .changeset/polite-vans-refuse.md
  .changeset/shy-flies-float.md
  .changeset/ten-eyes-tease.md
  .changeset/young-apes-battle.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/edge-preview-authenticated-proxy/CHANGELOG.md
  packages/edge-preview-authenticated-proxy/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/playground-preview-worker/CHANGELOG.md
  packages/playground-preview-worker/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7760 chore: update unenv depency version
  .changeset/fifty-flies-visit.md
  package.json
  packages/unenv-preset/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e

#7733 feat: pull resource names for provisioning from config if provided
  .changeset/smart-lions-suffer.md
  packages/wrangler/src/__tests__/provision.test.ts
  packages/wrangler/src/d1/list.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
Labels: e2e

#7720 chore(wrangler): use the unenv preset from `@cloudflare/unenv-preset`
  .changeset/cuddly-pets-smell.md
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  pnpm-lock.yaml
Labels: e2e

#7639 fix(workers-playground): sends raw request method through the `X-CF-HTTP-Method` header
  .changeset/odd-news-invent.md
  packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Labels: preview:workers-playground

#7774 fix(create-cloudflare): Fix regression in C3's next template
  .changeset/chilly-kings-retire.md
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/templates-experimental/astro/templates/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/js/src/index.js
  packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/ts/src/index.ts
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/vitest.config.js
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/src/index.ts
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/vitest.config.mts
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates-experimental/hono/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates-experimental/nuxt/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates-experimental/qwik/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/analog/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/astro/templates/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/common/ts/src/index.ts
  packages/create-cloudflare/templates/common/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/hello-world-durable-object/js/src/index.js
  packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts
  packages/create-cloudflare/templates/hello-world/js/vitest.config.js
  packages/create-cloudflare/templates/hello-world/ts/src/index.ts
  packages/create-cloudflare/templates/hello-world/ts/vitest.config.mts
  packages/create-cloudflare/templates/hello-world/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/hono/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/next/README.md
  packages/create-cloudflare/templates/next/c3.ts
  packages/create-cloudflare/templates/nuxt/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/openapi/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/pre-existing/c3.ts
  packages/create-cloudflare/templates/queues/ts/src/index.ts
  packages/create-cloudflare/templates/queues/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/qwik/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/remix/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/scheduled/js/src/index.js
  packages/create-cloudflare/templates/scheduled/ts/src/index.ts
  packages/create-cloudflare/templates/scheduled/ts/worker-configuration.d.ts
Labels: e2e

#7766 Version Packages
  .changeset/chilly-kings-retire.md
  .changeset/cuddly-pets-smell.md
  .changeset/fifty-flies-visit.md
  .changeset/honest-spies-prove.md
  .changeset/lovely-years-wash.md
  .changeset/odd-news-invent.md
  .changeset/proud-forks-build.md
  .changeset/smart-lions-suffer.md
  .changeset/tough-walls-poke.md
  .changeset/unlucky-timers-sort.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-playground/CHANGELOG.md
  packages/workers-playground/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7791 Revert "fix(workers-playground): sends raw request method through the `X-CF-HTTP-Method` header"
  .changeset/heavy-gorillas-punch.md
  packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Labels: skip-pr-description-validation

#7797 Revert "chore(wrangler): use the unenv preset from `@cloudflare/unenv-preset`"
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#7798 chore: add changeset
  .changeset/fifty-dragons-provide.md
Labels: skip-pr-description-validation

#7792 Version Packages
  .changeset/fifty-dragons-provide.md
  .changeset/heavy-gorillas-punch.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-playground/CHANGELOG.md
  packages/workers-playground/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7801 Version Packages
  .changeset/unlucky-apes-fix.md
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
Labels: skip-pr-description-validation

#7803 Version Packages
  .changeset/cold-turtles-impress.md
  .changeset/little-pugs-change.md
  .changeset/old-panthers-brush.md
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7826 fix Cloudflare Vite plugin beta release script
  .github/workflows/prereleases.yml
Labels: skip-pr-description-validation, no-changeset-required

#7806 chore: update unenv to 2.0.0-rc.0
  .changeset/red-comics-sit.md
  packages/unenv-preset/package.json
  packages/unenv-preset/tests/worker/index.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/deploy.test.ts
  pnpm-lock.yaml
Labels: e2e

#7818 chore: refactor wrangler tail to use createCommand
  packages/wrangler/src/index.ts
  packages/wrangler/src/tail/index.ts
Labels: no-changeset-required

#7816 add support for assets bindings to `getPlatformProxy`
  .changeset/thick-dots-sit.md
  fixtures/get-platform-proxy/public/test.txt
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler.toml
  packages/wrangler/src/api/integrations/platform/index.ts
Labels: e2e

#7817 chore: refactor `wrangler types` to use createCommand
  packages/wrangler/src/index.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e, no-changeset-required

#7828 fix(wrangler): improve multi account error message in non-interactive mode
  .changeset/twenty-ears-rescue.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/pages/secret.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/user/user.ts
Labels: e2e

#7715 Support service bindings from Pages projects to workers in a single `workerd` instance
  .changeset/gentle-sloths-eat.md
  packages/wrangler/e2e/multiworker-dev.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#7831 Only retry API failures
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/parse.ts
  packages/wrangler/src/pipelines/index.ts
  packages/wrangler/src/utils/retry.ts
  packages/wrangler/src/versions/upload.ts
Labels: no-changeset-required

#7833 Relax the Wrangler peer dependency for the Vite plugin
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/playground/cloudflare-env/package.json
  packages/vite-plugin-cloudflare/playground/durable-objects/package.json
  packages/vite-plugin-cloudflare/playground/external-durable-objects/package.json
  packages/vite-plugin-cloudflare/playground/external-workflows/package.json
  packages/vite-plugin-cloudflare/playground/hot-channel/package.json
  packages/vite-plugin-cloudflare/playground/module-resolution/package.json
  packages/vite-plugin-cloudflare/playground/multi-worker/package.json
  packages/vite-plugin-cloudflare/playground/node-compat/package.json
  packages/vite-plugin-cloudflare/playground/react-spa/package.json
  packages/vite-plugin-cloudflare/playground/spa-with-api/package.json
  packages/vite-plugin-cloudflare/playground/static-mpa/package.json
  packages/vite-plugin-cloudflare/playground/virtual-modules/package.json
  packages/vite-plugin-cloudflare/playground/websockets/package.json
  packages/vite-plugin-cloudflare/playground/worker/package.json
  packages/vite-plugin-cloudflare/playground/workflows/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: no-changeset-required

#7832 Relax the messaging when Wrangler uses redirected configuration
  .changeset/green-mice-carry.md
  packages/wrangler/src/__tests__/config/findWranglerConfig.test.ts
  packages/wrangler/src/config/config-helpers.ts
Labels: e2e

#7838 Add JSDoc to cloudflare function
  packages/vite-plugin-cloudflare/src/index.ts
Labels: no-changeset-required, vite-plugin

#7837 Vite plugin README updates
  .prettierrc
  packages/vite-plugin-cloudflare/README.md
Labels: no-changeset-required, vite-plugin

#7839 Improve README quick start
  packages/vite-plugin-cloudflare/README.md
Labels: no-changeset-required, vite-plugin

#7827 fix(create-cloudflare): bump vitest-pool-workers version on the templates
  .changeset/cuddly-radios-rule.md
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
  packages/create-cloudflare/templates/hello-world/js/package.json
  packages/create-cloudflare/templates/hello-world/js/test/index.spec.js
  packages/create-cloudflare/templates/hello-world/ts/package.json
Labels: e2e

#7466 SQC-352 SQC-353 Create cert upload command for client side mtls certificate/CA chain certificates
  .changeset/hip-cameras-yawn.md
  packages/wrangler/e2e/cert.test.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/cert.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/api/index.ts
  packages/wrangler/src/api/mtls-certificate.ts
  packages/wrangler/src/cert/cert.ts
  packages/wrangler/src/core/teams.d.ts
  packages/wrangler/src/index.ts
  pnpm-lock.yaml
Labels: e2e

#7843 change `watch` scripts to `dev` in packages for consistency
  packages/cloudflare-workers-bindings-extension/package.json
  packages/create-cloudflare/package.json
  packages/vite-plugin-cloudflare/package.json
Labels: no-changeset-required

#7846 [vite-plugin-cloudflare] make sure that runner initialization is properly validated
  .changeset/smart-mice-appear.md
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/runner-worker/index.ts
Labels: vite-plugin

#7863 [vite-plugin-cloudflare]: fix watch script not working
  packages/vite-plugin-cloudflare/package.json
  pnpm-lock.yaml
Labels: no-changeset-required

#7866 Revert "add support for assets bindings to `getPlatformProxy`"
  fixtures/get-platform-proxy/public/test.txt
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler.toml
  packages/wrangler/src/api/integrations/platform/index.ts
Labels: skip-pr-description-validation

#7868 Revert "Hyperdrive dev remote fix"
  .changeset/nervous-jeans-obey.md
  .changeset/silver-pillows-listen.md
  .github/workflows/e2e.yml
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/turbo.json
Labels: e2e, skip-pr-description-validation

#7861 Version Packages
  .changeset/eighty-penguins-complain.md
  .changeset/hip-cameras-yawn.md
  .changeset/revert-proxy-assets.md
  .changeset/silver-pillows-listen.md
  .changeset/smart-mice-appear.md
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7424 Add support for Images binding
  .changeset/beige-chicken-sort.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/images/fetcher.ts
  packages/wrangler/src/images/local.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/utils/print-bindings.ts
  pnpm-lock.yaml
Labels: e2e

#7848 Deploy staging versions of asset-worker and router-worker on merges to main
  .github/workflows/workers-shared-deploy-staging.yml
  packages/workers-shared/asset-worker/wrangler.toml
  packages/workers-shared/package.json
  packages/workers-shared/router-worker/wrangler.toml
Labels: no-changeset-required

#7882 Revert "Add support for Images binding"
  .changeset/beige-chicken-sort.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/images/fetcher.ts
  packages/wrangler/src/images/local.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/utils/print-bindings.ts
  pnpm-lock.yaml
Labels: e2e, skip-pr-description-validation, no-changeset-required

#7892 fix: tiny copy changes to vscode extension
  packages/cloudflare-workers-bindings-extension/src/home.ts
Labels: no-changeset-required

#7884 feat: make provisioning non-interactive by default
  .changeset/clean-carrots-draw.md
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/src/__tests__/provision.test.ts
  packages/wrangler/src/deploy/index.ts
Labels: e2e

#7879 Revert "Revert "Hyperdrive dev remote fix""
  .changeset/nervous-jeans-obey.md
  .github/workflows/e2e.yml
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/turbo.json
Labels: e2e, skip-pr-description-validation

#7793 fix(playground-preview-worker,edge-preview-authenticated-proxy): ensure no body is passed when constructing a GET or HEAD request to the preview worker
  .changeset/clean-sheep-promise.md
  packages/edge-preview-authenticated-proxy/src/index.ts
  packages/edge-preview-authenticated-proxy/tests/index.test.ts
  packages/playground-preview-worker/src/index.ts
  packages/playground-preview-worker/tests/index.test.ts
Labels: e2e, caretaking

#7907 refactor(wrangler): runWranglerDev always log error
  fixtures/shared/src/run-wrangler-long-lived.ts
Labels: no-changeset-required

#7876 refactor(wrangler): refine the type of buildOptions
  packages/wrangler/src/deployment-bundle/bundle.ts
Labels: no-changeset-required

#7880 add `formatOnSave` option to vscode `settings.json`
  .vscode/settings.json
Labels: no-changeset-required

#7859 refactor(wrangler): clarify the --env options
  packages/wrangler/src/__tests__/ai.test.ts
  packages/wrangler/src/__tests__/cert.test.ts
  packages/wrangler/src/__tests__/cloudchamber/create.test.ts
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/__tests__/cloudchamber/delete.test.ts
  packages/wrangler/src/__tests__/cloudchamber/images.test.ts
  packages/wrangler/src/__tests__/cloudchamber/list.test.ts
  packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
  packages/wrangler/src/__tests__/d1/d1.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/docs.test.ts
  packages/wrangler/src/__tests__/hyperdrive.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/mtls-certificates.test.ts
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/__tests__/pubsub.test.ts
  packages/wrangler/src/__tests__/queues.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/__tests__/worker-namespace.test.ts
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/index.ts
Labels: no-changeset-required

#7860 refactor(wrangler): make JSON parsing independent of Node
  .changeset/thick-bikes-teach.md
  packages/wrangler/src/__tests__/parse.test.ts
  packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/config/config-helpers.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/config/patch-config.ts
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/parse.ts
  packages/wrangler/src/r2/cors.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e

#7913 refactor(wrangler): max bundle size is now 3MiB
  packages/wrangler/src/deployment-bundle/bundle-reporter.ts
Labels: e2e, no-changeset-required

#7916 Version Packages
  .changeset/clean-sheep-promise.md
  .changeset/late-gorillas-walk.md
  .changeset/neat-needles-brush.md
  .changeset/nervous-jeans-obey.md
  .changeset/old-bees-design.md
  .changeset/old-teachers-bow.md
  .changeset/olive-tigers-raise.md
  .changeset/popular-pigs-glow.md
  .changeset/slimy-baboons-care.md
  .changeset/thick-bikes-teach.md
  packages/edge-preview-authenticated-proxy/CHANGELOG.md
  packages/edge-preview-authenticated-proxy/package.json
  packages/playground-preview-worker/CHANGELOG.md
  packages/playground-preview-worker/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7788 Switch to `capnp-es`
  .changeset/neat-foxes-cheer.md
  .prettierignore
  package.json
  packages/miniflare/package.json
  packages/miniflare/scripts/build-capnp.mjs
  packages/miniflare/scripts/types.mjs
  packages/miniflare/src/http/websocket.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/runtime/config/generated.ts
  packages/miniflare/src/runtime/config/index.ts
  packages/miniflare/src/runtime/config/workerd.capnp
  packages/miniflare/src/runtime/config/workerd.capnp.d.ts
  packages/miniflare/src/runtime/config/workerd.capnp.js
  packages/miniflare/src/runtime/config/workerd.ts
  packages/miniflare/src/workers/core/devalue.ts
  packages/miniflare/src/workers/shared/data.ts
  packages/miniflare/test/http/fetch.spec.ts
  packages/miniflare/test/http/websocket.spec.ts
  packages/unenv-preset/src/runtime/node/module/index.ts
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/playground/cloudflare-env/package.json
  packages/vite-plugin-cloudflare/playground/durable-objects/package.json
  packages/vite-plugin-cloudflare/playground/external-durable-objects/package.json
  packages/vite-plugin-cloudflare/playground/external-workflows/package.json
  packages/vite-plugin-cloudflare/playground/hot-channel/package.json
  packages/vite-plugin-cloudflare/playground/module-resolution/package.json
  packages/vite-plugin-cloudflare/playground/multi-worker/package.json
  packages/vite-plugin-cloudflare/playground/node-compat/package.json
  packages/vite-plugin-cloudflare/playground/package.json
  packages/vite-plugin-cloudflare/playground/react-spa/package.json
  packages/vite-plugin-cloudflare/playground/spa-with-api/package.json
  packages/vite-plugin-cloudflare/playground/static-mpa/package.json
  packages/vite-plugin-cloudflare/playground/virtual-modules/package.json
  packages/vite-plugin-cloudflare/playground/websockets/package.json
  packages/vite-plugin-cloudflare/playground/worker/package.json
  packages/vite-plugin-cloudflare/playground/workflows/package.json
  packages/vitest-pool-workers/package.json
  packages/vitest-pool-workers/scripts/build-capnp.mjs
  packages/vitest-pool-workers/scripts/rtti/query.mjs
  packages/vitest-pool-workers/scripts/rtti/rtti.capnp
  packages/vitest-pool-workers/scripts/rtti/rtti.capnp.d.ts
  packages/vitest-pool-workers/scripts/rtti/rtti.capnp.js
  packages/vitest-pool-workers/scripts/rtti/rtti.js
  packages/vitest-pool-workers/src/shared/chunking-socket.ts
  packages/vitest-pool-workers/tsconfig.json
  packages/workers-shared/asset-worker/src/assets-manifest.ts
  packages/wrangler/src/deployment-bundle/find-additional-modules.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/versions/secrets/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: e2e

#7928 chore: do not build the world when publishing Wrangler and C3
  packages/create-cloudflare/package.json
  packages/wrangler/package.json
Labels: no-changeset-required

#7897 Provides support for run_worker_first option
  .changeset/cuddly-wombats-decide.md
  fixtures/asset-config/html-handling.test.ts
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  fixtures/workers-with-assets-run-worker-first/README.md
  fixtures/workers-with-assets-run-worker-first/package.json
  fixtures/workers-with-assets-run-worker-first/public/index.html
  fixtures/workers-with-assets-run-worker-first/src/index.ts
  fixtures/workers-with-assets-run-worker-first/tests/index.test.ts
  fixtures/workers-with-assets-run-worker-first/tests/tsconfig.json
  fixtures/workers-with-assets-run-worker-first/tsconfig.json
  fixtures/workers-with-assets-run-worker-first/wrangler.toml
  fixtures/workers-with-assets-serve-directly/README.md
  fixtures/workers-with-assets/wrangler.toml
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
  packages/workers-shared/utils/types.ts
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  pnpm-lock.yaml
Labels: e2e

#7932 fix(wrangler): handling of `process.env.NODE_ENV` in bundling mode
  .changeset/lucky-jeans-relax.md
  packages/wrangler/src/deployment-bundle/bundle.ts
Labels: e2e

#7864 improve and test vite-plugin-cloudflare `.dev.vars` files support
  .changeset/orange-camels-hunt_vite-plugin.md
  .changeset/orange-camels-hunt_wrangler.md
  packages/vite-plugin-cloudflare/README.md
  packages/vite-plugin-cloudflare/playground/dev-vars/.dev.vars
  packages/vite-plugin-cloudflare/playground/dev-vars/.dev.vars.staging
  packages/vite-plugin-cloudflare/playground/dev-vars/.env.with-specified-env
  packages/vite-plugin-cloudflare/playground/dev-vars/.gitignore
  packages/vite-plugin-cloudflare/playground/dev-vars/__tests__/dev-vars-loading.spec.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/__tests__/with-specified-env/dev-vars-loading.spec.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/package.json
  packages/vite-plugin-cloudflare/playground/dev-vars/src/index.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/tsconfig.json
  packages/vite-plugin-cloudflare/playground/dev-vars/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/dev-vars/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/dev-vars/turbo.json
  packages/vite-plugin-cloudflare/playground/dev-vars/vite.config.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/vite.config.with-specified-env.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/worker-configuration.d.ts
  packages/vite-plugin-cloudflare/playground/dev-vars/wrangler.toml
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/config/index.ts
  pnpm-lock.yaml
Labels: e2e, vite-plugin

#7930 chore: don't fail the PR description check for draft PRs
  .github/workflows/validate-pr-description.yml
  tools/deployments/validate-pr-description.ts
Labels: no-changeset-required

#7937 Collapse CI jobs into one
  .github/workflows/test-and-check.yml
Labels: no-changeset-required

#7947 [wrangler] fix: avoid `getPlatformProxy` logging twice that it is using vars defined in `.dev.vars` files
  .changeset/gentle-foxes-float.md
  packages/wrangler/src/api/integrations/platform/index.ts
Labels: e2e

#7963 CI: compute the name for artifacts correctly
  .github/actions/run-c3-e2e/action.yml
Labels: skip-pr-description-validation, no-changeset-required

#7946 Skip C3 E2E if possible
  .github/workflows/c3-e2e-experimental.yml
  .github/workflows/c3-e2e.yml
Labels: no-changeset-required

#7889 feat: add provisioning to versions upload and reprovision on bucket jurisdiction changes
  .changeset/neat-sloths-reply.md
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/src/__tests__/provision.test.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/d1/info.ts
  packages/wrangler/src/d1/insights.ts
  packages/wrangler/src/d1/list.ts
  packages/wrangler/src/d1/migrations/apply.ts
  packages/wrangler/src/d1/timeTravel/utils.ts
  packages/wrangler/src/d1/utils.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#7965 test: quieten the logs on Wrangler retry helper tests
  packages/wrangler/src/__tests__/utils/retry.test.ts
Labels: no-changeset-required

#7945 Add support for Images binding
  .changeset/beige-chicken-sort.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/images/fetcher.ts
  packages/wrangler/src/images/local.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/utils/print-bindings.ts
  pnpm-lock.yaml
Labels: e2e

#7972 Bumps create-hono now that upstream has updated to use wrangler.json
  .changeset/fair-waves-punch.md
  packages/create-cloudflare/src/frameworks/package.json
  pnpm-lock.yaml
Labels: e2e

#7967 Revert "fix(wrangler): handling of `process.env.NODE_ENV` in bundling mode"
  .changeset/lucky-jeans-relax.md
  packages/wrangler/src/deployment-bundle/bundle.ts
Labels: skip-pr-description-validation, no-changeset-required

#7975 chore: fix lockfile
  pnpm-lock.yaml
Labels: no-changeset-required

#7933 Version Packages
  .changeset/beige-chicken-sort.md
  .changeset/cuddly-wombats-decide.md
  .changeset/cyan-suits-move.md
  .changeset/fair-waves-punch.md
  .changeset/gentle-foxes-float.md
  .changeset/neat-foxes-cheer.md
  .changeset/neat-sloths-reply.md
  .changeset/orange-camels-hunt_vite-plugin.md
  .changeset/orange-camels-hunt_wrangler.md
  .changeset/poor-hornets-exercise.md
  .changeset/poor-rabbits-compete.md
  .changeset/silver-wombats-bow.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7925 Add workflow for uploading asset-worker and router-worker
  .github/workflows/workers-shared-deploy-production.yml
Labels: no-changeset-required

#7936 fix(workers-playground): send raw request method through the `X-CF-HTTP-Method` header
  .changeset/odd-cougars-matter.md
  packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Labels: preview:workers-playground

#7979 Version Packages
  .changeset/dependabot-update-7971.md
  .changeset/long-bulldogs-clean.md
  .changeset/odd-cougars-matter.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-playground/CHANGELOG.md
  packages/workers-playground/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7991 Version Packages
  .changeset/gorgeous-geckos-call.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation
