Repository cloudflare/workers-sdk, pull requests merged in 2025-05, with the labels that each got.

#9108 Support running Vite in middleware mode
  .changeset/social-baboons-jog.md
  packages/vite-plugin-cloudflare/playground/middleware-mode/__tests__/middleware-mode.spec.ts
  packages/vite-plugin-cloudflare/playground/middleware-mode/__tests__/serve.ts
  packages/vite-plugin-cloudflare/playground/middleware-mode/package.json
  packages/vite-plugin-cloudflare/playground/middleware-mode/server.js
  packages/vite-plugin-cloudflare/playground/middleware-mode/src/index.ts
  packages/vite-plugin-cloudflare/playground/middleware-mode/tsconfig.json
  packages/vite-plugin-cloudflare/playground/middleware-mode/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/middleware-mode/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/middleware-mode/wrangler.jsonc
  packages/vite-plugin-cloudflare/playground/vitest-setup.ts
  packages/vite-plugin-cloudflare/src/index.ts
  pnpm-lock.yaml
Labels: vite-plugin

#9113 Add `x-mixed-mode` flag
  .changeset/violet-planets-march.md
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/experimental-flags.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/src/yargs-types.ts
Labels: skip-v3-pr

#9100 Version Packages
  .changeset/eager-bobcats-agree.md
  .changeset/red-planes-wash.md
  .changeset/social-baboons-jog.md
  .changeset/soft-wasps-beg.md
  .changeset/tough-bats-live.md
  .changeset/violet-planets-march.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9117 V3 Backport [#9089]: parse pem file with regex
  .changeset/soft-wasps-beg.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/test/plugins/core/index.spec.ts
Labels: skip-pr-description-validation

#9038 v3 Maintenance Release
  .changeset/eager-bobcats-agree.md
  .changeset/plenty-beans-enjoy.md
  .changeset/seven-humans-scream.md
  .changeset/soft-wasps-beg.md
  .changeset/stupid-paws-slide.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#7423 Clarify custom build logging
  .changeset/thirty-bears-appear.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deployment-bundle/run-custom-build.ts
Labels: e2e

#9112 Bump to Node.js 20
  .changeset/young-trainers-do.md
  .github/actions/install-dependencies/action.yml
  .github/workflows/deploy-pages-previews.yml
  .github/workflows/e2e.yml
  .github/workflows/test-and-check.yml
  .github/workflows/test-old-node-error.yml
  fixtures/import-npm/package.json
  packages/miniflare/src/plugins/core/errors/callsite.ts
  packages/wrangler/bin/wrangler.js
  packages/wrangler/src/__tests__/ai.local.test.ts
  packages/wrangler/src/__tests__/test-old-node-version.js
  packages/wrangler/src/sourcemap.ts
  packages/wrangler/src/wrangler-banner.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: e2e, skip-v3-pr

#9120 Add `experimental_startMixedModeSession` no-op utility
  .changeset/spicy-crews-give.md
  fixtures/mixed-mode-node-test/package.json
  fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
  fixtures/mixed-mode-node-test/tsconfig.json
  packages/wrangler/src/api/index.ts
  packages/wrangler/src/api/mixedMode/index.ts
  packages/wrangler/src/cli.ts
  packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
  packages/wrangler/templates/mixedMode/proxyServerWorker/wrangler.jsonc
  pnpm-lock.yaml
Labels: skip-v3-pr

#9118 fix: remove outdated js-doc comment for `unstable_startDevWorker`'s `entrypoint`
  .changeset/deep-symbols-fix.md
  packages/wrangler/src/api/startDevWorker/types.ts
Labels: skip-v3-pr

#9145 test: fix up old node.js tests
  .github/workflows/test-and-check.yml
  .github/workflows/test-old-node-error.yml
  packages/wrangler/src/__tests__/test-old-node-version.js
Labels: no-changeset-required, skip-v3-pr

#9123 Version Packages
  .changeset/deep-symbols-fix.md
  .changeset/spicy-crews-give.md
  .changeset/thirty-bears-appear.md
  .changeset/young-trainers-do.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9125 Remove unused `capnp-ts` patch
  package.json
  patches/capnp-ts@0.7.0.patch
  pnpm-lock.yaml
Labels: skip-pr-description-validation, skip-v3-pr

#9159 bump esbuild version to fix regression in 0.25.0
  .changeset/petite-bags-try.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: skip-v3-pr

#9163 V3 backport (#9162) Do not report "d1 execute" command file missing error to Sentry
  .changeset/social-cups-roll.md
  packages/wrangler/src/__tests__/d1/execute.test.ts
  packages/wrangler/src/d1/execute.ts
Labels: skip-v3-pr

#9150 Version Packages
  .changeset/dependabot-update-9092.md
  .changeset/dependabot-update-9160.md
  .changeset/every-results-behave.md
  .changeset/petite-bags-try.md
  .changeset/sad-taxis-kick.md
  .changeset/social-cups-roll.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9128 V3 Backport [#9118]: fix: remove outdated js-doc comment for unstable_startDevWorker's entrypoint
  .changeset/deep-symbols-fix.md
  packages/wrangler/src/api/startDevWorker/types.ts
Labels: skip-pr-description-validation, skip-v3-pr

#9124 make that `unstable_startWorker` can correctly throw configuration errors
  .changeset/metal-clubs-vanish.md
  fixtures/start-worker-node-test/package.json
  fixtures/start-worker-node-test/src/config-errors.test.js
  fixtures/start-worker-node-test/tsconfig.json
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#9167 Version Packages
  .changeset/c3-frameworks-update-9136.md
  .changeset/c3-frameworks-update-9137.md
  .changeset/c3-frameworks-update-9138.md
  .changeset/metal-clubs-vanish.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9122 Wrangler delete workflow
  .changeset/wise-rules-roll.md
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/workflows/commands/delete.ts
Labels: e2e

#9152 Support HTTPS and HTTP/2
  .changeset/cold-emus-jog.md
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/playground/spa-with-api/__tests__/https/spa-with-api.spec.ts
  packages/vite-plugin-cloudflare/playground/spa-with-api/package.json
  packages/vite-plugin-cloudflare/playground/spa-with-api/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/spa-with-api/vite.config.https.ts
  packages/vite-plugin-cloudflare/playground/streaming/__tests__/base-tests.ts
  packages/vite-plugin-cloudflare/playground/streaming/__tests__/https/streaming.spec.ts
  packages/vite-plugin-cloudflare/playground/streaming/__tests__/streaming.spec.ts
  packages/vite-plugin-cloudflare/playground/streaming/package.json
  packages/vite-plugin-cloudflare/playground/streaming/src/index.ts
  packages/vite-plugin-cloudflare/playground/streaming/tsconfig.json
  packages/vite-plugin-cloudflare/playground/streaming/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/streaming/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/streaming/turbo.json
  packages/vite-plugin-cloudflare/playground/streaming/vite.config.https.ts
  packages/vite-plugin-cloudflare/playground/streaming/vite.config.ts
  packages/vite-plugin-cloudflare/playground/streaming/wrangler.jsonc
  packages/vite-plugin-cloudflare/playground/vitest-setup.ts
  packages/vite-plugin-cloudflare/src/index.ts
  pnpm-lock.yaml
Labels: e2e, vite-plugin, c3-e2e

#9176 Fix workers-types version
  packages/vite-plugin-cloudflare/playground/streaming/package.json
  pnpm-lock.yaml
Labels: no-changeset-required

#9161 Fix d1 info command showing read_replication: [object Object]
  .changeset/four-cherries-deny.md
  packages/wrangler/src/__tests__/d1/info.test.ts
  packages/wrangler/src/d1/info.ts
  packages/wrangler/src/d1/types.ts
Labels: e2e

#9178 Support merge queues
  .github/workflows/test-and-check.yml
Labels: skip-pr-description-validation

#9168 add `mixedModeConnectionString` to the various binding configs
  .changeset/chatty-years-speak.md
  .changeset/thin-years-jump.md
  packages/miniflare/src/plugins/core/services.ts
  packages/miniflare/src/plugins/d1/index.ts
  packages/miniflare/src/plugins/do/index.ts
  packages/miniflare/src/plugins/kv/index.ts
  packages/miniflare/src/plugins/queues/index.ts
  packages/miniflare/src/plugins/r2/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/src/plugins/workflows/index.ts
  packages/wrangler/src/api/mixedMode/index.ts
Labels: e2e, skip-v3-pr

#8794 wrangler types - Import correct types for bound services
  .changeset/khaki-plums-clap.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/type-generation/helpers.ts
  packages/wrangler/src/type-generation/index.ts
Labels: enhancement, post-devweek

#9166 V3 Backport [#9161]: Fix d1 info command showing read_replication: [object Object]
  .changeset/yellow-rabbits-tap.md
  packages/wrangler/src/__tests__/d1/info.test.ts
  packages/wrangler/src/d1/info.ts
  packages/wrangler/src/d1/types.ts
Labels: e2e

#9149 Implement Mixed Mode proxy server & client
  .changeset/red-trains-drive.md
  .github/workflows/test-and-check.yml
  fixtures/mixed-mode-node-test/package.json
  fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
  fixtures/mixed-mode-node-test/turbo.json
  packages/miniflare/src/plugins/ai/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/workers/shared/mixed-mode-client.worker.ts
  packages/wrangler/src/api/mixedMode/index.ts
  packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#9185 test: hide stdout.write in tests
  packages/wrangler/src/__tests__/helpers/mock-process.ts
Labels: no-changeset-required

#8968 use well known secret + store in e2e tests
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
Labels: e2e, no-changeset-required

#9188 test: improve some tests to be more resilient to locale changes
  packages/wrangler/src/__tests__/ai.test.ts
  packages/wrangler/src/__tests__/cli-hotkeys.test.ts
  packages/wrangler/src/__tests__/cloudchamber/images.test.ts
  packages/wrangler/src/__tests__/d1/info.test.ts
  packages/wrangler/src/__tests__/d1/list.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/normalize.ts
  packages/wrangler/src/__tests__/hyperdrive.test.ts
  packages/wrangler/src/__tests__/pages/deployment-list.test.ts
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/__tests__/queues.test.ts
  packages/wrangler/src/__tests__/secrets-store.test.ts
  packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
  packages/wrangler/src/__tests__/whoami.test.ts
  packages/wrangler/src/__tests__/workflows.test.ts
Labels: no-changeset-required, every-os

#9191 test: make asset deploy tests more resilient
  packages/wrangler/src/__tests__/deploy.test.ts
Labels: no-changeset-required

#9192 Fix mixed mode fixture test on Windows
  .github/workflows/test-and-check.yml
  fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr, every-os

#9165 fix(r2): validate bucket names
  .changeset/lemon-pants-jam.md
  fixtures/pages-functions-app/functions/r2/create.ts
  fixtures/pages-functions-app/functions/r2/get.ts
  fixtures/pages-functions-app/package.json
  fixtures/pages-functions-app/tests/index.test.ts
  fixtures/pages-workerjs-directory/package.json
  fixtures/pages-workerjs-directory/public/_worker.js/index.js
  fixtures/pages-workerjs-directory/tests/index.test.ts
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/config/configuration.pages.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/helpers/generate-wrangler-config.ts
  packages/wrangler/src/__tests__/r2.local.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pipelines/cli/create.ts
  packages/wrangler/src/r2/bucket.ts
  packages/wrangler/src/r2/helpers.ts
Labels: e2e, c3-e2e, skip-v3-pr

#9190 Bump next template to`@opennextjs/cloudflare@^1.0.2`
  .changeset/many-birds-enjoy.md
  packages/create-cloudflare/templates/next/workers/c3.ts
Labels: c3-e2e

#9172 [v3] fix(r2): validate bucket names
  .changeset/lemon-pants-jam.md
  fixtures/pages-functions-app/functions/r2/create.ts
  fixtures/pages-functions-app/functions/r2/get.ts
  fixtures/pages-functions-app/package.json
  fixtures/pages-functions-app/tests/index.test.ts
  fixtures/pages-workerjs-directory/package.json
  fixtures/pages-workerjs-directory/public/_worker.js/index.js
  fixtures/pages-workerjs-directory/tests/index.test.ts
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/config/configuration.pages.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/helpers/generate-wrangler-config.ts
  packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
  packages/wrangler/src/__tests__/r2.local.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/pipelines/cli/create.ts
  packages/wrangler/src/r2/bucket.ts
  packages/wrangler/src/r2/helpers.ts
Labels: e2e, c3-e2e

#9177 Use createHeaders util in place of custom function
  packages/vite-plugin-cloudflare/src/utils.ts
  packages/vite-plugin-cloudflare/src/websockets.ts
Labels: no-changeset-required, vite-plugin

#9209 [c3] Do not pin create-next-app
  .changeset/thirty-ghosts-argue.md
  packages/create-cloudflare/templates/next/workers/c3.ts
Labels: c3-e2e

#9213 Skip mixed mode tests when tokens not provided
  fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
Labels: skip-pr-description-validation

#7914 Strip CF-Connecting-IP header from all outbound requests
  .changeset/cyan-years-relate.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/workers/core/strip-cf-connecting-ip.worker.ts
  packages/miniflare/test/index.spec.ts
  packages/miniflare/turbo.json
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
Labels: e2e, caretaking, skip-v3-pr

#8681 V3 Backport (fix(wrangler): strip CF-Connecting-IP header from all outbound requests #7914)
  .changeset/cyan-years-relate.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/workers/core/strip-cf-connecting-ip.worker.ts
  packages/miniflare/test/index.spec.ts
  packages/miniflare/turbo.json
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
Labels: skip-pr-description-validation, skip-v3-pr

#9211 V3 backport (#9198): fix: start transferred MessagePort in fetch-sync worker
  .changeset/stupid-files-jog.md
  packages/miniflare/src/plugins/core/proxy/fetch-sync.ts
Labels: skip-pr-description-validation, skip-v3-pr

#9183 add `remote` option to initial bindings
  .changeset/orange-ads-judge.md
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e, skip-v3-pr

#9175 Version Packages
  .changeset/c3-frameworks-update-9201.md
  .changeset/c3-frameworks-update-9202.md
  .changeset/c3-frameworks-update-9203.md
  .changeset/c3-frameworks-update-9204.md
  .changeset/c3-frameworks-update-9205.md
  .changeset/chatty-years-speak.md
  .changeset/chubby-gifts-sip.md
  .changeset/cold-emus-jog.md
  .changeset/cyan-years-relate.md
  .changeset/dependabot-update-9174.md
  .changeset/four-cherries-deny.md
  .changeset/happy-avocados-peel.md
  .changeset/khaki-plums-clap.md
  .changeset/lemon-pants-jam.md
  .changeset/many-birds-enjoy.md
  .changeset/old-trainers-camp.md
  .changeset/orange-ads-judge.md
  .changeset/red-trains-drive.md
  .changeset/slimy-eels-wink.md
  .changeset/soft-bears-pump.md
  .changeset/stupid-files-jog.md
  .changeset/thin-years-jump.md
  .changeset/thirty-ghosts-argue.md
  .changeset/wise-rules-roll.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9219 bump unenv to 2.0.0-rc.17
  .changeset/new-clocks-obey.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/unenv-preset/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#9220 Sync unenv-preset with workerd
  .changeset/five-peaches-cough.md
  packages/unenv-preset/package.json
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/async_hooks.ts
  packages/unenv-preset/src/runtime/node/tls.ts
  packages/unenv-preset/tests/worker/index.ts
  pnpm-lock.yaml
Labels: nodejs compat, e2e, agents

#9228 [vite] Bump unenv to 2.0.0-rc.17
  .changeset/nine-ends-train.md
  packages/vite-plugin-cloudflare/package.json
  pnpm-lock.yaml
Labels: e2e

#9241 test: fail e2e test if peer dependencies are broken
  packages/vite-plugin-cloudflare/e2e/helpers.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9247 fix c3 tests
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
Labels: skip-pr-description-validation, no-changeset-required, c3-e2e, skip-v3-pr

#9248 fix unenv version mismatch
  .changeset/four-books-heal.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/vite-plugin-cloudflare/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: wrangler, nodejs compat, e2e, vite-plugin, skip-v3-pr

#9226 Version Packages
  .changeset/five-peaches-cough.md
  .changeset/four-books-heal.md
  .changeset/funny-trees-drop.md
  .changeset/new-clocks-obey.md
  .changeset/nine-ends-train.md
  .changeset/public-cameras-thank.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9256 Move the AE simulator from JSRPC to a Wrapped binding
  .changeset/tricky-wolves-cry.md
  packages/miniflare/src/plugins/analytics-engine/index.ts
  packages/miniflare/src/workers/analytics-engine/analytics-engine.worker.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e, skip-v3-pr

#9261 Version Packages
  .changeset/great-berries-grow.md
  .changeset/tricky-wolves-cry.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9231 allow wrangler dev to connect to remote mixed-mode bindings
  .changeset/hip-grapes-lay.md
  packages/wrangler/e2e/dev-mixed-mode.test.ts
  packages/wrangler/src/api/mixedMode/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
Labels: e2e, skip-v3-pr

#9245 Support Mixed Mode Dispatch Namespaces
  .changeset/tough-seals-whisper.md
  fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
  packages/miniflare/src/plugins/dispatch-namespace/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/workers/dispatch-namespace/dispatch-namespace.worker.ts
  packages/miniflare/src/workers/shared/mixed-mode-client.worker.ts
  packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
Labels: skip-v3-pr

#8957 V3 Backport [#7423]: Clarify custom build logging
  .changeset/thirty-bears-appear.md
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deployment-bundle/run-custom-build.ts
Labels: e2e, skip-pr-description-validation, skip-v3-pr

#9275 Remove the unenv-preset package from v3
  packages/unenv-preset/.eslintrc.js
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/LICENSE-APACHE
  packages/unenv-preset/LICENSE-MIT
  packages/unenv-preset/README.md
  packages/unenv-preset/build.config.ts
  packages/unenv-preset/package.json
  packages/unenv-preset/src/index.ts
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/async_hooks.ts
  packages/unenv-preset/src/runtime/node/console.ts
  packages/unenv-preset/src/runtime/node/crypto.ts
  packages/unenv-preset/src/runtime/node/module.ts
  packages/unenv-preset/src/runtime/node/process.ts
  packages/unenv-preset/src/runtime/node/util.ts
  packages/unenv-preset/src/runtime/polyfill/package.json
  packages/unenv-preset/src/runtime/polyfill/performance.ts
  packages/unenv-preset/tests/index.test.ts
  packages/unenv-preset/tests/worker/index.ts
  packages/unenv-preset/tests/worker/wrangler.json
  packages/unenv-preset/tsconfig.json
  packages/unenv-preset/turbo.json
  tools/deployments/__tests__/validate-changesets.test.ts
Labels: no-changeset-required

#9250 V3 Backport [#9246]: fix: strips CF-Connecting-IP header within Wrangler
  .changeset/public-cameras-thank.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/test/index.spec.ts
  packages/wrangler/src/__tests__/api/startDevWorker/startWorker.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/templates/strip-cf-connecting-ip-header.js
Labels: skip-pr-description-validation, skip-v3-pr

#9282 fix the prerelases workflow
  .github/workflows/prereleases.yml
Labels: no-changeset-required

#9283 chore: backport changes to v3 with "v3-backport" branch prefix and label
  tools/deployments/open-v3-pr.ts
Labels: no-changeset-required

#9284 chore: accept backport PR with v3-backport branch prefix
  tools/deployments/__tests__/check-v3-backport-status.test.ts
  tools/deployments/check-v3-backport-status.ts
Labels: no-changeset-required

#9259 V3 Backport [#9257]: Revert R2 bucket validation for commands
  .changeset/great-berries-grow.md
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e, skip-pr-description-validation, skip-v3-pr

#9289 fix wrangler mixed-mode windows e2e test failure
  packages/wrangler/e2e/dev-mixed-mode.test.ts
Labels: e2e, no-changeset-required, skip-v3-pr, every-os

#9287 run Wrangler e2e ci twice to reduce flakes
  tools/e2e/runIndividualE2EFiles.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required, skip-v3-pr, every-os

#9260 docs: add update frequency table to workspace file
  pnpm-workspace.yaml
Labels: no-changeset-required, skip-v3-pr

#9266 fix: setting triggers.crons:[] in Wrangler config should delete deployed cron schedules
  .changeset/shaky-planets-feel.md
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/__tests__/vitest.setup.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/triggers/deploy.ts
Labels: e2e, every-os

#9288 allow --name and --env args on wrangler deploy
  .changeset/six-rockets-show.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
  packages/wrangler/src/__tests__/helpers/mock-workers-subdomain.ts
  packages/wrangler/src/utils/getScriptName.ts
Labels: e2e

#9221 bump `@cloudflare/unenv-preset`
  .changeset/olive-candies-nail.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/unenv-preset/tests/worker/index.ts
  packages/vite-plugin-cloudflare/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: wrangler, nodejs compat, e2e, skip-v3-pr, every-os

#9267 V3 Backport [#9266]: fix: setting triggers.crons:[] in Wrangler config should delete deployed cron schedules
  .changeset/shaky-planets-feel.md
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/__tests__/vitest.setup.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/triggers/deploy.ts
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#9299 fix typo in #9288 changeset
  .changeset/six-rockets-show.md
Labels: skip-pr-description-validation, skip-v3-pr

#9269 Wire up mixed-mode remote bindings for multi-worker `wrangler dev`
  .changeset/dull-areas-invent.md
  packages/miniflare/src/plugins/core/index.ts
  packages/wrangler/e2e/dev-mixed-mode.test.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
Labels: e2e, skip-v3-pr

#9277 Support Mixed Mode for more binding types
  .changeset/real-games-add.md
  .github/workflows/e2e.yml
  .gitignore
  fixtures/mixed-mode-node-test/package.json
  fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
  fixtures/mixed-mode-node-test/tsconfig.json
  fixtures/mixed-mode-node-test/turbo.json
  packages/miniflare/package.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/d1/index.ts
  packages/miniflare/src/plugins/images/fetcher.ts
  packages/miniflare/src/plugins/images/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/plugins/kv/index.ts
  packages/miniflare/src/plugins/r2/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/src/plugins/vectorize/index.ts
  packages/miniflare/src/workers/core/constants.ts
  packages/wrangler/.eslintrc.js
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/helpers/wrangler.ts
  packages/wrangler/e2e/miniflare-mixed-mode-resources.test.ts
  packages/wrangler/e2e/seed-files/mixed-mode-workers/ai.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/browser.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/d1.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/dispatch-namespace.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/images.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/kv.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/r2.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/service-binding.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/vectorize.js
  packages/wrangler/src/api/mixedMode/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/remote.ts
  packages/wrangler/turbo.json
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#9303 test: simplify docs test
  packages/wrangler/src/__tests__/docs.test.ts
Labels: skip-pr-description-validation, skip-v3-pr

#9262 V3 Backport [#9234]: add no-op to getPlatformProxy to fix types mismatch
  .changeset/clear-beans-leave.md
  fixtures/get-platform-proxy/tests/get-platform-proxy.ctx.test.ts
  packages/wrangler/src/api/integrations/platform/executionContext.ts
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#9151 containers: allow users to specify the kind of container rollout they want
  .changeset/grumpy-baboons-post.md
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-v3-pr

#9268 wrangler containers: Delete should have better error handling
  .changeset/curvy-hairs-attend.md
  packages/wrangler/src/__tests__/containers/delete.test.ts
  packages/wrangler/src/containers/containers.ts
Labels: skip-v3-pr

#9306 chore: run ci for external forks by commit sha
  .github/workflows/run-ci-for-external-forks.yml
Labels: skip-pr-description-validation

#9326 Remove product drop down
  .github/ISSUE_TEMPLATE/bug-template.yaml
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9164 v3 Maintenance Release
  .changeset/clear-beans-leave.md
  .changeset/cyan-years-relate.md
  .changeset/deep-symbols-fix.md
  .changeset/great-berries-grow.md
  .changeset/lemon-pants-jam.md
  .changeset/public-cameras-thank.md
  .changeset/shaky-planets-feel.md
  .changeset/social-cups-roll.md
  .changeset/stupid-files-jog.md
  .changeset/thirty-bears-appear.md
  .changeset/yellow-rabbits-tap.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e, c3-e2e

#9325 feat(wrangler): uses local images binding from miniflare if `experimentalImagesLocalMode` is enabled
  .changeset/tall-beers-burn.md
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/images/fetcher.ts
  packages/wrangler/src/images/local.ts
  pnpm-lock.yaml
Labels: e2e

#9331 fix the Vitest integration to support Workers where Node.js compatibility is only v1 in production
  .changeset/shy-beans-warn.md
  fixtures/vitest-pool-workers-examples/basics-integration-auxiliary/vitest.config.ts
  packages/vitest-pool-workers/src/pool/index.ts
Labels: skip-v3-pr

#9332 c3: add extra information about asset serving to hello-world templates
  .changeset/violet-hats-guess.md
  packages/create-cloudflare/templates/hello-world-assets-only/templates/public/index.html
  packages/create-cloudflare/templates/hello-world-assets-only/templates/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/public/index.html
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/public/index.html
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/public/index.html
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-with-assets/js/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/js/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-with-assets/py/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/py/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-with-assets/ts/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/ts/wrangler.jsonc
Labels: c3-e2e, skip-v3-pr

#8973 Show latest instance by default
  .changeset/yummy-dolls-rescue.md
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/workflows/commands/instances/describe.ts
Labels: awaiting reporter response, internal, e2e, caretaking

#9106 fix(miniflare): decouple KV plugin from Secrets Store plugin to avoid service name conflicts
  .changeset/silver-bats-brush.md
  packages/miniflare/src/plugins/kv/index.ts
  packages/miniflare/src/plugins/secret-store/index.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
Labels: e2e, every-os

#9335 Redesign `wrangler dev`
  .changeset/kind-dots-argue.md
  fixtures/interactive-dev-tests/tests/index.test.ts
  packages/miniflare/src/index.ts
  packages/miniflare/src/shared/log.ts
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/dev-mixed-mode.test.ts
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/cli-hotkeys.test.ts
  packages/wrangler/src/__tests__/config/configuration.pages.test.ts
  packages/wrangler/src/__tests__/d1/info.test.ts
  packages/wrangler/src/__tests__/d1/list.test.ts
  packages/wrangler/src/__tests__/d1/timeTravel.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
  packages/wrangler/src/__tests__/provision.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/tail.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/cli-hotkeys.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/dev/hotkeys.ts
  packages/wrangler/src/utils/print-bindings.ts
  packages/wrangler/src/wrangler-banner.ts
Labels: e2e, skip-v3-pr

#9348 Fix E2E snapshots on Windows
  packages/wrangler/e2e/dev-mixed-mode.test.ts
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/pages-dev.test.ts
Labels: e2e, skip-pr-description-validation, every-os

#9351 Try to address e2e Windows flakiness
  packages/wrangler/e2e/pages-dev.test.ts
Labels: e2e, no-changeset-required, skip-v3-pr, every-os

#9330 feat: introduce defaultPersistRoot option
  .changeset/blue-streets-thank.md
  .changeset/twenty-cats-clap.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/cache/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/d1/index.ts
  packages/miniflare/src/plugins/do/index.ts
  packages/miniflare/src/plugins/kv/index.ts
  packages/miniflare/src/plugins/r2/index.ts
  packages/miniflare/src/plugins/secret-store/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/src/plugins/workflows/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/kv/helpers.ts
  packages/wrangler/src/r2/helpers.ts
  packages/wrangler/src/secrets-store/commands.ts
Labels: e2e

#9373 chore: update changeset
  .changeset/tall-beers-burn.md
Labels: no-changeset-required, skip-v3-pr

#9376 Support Node.js style custom handlers for service bindings and outbound services
  .changeset/yummy-pillows-send.md
  packages/miniflare/README.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/constants.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/core/services.ts
  packages/miniflare/src/plugins/images/index.ts
  packages/miniflare/src/workers/core/constants.ts
  packages/miniflare/test/index.spec.ts
Labels: e2e

#9388 Remove ORIGINAL_URL header from custom Node service
  packages/miniflare/src/plugins/core/index.ts
Labels: miniflare, no-changeset-required

#9387 Prevent leaking Miniflare server logs
  .changeset/dull-plants-act.md
  .changeset/hot-tips-do.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/shared/log.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
Labels: vite-plugin

#9392 Miniflare: reduce email test flakes
  packages/miniflare/package.json
  packages/miniflare/test/plugins/email/index.spec.ts
  packages/miniflare/test/test-shared/asserts.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9347 Improve wrapped bindings UI
  .changeset/small-toes-give.md
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e, skip-v3-pr

#9398 Fix Vite plugin e2e windows failures
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/dynamic.test.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/vite-plugin-cloudflare/e2e/invalid-worker-env-configs.test.ts
  packages/vite-plugin-cloudflare/e2e/mixed-mode.test.ts
  packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
Labels: e2e, no-changeset-required, every-os

#9400 Move minimal mode to session config
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/dev/remote.ts
Labels: e2e, no-changeset-required, skip-v3-pr

#9389 improve wrangler dev mixed mode tests
  packages/wrangler/e2e/dev-mixed-mode.test.ts
  packages/wrangler/e2e/seed-files/mixed-mode-workers/local-and-remote-service-bindings.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/local-service-binding-and-remote-ai.js
  packages/wrangler/e2e/seed-files/mixed-mode-workers/simple-service-binding.js
  packages/wrangler/e2e/wrangler-mixed-mode-resources.test.ts
Labels: e2e, no-changeset-required, every-os

#9313 feat(miniflare): add dev registry support
  .changeset/wise-rules-march.md
  packages/miniflare/package.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/do/index.ts
  packages/miniflare/src/shared/dev-registry.ts
  packages/miniflare/src/shared/external-service.ts
  packages/miniflare/test/dev-registry.spec.ts
  packages/miniflare/test/test-shared/asserts.ts
  pnpm-lock.yaml
Labels: e2e, every-os

#9390 Support additional mixed mode resources in Wrangler
  .changeset/five-ladybugs-sell.md
  .changeset/huge-bats-itch.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/analytics-engine/index.ts
  packages/miniflare/src/plugins/browser-rendering/index.ts
  packages/miniflare/src/plugins/dispatch-namespace/index.ts
  packages/miniflare/src/plugins/email/index.ts
  packages/miniflare/src/plugins/ratelimit/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/src/plugins/vectorize/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/wrangler/e2e/dev-mixed-mode.test.ts
  packages/wrangler/e2e/wrangler-mixed-mode-resources.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e, skip-v3-pr

#9407 chore: refactor the `workers-shared` package and Wrangler builds
  fixtures/import-npm/package-lock.json
  fixtures/workers-shared-asset-config/html-handling.test.ts
  fixtures/workers-shared-asset-config/package.json
  fixtures/workers-shared-asset-config/redirects.test.ts
  fixtures/workers-shared-asset-config/url-normalization.test.ts
  packages/miniflare/package.json
  packages/miniflare/src/workers/assets/assets.worker.ts
  packages/miniflare/src/workers/assets/router.worker.ts
  packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
  packages/miniflare/tsconfig.json
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/src/asset-workers/asset-worker.ts
  packages/vite-plugin-cloudflare/src/asset-workers/router-worker.ts
  packages/vite-plugin-cloudflare/tsup.config.ts
  packages/workers-shared/asset-worker/index.ts
  packages/workers-shared/asset-worker/src/assets-manifest.ts
  packages/workers-shared/asset-worker/src/handler.ts
  packages/workers-shared/asset-worker/src/utils/headers.ts
  packages/workers-shared/asset-worker/src/worker.ts
  packages/workers-shared/asset-worker/tsconfig.json
  packages/workers-shared/asset-worker/wrangler.jsonc
  packages/workers-shared/index.ts
  packages/workers-shared/package.json
  packages/workers-shared/router-worker/index.ts
  packages/workers-shared/router-worker/src/worker.ts
  packages/workers-shared/router-worker/tests/index.test.ts
  packages/workers-shared/router-worker/tsconfig.json
  packages/workers-shared/router-worker/wrangler.jsonc
  packages/workers-shared/turbo.json
  packages/workers-shared/utils/tsconfig.json
  packages/wrangler/api-extractor.json
  packages/wrangler/package.json
  packages/wrangler/scripts/bundle.ts
  packages/wrangler/scripts/emit-types.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/miniflare-cli/assets.ts
  packages/wrangler/src/sites.ts
  packages/wrangler/src/sourcemap.ts
  packages/wrangler/src/utils/filesystem.ts
  packages/wrangler/tsconfig.json
  packages/wrangler/tsup.config.ts
  pnpm-lock.yaml
Labels: e2e, no-changeset-required, c3-e2e, skip-v3-pr, every-os

#9410 fix: remove unnecessary remote warnings for mixed mode in the vite plugin
  .changeset/mean-news-sell.md
  .changeset/mean-news-throw.md
  packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
  packages/vite-plugin-cloudflare/src/deploy-config.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/vite-plugin-cloudflare/src/workers-configs.ts
  packages/wrangler/src/config/index.ts
Labels: e2e, skip-v3-pr

#9413 test: fix environment variable expansion of Wrangler e2e tests to work on Windows
  packages/wrangler/e2e/vitest.config.mts
  packages/wrangler/package.json
Labels: e2e, skip-pr-description-validation, no-changeset-required, skip-v3-pr, every-os
