Repository cloudflare/workers-sdk, pull requests merged in 2025-10, with the labels that each got.

#10766 Do not override any `.env` settings in `.gitignore` files
  .changeset/silly-parks-fall.md
  packages/create-cloudflare/src/__tests__/templates.test.ts
  packages/create-cloudflare/src/templates.ts
Labels: skip-v3-pr

#10836 test: do not show unnecessary logging in version upload unit tests
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
Labels: no-changeset-required, skip-v3-pr

#10832 retry subdomain requests to be more resilient to flakes
  .changeset/tangy-donuts-jog.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/helpers/mock-workers-subdomain.ts
  packages/wrangler/src/__tests__/utils/retry.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/cfetch/index.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/utils/retry.ts
Labels: skip-v3-pr

#10761 switch zone route warning to an info message
  .changeset/puny-coins-dream.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deploy/deploy.ts
Labels: skip-v3-pr

#10835 hide unwanted logging from cloudchamber unit test output
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10838 fix(wrangler): skip banner when outputing json with queues subscription commands
  .changeset/dark-hairs-build.md
  packages/wrangler/src/__tests__/queues/__snapshots__/queues.test.ts.snap
  packages/wrangler/src/__tests__/queues/queues-subscription.test.ts
  packages/wrangler/src/__tests__/queues/queues.test.ts
  packages/wrangler/src/queues/cli/commands/subscription/get.ts
  packages/wrangler/src/queues/cli/commands/subscription/list.ts
  packages/wrangler/src/queues/cli/commands/subscription/update.ts
Labels: skip-v3-pr

#10673 Stricter handling of `/cdn-cgi/handler/` routes.
  .changeset/hungry-pants-talk.md
  .changeset/social-foxes-crash.md
  packages/miniflare/src/workers/core/entry.worker.ts
  packages/miniflare/test/index.spec.ts
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin, skip-v3-pr

#10844 Adds new instance types to allowed list
  .changeset/hip-ants-wait.md
  packages/containers-shared/src/client/models/InstanceType.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/create.test.ts
  packages/wrangler/src/__tests__/cloudchamber/limits.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/containers/config.test.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/cloudchamber/create.ts
  packages/wrangler/src/cloudchamber/instance-type/instance-type.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/containers/config.ts
Labels: skip-v3-pr

#10762 Backport [#10761]: switch zone route warning to an info message
  .changeset/puny-coins-dream.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deploy/deploy.ts
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#10757 Wrangler: fix `console.debug` logs not being logged at the `info` level (as users expect)
  .changeset/mean-parks-take.md
  fixtures/worker-logs/tests/index.test.ts
  packages/wrangler/src/dev/miniflare/stdio.ts
Labels: skip-v3-pr

#10850 test: add test that was missing in #10761
  packages/wrangler/src/__tests__/deploy.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10863 fixup changeset for new env-var
  .changeset/angry-apes-share.md
Labels: skip-pr-description-validation, skip-v3-pr

#10758 V3 backport #10757
  .changeset/mean-parks-take.md
  fixtures/worker-logs/tests/index.test.ts
  packages/wrangler/src/dev/miniflare/stdio.ts
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#10782 V3 backport #10734
  .changeset/spotty-knives-roll.md
  packages/wrangler/src/__tests__/cfetch-utils.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
  packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
  packages/wrangler/src/__tests__/pages/secret.test.ts
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/__tests__/queues.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/dev/remote.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/utils/isAbortError.ts
Labels: skip-pr-description-validation, v3-backport

#10872 test: fix snapshots for certificate tests
  packages/wrangler/src/__tests__/cert.test.ts
  packages/wrangler/src/__tests__/mtls-certificates.test.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10851 remove unused `@actions/artifact` dependency alongside prerelease workflow
  .github/prereleases/0-packages.mjs
  .github/prereleases/1-versions.mjs
  .github/prereleases/2-build-pack-upload.mjs
  .github/prereleases/3-comment.mjs
  .github/workflows/create-pullrequest-prerelease.yml
  package.json
  pnpm-lock.yaml
Labels: skip-pr-description-validation

#10440 v3 Maintenance Release
  .changeset/hungry-crews-tap.md
  .changeset/loose-glasses-poke.md
  .changeset/mean-parks-take.md
  .changeset/puny-coins-dream.md
  .changeset/small-things-poke.md
  .changeset/spotty-knives-roll.md
  .changeset/three-toys-feel.md
  .changeset/warm-clowns-visit.md
  .changeset/yummy-parents-remain.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e, v3-backport

#10902 Revert "Use updated VSCode"
  .changeset/blue-dancers-cry.md
  .github/workflows/deploy-pages-previews.yml
  packages/workers-playground/src/QuickEditor/VSCodeEditor.tsx
Labels: skip-pr-description-validation

#10862 investigate configcontroller test flakes
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/dev/remote-bindings.test.ts
  packages/wrangler/src/__tests__/r2/bucket.test.ts
  packages/wrangler/src/api/startDevWorker/BaseController.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/NoOpProxyController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr
