Repository cloudflare/workers-sdk, pull requests merged in 2025-09, with the labels that each got.

#10401 improve diff lines ordering in remote deploy config diffing logic
  .changeset/loud-insects-drive.md
  packages/wrangler/src/__tests__/deploy/config-diffs.test.ts
  packages/wrangler/src/cloudchamber/helpers/diff.ts
Labels: skip-v3-pr

#10528 Add tests for /_image request blocking in Router Worker
  packages/workers-shared/router-worker/tests/index.test.ts
Labels: no-changeset-required

#10503 Support setting container affinities
  .changeset/real-bottles-report.md
  packages/containers-shared/src/client/models/ApplicationAffinities.ts
  packages/containers-shared/src/client/models/ApplicationAffinityHardwareGeneration.ts
  packages/containers-shared/src/types.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/containers/config.test.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/containers/config.ts
  packages/wrangler/src/containers/deploy.ts
Labels: skip-v3-pr

#10497 Python templates: include pywrangler dev dep in pyproject.toml
  .changeset/great-singers-poke.md
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/pyproject.toml
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/uv.lock
  packages/create-cloudflare/templates/hello-world-durable-object/py/pyproject.toml
  packages/create-cloudflare/templates/hello-world-durable-object/py/uv.lock
  packages/create-cloudflare/templates/hello-world-with-assets/py/pyproject.toml
  packages/create-cloudflare/templates/hello-world-with-assets/py/uv.lock
  packages/create-cloudflare/templates/hello-world/py/pyproject.toml
  packages/create-cloudflare/templates/hello-world/py/uv.lock
Labels: no-tests

#10527 Bump `unenv` to 2.0.0-rc.20
  .changeset/lemon-boxes-flow.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: wrangler, vite-plugin, skip-v3-pr

#10537 refactor unenv e2e tests now that workerd >= 20250901
  packages/wrangler/e2e/unenv-preset/preset.test.ts
Labels: no-changeset-required, skip-v3-pr

#10544 Set `preserveEntrySignatures: "strict"` for Worker environments
  .changeset/bumpy-garlics-call.md
  packages/vite-plugin-cloudflare/playground/worker/__tests__/worker.spec.ts
  packages/vite-plugin-cloudflare/playground/worker/src/a.ts
  packages/vite-plugin-cloudflare/playground/worker/src/b.ts
  packages/vite-plugin-cloudflare/playground/worker/src/index.ts
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Labels: vite-plugin

#10547 fix version upload e2e test
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/e2e/versions.test.ts
Labels: no-changeset-required

#10492 Include cursor in text prompts
  .changeset/orange-signs-lose.md
  packages/cli/interactive.ts
  packages/cli/package.json
  tools/deployments/__tests__/validate-changesets.test.ts
Labels: skip-v3-pr

#10596 Add Miniflare & Wrangler support for unbound Durable Objects
  .changeset/stupid-pandas-think.md
  fixtures/unbound-durable-object/package.json
  fixtures/unbound-durable-object/src/index.ts
  fixtures/unbound-durable-object/tests/index.test.ts
  fixtures/unbound-durable-object/tests/tsconfig.json
  fixtures/unbound-durable-object/tsconfig.json
  fixtures/unbound-durable-object/wrangler.jsonc
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/do/index.ts
  packages/wrangler/e2e/remote-binding/dev-remote-bindings.test.ts
  packages/wrangler/src/dev/miniflare/index.ts
  pnpm-lock.yaml
Labels: skip-v3-pr

#10631 Fix up vite-plugin runner type params
  packages/vite-plugin-cloudflare/src/runner-worker/index.ts
  packages/wrangler/e2e/remote-binding/start-worker-remote-bindings.test.ts
  packages/wrangler/e2e/start-worker-auth-opts.test.ts
  packages/wrangler/e2e/startWorker.test.ts
Labels: skip-pr-description-validation, no-changeset-required, vite-plugin

#10657 Disable remote bindings with the `--local` flag
  .changeset/swift-buses-design.md
  packages/wrangler/e2e/remote-binding/wrangler-remote-resources.test.ts
  packages/wrangler/src/dev.ts
Labels: skip-v3-pr

#10658 fix: skip service tagging when no top-level name configured
  .changeset/bumpy-islands-slide.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/environments/index.ts
Labels: skip-v3-pr

#10577 Use workerd `node:process` v2 when available
  .changeset/red-wasps-kick.md
  fixtures/worker-logs/tests/index.test.ts
  packages/unenv-preset/package.json
  packages/unenv-preset/src/runtime/node/process.ts
  packages/wrangler/e2e/unenv-preset/preset.test.ts
  packages/wrangler/e2e/unenv-preset/worker/index.ts
  pnpm-lock.yaml
Labels: blocked, skip-v3-pr

#10663 Update Prisma playground
  packages/vite-plugin-cloudflare/playground/prisma/.gitignore
  packages/vite-plugin-cloudflare/playground/prisma/package.json
  packages/vite-plugin-cloudflare/playground/prisma/prisma/schema.prisma
  packages/vite-plugin-cloudflare/playground/prisma/src/index.ts
  packages/vite-plugin-cloudflare/playground/prisma/wrangler.jsonc
  pnpm-lock.yaml
Labels: no-changeset-required, vite-plugin

#10654 fix: update R2 SQL response format and env variable
  .changeset/easy-guests-end.md
  packages/wrangler/src/__tests__/r2/sql.test.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/r2/sql.ts
  packages/wrangler/src/user/auth-variables.ts
  packages/wrangler/turbo.json
Labels: skip-v3-pr

#10651 Add new attribute allowed_sender_addresses
  .changeset/soft-flies-search.md
  packages/miniflare/src/plugins/email/index.ts
  packages/miniflare/src/workers/email/send_email.worker.ts
  packages/miniflare/test/plugins/email/index.spec.ts
  packages/wrangler/src/__tests__/init.test.ts
  packages/wrangler/src/__tests__/versions/versions.view.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/utils/map-worker-metadata-bindings.ts
  packages/wrangler/src/utils/print-bindings.ts
  packages/wrangler/src/versions/view.ts
Labels: skip-v3-pr

#10674 Fix remote/local display
  .changeset/giant-cherries-shake.md
  packages/wrangler/src/dev/miniflare/index.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: skip-v3-pr

#10687 chore(vite-plugin-cloudflare): test local mode support for image bindings
  packages/vite-plugin-cloudflare/playground/bindings/__tests__/worker.spec.ts
  packages/vite-plugin-cloudflare/playground/bindings/src/image.png
  packages/vite-plugin-cloudflare/playground/bindings/src/index.ts
  packages/vite-plugin-cloudflare/playground/bindings/worker-configuration.d.ts
  packages/vite-plugin-cloudflare/playground/bindings/wrangler.jsonc
Labels: no-changeset-required

#10701 Fix hotkeys double render
  .changeset/rich-hats-chew.md
  packages/wrangler/src/cli-hotkeys.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/hotkeys.ts
Labels: skip-v3-pr

#10380 chore: improvements to remote-bindings tests to reduce flakes
  .github/workflows/e2e.yml
  .github/workflows/test-and-check.yml
  fixtures/get-platform-proxy-remote-bindings/package.json
  fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
  fixtures/get-platform-proxy-remote-bindings/turbo.json
  fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/wrangler/e2e/dev-env.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/e2e/remote-binding/dev-remote-bindings.test.ts
  packages/wrangler/e2e/remote-binding/miniflare-remote-resources.test.ts
  packages/wrangler/e2e/remote-binding/remote-bindings-api.test.ts
  packages/wrangler/e2e/remote-binding/start-worker-remote-bindings.test.ts
  packages/wrangler/e2e/remote-binding/wrangler-remote-resources.test.ts
  packages/wrangler/e2e/start-worker-auth-opts.test.ts
  packages/wrangler/e2e/startWorker.test.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/e2e/vitest.config.mts
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/dev/remote-bindings.test.ts
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/remoteBindings/index.ts
  packages/wrangler/src/api/remoteBindings/start-remote-proxy-session.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/start-dev.ts
  packages/wrangler/src/pages/dev.ts
  tools/e2e/runIndividualE2EFiles.ts
Labels: skip-pr-description-validation, no-changeset-required

#10685 add `@cloudflare/` scope to all private packages and rename root package
  fixtures/import-npm/packages/import-example/package.json
  lint-turbo.mjs
  package.json
  packages/devprod-status-bot/package.json
  packages/edge-preview-authenticated-proxy/package.json
  packages/format-errors/package.json
  packages/playground-preview-worker/package.json
  packages/quick-edit-extension/package.json
  packages/turbo-r2-archive/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/invalid-worker-environment-options/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/package.json
  packages/workers-playground/package.json
  tools/deployments/__tests__/deploy-non-npm-packages.test.ts
  tools/deployments/__tests__/validate-changesets.test.ts
  tools/deployments/validate-private-packages.ts
  tools/package.json
Labels: no-changeset-required, skip-v3-pr

#10724 Use Cap'n Web in `workers-sdk`
  .changeset/odd-trains-hear.md
  .gitignore
  .prettierignore
  packages/miniflare/package.json
  packages/miniflare/src/workers/dispatch-namespace/dispatch-namespace.worker.ts
  packages/miniflare/src/workers/shared/remote-proxy-client.worker.ts
  packages/miniflare/src/workers/shared/timers.worker.ts
  packages/miniflare/src/workers/tsconfig.json
  packages/wrangler/package.json
  packages/wrangler/templates/remoteBindings/ProxyServerWorker.ts
  pnpm-lock.yaml
  vendor/jsrpc/dist/index.d.ts
  vendor/jsrpc/dist/index.js
  vendor/jsrpc/package.json
Labels: skip-v3-pr

#10743 Updated catalog compaction arg, small pipelines fixes
  .changeset/brave-memes-raise.md
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/pipelines/cli/setup.ts
  packages/wrangler/src/pipelines/cli/sinks/create.ts
  packages/wrangler/src/pipelines/cli/sinks/utils.ts
  packages/wrangler/src/pipelines/cli/streams/utils.ts
  packages/wrangler/src/pipelines/defaults.ts
  packages/wrangler/src/pipelines/types.ts
  packages/wrangler/src/r2/catalog.ts
Labels: skip-v3-pr

#10752 Update changeset
  .changeset/brave-memes-raise.md
Labels: skip-pr-description-validation, skip-v3-pr

#10708 remove unused `@actions/artifact` dependency
  package.json
  pnpm-lock.yaml
Labels: no-changeset-required

#10759 test: do not require remote bindings in basic vite e2e tests
  .github/workflows/e2e.yml
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/api/index.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/entry-worker/src/index.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/entry-worker/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts
Labels: skip-pr-description-validation, no-changeset-required

#10668 wrangler: fix: support the deletion of secrets with complex names
  .changeset/warm-clowns-visit.md
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/secret/index.ts
Labels: skip-v3-pr

#10739 Pbd/test configcontroller flakes
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
Labels: skip-pr-description-validation, no-changeset-required

#10771 Fix Worker Loader binding type
  .changeset/modern-bobcats-tie.md
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/utils/map-worker-metadata-bindings.ts
Labels: skip-v3-pr

#10720 Refactor plugins into separate files
  packages/vite-plugin-cloudflare/src/additional-modules.ts
  packages/vite-plugin-cloudflare/src/build.ts
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/constants.ts
  packages/vite-plugin-cloudflare/src/debugging.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/output-config.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/vite-plugin-cloudflare/src/plugins/additional-modules.ts
  packages/vite-plugin-cloudflare/src/plugins/nodejs-compat.ts
  packages/vite-plugin-cloudflare/src/plugins/output-config.ts
  packages/vite-plugin-cloudflare/src/plugins/utils.ts
  packages/vite-plugin-cloudflare/src/plugins/virtual-modules.ts
  packages/vite-plugin-cloudflare/src/plugins/wasm.ts
  packages/vite-plugin-cloudflare/src/runner-worker/module-runner.ts
  packages/vite-plugin-cloudflare/src/shared.ts
  packages/vite-plugin-cloudflare/src/workers-configs.ts
Labels: no-changeset-required, vite-plugin

#10602 fix: update Secrets Store status from alpha to open-beta
  .changeset/bitter-banks-teach.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/secrets-store.test.ts
  packages/wrangler/src/secrets-store/commands.ts
  packages/wrangler/src/secrets-store/index.ts
Labels: skip-v3-pr

#10742 feat(workers-shared): add fed configs for assets workers
  packages/workers-shared/asset-worker/src/types.ts
  packages/workers-shared/asset-worker/wrangler.jsonc
  packages/workers-shared/router-worker/src/types.ts
  packages/workers-shared/router-worker/wrangler.jsonc
Labels: no-changeset-required

#10786 test: only watch config files in ConfigController when not testing
  packages/wrangler/src/__tests__/dev/remote-bindings.test.ts
  packages/wrangler/src/__tests__/vitest.setup.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
Labels: no-changeset-required, skip-v3-pr

#10679 fix(wrangler): Nested object rendering in Containers list/info commands
  .changeset/red-keys-clean.md
  packages/wrangler/package.json
  packages/wrangler/src/containers/containers.ts
  pnpm-lock.yaml
Labels: skip-v3-pr

#10323 Run cleanup every 2 hours and only cleanup kvs that are older than an hour
  .github/workflows/e2e-project-cleanup.yml
  fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
  packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
  packages/wrangler/e2e/cert.test.ts
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/cert.ts
  packages/wrangler/e2e/helpers/command.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/provision.test.ts
  tools/e2e/common.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10769 Mark more errors as `UserError`
  .changeset/popular-moons-knock.md
  fixtures/ratelimit-app/tsconfig.json
  fixtures/worker-ts/wrangler.jsonc
  packages/containers-shared/src/build.ts
  packages/containers-shared/src/error.ts
  packages/containers-shared/src/images.ts
  packages/containers-shared/src/inspect.ts
  packages/containers-shared/src/login.ts
  packages/containers-shared/src/utils.ts
  packages/containers-shared/tests/docker-context.test.ts
  packages/edge-preview-authenticated-proxy/tests/tsconfig.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/runtime/index.ts
  packages/miniflare/src/shared/error.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/d1/execute.ts
  packages/wrangler/src/dev/miniflare/stdio.ts
  packages/wrangler/src/index.ts
Labels: skip-v3-pr

#8314 feat: add Waku to C3
  .changeset/moody-hands-sort.md
  packages/create-cloudflare/e2e/tests/cli/cli.test.ts
  packages/create-cloudflare/e2e/tests/frameworks/test-config.ts
  packages/create-cloudflare/src/frameworks/package.json
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/waku/c3.ts
  packages/create-cloudflare/templates/waku/wrangler.jsonc
Labels: skip-pr-description-validation, c3-e2e

#10734 Improve error logging
  .changeset/spotty-knives-roll.md
  packages/wrangler/e2e/secrets-store.test.ts
  packages/wrangler/src/__tests__/cfetch-utils.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/pages/functions-build.test.ts
  packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
  packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
  packages/wrangler/src/__tests__/pages/secret.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/api/startDevWorker/DevEnv.ts
  packages/wrangler/src/dev/remote.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/utils/isAbortError.ts
Labels: skip-v3-pr
