Repository cloudflare/workers-sdk, pull requests merged in 2025-06, with the labels that each got.

#9399 add (no-op) ContainerService and config to miniflare
  fixtures/container-app/.gitignore
  fixtures/container-app/Dockerfile
  fixtures/container-app/README.md
  fixtures/container-app/container/go.mod
  fixtures/container-app/container/go.sum
  fixtures/container-app/container/main.go
  fixtures/container-app/package.json
  fixtures/container-app/src/index.ts
  fixtures/container-app/tests/index.test.ts
  fixtures/container-app/tests/tsconfig.json
  fixtures/container-app/tsconfig.json
  fixtures/container-app/vitest.config.mts
  fixtures/container-app/worker-configuration.d.ts
  fixtures/container-app/wrangler.jsonc
  fixtures/container-app/wrangler.no-containers.jsonc
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/containers/index.ts
  packages/miniflare/src/plugins/containers/service/index.ts
  packages/miniflare/src/plugins/index.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/dev/miniflare.ts
  pnpm-lock.yaml
Labels: e2e, no-changeset-required, skip-v3-pr

#9437 test: re-enable the Vite plugin basic e2e tests on Windows
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
Labels: e2e, no-changeset-required, skip-v3-pr, every-os

#9447 VP fixups
  fixtures/container-app/tests/index.test.ts
  packages/wrangler/e2e/provision.test.ts
  packages/wrangler/e2e/wrangler-mixed-mode-resources.test.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required, skip-v3-pr, every-os

#9408 Version Packages
  .changeset/bright-cloths-turn.md
  .changeset/c3-frameworks-update-9424.md
  .changeset/c3-frameworks-update-9425.md
  .changeset/c3-frameworks-update-9427.md
  .changeset/c3-frameworks-update-9428.md
  .changeset/c3-frameworks-update-9429.md
  .changeset/c3-frameworks-update-9430.md
  .changeset/dirty-grapes-mate.md
  .changeset/eight-donkeys-play.md
  .changeset/empty-islands-draw.md
  .changeset/five-ladybugs-sell.md
  .changeset/huge-bats-itch.md
  .changeset/large-brooms-fail.md
  .changeset/mean-news-sell.md
  .changeset/mean-news-throw.md
  .changeset/rich-nails-taste.md
  .changeset/wise-rules-march.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9442 Add _headers file to NextJS workers template
  .changeset/slow-results-design.md
  packages/create-cloudflare/templates/next/workers/templates/public/_headers
Labels: c3-e2e

#9457 VP fixups
  .changeset/slow-results-design.md
  packages/wrangler/e2e/provision.test.ts
Labels: e2e, skip-pr-description-validation, skip-v3-pr

#9452 Version Packages
  .changeset/c3-frameworks-update-9426.md
  .changeset/slow-results-design.md
  .changeset/ten-cities-like.md
  .changeset/tiny-socks-wish.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9453 backport #9353 (fix telemetry.md link)
  .changeset/forty-things-beam.md
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/metrics/commands.ts
Labels: e2e, c3-e2e

#9469 refactor(miniflare): dev registry should create a file watcher only when necessary
  .changeset/gold-experts-sniff.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/shared/dev-registry.ts
Labels: e2e

#9404 Fix some typos
  fixtures/workflow/tests/index.test.ts
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/src/__tests__/metrics.test.ts
  packages/kv-asset-handler/src/mocks.ts
  packages/wrangler/src/tail/filters.ts
Labels: skip-pr-description-validation, no-changeset-required, c3-e2e, skip-v3-pr

#9478 remove erroneous TBD that prevents workflows starter from deploying
  .changeset/yummy-jokes-lose.md
  packages/create-cloudflare/templates/hello-world-workflows/ts/wrangler.jsonc
Labels: c3-e2e

#9483 [unenv/preset] Use crypto.constants from workerd
  .changeset/solid-sides-join.md
  fixtures/nodejs-hybrid-app/src/index.ts
  packages/unenv-preset/src/runtime/node/crypto.ts
Labels: node compat, wrangler, e2e, skip-v3-pr

#9223 clarify the description of `--keep-vars`
  packages/wrangler/src/deploy/index.ts
Labels: wrangler, e2e, no-changeset-required

#9461 Consider disk limits when building containers
  .changeset/empty-shirts-judge.md
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/cloudchamber/utils.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/deploy.ts
  packages/wrangler/src/config/environment.ts
Labels: skip-v3-pr

#9480 add `experimentalMixedMode` dev option to `unstable_startWorker`
  .changeset/modern-memes-appear.md
  packages/wrangler/e2e/start-worker-mixed-mode.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
Labels: e2e, skip-v3-pr

#9499 c3: use "cloudflare" image processing in astro projects
  .changeset/quick-snails-follow.md
  packages/create-cloudflare/templates/astro/pages/c3.ts
  packages/create-cloudflare/templates/astro/workers/c3.ts
Labels: c3, c3-e2e, every-os

#9416 Add support for static routing to Workers Assets
  .changeset/tasty-hoops-own.md
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/src/handler.ts
  packages/workers-shared/asset-worker/src/utils/rules-engine.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
  packages/workers-shared/asset-worker/tests/rules-engine.test.ts
  packages/workers-shared/router-worker/src/analytics.ts
  packages/workers-shared/router-worker/src/configuration.ts
  packages/workers-shared/router-worker/src/worker.ts
  packages/workers-shared/router-worker/tests/index.test.ts
  packages/workers-shared/utils/types.ts
Labels: e2e, every-os

#9540 Turn on dependabot
  .github/dependabot.yml
Labels: skip-pr-description-validation

#9476 Version Packages
  .changeset/beige-llamas-punch.md
  .changeset/chatty-turkeys-do.md
  .changeset/dependabot-update-9385.md
  .changeset/empty-shirts-judge.md
  .changeset/free-buttons-wash.md
  .changeset/gold-experts-sniff.md
  .changeset/modern-memes-appear.md
  .changeset/quick-snails-follow.md
  .changeset/solid-sides-join.md
  .changeset/tasty-hoops-own.md
  .changeset/yummy-jokes-lose.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9443 add mTLS mixed mode support
  .changeset/famous-candies-start.md
  .changeset/lemon-laws-mate.md
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/plugins/mtls/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/wrangler/e2e/cert.test.ts
  packages/wrangler/e2e/helpers/cert.ts
  packages/wrangler/e2e/miniflare-mixed-mode-resources.test.ts
  packages/wrangler/e2e/seed-files/mixed-mode-workers/mtls.js
  packages/wrangler/src/api/mixedMode/index.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/cli.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e, skip-v3-pr, every-os

#8617 chore: app option to run the vite-plugin playground serve tests in parallel
  packages/vite-plugin-cloudflare/playground/package.json
Labels: no-changeset-required, vite-plugin

#9572 Changesets minor -> patch
  .changeset/forty-waves-stare.md
  .changeset/rich-bottles-hug.md
Labels: skip-v3-pr

#9570 Revert "chore: update node versions in various places"
  .github/workflows/c3-e2e.yml
  fixtures/node-app-pages/package.json
  fixtures/pages-d1-shim/package.json
  fixtures/pages-dev-proxy-with-script/package.json
  fixtures/pages-functions-app/package.json
  fixtures/pages-functions-wasm-app/package.json
  fixtures/pages-functions-with-config-file-app/package.json
  fixtures/pages-functions-with-routes-app/package.json
  fixtures/pages-nodejs-v2-compat/package.json
  fixtures/pages-plugin-mounted-on-root-app/package.json
  fixtures/pages-simple-assets/package.json
  fixtures/pages-workerjs-and-functions-app/package.json
  fixtures/pages-workerjs-app/package.json
  fixtures/pages-workerjs-directory/package.json
  fixtures/pages-workerjs-wasm-app/package.json
  fixtures/pages-workerjs-with-config-file-app/package.json
  fixtures/pages-workerjs-with-routes-app/package.json
  package.json
  packages/kv-asset-handler/package.json
  packages/miniflare/package.json
  packages/workers-shared/package.json
  packages/workflows-shared/package.json
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#9560 test: add test cases for run_worker_first routes behaviour
  packages/wrangler/e2e/deployments.test.ts
Labels: e2e, no-changeset-required, every-os

#9493 [miniflare] bump capnp-es to 0.0.11
  .changeset/tasty-otters-go.md
  packages/miniflare/package.json
  packages/miniflare/src/runtime/config/generated.ts
  pnpm-lock.yaml
Labels: wrangler, e2e

#9566 Bump `@cloudflare/unenv-preset` to 2.3.3
  .changeset/shy-cups-float.md
  packages/vite-plugin-cloudflare/package.json
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: wrangler, e2e, vite-plugin, skip-v3-pr

#9550 allow `startWorker` to accept `false` as an `inspector` option (to disable the inspector server)
  .changeset/true-cities-try.md
  fixtures/start-worker-node-test/src/config-errors.test.js
  packages/wrangler/e2e/startWorker.test.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/api/mixedMode/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/ProxyController.ts
  packages/wrangler/src/api/startDevWorker/events.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/dev/hotkeys.ts
Labels: e2e, skip-v3-pr

#9564 containers: switch to Cloudflare container registry
  .changeset/dirty-roses-itch.md
  packages/containers-shared/index.ts
  packages/containers-shared/src/constants.ts
  packages/containers-shared/src/knobs.ts
  packages/containers-shared/src/login.ts
  packages/containers-shared/src/registry.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/cloudchamber/utils.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/cloudchamber/images/list.ts
Labels: skip-v3-pr

#9588 switch from container playground/fixture to node
  fixtures/container-app/Dockerfile
  fixtures/container-app/container/go.mod
  fixtures/container-app/container/go.sum
  fixtures/container-app/container/main.go
  fixtures/container-app/container/simple-node-app.js
Labels: no-changeset-required

#9548 Enable HTML handling for HTML files in the public directory
  .changeset/odd-queens-enjoy.md
  packages/vite-plugin-cloudflare/playground/static-mpa/__tests__/static-mpa.spec.ts
  packages/vite-plugin-cloudflare/playground/static-mpa/public-html.html
  packages/vite-plugin-cloudflare/playground/static-mpa/public/public-html.html
  packages/vite-plugin-cloudflare/src/asset-workers/asset-worker.ts
  packages/vite-plugin-cloudflare/src/constants.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/utils.ts
Labels: e2e, vite-plugin, every-os

#9595 [vitest-pool-worker] Add `type: module` in package.json
  .changeset/five-chefs-kneel.md
  packages/vitest-pool-workers/.eslintrc.cjs
  packages/vitest-pool-workers/package.json
Labels: e2e

#9573 warn instead of erroring if no exposed ports. and remove unused dev_exposed_ports
  packages/miniflare/src/plugins/containers/service/index.ts
  packages/wrangler/e2e/containers.dev.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/config/environment.ts
Labels: e2e, no-changeset-required

#9593 drop unused `WRANGLER_UNENV_RESOLVE_PATHS` env var
  .changeset/sharp-phones-hope.md
  packages/unenv-preset/tests/index.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
Labels: wrangler, e2e, skip-v3-pr

#9598 test: correctly delete test d1 databases
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  tools/e2e/__tests__/common.test.ts
  tools/e2e/common.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9344 add warning about env not specified to potentially risky wrangler commands
  .changeset/some-cloths-move.md
  .changeset/spotty-worlds-rest.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
  packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
  packages/wrangler/src/__tests__/versions/secrets/put.test.ts
  packages/wrangler/src/__tests__/versions/secrets/utils.ts
  packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/core/types.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/triggers/index.ts
  packages/wrangler/src/versions/deploy.ts
  packages/wrangler/src/versions/secrets/bulk.ts
  packages/wrangler/src/versions/secrets/delete.ts
  packages/wrangler/src/versions/secrets/put.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e, skip-v3-pr

#9506 fix: use connect_pass_through flag instead of workaround for TCP regression
  .changeset/fix-tcp-regression-connect-pass-through.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/test/index.spec.ts
  packages/unenv-preset/package.json
  packages/wrangler/src/__tests__/api/startDevWorker/startWorker.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/templates/strip-cf-connecting-ip-header.js
  pnpm-lock.yaml
Labels: skip-v3-pr

#9551 Update Devtools Patches
  .changeset/fifty-bananas-applaud.md
  packages/chrome-devtools-patches/Makefile
  packages/chrome-devtools-patches/patches/0001-Expand-Browser-support-make-it-work-in-Firefox-Safar.patch
  packages/chrome-devtools-patches/patches/0002-Setup-Cloudflare-devtools-target-type.patch
  packages/chrome-devtools-patches/patches/0003-Add-ping-to-improve-connection-stability.-Without-th.patch
  packages/chrome-devtools-patches/patches/0004-Support-viewing-source-files-over-the-network.-This-.patch
  packages/chrome-devtools-patches/patches/0005-Support-forcing-the-devtools-theme-via-a-query-param.patch
  packages/chrome-devtools-patches/patches/0006-All-about-the-network-tab.patch
  packages/chrome-devtools-patches/patches/0007-Limit-heap-profiling-modes-available.patch
  packages/chrome-devtools-patches/patches/0008-Use-the-worker-name-as-the-title-for-the-Javascript-.patch
Labels: preview:workers-playground, preview:chrome-devtools-patches

#9624 remove todo comment left in changelog by mistake
  .changeset/some-cloths-move.md
Labels: skip-v3-pr

#9629 fix up changelog after hotfix
  .changeset/eight-spoons-build.md
  packages/create-cloudflare/CHANGELOG.md
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#9579 Version Packages
  .changeset/cool-peas-march.md
  .changeset/dependabot-update-9529.md
  .changeset/dirty-files-bet.md
  .changeset/dirty-roses-itch.md
  .changeset/fair-lamps-fix.md
  .changeset/fifty-bananas-applaud.md
  .changeset/five-chefs-kneel.md
  .changeset/fix-tcp-regression-connect-pass-through.md
  .changeset/forty-things-beam.md
  .changeset/itchy-ears-carry.md
  .changeset/nine-facts-kneel.md
  .changeset/odd-queens-enjoy.md
  .changeset/sharp-phones-hope.md
  .changeset/shy-cups-float.md
  .changeset/six-parrots-clap.md
  .changeset/slick-ideas-shave.md
  .changeset/some-cloths-move.md
  .changeset/spotty-worlds-rest.md
  .changeset/tall-insects-read.md
  .changeset/tasty-otters-go.md
  .changeset/true-cities-try.md
  .changeset/violet-donkeys-fail.md
  .changeset/wet-socks-read.md
  packages/chrome-devtools-patches/CHANGELOG.md
  packages/chrome-devtools-patches/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9631 V3 backport [#9628]: Remove "Cloudchamber" from user facing error messages
  .changeset/thick-ways-visit.md
  packages/wrangler/src/cloudchamber/common.ts
Labels: skip-pr-description-validation, skip-v3-pr

#9636 Correctly mock out getDockerImageDigest for testing buildAndMaybePush
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
Labels: skip-pr-description-validation, every-os

#9632 Version Packages
  .changeset/c3-frameworks-update-9524.md
  .changeset/c3-frameworks-update-9525.md
  .changeset/c3-frameworks-update-9526.md
  .changeset/c3-frameworks-update-9527.md
  .changeset/dependabot-update-9591.md
  .changeset/rare-wasps-cough.md
  .changeset/thick-ways-visit.md
  .changeset/weak-months-speak.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9621 containers: Default scheduling policy should be the default
  .changeset/nasty-cameras-poke.md
  packages/containers-shared/package.json
  packages/containers-shared/src/client/models/SchedulingPolicy.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/config/environment.ts
Labels: e2e, skip-v3-pr

#9650 Version Packages
  .changeset/nasty-cameras-poke.md
  .changeset/nice-falcons-yell.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9305 Add @handler to Python templates.
  .changeset/funny-onions-post.md
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/src/entry.py
  packages/create-cloudflare/templates/hello-world-durable-object/py/src/entry.py
  packages/create-cloudflare/templates/hello-world-with-assets/py/src/entry.py
Labels: c3-e2e

#9649 add changeset to trigger release of workers/pages projects
  .changeset/lazy-ghosts-spend.md
Labels: skip-pr-description-validation, skip-v3-pr

#9648 chore: remove redundant binding guide
  packages/wrangler/docs/how-to/add-a-binding.md
Labels: no-changeset-required

#9669 Revert "Migrate from unbuild to obuild"
  .changeset/purple-tools-change.md
  packages/unenv-preset/build.config.ts
  packages/unenv-preset/package.json
  packages/unenv-preset/src/preset.ts
  pnpm-lock.yaml
Labels: skip-pr-description-validation, skip-v3-pr

#9661 Router worker performs free tier limiting
  .changeset/tidy-bobcats-lose.md
  packages/workers-shared/router-worker/src/analytics.ts
  packages/workers-shared/router-worker/src/configuration.ts
  packages/workers-shared/router-worker/src/limited-response.ts
  packages/workers-shared/router-worker/src/worker.ts
  packages/workers-shared/router-worker/tests/index.test.ts
  packages/workers-shared/router-worker/wrangler.jsonc
  packages/workers-shared/utils/types.ts
Labels: e2e

#9663 chore: test hello world binding support in vite plugin
  packages/vite-plugin-cloudflare/playground/bindings/__tests__/worker.spec.ts
  packages/vite-plugin-cloudflare/playground/bindings/package.json
  packages/vite-plugin-cloudflare/playground/bindings/src/index.ts
  packages/vite-plugin-cloudflare/playground/bindings/tsconfig.json
  packages/vite-plugin-cloudflare/playground/bindings/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/bindings/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/bindings/turbo.json
  packages/vite-plugin-cloudflare/playground/bindings/vite.config.ts
  packages/vite-plugin-cloudflare/playground/bindings/worker-configuration.d.ts
  packages/vite-plugin-cloudflare/playground/bindings/wrangler.jsonc
  pnpm-lock.yaml
Labels: no-changeset-required

#9662 chore: test hello world binding support in vitest-pool-workers
  packages/vitest-pool-workers/test/bindings.test.ts
Labels: no-changeset-required

#9671 chore: Run C3 e2e tests on every OS only if both `every-os` and `c3-e2e` labels are applied
  .github/workflows/c3-e2e.yml
Labels: no-changeset-required, skip-v3-pr

#9673 fix: ensure that wrangler deploy and version upload don't override the remote-bindings flag
  .changeset/better-rings-heal.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e, skip-v3-pr, every-os

#9664 Remove confirmation dialog for cloudchamber apply when not interactive
  .changeset/cuddly-sites-doubt.md
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
Labels: skip-v3-pr

#9653 Containers fixups
  .changeset/clever-crews-destroy.md
  .changeset/giant-kiwis-provide.md
  packages/containers-shared/src/utils.ts
  packages/wrangler/e2e/containers.dev.test.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/images/images.ts
  packages/wrangler/src/cloudchamber/images/list.ts
  packages/wrangler/src/cloudchamber/index.ts
  packages/wrangler/src/cloudchamber/ssh/ssh.ts
  packages/wrangler/src/containers/index.ts
  packages/wrangler/src/core/CommandRegistry.ts
  packages/wrangler/src/environment-variables/factory.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
  packages/wrangler/turbo.json
Labels: e2e, skip-v3-pr

#9681 Skip authed fixture on forks
  fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
Labels: skip-pr-description-validation

#9691 Temporarily skip Openapi C3 e2e tests
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
Labels: e2e, no-changeset-required, c3-e2e, skip-v3-pr, every-os

#9633 CC-5418: Set instance_type in wrangler
  .changeset/sad-drinks-relate.md
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/create.test.ts
  packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/create.ts
  packages/wrangler/src/cloudchamber/modify.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
Labels: e2e, skip-v3-pr, every-os

#9697 Version Packages
  .changeset/better-sheep-reply.md
  .changeset/bumpy-beers-stare.md
  .changeset/hot-lamps-laugh.md
  .changeset/new-pants-fail.md
  .changeset/sad-drinks-relate.md
  .changeset/thick-icons-visit.md
  packages/containers-shared/CHANGELOG.md
  packages/containers-shared/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9695 allow printing hotkeys conditionally
  .changeset/early-views-pay.md
  fixtures/interactive-dev-tests/Dockerfile
  fixtures/interactive-dev-tests/index.js
  fixtures/interactive-dev-tests/src/container.mjs
  fixtures/interactive-dev-tests/tests/index.test.ts
  fixtures/interactive-dev-tests/wrangler.container.jsonc
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/hotkeys.ts
Labels: e2e, c3-e2e, skip-v3-pr, every-os

#9098 Migrate Workers Containers commands to Containers API Endpoints
  .changeset/rude-kings-teach.md
  packages/containers-shared/src/client/core/request.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/__tests__/cloudchamber/utils.ts
  packages/wrangler/src/__tests__/containers/delete.test.ts
  packages/wrangler/src/__tests__/containers/info.test.ts
  packages/wrangler/src/__tests__/containers/list.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/cloudchamber/deploy.ts
  packages/wrangler/src/cloudchamber/images/images.ts
  packages/wrangler/src/cloudchamber/images/list.ts
  packages/wrangler/src/cloudchamber/index.ts
  packages/wrangler/src/cloudchamber/locations.ts
  packages/wrangler/src/cloudchamber/ssh/ssh.ts
  packages/wrangler/src/containers/containers.ts
  packages/wrangler/src/containers/index.ts
  packages/wrangler/src/user/user.ts
Labels: e2e, skip-v3-pr, every-os

#9704 Version Packages
  .changeset/angry-poems-tease.md
  .changeset/c3-frameworks-update-9700.md
  .changeset/c3-frameworks-update-9701.md
  .changeset/c3-frameworks-update-9702.md
  .changeset/early-views-pay.md
  .changeset/hip-experts-smile.md
  .changeset/rude-kings-teach.md
  .changeset/thick-forks-press.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9666 Add default value for container apps if no name is present
  .changeset/witty-schools-run.md
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-v3-pr, every-os

#9720 Version Packages
  .changeset/chilly-dancers-clap.md
  .changeset/happy-mammals-end.md
  .changeset/quiet-words-act.md
  .changeset/twelve-webs-think.md
  .changeset/witty-schools-run.md
  packages/containers-shared/CHANGELOG.md
  packages/containers-shared/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9713 V3 backport: Support `wrangler version upload` for Python Workers
  .changeset/chilly-dancers-clap.md
  packages/wrangler/src/__tests__/helpers/assert-request.ts
  packages/wrangler/src/__tests__/helpers/write-worker-source.ts
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/api/startDevWorker/BundlerController.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/no-bundle-worker.ts
  packages/wrangler/src/versions/upload.ts
Labels: v3-backport

#9641 Update buildAndMaybePush to use more robust method to find local digests
  .changeset/orange-teams-glow.md
  packages/containers-shared/src/images.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/cloudchamber/build.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/cloudchamber/apply.ts
  packages/wrangler/src/cloudchamber/build.ts
  packages/wrangler/src/cloudchamber/deploy.ts
  packages/wrangler/src/config/validation.ts
Labels: skip-v3-pr

#9667 Verify docker installation earlier when deploying container
  .changeset/social-dryers-feel.md
  packages/containers-shared/src/utils.ts
  packages/wrangler/e2e/containers.dev.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deploy/deploy.ts
Labels: e2e, skip-v3-pr, every-os

#9736 containers: Do not check scopes if not init
  .changeset/slimy-clocks-matter.md
  packages/wrangler/src/cloudchamber/common.ts
Labels: e2e, skip-v3-pr

#9732 Version Packages
  .changeset/busy-planets-accept.md
  .changeset/orange-teams-glow.md
  .changeset/slimy-clocks-matter.md
  .changeset/social-dryers-feel.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9620 CC-5462: Simplify containers images list output
  .changeset/hungry-garlics-flow.md
  packages/wrangler/src/__tests__/cloudchamber/images.test.ts
  packages/wrangler/src/cloudchamber/images/list.ts
Labels: skip-v3-pr, every-os

#7871 add support for assets bindings to `getPlatformProxy` (take 2)
  .changeset/thick-dots-sit.md
  fixtures/get-platform-proxy/public/test.txt
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler.jsonc
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/assets.ts
Labels: e2e, skip-v3-pr

#9694 V3 backport [#7871]: add support for assets bindings to `getPlatformProxy`
  .changeset/thick-dots-sit.md
  fixtures/get-platform-proxy/public/test.txt
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  fixtures/get-platform-proxy/wrangler.jsonc
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/assets.ts
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#9737 Run more tests, more of the time
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/c3-e2e.yml
  .github/workflows/e2e.yml
  .github/workflows/open-v3-maintenance-prs.yml
  .github/workflows/test-and-check.yml
  fixtures/interactive-dev-tests/package.json
  pnpm-lock.yaml
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: skip-pr-description-validation, skip-v3-pr

#9726 chore: Force fail e2e tests job if fork PR
  .github/workflows/e2e.yml
Labels: no-changeset-required

#9777 Fix the v3 backport message to use v3-backport-PR
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/open-v3-pr.ts
Labels: no-changeset-required

#9753 Allow `optimizeDeps.exclude` to be specified for Worker environments
  .changeset/warm-masks-chew.md
  packages/vite-plugin-cloudflare/e2e/fixtures/invalid-worker-environment-options/index.js
  packages/vite-plugin-cloudflare/e2e/fixtures/invalid-worker-environment-options/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/invalid-worker-environment-options/vite.config.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/invalid-worker-environment-options/wrangler.jsonc
  packages/vite-plugin-cloudflare/e2e/invalid-worker-env-configs.test.ts
  packages/vite-plugin-cloudflare/e2e/invalid-worker-environment-options.test.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/__tests__/base-tests.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/package.json
  packages/vite-plugin-cloudflare/playground/module-resolution/packages/excludes/index.js
  packages/vite-plugin-cloudflare/playground/module-resolution/packages/excludes/package.json
  packages/vite-plugin-cloudflare/playground/module-resolution/packages/excludes/plugin.js
  packages/vite-plugin-cloudflare/playground/module-resolution/packages/imports/package.json
  packages/vite-plugin-cloudflare/playground/module-resolution/packages/requires/package.json
  packages/vite-plugin-cloudflare/playground/module-resolution/src/external-cloudflare-imports.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/src/index.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/src/require-ext.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/src/require-json.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/src/require-no-ext.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/vite.config.nodejs-compat.ts
  packages/vite-plugin-cloudflare/playground/module-resolution/vite.config.ts
  packages/vite-plugin-cloudflare/src/__tests__/validate-worker-environment-options.spec.ts
  packages/vite-plugin-cloudflare/src/__tests__/validate_worker_environments_resolved_configs.spec.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/vite-config.ts
  packages/vite-plugin-cloudflare/src/worker-environments-validation.ts
  pnpm-lock.yaml
Labels: e2e, vite-plugin, skip-v3-pr

#9773 Support Vite 7
  .changeset/olive-rabbits-tell.md
  packages/vite-plugin-cloudflare/e2e/fixtures/invalid-worker-environment-options/package.json
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: vite-plugin
