Repository cloudflare/workers-sdk, pull requests merged in 2025-03, with the labels that each got.

#8309 fix(unenv-preset): define __filename
  packages/unenv-preset/build.config.ts
Labels: no-changeset-required

#8256 Add Queues commands to pause-delivery and resume-delivery
  .changeset/shiny-zebras-switch.md
  packages/wrangler/src/__tests__/queues.test.ts
  packages/wrangler/src/queues/cli/commands/index.ts
  packages/wrangler/src/queues/cli/commands/pause-resume.ts
  packages/wrangler/src/queues/client.ts
Labels: e2e

#8123 fix: nonretryable error and errored step caching
  .changeset/odd-numbers-cheat.md
  packages/workflows-shared/package.json
  packages/workflows-shared/src/context.ts
  packages/workflows-shared/src/engine.ts
  packages/workflows-shared/tests/engine.test.ts
  packages/workflows-shared/tests/env.d.ts
  packages/workflows-shared/tests/tsconfig.json
  packages/workflows-shared/tsconfig.json
  packages/workflows-shared/vitest.config.ts
  pnpm-lock.yaml
Labels: e2e, workflows

#8336 Revert "Upload metafiles for Workers Assets"
  .changeset/chatty-seas-grin.md
  fixtures/asset-config/html-handling.test.ts
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/assets/schema.ts
  packages/vitest-pool-workers/src/pool/config.ts
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/src/handler.ts
  packages/workers-shared/asset-worker/src/index.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
  packages/workers-shared/router-worker/src/configuration.ts
  packages/workers-shared/router-worker/src/index.ts
  packages/workers-shared/utils/types.ts
  packages/wrangler/src/__tests__/assets.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/remote.ts
  packages/wrangler/src/sourcemap.ts
  packages/wrangler/src/type-generation/runtime/index.ts
  packages/wrangler/src/utils/filesystem.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-pr-description-validation, c3-e2e

#8282 Version Packages
  .changeset/all-sloths-fly.md
  .changeset/brown-tools-dream.md
  .changeset/c3-frameworks-update-8324.md
  .changeset/fifty-bears-wink.md
  .changeset/five-streets-act.md
  .changeset/itchy-peaches-kneel.md
  .changeset/nine-states-call.md
  .changeset/odd-numbers-cheat.md
  .changeset/public-groups-thank.md
  .changeset/red-rockets-lie.md
  .changeset/salty-bugs-begin.md
  .changeset/shiny-zebras-switch.md
  .changeset/silver-tools-promise.md
  .changeset/sixty-spoons-unite.md
  .changeset/small-news-kneel.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-playground/CHANGELOG.md
  packages/workers-playground/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8338 Upload metafiles for Workers Assets
  .changeset/chatty-seas-grin.md
  fixtures/asset-config/html-handling.test.ts
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/assets/schema.ts
  packages/vitest-pool-workers/src/pool/config.ts
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/src/handler.ts
  packages/workers-shared/asset-worker/src/index.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
  packages/workers-shared/router-worker/src/configuration.ts
  packages/workers-shared/router-worker/src/index.ts
  packages/workers-shared/utils/types.ts
  packages/wrangler/src/__tests__/assets.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
  packages/wrangler/src/assets.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/dev/remote.ts
  packages/wrangler/src/sourcemap.ts
  packages/wrangler/src/type-generation/runtime/index.ts
  packages/wrangler/src/utils/filesystem.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-pr-description-validation, c3-e2e

#8288 feat(miniflare): Add assets Proxy Worker skeleton in miniflare
  .changeset/dry-ends-post.md
  fixtures/workers-with-assets-only/tests/index.test.ts
  fixtures/workers-with-assets-run-worker-first/tests/index.test.ts
  fixtures/workers-with-assets/tests/index.test.ts
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/assets/constants.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/assets/schema.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
  packages/vitest-pool-workers/src/pool/config.ts
  packages/wrangler/e2e/multiworker-dev.test.ts
Labels: e2e

#8166 feat: graduate `--x-include-runtime`
  .changeset/nasty-kiwis-talk.md
  .changeset/shiny-donkeys-act.md
  fixtures/type-generation/package.json
  fixtures/type-generation/tests/type-generation.file-comment.test.ts
  fixtures/type-generation/vitest.config.mts
  fixtures/type-generation/wrangler.toml
  packages/wrangler/e2e/types.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/core/types.ts
  packages/wrangler/src/type-generation/helpers.ts
  packages/wrangler/src/type-generation/index.ts
  packages/wrangler/src/type-generation/runtime/index.ts
  packages/wrangler/src/type-generation/runtime/log-runtime-types-message.ts
  pnpm-lock.yaml
Labels: e2e, v4, c3-e2e

#8344 chore: update eslint-config-turbo version
  packages/eslint-config-worker/index.js
  packages/eslint-config-worker/package.json
  packages/eslint-config-worker/react.js
  pnpm-lock.yaml
Labels: no-changeset-required

#8304 chore: add concurrency and caching for Zone IDs and Workers routes lookups
  .changeset/nasty-sloths-brush.md
  packages/wrangler/src/__tests__/zones.test.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/zones.ts
Labels: e2e

#8355 Add default empty router config for assets in Miniflare
  .changeset/purple-taxis-call.md
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/miniflare/src/plugins/assets/index.ts
Labels: skip-pr-description-validation, c3-e2e

#7752 C3 - add workers/pages platform variant support
  .changeset/tasty-apes-walk.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-to-test.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/src/types.ts
  packages/create-cloudflare/templates/docusaurus/c3.ts
  packages/create-cloudflare/templates/docusaurus/pages/c3.ts
  packages/create-cloudflare/templates/docusaurus/workers/c3.ts
  packages/create-cloudflare/templates/docusaurus/workers/templates/wrangler.jsonc
Labels: c3-e2e

#8300 Use @cloudflare/unenv-preset in wrangler
  .changeset/petite-mangos-wink.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  fixtures/pages-nodejs-v2-compat/tests/index.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/unenv/unenv.test.ts
  packages/wrangler/src/deployment-bundle/bundle.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
  pnpm-lock.yaml
Labels: e2e

#8356 Support dynamic import paths in preview mode
  .changeset/giant-breads-taste.md
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/__tests__/dynamic-import-paths.spec.ts
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/package.json
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/src/another.js
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/src/index.ts
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/tsconfig.json
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/turbo.json
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/vite.config.ts
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/wrangler.toml
  packages/vite-plugin-cloudflare/playground/vitest.config.e2e.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8339 Version Packages
  .changeset/chatty-seas-grin.md
  .changeset/dependabot-update-8251.md
  .changeset/dry-ends-post.md
  .changeset/giant-breads-taste.md
  .changeset/happy-pots-explode.md
  .changeset/nasty-sloths-brush.md
  .changeset/new-badgers-create.md
  .changeset/petite-mangos-wink.md
  .changeset/purple-taxis-call.md
  .changeset/quiet-apples-press.md
  .changeset/tasty-apes-walk.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e, c3-e2e

#8349 Add type gen command to react + vite + assets template
  .changeset/shaggy-pugs-obey.md
  packages/create-cloudflare/templates-experimental/react/c3.ts
  packages/create-cloudflare/templates-experimental/react/js/wrangler.jsonc
  packages/create-cloudflare/templates-experimental/react/ts/api/index.ts
  packages/create-cloudflare/templates-experimental/react/ts/tsconfig.worker.json
  packages/create-cloudflare/templates-experimental/react/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates-experimental/react/ts/wrangler.jsonc
Labels: c3-e2e

#8371 graduate C3 React (Workers) template
  .changeset/mighty-moments-march.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/react/c3.ts
  packages/create-cloudflare/templates/react/pages/c3.ts
  packages/create-cloudflare/templates/react/workers/c3.ts
  packages/create-cloudflare/templates/react/workers/js/api/index.js
  packages/create-cloudflare/templates/react/workers/js/src/App.jsx
  packages/create-cloudflare/templates/react/workers/js/src/assets/Cloudflare_Logo.svg
  packages/create-cloudflare/templates/react/workers/js/wrangler.jsonc
  packages/create-cloudflare/templates/react/workers/ts/api/index.ts
  packages/create-cloudflare/templates/react/workers/ts/src/App.tsx
  packages/create-cloudflare/templates/react/workers/ts/src/assets/Cloudflare_Logo.svg
  packages/create-cloudflare/templates/react/workers/ts/tsconfig.worker.json
  packages/create-cloudflare/templates/react/workers/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/react/workers/ts/wrangler.jsonc
Labels: e2e, c3-e2e

#8370 Version Packages
  .changeset/mighty-moments-march.md
  .changeset/shaggy-pugs-obey.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
Labels: e2e, c3-e2e

#8291 chore(create-cloudflare): bump template vitest packages version
  .changeset/yummy-spies-like.md
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
  packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
  packages/create-cloudflare/templates/hello-world/js/package.json
  packages/create-cloudflare/templates/hello-world/ts/package.json
Labels: c3-e2e

#8358 add vite + worker to vue experimental template
  .changeset/tangy-parts-dig.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/templates-experimental/vue/c3.ts
  packages/create-cloudflare/templates-experimental/vue/js/server/index.js
  packages/create-cloudflare/templates-experimental/vue/js/src/App.vue
  packages/create-cloudflare/templates-experimental/vue/js/src/components/HelloWorld.vue
  packages/create-cloudflare/templates-experimental/vue/js/vite.config.js
  packages/create-cloudflare/templates-experimental/vue/js/wrangler.jsonc
  packages/create-cloudflare/templates-experimental/vue/templates/wrangler.jsonc
  packages/create-cloudflare/templates-experimental/vue/ts/server/index.ts
  packages/create-cloudflare/templates-experimental/vue/ts/src/App.vue
  packages/create-cloudflare/templates-experimental/vue/ts/src/components/HelloWorld.vue
  packages/create-cloudflare/templates-experimental/vue/ts/tsconfig.worker.json
  packages/create-cloudflare/templates-experimental/vue/ts/vite.config.ts
  packages/create-cloudflare/templates-experimental/vue/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates-experimental/vue/ts/wrangler.jsonc
Labels: c3-e2e

#8378 Version Packages
  .changeset/tangy-parts-dig.md
  .changeset/whole-dots-smile.md
  .changeset/yummy-spies-like.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8347 Add Assets JSRPC test cases
  packages/wrangler/e2e/assets-multiworker.test.ts
  packages/wrangler/e2e/multiworker-dev.test.ts
Labels: e2e, no-changeset-required

#8390 Workers Assets metafiles in `wrangler dev`
  .changeset/thin-mails-live.md
  fixtures/workers-with-assets/.gitignore
  fixtures/workers-with-assets/public/.assetsignore
  fixtures/workers-with-assets/public/_headers
  fixtures/workers-with-assets/public/_redirects
  fixtures/workers-with-assets/public/_worker.js
  fixtures/workers-with-assets/public/bar.html
  fixtures/workers-with-assets/public/foo.html
  fixtures/workers-with-assets/public/ignore-me.txt
  fixtures/workers-with-assets/tests/index.test.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/pages-shared/__tests__/asset-server/handler.test.ts
  packages/pages-shared/__tests__/metadata-generator/createMetadataObject.test.ts
  packages/pages-shared/metadata-generator/createMetadataObject.ts
  packages/pages-shared/metadata-generator/types.ts
  packages/workers-shared/package.json
  packages/workers-shared/utils/configuration/constants.ts
  packages/workers-shared/utils/configuration/constructConfiguration.ts
  packages/workers-shared/utils/configuration/parseHeaders.ts
  packages/workers-shared/utils/configuration/parseRedirects.ts
  packages/workers-shared/utils/configuration/types.ts
  packages/workers-shared/utils/configuration/validateURL.ts
  packages/workers-shared/utils/constants.ts
  packages/workers-shared/utils/helpers.ts
  packages/workers-shared/utils/tests/helpers.test.ts
  packages/workers-shared/utils/tests/parseHeaders.invalid.test.ts
  packages/workers-shared/utils/tests/parseHeaders.valid.test.ts
  packages/workers-shared/utils/tests/parseRedirects.invalid.test.ts
  packages/workers-shared/utils/tests/parseRedirects.valid.test.ts
  packages/workers-shared/utils/types.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/package.json
  packages/wrangler/src/assets.ts
  packages/wrangler/src/miniflare-cli/assets.ts
  packages/wrangler/src/sites.ts
  packages/wrangler/src/utils/filesystem.ts
  pnpm-lock.yaml
Labels: e2e

#8392 fix: retry zone and route lookup API calls
  .changeset/wise-taxes-strive.md
  packages/wrangler/src/assets.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/pages/upload.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/zones.ts
Labels: e2e

#8383 fix(wrangler): Make kv bulk put --local respect base64:true
  .changeset/chatty-glasses-drum.md
  packages/wrangler/src/__tests__/kv.local.test.ts
  packages/wrangler/src/kv/index.ts
Labels: e2e

#8414 fix wrangler version in the vite plugin playground
  packages/vite-plugin-cloudflare/playground/dynamic-import-paths/package.json
  pnpm-lock.yaml
Labels: no-changeset-required

#8417 fix `test:ci` should not watch file changes locally
  packages/workflows-shared/package.json
Labels: no-changeset-required

#8416 Sync the preset with `unenv@2.0.0-rc.14`
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/perf_hooks.ts
  pnpm-lock.yaml
Labels: no-changeset-required

#8424 fix outdated files in the dist folder of 2.0.1 release
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
Labels: no-changeset-required

#8384 test: add e2e tests of the build+preview use case
  packages/vite-plugin-cloudflare/e2e/README.md
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
  packages/vite-plugin-cloudflare/e2e/global-setup.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
Labels: no-changeset-required

#8434 Revert "test: add e2e tests of the build+preview use case"
  packages/vite-plugin-cloudflare/e2e/README.md
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
  packages/vite-plugin-cloudflare/e2e/global-setup.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required

#8439 chore: update changeset
  .changeset/thin-mails-live.md
Labels: no-changeset-required

#8440 .gitignore stuff
  .changeset/deep-owls-travel.md
  packages/create-cloudflare/src/__tests__/templates.test.ts
  packages/create-cloudflare/src/helpers/__tests__/args.test.ts
  packages/create-cloudflare/src/templates.ts
  packages/vite-plugin-cloudflare/README.md
Labels: c3-e2e

#8429 Try and make unstable dev dev registry more stable
  packages/wrangler/e2e/dev-registry.test.ts
Labels: e2e, skip-pr-description-validation

#8386 Version Packages
  .changeset/chatty-glasses-drum.md
  .changeset/deep-owls-travel.md
  .changeset/dependabot-update-8423.md
  .changeset/green-ties-sit.md
  .changeset/slow-numbers-spend.md
  .changeset/stupid-chicken-cry.md
  .changeset/tangy-lizards-vanish.md
  .changeset/thin-mails-live.md
  .changeset/thirty-emus-find.md
  .changeset/wild-mails-end.md
  .changeset/wise-taxes-strive.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8446 Version Packages
  .changeset/funny-pets-punch.md
  .changeset/itchy-walls-reply.md
  .changeset/major-remove-args-config.md
  .changeset/major-remove-d1-backups.md
  .changeset/major-remove-d1-deprecated-batch-size.md
  .changeset/major-remove-d1-migrations-alpha.md
  .changeset/major-remove-generate.md
  .changeset/major-remove-init.md
  .changeset/major-remove-legacy-assets.md
  .changeset/major-remove-publish.md
  .changeset/major-remove-version.md
  .changeset/nasty-kiwis-talk.md
  .changeset/node-compat-v4.md
  .changeset/proud-otters-bow.md
  .changeset/serious-teachers-marry.md
  .changeset/shiny-donkeys-act.md
  .changeset/slimy-pumpkins-tickle.md
  packages/kv-asset-handler/CHANGELOG.md
  packages/kv-asset-handler/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#7400 Automatically backport Wrangler patches to v3
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/open-v3-pr.ts
Labels: blocked, skip-pr-description-validation, v4

#8469 chore(vite-plugin): Add tests for promise pipelining
  packages/vite-plugin-cloudflare/playground/multi-worker/__tests__/multi-worker.spec.ts
  packages/vite-plugin-cloudflare/playground/multi-worker/worker-a/index.ts
  packages/vite-plugin-cloudflare/playground/multi-worker/worker-b/index.ts
Labels: no-changeset-required, vite-plugin

#8442 c3: pin C3 e2e tests to use the local version of create-cloudflare rather than latest
  packages/create-cloudflare/e2e-tests/helpers.ts
Labels: no-changeset-required, c3-e2e

#8485 Fix v3 maintenance
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/open-v3-pr.ts
Labels: skip-pr-description-validation

#8478 Add `wrangler types` support for importable env and `process.env`
  .changeset/green-shrimps-grab.md
  packages/wrangler/e2e/types.test.ts
  packages/wrangler/src/__tests__/process-env-populated.test.ts
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/process-env.ts
  packages/wrangler/src/type-generation/index.ts
Labels: e2e

#8463 Replace Cloudflare logo in React Vite example and add Cloudflare styles
  packages/create-cloudflare/templates/react/workers/js/src/App.css
  packages/create-cloudflare/templates/react/workers/js/src/assets/Cloudflare_Logo.svg
  packages/create-cloudflare/templates/react/workers/ts/src/App.css
  packages/create-cloudflare/templates/react/workers/ts/src/assets/Cloudflare_Logo.svg
Labels: skip-pr-description-validation, c3-e2e

#8433 Two minor chore fixes in the miniflare workflows test
  packages/miniflare/test/plugins/workflows/index.spec.ts
Labels: no-changeset-required

#8480 Add 'using' test
  fixtures/worker-app/src/explicit-resource-management.js
  fixtures/worker-app/src/index.js
  fixtures/worker-app/tests/index.test.ts
Labels: skip-pr-description-validation

#8490 More attempts to improve v3-maintenance
  tools/deployments/open-v3-pr.ts
Labels: skip-pr-description-validation

#8493 Remove v3 maintenance comments
  .github/workflows/open-v3-maintenance-prs.yml
Labels: skip-pr-description-validation

#8492 Use a shared Vectorize index for the Vectorize E2E tests
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
Labels: e2e, no-changeset-required

#8495 fix: Fix error in `open-v3-pr` script
  tools/deployments/open-v3-pr.ts
Labels: skip-pr-description-validation

#8491 fix c3 tests
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
Labels: no-changeset-required, c3-e2e

#8504 Backport #8503 to Wrangler v3
  .changeset/mighty-lies-see.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/assets.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8451 Update Next.js version in the experimental template
  .changeset/real-clocks-ask.md
  packages/create-cloudflare/templates-experimental/next/c3.ts
  packages/create-cloudflare/templates-experimental/next/templates/open-next.config.ts
  packages/create-cloudflare/templates-experimental/next/templates/wrangler.jsonc
Labels: c3, c3-e2e

#8506 Add `MINIFLARE_WORKERD_PATH` to more places in turbo
  packages/miniflare/turbo.json
  turbo.json
Labels: skip-pr-description-validation

#8520 backport vectorize e2e changes
  .github/workflows/test-and-check.yml
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  packages/wrangler/e2e/helpers/normalize.ts
  packages/wrangler/e2e/types.test.ts
Labels: e2e, skip-pr-description-validation

#8521 backport #8472 to v3
  .changeset/cute-pianos-joke.md
  packages/wrangler/src/check/commands.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8524 Don't publish downstream packages of Wrangler & Miniflare from the v3 branch
  .changeset/config.json
  .github/workflows/c3-dependabot-versioning-prs.yml
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  packages/wrangler/e2e/c3-integration.test.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required

#8527 Use private packages
  fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/package.json
  tools/deployments/__tests__/validate-changesets.test.ts
Labels: skip-pr-description-validation

#8531 Remove ignored packages
  .changeset/config.json
Labels: skip-pr-description-validation

#8532 Skip Vite E2E for v3 branch
  .github/workflows/e2e.yml
Labels: skip-pr-description-validation

#8401 Support `no_bundle` config in Pages for both `dev` and `deploy`.
  .changeset/crazy-sheep-give.md
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/config/validation-pages.ts
  packages/wrangler/src/pages/deploy.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#8453 v3 Maintenance Release
  .changeset/beige-kings-wash.md
  .changeset/crazy-sheep-give.md
  .changeset/cute-pianos-joke.md
  .changeset/mighty-lies-see.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8488 Version Packages
  .changeset/c3-frameworks-update-8418.md
  .changeset/c3-frameworks-update-8420.md
  .changeset/crazy-sheep-give.md
  .changeset/cute-pianos-joke.md
  .changeset/dependabot-update-8452.md
  .changeset/evil-tools-accept.md
  .changeset/fuzzy-regions-post.md
  .changeset/green-shrimps-grab.md
  .changeset/mighty-lies-see.md
  .changeset/real-clocks-ask.md
  .changeset/wise-points-love.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e, skip-v3-pr

#8523 [vite-plugin] add validation for the Wrangler config `main` field
  .changeset/evil-terms-teach.md
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/incorrect-dir-main-wrangler.toml
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/index.ts
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/non-existing-main-wrangler.toml
  packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
  packages/vite-plugin-cloudflare/src/workers-configs.ts
  packages/vite-plugin-cloudflare/tsconfig.plugin.json
Labels: vite-plugin

#8505 Support Wrangler v4 as peer dependency
  .changeset/chubby-bats-start.md
  packages/vite-plugin-cloudflare/package.json
Labels: vite-plugin

#8357 feat: add new `unsafeInspectorProxy` option to miniflare
  .changeset/little-spiders-sell.md
  packages/miniflare/package.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/core/inspector-proxy/devtools.ts
  packages/miniflare/src/plugins/core/inspector-proxy/index.ts
  packages/miniflare/src/plugins/core/inspector-proxy/inspector-proxy-controller.ts
  packages/miniflare/src/plugins/core/inspector-proxy/inspector-proxy.ts
  packages/miniflare/src/shared/error.ts
  packages/miniflare/test/plugins/core/inspector-proxy/index.spec.ts
  pnpm-lock.yaml
Labels: e2e

#8515 Set `target` in `optimizeDeps.esbuildOptions`
  .changeset/nasty-bars-sniff.md
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Labels: vite-plugin

#8525 Use `coupleWebSocket` function from Miniflare
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/websockets.ts
Labels: no-changeset-required, vite-plugin

#8496 Add tests for _headers and _redirects in preview
  packages/vite-plugin-cloudflare/playground/__test-utils__/responses.ts
  packages/vite-plugin-cloudflare/playground/static-mpa/__tests__/assets.spec.ts
  packages/vite-plugin-cloudflare/playground/static-mpa/public/_headers
  packages/vite-plugin-cloudflare/playground/static-mpa/public/_redirects
  packages/vite-plugin-cloudflare/playground/static-mpa/public/text-file.txt
  packages/vite-plugin-cloudflare/src/index.ts
Labels: no-changeset-required, vite-plugin

#8514 Use the native implementation of `node:tls`
  .changeset/loud-crabs-remain.md
  .changeset/small-pigs-marry.md
  fixtures/nodejs-hybrid-app/src/index.ts
  fixtures/nodejs-hybrid-app/tests/index.test.ts
  packages/unenv-preset/package.json
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/tls.ts
  pnpm-lock.yaml
Labels: e2e

#8379 chore: graduate hello world workers + assets templates
  .changeset/angry-parents-post.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/helpers/cli.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/hello-world-assets-only/c3.ts
  packages/create-cloudflare/templates/hello-world-assets-only/templates/package.json
  packages/create-cloudflare/templates/hello-world-assets-only/templates/public/index.html
  packages/create-cloudflare/templates/hello-world-assets-only/templates/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/c3.ts
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/.editorconfig
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/.gitignore
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/.prettierrc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/package.json
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/public/index.html
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/src/index.js
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/.editorconfig
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/.gitignore
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/.prettierrc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/package.json
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/public/index.html
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/src/index.ts
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/tsconfig.json
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object/c3.ts
  packages/create-cloudflare/templates/hello-world-with-assets/c3.ts
  packages/create-cloudflare/templates/hello-world-with-assets/js/.editorconfig
  packages/create-cloudflare/templates/hello-world-with-assets/js/.gitignore
  packages/create-cloudflare/templates/hello-world-with-assets/js/.prettierrc
  packages/create-cloudflare/templates/hello-world-with-assets/js/package.json
  packages/create-cloudflare/templates/hello-world-with-assets/js/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/js/src/index.js
  packages/create-cloudflare/templates/hello-world-with-assets/js/test/index.spec.js
  packages/create-cloudflare/templates/hello-world-with-assets/js/vitest.config.js
  packages/create-cloudflare/templates/hello-world-with-assets/js/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-with-assets/py/.gitignore
  packages/create-cloudflare/templates/hello-world-with-assets/py/package.json
  packages/create-cloudflare/templates/hello-world-with-assets/py/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/py/src/entry.py
  packages/create-cloudflare/templates/hello-world-with-assets/py/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-with-assets/ts/.editorconfig
  packages/create-cloudflare/templates/hello-world-with-assets/ts/.gitignore
  packages/create-cloudflare/templates/hello-world-with-assets/ts/.prettierrc
  packages/create-cloudflare/templates/hello-world-with-assets/ts/package.json
  packages/create-cloudflare/templates/hello-world-with-assets/ts/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/ts/src/index.ts
  packages/create-cloudflare/templates/hello-world-with-assets/ts/test/index.spec.ts
  packages/create-cloudflare/templates/hello-world-with-assets/ts/test/tsconfig.json
  packages/create-cloudflare/templates/hello-world-with-assets/ts/tsconfig.json
  packages/create-cloudflare/templates/hello-world-with-assets/ts/vitest.config.mts
  packages/create-cloudflare/templates/hello-world-with-assets/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/hello-world-with-assets/ts/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world/c3.ts
  packages/wrangler/e2e/c3-integration.test.ts
Labels: e2e, c3-e2e

#8508 chore: add v3 backport to PR checklist
  .github/pull_request_template.md
  tools/deployments/__tests__/validate-pr-description.test.ts
  tools/deployments/validate-pr-description.ts
Labels: no-changeset-required

#8547 Release `@cloudflare/unenv-preset@2.1.0`
  .changeset/loud-crabs-remain.md
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
Labels: no-changeset-required, skip-v3-pr

#8549 Don't error on removed changesets in PRs
  tools/deployments/open-v3-pr.ts
Labels: skip-pr-description-validation

#8557 Collapse C3 E2E jobs
  .github/workflows/c3-e2e.yml
Labels: skip-pr-description-validation, c3-e2e

#8540 Version Packages
  .changeset/angry-parents-post.md
  .changeset/chilly-knives-itch.md
  .changeset/chubby-bats-start.md
  .changeset/common-paws-invite.md
  .changeset/evil-terms-teach.md
  .changeset/lazy-ghosts-report.md
  .changeset/little-spiders-sell.md
  .changeset/nasty-bars-sniff.md
  .changeset/silly-dragons-doubt.md
  .changeset/small-pigs-marry.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8402 graduate astro + workers template
  .changeset/pink-crews-throw.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates-experimental/astro/templates/js/public/.assetsignore
  packages/create-cloudflare/templates-experimental/astro/templates/ts/public/.assetsignore
  packages/create-cloudflare/templates/astro/c3.ts
  packages/create-cloudflare/templates/astro/pages/c3.ts
  packages/create-cloudflare/templates/astro/pages/templates/js/wrangler.jsonc
  packages/create-cloudflare/templates/astro/pages/templates/ts/src/env.d.ts
  packages/create-cloudflare/templates/astro/pages/templates/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/astro/pages/templates/ts/wrangler.jsonc
  packages/create-cloudflare/templates/astro/workers/c3.ts
  packages/create-cloudflare/templates/astro/workers/templates/js/public/.assetsignore
  packages/create-cloudflare/templates/astro/workers/templates/js/wrangler.jsonc
  packages/create-cloudflare/templates/astro/workers/templates/ts/public/.assetsignore
  packages/create-cloudflare/templates/astro/workers/templates/ts/src/env.d.ts
  packages/create-cloudflare/templates/astro/workers/templates/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/astro/workers/templates/ts/wrangler.jsonc
Labels: c3-e2e

#8550 Bump `@cloudflare/unenv-preset` to 2.2.0
  .changeset/vast-plums-invite.md
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/deploy.test.ts
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#8460 Update the C3 Durable Objects example to use SQLite
  .changeset/chilled-moons-enjoy.md
  packages/create-cloudflare/templates/hello-world-durable-object/js/src/index.js
  packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts
  packages/create-cloudflare/templates/hello-world-durable-object/ts/wrangler.jsonc
Labels: awaiting reporter response, skip-pr-description-validation, c3-e2e

#8443 asset-worker support for SPA mode
  .changeset/all-mugs-give.md
  fixtures/asset-config/html-handling.test.ts
  fixtures/asset-config/redirects.test.ts
  fixtures/asset-config/url-normalization.test.ts
  packages/workers-shared/asset-worker/src/analytics.ts
  packages/workers-shared/asset-worker/src/compatibility-flags.ts
  packages/workers-shared/asset-worker/src/configuration.ts
  packages/workers-shared/asset-worker/src/handler.ts
  packages/workers-shared/asset-worker/src/index.ts
  packages/workers-shared/asset-worker/tests/compatibility-flags.test.ts
  packages/workers-shared/asset-worker/tests/handler.test.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8552 chore: graduate workers + assets remix template
  .changeset/silent-trees-shout.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/remix/c3.ts
  packages/create-cloudflare/templates/remix/pages/c3.ts
  packages/create-cloudflare/templates/remix/pages/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/remix/pages/templates/wrangler.jsonc
  packages/create-cloudflare/templates/remix/workers/c3.ts
  packages/create-cloudflare/templates/remix/workers/templates/public/.assetsignore
  packages/create-cloudflare/templates/remix/workers/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/remix/workers/templates/wrangler.toml
Labels: c3-e2e

#8501 wrangler support for SPA mode
  .changeset/fine-jars-lick.md
  fixtures/workers-with-assets-spa/README.md
  fixtures/workers-with-assets-spa/package.json
  fixtures/workers-with-assets-spa/public/index.html
  fixtures/workers-with-assets-spa/public/shadowed-by-asset.txt
  fixtures/workers-with-assets-spa/src/index.ts
  fixtures/workers-with-assets-spa/tests/__image_snapshots__/index-test-ts-workers-assets-spa-renders-the-homepage-in-a-browser-correctly-1-snap.png
  fixtures/workers-with-assets-spa/tests/index.test.ts
  fixtures/workers-with-assets-spa/tests/tsconfig.json
  fixtures/workers-with-assets-spa/tsconfig.json
  fixtures/workers-with-assets-spa/wrangler.toml
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/assets/schema.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/vite-plugin-cloudflare/playground/package.json
  packages/wrangler/src/assets.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: skip-pr-description-validation

#8436 test: add e2e tests of the build+preview use case (un-revert of #8384)
  packages/vite-plugin-cloudflare/e2e/README.md
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
  packages/vite-plugin-cloudflare/e2e/global-setup.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
Labels: e2e, no-changeset-required

#8365 vite-plugin: update unenv preset dependency
  .changeset/cold-baths-knock.md
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  pnpm-lock.yaml
Labels: e2e, vite-plugin, c3-e2e

#8534 Improve the error messaging when the user provides neither an entry point nor an asset directory
  .changeset/rude-socks-glow.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/deployment-bundle/entry.ts
Labels: e2e

#8387 Support Text and Data module types
  .changeset/silver-rooms-hear.md
  packages/vite-plugin-cloudflare/playground/additional-modules/README.md
  packages/vite-plugin-cloudflare/playground/additional-modules/__tests__/additional-modules.spec.ts
  packages/vite-plugin-cloudflare/playground/additional-modules/package.json
  packages/vite-plugin-cloudflare/playground/additional-modules/src/index.ts
  packages/vite-plugin-cloudflare/playground/additional-modules/src/modules/bin-example.bin
  packages/vite-plugin-cloudflare/playground/additional-modules/src/modules/html-example.html
  packages/vite-plugin-cloudflare/playground/additional-modules/src/modules/text-example.txt
  packages/vite-plugin-cloudflare/playground/additional-modules/src/modules/wasm-example.wasm
  packages/vite-plugin-cloudflare/playground/additional-modules/tsconfig.json
  packages/vite-plugin-cloudflare/playground/additional-modules/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/additional-modules/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/additional-modules/turbo.json
  packages/vite-plugin-cloudflare/playground/additional-modules/vite.config.ts
  packages/vite-plugin-cloudflare/playground/additional-modules/wrangler.toml
  packages/vite-plugin-cloudflare/playground/wasm/README.md
  packages/vite-plugin-cloudflare/playground/wasm/__tests__/wasm.spec.ts
  packages/vite-plugin-cloudflare/playground/wasm/src/index.ts
  packages/vite-plugin-cloudflare/src/__tests__/get-warning-for-workers-resolved-configs.spec.ts
  packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
  packages/vite-plugin-cloudflare/src/additional-modules.ts
  packages/vite-plugin-cloudflare/src/constants.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/runner-worker/module-runner.ts
  packages/vite-plugin-cloudflare/src/shared.ts
  packages/vite-plugin-cloudflare/src/utils.ts
  packages/vite-plugin-cloudflare/src/workers-configs.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8376 feat(miniflare): Implement Assets RPC Proxy Worker behaviour
  .changeset/real-jobs-own.md
  fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
  fixtures/workers-with-assets-and-service-bindings/vitest.config.mts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/workerD.util.ts
  fixtures/workers-with-assets-and-service-bindings/workerB-with-default-export/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerC-with-default-entrypoint/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerD-with-named-entrypoint/src/index.ts
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
  packages/wrangler/e2e/assets-multiworker.test.ts
Labels: e2e, skip-v3-pr

#8592 fix PR template
  .github/pull_request_template.md
Labels: no-changeset-required

#8455 test: add console log "grouping" to Wrangler e2e tests
  tools/e2e/runIndividualE2EFiles.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required

#8574 chore: graduate svelte workers assets template
  .changeset/stupid-crews-crash.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates-experimental/svelte/templates/static/.assetsignore
  packages/create-cloudflare/templates/svelte/c3.ts
  packages/create-cloudflare/templates/svelte/pages/c3.ts
  packages/create-cloudflare/templates/svelte/pages/templates/wrangler.jsonc
  packages/create-cloudflare/templates/svelte/workers/c3.ts
  packages/create-cloudflare/templates/svelte/workers/templates/static/.assetsignore
  packages/create-cloudflare/templates/svelte/workers/templates/wrangler.jsonc
Labels: c3-e2e

#8587 Add Wasm helper
  .changeset/eighty-glasses-talk.md
  packages/vite-plugin-cloudflare/playground/additional-modules/__tests__/additional-modules.spec.ts
  packages/vite-plugin-cloudflare/playground/additional-modules/src/index.ts
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#8528 Support wrangler types for Pipelines
  .changeset/swift-beers-battle.md
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/type-generation/index.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8272 Adds Python print e2e test again.
  packages/wrangler/e2e/dev.test.ts
Labels: e2e

#8535 Backport #8534 to Wrangler v3
  .changeset/rude-socks-glow.md
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/deployment-bundle/entry.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8109 chore: include banner in output of tests for commands with json/pretty mode
  packages/wrangler/src/__tests__/d1/execute.test.ts
  packages/wrangler/src/__tests__/d1/info.test.ts
  packages/wrangler/src/__tests__/d1/list.test.ts
  packages/wrangler/src/__tests__/d1/timeTravel.test.ts
  packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
  packages/wrangler/src/__tests__/tail.test.ts
Labels: skip-pr-description-validation, no-changeset-required

#8609 Revert Vite E2E
  packages/vite-plugin-cloudflare/e2e/README.md
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
  packages/vite-plugin-cloudflare/e2e/global-setup.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
Labels: e2e, skip-pr-description-validation

#8571 Version Packages
  .changeset/all-mugs-give.md
  .changeset/chilled-moons-enjoy.md
  .changeset/cold-baths-dance.md
  .changeset/cold-baths-knock.md
  .changeset/crazy-groups-lie.md
  .changeset/dependabot-update-8591.md
  .changeset/eighty-glasses-talk.md
  .changeset/fine-jars-lick.md
  .changeset/four-shirts-know.md
  .changeset/lemon-areas-tap.md
  .changeset/orange-gifts-cover.md
  .changeset/pink-crews-throw.md
  .changeset/plenty-bats-jog.md
  .changeset/polite-walls-bathe.md
  .changeset/quiet-wombats-lead.md
  .changeset/real-jobs-own.md
  .changeset/red-cow-eats.md
  .changeset/rotten-monkeys-tan.md
  .changeset/rude-socks-glow.md
  .changeset/silent-trees-shout.md
  .changeset/silver-rooms-hear.md
  .changeset/stupid-crews-crash.md
  .changeset/swift-beers-battle.md
  .changeset/vast-plums-invite.md
  .changeset/warm-forks-visit.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8594 fix(miniflare): Simplify `RpcProxyWorker` and add more fixture tests
  .changeset/thick-bars-sing.md
  fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/workerB.util.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/workerC.util.ts
  fixtures/workers-with-assets-and-service-bindings/workerA/src/workerD.util.ts
  fixtures/workers-with-assets-and-service-bindings/workerB-with-default-export/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerC-with-default-entrypoint/src/index.ts
  fixtures/workers-with-assets-and-service-bindings/workerD-with-named-entrypoint/src/index.ts
  packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
Labels: e2e

#8382 feat(wrangler): Add Secrets Store support
  .changeset/soft-buses-sniff.md
  packages/wrangler/e2e/secrets-store.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/secrets-store.test.ts
  packages/wrangler/src/__tests__/user.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/secrets-store/client.ts
  packages/wrangler/src/secrets-store/commands.ts
  packages/wrangler/src/secrets-store/index.ts
  packages/wrangler/src/user/user.ts
Labels: e2e, skip-pr-description-validation, skip-v3-pr

#8608 [vite-plugin] export `PluginConfig` type
  .changeset/short-hats-add.md
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#8607 chore: remove unused `~utils` alias in vite-plugin-cloudflare playground
  packages/vite-plugin-cloudflare/playground/vitest.config.e2e.ts
Labels: no-changeset-required, vite-plugin

#8597 feat: Graduate experimental RPC support for Workers with assets in local dev
  .changeset/orange-beans-run.md
  fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
  fixtures/workers-with-assets-only/tests/index.test.ts
  fixtures/workers-with-assets-run-worker-first/tests/index.test.ts
  fixtures/workers-with-assets-spa/tests/index.test.ts
  fixtures/workers-with-assets/tests/index.test.ts
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/src/plugins/shared/index.ts
  packages/vitest-pool-workers/src/pool/config.ts
  packages/wrangler/e2e/assets-multiworker.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/experimental-flags.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/versions/upload.ts
Labels: e2e

#8598 chore: graduate qwik + assets template
  .changeset/fresh-icons-hide.md
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config-experimental.ts
  packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/qwik/c3.ts
  packages/create-cloudflare/templates/qwik/pages/c3.ts
  packages/create-cloudflare/templates/qwik/pages/snippets/getPlatformProxy.ts
  packages/create-cloudflare/templates/qwik/pages/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/qwik/pages/templates/wrangler.jsonc
  packages/create-cloudflare/templates/qwik/workers/c3.ts
  packages/create-cloudflare/templates/qwik/workers/snippets/getPlatformProxy.ts
  packages/create-cloudflare/templates/qwik/workers/templates/public/.assetsignore
  packages/create-cloudflare/templates/qwik/workers/templates/worker-configuration.d.ts
  packages/create-cloudflare/templates/qwik/workers/templates/wrangler.jsonc
Labels: c3-e2e

#8621 Remove assets compat flag gate
  packages/miniflare/src/plugins/core/index.ts
Labels: skip-pr-description-validation, no-changeset-required

#8606 feat: implement local dev for createBatch
  .changeset/olive-dodos-judge.md
  fixtures/workflow/src/index.ts
  fixtures/workflow/tests/index.test.ts
  packages/workflows-shared/src/binding.ts
Labels: e2e

#8615 Reduce E2E flakes
  .github/workflows/e2e.yml
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/vitest.config.mts
  packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts
Labels: e2e, skip-pr-description-validation

#8507 [vite-plugin] fix: make sure that internal variables are not exposed in the importable `env` object
  .changeset/smart-jars-guess.md
  packages/vite-plugin-cloudflare/playground/importable-env/.dev.vars
  packages/vite-plugin-cloudflare/playground/importable-env/.gitignore
  packages/vite-plugin-cloudflare/playground/importable-env/__tests__/env-entries.spec.ts
  packages/vite-plugin-cloudflare/playground/importable-env/package.json
  packages/vite-plugin-cloudflare/playground/importable-env/src/index.ts
  packages/vite-plugin-cloudflare/playground/importable-env/tsconfig.json
  packages/vite-plugin-cloudflare/playground/importable-env/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/importable-env/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/importable-env/turbo.json
  packages/vite-plugin-cloudflare/playground/importable-env/vite.config.ts
  packages/vite-plugin-cloudflare/playground/importable-env/wrangler.toml
  packages/vite-plugin-cloudflare/src/runner-worker/module-runner.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8575 feat: add endpoint for workflow deletion
  .changeset/floppy-snails-fetch.md
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/workflows/commands/delete.ts
Labels: e2e

#8632 Disable C3 Bun tests
  .github/workflows/c3-e2e.yml
Labels: skip-pr-description-validation, c3-e2e

#8613 Version Packages
  .changeset/dependabot-update-8618.md
  .changeset/eight-cars-fall.md
  .changeset/floppy-snails-fetch.md
  .changeset/fresh-icons-hide.md
  .changeset/many-wolves-yell.md
  .changeset/olive-dodos-judge.md
  .changeset/orange-beans-run.md
  .changeset/short-hats-add.md
  .changeset/smart-jars-guess.md
  .changeset/soft-buses-sniff.md
  .changeset/thick-bars-sing.md
  .changeset/wicked-eels-exist.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8604 Amend `pages dev` error message when an environment is requested
  .changeset/legal-camels-dance.md
  packages/wrangler/src/__tests__/pages/dev.test.ts
  packages/wrangler/src/pages/dev.ts
Labels: e2e

#8610 Update DO + assets template to use sqlite
  .changeset/lazy-beers-teach.md
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/src/index.js
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/src/index.ts
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/worker-configuration.d.ts
  packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/wrangler.jsonc
  packages/create-cloudflare/templates/hello-world-durable-object/ts/worker-configuration.d.ts
Labels: c3-e2e

#8644 refactor: pass the request through the asset-worker `exists` and `getByETag` functions
  packages/workers-shared/asset-worker/src/handler.ts
  packages/workers-shared/asset-worker/src/index.ts
Labels: e2e, no-changeset-required

#8654 Small testing fixups
  fixtures/d1-worker-app/vitest.config.mts
  fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
Labels: no-changeset-required

#8656 fix(create-cloudflare): improve html semantics from c3 init
  .changeset/fluffy-icons-pump.md
  packages/create-cloudflare/templates/hello-world-with-assets/js/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/py/public/index.html
  packages/create-cloudflare/templates/hello-world-with-assets/ts/public/index.html
Labels: c3-e2e

#8432 Metafiles support in vite-plugin-cloudflare
  .changeset/deep-symbols-heal.md
  packages/vite-plugin-cloudflare/playground/react-spa/__tests__/assets.spec.ts
  packages/vite-plugin-cloudflare/playground/react-spa/__tests__/experimental-headers-and-redirects/assets.spec.ts
  packages/vite-plugin-cloudflare/playground/react-spa/public/_headers
  packages/vite-plugin-cloudflare/playground/react-spa/public/_redirects
  packages/vite-plugin-cloudflare/playground/react-spa/public/file.txt
  packages/vite-plugin-cloudflare/playground/react-spa/public/redirect.svg
  packages/vite-plugin-cloudflare/playground/react-spa/public/rewrite.svg
  packages/vite-plugin-cloudflare/playground/react-spa/public/target.svg
  packages/vite-plugin-cloudflare/playground/react-spa/vite.config.experimental-headers-and-redirects.ts
  packages/vite-plugin-cloudflare/src/asset-config.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/workers-shared/utils/configuration/constructConfiguration.ts
  packages/workers-shared/utils/configuration/parseHeaders.ts
  packages/workers-shared/utils/configuration/parseRedirects.ts
  packages/workers-shared/utils/tsconfig.json
Labels: e2e, skip-pr-description-validation

#8625 Provide more informative error messages for Workers CI tag validation
  packages/wrangler/src/__tests__/match-tag.test.ts
  packages/wrangler/src/environment-variables/misc-variables.ts
  packages/wrangler/src/match-tag.ts
Labels: no-changeset-required

#8662 Backport #8604 to Wrangler v3
  .changeset/legal-camels-dance.md
  packages/wrangler/src/__tests__/pages/dev.test.ts
  packages/wrangler/src/pages/dev.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8647 Version Packages
  .changeset/c3-frameworks-update-8516.md
  .changeset/c3-frameworks-update-8518.md
  .changeset/cute-plants-wash.md
  .changeset/deep-symbols-heal.md
  .changeset/dependabot-update-8650.md
  .changeset/early-maps-make.md
  .changeset/few-parts-tell.md
  .changeset/fluffy-icons-pump.md
  .changeset/lazy-beers-teach.md
  .changeset/legal-camels-dance.md
  .changeset/short-dryers-look.md
  .changeset/tangy-streets-attack.md
  .changeset/vast-rockets-swim.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8620 feat(wrangler): Add Bulk Key Get command to KV
  .changeset/modern-parts-check.md
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/kv.local.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/kv/helpers.ts
  packages/wrangler/src/kv/index.ts
Labels: e2e

#8675 Bump `@cloudflare/unenv-preset` to 2.3.1
  .changeset/green-donuts-run.md
  fixtures/nodejs-hybrid-app/src/index.ts
  packages/wrangler/package.json
  pnpm-lock.yaml
Labels: e2e, skip-v3-pr

#8435 fix: include asset binding when printing binding summary
  .changeset/chatty-rockets-call.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e, skip-pr-description-validation

#8602 v3 Maintenance Release
  .changeset/legal-camels-dance.md
  .changeset/rude-socks-glow.md
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8693 Fix Workers KV ownership
  CODEOWNERS
Labels: skip-pr-description-validation

#8207 vite-plugin: show warning if the user has forgotten to turn on nodejs_compat
  .changeset/loud-worlds-ask.md
  packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts
  packages/vite-plugin-cloudflare/playground/node-compat/package.json
  packages/vite-plugin-cloudflare/playground/node-compat/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-warnings.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-warnings/index.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-warnings/wrangler.toml
  packages/vite-plugin-cloudflare/playground/package.json
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  pnpm-lock.yaml
Labels: e2e

#8683 Backport #8666 to Wrangler v3
  .changeset/violet-ravens-draw.md
  packages/miniflare/src/plugins/core/modules.ts
  packages/miniflare/src/runtime/config/workerd.ts
  packages/miniflare/test/fixtures/modules/index.node.cjs
  packages/miniflare/test/plugins/core/modules.spec.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/deployment-bundle/worker.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8666 Remove `NodeJSCompatModule`
  .changeset/violet-ravens-draw.md
  packages/miniflare/src/plugins/core/modules.ts
  packages/miniflare/src/runtime/config/workerd.ts
  packages/miniflare/test/fixtures/modules/index.node.cjs
  packages/miniflare/test/plugins/core/modules.spec.ts
  packages/vitest-pool-workers/src/pool/index.ts
  packages/vitest-pool-workers/src/pool/module-fallback.ts
  packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/module-collection.ts
  packages/wrangler/src/deployment-bundle/worker.ts
Labels: e2e

#8704 Revert "[wrangler] Wrangler pages deployments list - added ID to output"
  .changeset/lemon-dragons-glow.md
  packages/wrangler/src/pages/deployments.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8695 Version Packages
  .changeset/cute-dragons-worry.md
  .changeset/funny-eggs-divide.md
  .changeset/loud-worlds-ask.md
  .changeset/violet-ravens-draw.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8703 Backport #8583 to Wrangler v3
  .changeset/good-taxis-repeat.md
  packages/wrangler/src/__tests__/hyperdrive.test.ts
  packages/wrangler/src/hyperdrive/list.ts
  packages/wrangler/src/hyperdrive/shared.ts
Labels: skip-pr-description-validation, skip-v3-pr

#8706 Add X-Forwarded-Host header to requests
  .changeset/common-baths-fold.md
  packages/vite-plugin-cloudflare/playground/worker/__tests__/worker.spec.ts
  packages/vite-plugin-cloudflare/playground/worker/src/index.ts
  packages/vite-plugin-cloudflare/src/utils.ts
Labels: vite-plugin

#8395 remove `Application Starter` option in C3 experimental menu
  .changeset/metal-shoes-cut.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/src/helpers/args.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates/common/c3.ts
  packages/create-cloudflare/templates/hello-world-durable-object/c3.ts
  packages/create-cloudflare/templates/hello-world-with-assets/c3.ts
  packages/create-cloudflare/templates/openapi/c3.ts
  packages/create-cloudflare/templates/pre-existing/c3.ts
  packages/create-cloudflare/templates/queues/c3.ts
  packages/create-cloudflare/templates/scheduled/c3.ts
Labels: c3-e2e

#8710 Version Packages
  .changeset/common-baths-fold.md
  .changeset/good-taxis-repeat.md
  .changeset/metal-shoes-cut.md
  .changeset/tangy-camels-write.md
  .changeset/warm-poets-feel.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8572 [vite-plugin] add validation for `configPath`s
  .changeset/sharp-dogs-love.md
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/index.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/vite.config.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/wrangler.toml
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config/vite.config.ts
  packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/empty-dir.toml/.gitkeep
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/empty-dir/.gitkeep
  packages/vite-plugin-cloudflare/src/__tests__/fixtures/wrangler.toml
  packages/vite-plugin-cloudflare/src/__tests__/get-validated-wrangler-config-path.spec.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
  packages/vite-plugin-cloudflare/src/workers-configs.ts
Labels: vite-plugin

#8705 chore: improve backport PR creation and PR template text
  .github/pull_request_template.md
  .github/workflows/open-v3-maintenance-prs.yml
  tools/deployments/open-v3-pr.ts
Labels: skip-pr-description-validation, no-changeset-required

#8736 chore: fix vite-plugin e2es using non existent `viteCommand` function
  packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
Labels: e2e, no-changeset-required, vite-plugin
