Repository cloudflare/workers-sdk, pull requests merged in 2025-02, with the labels that each got.

#7968 chore: configure pnpm to use the version specified in package.json engines field
  .npmrc
Labels: no-changeset-required

#7982 test: log the C3 e2e log file to the console when a test fails
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
Labels: no-changeset-required

#7995 Fix Workers Shared Production deploy workflow
  .github/workflows/workers-shared-deploy-production.yml
Labels: no-changeset-required

#8018 test: add sleep to try to lower flakyness of test
  packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
Labels: skip-pr-description-validation, no-changeset-required

#7992 Version Packages
  .changeset/c3-frameworks-update-8005.md
  .changeset/c3-frameworks-update-8006.md
  .changeset/c3-frameworks-update-8007.md
  .changeset/cuddly-bees-allow.md
  .changeset/early-grapes-care.md
  .changeset/thin-countries-clean.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7902 Implement verdaccio local npm registry for vitest-pool-workers tests
  .vscode/settings.json
  packages/create-cloudflare/e2e-tests/global-setup.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
  packages/create-cloudflare/package.json
  packages/create-cloudflare/turbo.json
  packages/create-cloudflare/vitest-e2e.config.mts
  packages/eslint-config-worker/index.js
  packages/mock-npm-registry/.eslintrc.cjs
  packages/mock-npm-registry/README.md
  packages/mock-npm-registry/package.json
  packages/mock-npm-registry/src/index.ts
  packages/mock-npm-registry/tsconfig.json
  packages/mock-npm-registry/turbo.json
  packages/vitest-pool-workers/package.json
  packages/vitest-pool-workers/test/README.md
  packages/vitest-pool-workers/test/global-setup.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
  pnpm-lock.yaml
  turbo.json
Labels: no-changeset-required

#8017 Fix asset-worker analytics not sending on success
  packages/workers-shared/asset-worker/src/index.ts
Labels: no-changeset-required

#7769 Refactor pipelines commands into separate files, rename some options
  .changeset/plenty-birds-melt.md
  .changeset/short-kids-hunt.md
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/pipelines/cli/create.ts
  packages/wrangler/src/pipelines/cli/delete.ts
  packages/wrangler/src/pipelines/cli/list.ts
  packages/wrangler/src/pipelines/cli/show.ts
  packages/wrangler/src/pipelines/cli/update.ts
  packages/wrangler/src/pipelines/client.ts
  packages/wrangler/src/pipelines/index.ts
  packages/wrangler/src/pipelines/validate.ts
Labels: caretaking

#8012 Use fetchPagedListResult when listing Hyperdrive configs from API
  .changeset/smooth-games-cover.md
  packages/wrangler/src/hyperdrive/client.ts
Labels: caretaking

#8008 Add support for Images bindings, with dynamic Sharp import
  .changeset/ninety-donuts-warn.md
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/package.json
  packages/wrangler/scripts/deps.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/__tests__/tsconfig.json
  packages/wrangler/src/__tests__/type-generation.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/startDevWorker/ConfigController.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/api/startDevWorker/utils.ts
  packages/wrangler/src/config/config.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/deployment-bundle/bindings.ts
  packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
  packages/wrangler/src/deployment-bundle/worker.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/dev/miniflare.ts
  packages/wrangler/src/images/fetcher.ts
  packages/wrangler/src/images/local.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/secret/index.ts
  packages/wrangler/src/utils/print-bindings.ts
  pnpm-lock.yaml
Labels: e2e, caretaking

#7819 chore: refactor wrangler secrets commands
  packages/wrangler/src/index.ts
  packages/wrangler/src/secret/index.ts
Labels: no-changeset-required

#8028 feat: add some logging when no bindings are found
  .changeset/sharp-carrots-deliver.md
  packages/wrangler/e2e/deployments.test.ts
  packages/wrangler/e2e/versions.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e

#8035 test: fix snapshot
  packages/wrangler/src/__tests__/deploy.test.ts
Labels: skip-pr-description-validation, no-changeset-required

#8025 test: run unenv-preset tests on Windows
  packages/unenv-preset/tests/index.test.ts
Labels: no-changeset-required

#8038 Require admin review on changes to Wrangler & Miniflare dependencies
  CODEOWNERS
Labels: skip-pr-description-validation

#8048 chore: change some `asserts` to UserErrors so they don't get reported to sentry
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/triggers/deploy.ts
  packages/wrangler/src/versions/deploy.ts
  packages/wrangler/src/versions/deployments/list.ts
  packages/wrangler/src/versions/deployments/status.ts
  packages/wrangler/src/versions/list.ts
  packages/wrangler/src/versions/rollback/index.ts
  packages/wrangler/src/versions/upload.ts
  packages/wrangler/src/versions/view.ts
Labels: no-changeset-required

#7986 Better messaging in dev console
  .changeset/light-taxis-move.md
  packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
  packages/wrangler/e2e/pages-dev.test.ts
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/logger.ts
  packages/wrangler/src/utils/print-bindings.ts
Labels: e2e

#8050 chore: pin Miniflare deps
  packages/miniflare/package.json
  pnpm-lock.yaml
Labels: e2e, skip-pr-description-validation

#8060 chore: use node 18.20.6 in CI
  .github/actions/install-dependencies/action.yml
Labels: e2e, caretaking, no-changeset-required

#7290 fix: allow assets in multiworker setup
  .changeset/poor-otters-drop.md
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/assets/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/wrangler/e2e/multiworker-dev.test.ts
Labels: e2e

#8031 Support WebAssembly modules
  .changeset/wild-schools-kiss.md
  packages/vite-plugin-cloudflare/playground/prisma/.gitignore
  packages/vite-plugin-cloudflare/playground/prisma/__tests__/prisma.spec.ts
  packages/vite-plugin-cloudflare/playground/prisma/migrations/0001_create_user_table.sql
  packages/vite-plugin-cloudflare/playground/prisma/package.json
  packages/vite-plugin-cloudflare/playground/prisma/prisma/schema.prisma
  packages/vite-plugin-cloudflare/playground/prisma/src/index.ts
  packages/vite-plugin-cloudflare/playground/prisma/tsconfig.json
  packages/vite-plugin-cloudflare/playground/prisma/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/prisma/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/prisma/turbo.json
  packages/vite-plugin-cloudflare/playground/prisma/vite.config.ts
  packages/vite-plugin-cloudflare/playground/prisma/wrangler.toml
  packages/vite-plugin-cloudflare/playground/wasm/README.md
  packages/vite-plugin-cloudflare/playground/wasm/__tests__/wasm.spec.ts
  packages/vite-plugin-cloudflare/playground/wasm/package.json
  packages/vite-plugin-cloudflare/playground/wasm/src/index.ts
  packages/vite-plugin-cloudflare/playground/wasm/src/minimal.wasm
  packages/vite-plugin-cloudflare/playground/wasm/tsconfig.json
  packages/vite-plugin-cloudflare/playground/wasm/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/wasm/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/wasm/turbo.json
  packages/vite-plugin-cloudflare/playground/wasm/vite.config.ts
  packages/vite-plugin-cloudflare/playground/wasm/wrangler.toml
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/constants.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/runner-worker/module-runner.ts
  packages/vite-plugin-cloudflare/src/shared.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8078 clarify e2e refers to wrangler e2e tests in PR template
  .github/pull_request_template.md
Labels: no-changeset-required

#8083 Ensure the correct data types are sent in WebSocket messages from the client to the Worker
  .changeset/silver-bats-burn.md
  packages/vite-plugin-cloudflare/playground/websockets/__tests__/websockets.spec.ts
  packages/vite-plugin-cloudflare/playground/websockets/src/index.html
  packages/vite-plugin-cloudflare/playground/websockets/src/index.ts
  packages/vite-plugin-cloudflare/src/websockets.ts
Labels: vite-plugin

#8091 Omit files from public directory in Worker builds
  .changeset/hip-beans-hug.md
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Labels: vite-plugin

#8092 chore: fix up some changesets
  .changeset/kind-sloths-speak.md
  .changeset/stupid-turtles-hammer.md
  .changeset/wild-schools-kiss.md
Labels: skip-pr-description-validation, no-changeset-required

#8085 test: turn on Prisma playground tests for Vite plugin
  packages/vite-plugin-cloudflare/playground/__test-utils__/responses.ts
  packages/vite-plugin-cloudflare/playground/prisma/__tests__/prisma.spec.ts
  packages/vite-plugin-cloudflare/playground/prisma/__tests__/serve.ts
  packages/vite-plugin-cloudflare/playground/vitest-setup.ts
Labels: no-changeset-required, vite-plugin

#8027 Version Packages
  .changeset/c3-frameworks-update-7917.md
  .changeset/c3-frameworks-update-7918.md
  .changeset/c3-frameworks-update-7919.md
  .changeset/c3-frameworks-update-7978.md
  .changeset/c3-frameworks-update-8076.md
  .changeset/cool-monkeys-exercise.md
  .changeset/dependabot-update-8032.md
  .changeset/famous-coats-admire.md
  .changeset/hip-beans-hug.md
  .changeset/kind-sloths-speak.md
  .changeset/lazy-windows-provide.md
  .changeset/light-taxis-move.md
  .changeset/ninety-donuts-warn.md
  .changeset/plenty-birds-melt.md
  .changeset/poor-otters-drop.md
  .changeset/sharp-carrots-deliver.md
  .changeset/short-kids-hunt.md
  .changeset/silver-bats-burn.md
  .changeset/smooth-games-cover.md
  .changeset/spicy-eggs-tan.md
  .changeset/stupid-turtles-hammer.md
  .changeset/wet-glasses-rush.md
  .changeset/wild-schools-kiss.md
  .changeset/wise-pants-raise.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/unenv-preset/CHANGELOG.md
  packages/unenv-preset/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#7830 vite-plugin: update to use the new `@cloudflare/unenv-preset`
  .changeset/eleven-lemons-jump.md
  .changeset/kind-ducks-bake.md
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: vite-plugin

#8096 Version Packages
  .changeset/eleven-lemons-jump.md
  .changeset/kind-ducks-bake.md
  .changeset/large-badgers-deny.md
  .changeset/short-cars-allow.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
Labels: skip-pr-description-validation

#8098 Bugfix: npx --> pnpx for workers-shared
  packages/workers-shared/package.json
Labels: no-changeset-required

#8097 Version Packages
  .changeset/cuddly-jeans-check.md
  .changeset/fifty-hairs-drum.md
  .changeset/gold-frogs-rest.md
  .changeset/proud-days-study.md
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/e2e/c3-integration.test.ts
  packages/wrangler/package.json
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/vitest.setup.ts
Labels: e2e, skip-pr-description-validation

#8102 Pass through version tag as sentry release
  packages/workers-shared/asset-worker/src/index.ts
  packages/workers-shared/router-worker/src/index.ts
  packages/workers-shared/utils/sentry.ts
Labels: no-changeset-required

#7943 refactor: `wrangler deploy` to use`createCommand`
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/index.ts
Labels: e2e, no-changeset-required

#8099 Add vite plugin to bug report template
  .github/ISSUE_TEMPLATE/bug-template.yaml
Labels: no-changeset-required

#8079 Call `writeDeployConfig` in `writeBundle` rather than `builder.buildApp`
  .changeset/modern-cycles-build.md
  packages/vite-plugin-cloudflare/src/deploy-config.ts
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#8124 Remove debug ids from upload-sourcemaps.ts
  packages/workers-shared/scripts/upload-sourcemaps.ts
Labels: no-changeset-required

#8080 No longer call `next` in server middleware.
  .changeset/stale-zoos-drop.md
  packages/vite-plugin-cloudflare/playground/hot-channel/vite.config.ts
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/index.ts
Labels: vite-plugin

#7950 Add Worker Pipelines Binding to Miniflare
  .changeset/slimy-otters-rush.md
  fixtures/vitest-pool-workers-examples/README.md
  fixtures/vitest-pool-workers-examples/pipelines/README.md
  fixtures/vitest-pool-workers-examples/pipelines/src/env.d.ts
  fixtures/vitest-pool-workers-examples/pipelines/src/index.ts
  fixtures/vitest-pool-workers-examples/pipelines/src/tsconfig.json
  fixtures/vitest-pool-workers-examples/pipelines/test/env.d.ts
  fixtures/vitest-pool-workers-examples/pipelines/test/pipeline-send-integration-self.test.ts
  fixtures/vitest-pool-workers-examples/pipelines/test/pipeline-send-unit.test.ts
  fixtures/vitest-pool-workers-examples/pipelines/test/tsconfig.json
  fixtures/vitest-pool-workers-examples/pipelines/tsconfig.json
  fixtures/vitest-pool-workers-examples/pipelines/vitest.config.ts
  fixtures/vitest-pool-workers-examples/pipelines/wrangler.toml
  packages/miniflare/README.md
  packages/miniflare/src/plugins/index.ts
  packages/miniflare/src/plugins/pipelines/index.ts
  packages/miniflare/src/workers/pipelines/pipeline.worker.ts
  packages/miniflare/test/plugins/pipelines/index.spec.ts
  packages/wrangler/e2e/dev-with-resources.test.ts
  packages/wrangler/src/dev/miniflare.ts
Labels: miniflare, e2e

#8132 Provide unique sentry tag+release for asset-worker and routr-worker
  packages/workers-shared/package.json
Labels: no-changeset-required

#8107 Version Packages
  .changeset/early-melons-deny.md
  .changeset/eighty-panthers-rule.md
  .changeset/few-bobcats-brake.md
  .changeset/gentle-tables-guess.md
  .changeset/gorgeous-papayas-trade.md
  .changeset/kind-spiders-hunt.md
  .changeset/lucky-humans-glow.md
  .changeset/modern-cycles-build.md
  .changeset/odd-months-crash.md
  .changeset/orange-rockets-leave.md
  .changeset/rich-pots-mate.md
  .changeset/rotten-eyes-boil.md
  .changeset/sharp-numbers-search.md
  .changeset/slimy-otters-rush.md
  .changeset/stale-zoos-drop.md
  .changeset/startup-profiling.md
  .changeset/tidy-keys-sin.md
  .changeset/wet-starfishes-drum.md
  .changeset/wicked-pets-jump.md
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#8118 fix node.js compat module resolution
  .changeset/wild-days-jog.md
  packages/vite-plugin-cloudflare/e2e/README.md
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/.gitignore
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/README.md
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/api/index.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/eslint.config.js
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/index.html
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/public/vite.svg
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/src/App.css
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/src/App.tsx
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/src/assets/react.svg
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/src/index.css
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/src/main.tsx
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/src/vite-env.d.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/tsconfig.app.json
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/tsconfig.json
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/tsconfig.node.json
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/tsconfig.worker.json
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/vite.config.ts
  packages/vite-plugin-cloudflare/e2e/fixtures/basic/wrangler.toml
  packages/vite-plugin-cloudflare/e2e/global-setup.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/vite-plugin-cloudflare/e2e/tsconfig.json
  packages/vite-plugin-cloudflare/e2e/vitest.config.js
  packages/vite-plugin-cloudflare/e2e/vitest.config.ts
  packages/vite-plugin-cloudflare/package.json
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  packages/vite-plugin-cloudflare/turbo.json
  pnpm-lock.yaml
  turbo.json
Labels: vite-plugin

#8141 [vite-plugin-cloudflare] simplify playground playwright install
  packages/vite-plugin-cloudflare/playground/package.json
Labels: no-changeset-required

#8137 Version Packages
  .changeset/unlucky-actors-swim.md
  .changeset/wild-days-jog.md
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation

#8133 Bump toucan version in workers-shared
  package.json
  packages/workers-shared/package.json
  packages/workers-shared/utils/sentry.ts
  patches/toucan-js@4.0.0.patch
  pnpm-lock.yaml
Labels: no-changeset-required

#8036 Send alert to chat on release failure
  .github/workflows/changesets.yml
  .gitignore
  packages/devprod-status-bot/src/index.ts
  packages/devprod-status-bot/worker-configuration.d.ts
  tools/deployments/__tests__/deploy-non-npm-packages.test.ts
  tools/deployments/alert-on-error.ts
  tools/deployments/deploy-non-npm-packages.ts
Labels: no-changeset-required

#8142 Version Packages
  .changeset/great-walls-bow.md
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
Labels: skip-pr-description-validation

#8144 Version Packages
  .changeset/sharp-dogs-relate.md
  packages/workers.new/CHANGELOG.md
  packages/workers.new/package.json
Labels: skip-pr-description-validation

#8146 Version Packages
  .changeset/spicy-ducks-push.md
  packages/devprod-status-bot/CHANGELOG.md
  packages/devprod-status-bot/package.json
  packages/solarflare-theme/CHANGELOG.md
  packages/solarflare-theme/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/workers.new/CHANGELOG.md
  packages/workers.new/package.json
Labels: skip-pr-description-validation

#8056 remove unused function/imports in wrangler entry
  packages/wrangler/bin/wrangler.js
Labels: no-changeset-required

#8167 Reduce C3 CI runs
  .github/pr-labeler.config.yml
  .github/workflows/README.md
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
Labels: no-changeset-required

#7687 fix: pages deploy fails with git rev-parse error on new repo
  .changeset/loud-ants-prove.md
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/pages/deploy.ts
Labels: caretaking

#8169 Reduce CI concurrency
  .github/workflows/test-and-check.yml
Labels: no-changeset-required

#8174 Update dependencies
  package.json
  packages/cloudflare-workers-bindings-extension/package.json
  packages/create-cloudflare/package.json
  packages/devprod-status-bot/package.json
  packages/eslint-config-worker/package.json
  packages/miniflare/package.json
  packages/vitest-pool-workers/package.json
  packages/workers-editor-shared/package.json
  packages/workers-playground/package.json
  pnpm-lock.yaml
Labels: no-changeset-required, c3-e2e

#8165 refactor nodejs-hybrid-app tests
  fixtures/nodejs-hybrid-app/src/index.ts
Labels: no-changeset-required

#8177 More dependency updates
  package.json
  packages/edge-preview-authenticated-proxy/package.json
  packages/playground-preview-worker/package.json
  packages/workers-shared/package.json
  pnpm-lock.yaml
  turbo/generators/config.ts
  turbo/generators/templates/.eslintrc.js.hbs
  turbo/generators/templates/package.json.hbs
  turbo/generators/templates/tsconfig.json.hbs
Labels: skip-pr-description-validation, c3-e2e

#8148 Version Packages
  .changeset/dependabot-update-8171.md
  .changeset/fresh-doors-cheat.md
  .changeset/good-plants-stare.md
  .changeset/hot-ravens-roll.md
  .changeset/loud-ants-prove.md
  .changeset/olive-gifts-flash.md
  .changeset/wild-kiwis-behave.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/playground-preview-worker/CHANGELOG.md
  packages/playground-preview-worker/package.json
  packages/turbo-r2-archive/CHANGELOG.md
  packages/turbo-r2-archive/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: skip-pr-description-validation, c3-e2e

#8184 Update users in status bot
  packages/devprod-status-bot/src/index.ts
Labels: no-changeset-required

#8147 Add job summaries for workers-shared deployments
  .github/workflows/workers-shared-deploy-production.yml
  .github/workflows/workers-shared-deploy-staging.yml
Labels: no-changeset-required

#8110 Pbd/update contrib guide
  CONTRIBUTING.md
  package.json
Labels: skip-pr-description-validation, no-changeset-required

#8176 fix: refactor Node.js compat support to ensure all polyfills are pre-bundled before the first request
  .changeset/ninety-phones-tell.md
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  packages/vite-plugin-cloudflare/src/utils.ts
Labels: vite-plugin

#8194 Always use labels for E2E
  .github/pr-labeler.config.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/e2e.yml
Labels: skip-pr-description-validation

#8190 Version Packages
  .changeset/ninety-phones-tell.md
  .changeset/soft-drinks-hug.md
  .changeset/twenty-chefs-lick.md
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
Labels: e2e, skip-pr-description-validation, c3-e2e

#8175 fix(wrangler): ignore comments when splitting sql into statements
  .changeset/ten-falcons-applaud.md
  fixtures/vitest-pool-workers-examples/d1/migrations/0000_initial.sql
  packages/wrangler/src/__tests__/d1/splitter.test.ts
  packages/wrangler/src/d1/splitter.ts
Labels: d1, e2e

#8217 chore(vite-plugin): skip node_compat test for now due to flakiness
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
Labels: skip-pr-description-validation

#8204 Version Packages
  .changeset/big-pillows-cough.md
  .changeset/ten-falcons-applaud.md
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8238 Version Packages
  .changeset/green-hornets-camp.md
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
Labels: e2e, c3-e2e

#8240 fix: remove unnecessary flags passed to `create-next-app` when creating Next.js apps in experimental mode
  .changeset/four-mammals-report.md
  packages/create-cloudflare/templates-experimental/next/c3.ts
Labels: c3-e2e

#8215 fix(create-cloudflare): make DNS poling copy more user friendly
  .changeset/large-hotels-create.md
  packages/create-cloudflare/src/helpers/poll.ts
Labels: c3-e2e

#8195 Adds Python `wrangler dev` test to verify `print` works.
  packages/wrangler/e2e/dev.test.ts
Labels: e2e, no-changeset-required

#8239 fix(vitest-pool-workers): fetchMock support on auxiliary worker
  .changeset/huge-pears-tickle.md
  packages/miniflare/src/plugins/core/index.ts
  packages/miniflare/test/index.spec.ts
Labels: e2e

#8252 Use print in Python console.log test
  packages/wrangler/e2e/dev.test.ts
Labels: e2e, no-changeset-required

#8191 fix(hybrid-nodejs-compat): inject modules only once
  .changeset/beige-buses-poke.md
  packages/wrangler/src/__tests__/hybrid-nodejs-compat.test.ts
  packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Labels: e2e

#8243 fix(create-cloudflare): Ensure we exit the process on "SIGINT" and "SIGTERM"
  .changeset/ripe-socks-stay.md
  packages/create-cloudflare/src/cli.ts
  packages/create-cloudflare/src/metrics.ts
Labels: c3-e2e

#8253 feat(wrangler): support `--cwd` cli argument
  .changeset/khaki-years-act.md
  packages/wrangler/src/__tests__/ai.test.ts
  packages/wrangler/src/__tests__/cert.test.ts
  packages/wrangler/src/__tests__/cloudchamber/create.test.ts
  packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
  packages/wrangler/src/__tests__/cloudchamber/delete.test.ts
  packages/wrangler/src/__tests__/cloudchamber/images.test.ts
  packages/wrangler/src/__tests__/cloudchamber/list.test.ts
  packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
  packages/wrangler/src/__tests__/d1/d1.test.ts
  packages/wrangler/src/__tests__/deployments.test.ts
  packages/wrangler/src/__tests__/docs.test.ts
  packages/wrangler/src/__tests__/hyperdrive.test.ts
  packages/wrangler/src/__tests__/index.test.ts
  packages/wrangler/src/__tests__/kv.test.ts
  packages/wrangler/src/__tests__/mtls-certificates.test.ts
  packages/wrangler/src/__tests__/pages/deploy.test.ts
  packages/wrangler/src/__tests__/pages/pages.test.ts
  packages/wrangler/src/__tests__/pipelines.test.ts
  packages/wrangler/src/__tests__/pubsub.test.ts
  packages/wrangler/src/__tests__/queues.test.ts
  packages/wrangler/src/__tests__/r2.test.ts
  packages/wrangler/src/__tests__/secret.test.ts
  packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
  packages/wrangler/src/__tests__/versions/versions.help.test.ts
  packages/wrangler/src/__tests__/worker-namespace.test.ts
  packages/wrangler/src/__tests__/workflows.test.ts
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/generate/index.ts
  packages/wrangler/src/index.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/yargs-types.ts
Labels: skip-pr-description-validation

#8259 Pbd/release-fixups
  .changeset/beige-crews-wash.md
  packages/wrangler/e2e/dev.test.ts
  turbo.json
Labels: e2e, skip-pr-description-validation, no-changeset-required

#8242 Version Packages
  .changeset/beige-buses-poke.md
  .changeset/beige-crews-wash.md
  .changeset/c3-frameworks-update-8233.md
  .changeset/fluffy-fans-bake.md
  .changeset/four-mammals-report.md
  .changeset/huge-pears-tickle.md
  .changeset/khaki-years-act.md
  .changeset/large-hotels-create.md
  .changeset/quick-shoes-jump.md
  .changeset/ripe-socks-stay.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/miniflare/CHANGELOG.md
  packages/miniflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/workers-shared/CHANGELOG.md
  packages/workers-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8264 fixes #8065
  .changeset/silver-flowers-notice.md
  packages/create-cloudflare/src/__tests__/git.test.ts
  packages/create-cloudflare/src/git.ts
Labels: e2e, c3-e2e

#8257 Fix deployment summary
  .github/workflows/workers-shared-deploy-production.yml
  .github/workflows/workers-shared-deploy-staging.yml
Labels: skip-pr-description-validation, no-changeset-required

#8206 Add support for binding to named entrypoints in the same Worker
  .changeset/bitter-teeth-think.md
  packages/vite-plugin-cloudflare/playground/node-compat/worker-basic/index.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-basic/wrangler.toml
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/__tests__/same-worker-service-bindings.spec.ts
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/package.json
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/src/index.ts
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/tsconfig.json
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/turbo.json
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/vite.config.ts
  packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/wrangler.toml
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8266 Make `builder.buildApp` overridable
  .changeset/good-rooms-sneeze.md
  packages/vite-plugin-cloudflare/playground/custom-build-app/__tests__/custom-build-app.spec.ts
  packages/vite-plugin-cloudflare/playground/custom-build-app/package.json
  packages/vite-plugin-cloudflare/playground/custom-build-app/src/index.ts
  packages/vite-plugin-cloudflare/playground/custom-build-app/tsconfig.json
  packages/vite-plugin-cloudflare/playground/custom-build-app/tsconfig.node.json
  packages/vite-plugin-cloudflare/playground/custom-build-app/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/custom-build-app/turbo.json
  packages/vite-plugin-cloudflare/playground/custom-build-app/vite.config.ts
  packages/vite-plugin-cloudflare/playground/custom-build-app/wrangler.toml
  packages/vite-plugin-cloudflare/src/index.ts
  pnpm-lock.yaml
Labels: vite-plugin

#8268 chore: use main testing account on c3 e2e tests
  .github/workflows/c3-e2e-quarantine.yml
  .github/workflows/c3-e2e.yml
  .github/workflows/e2e-project-cleanup.yml
  packages/create-cloudflare/e2e-tests/cli.test.ts
Labels: no-changeset-required, c3-e2e

#8281 Fix changeset bump
  .changeset/quick-singers-stand.md
Labels: skip-pr-description-validation

#8265 Version Packages
  .changeset/bitter-teeth-think.md
  .changeset/blue-foxes-notice.md
  .changeset/good-rooms-sneeze.md
  .changeset/quick-singers-stand.md
  .changeset/seven-flies-repair.md
  .changeset/silver-flowers-notice.md
  .changeset/vast-trains-joke.md
  .changeset/weak-chairs-tap.md
  packages/create-cloudflare/CHANGELOG.md
  packages/create-cloudflare/package.json
  packages/pages-shared/CHANGELOG.md
  packages/pages-shared/package.json
  packages/vite-plugin-cloudflare/CHANGELOG.md
  packages/vite-plugin-cloudflare/package.json
  packages/vitest-pool-workers/CHANGELOG.md
  packages/vitest-pool-workers/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#8232 fix: remove extra config files that are generated by c3 with `--existing-script `
  .changeset/sixty-spoons-unite.md
  packages/create-cloudflare/e2e-tests/cli.test.ts
  packages/create-cloudflare/templates/pre-existing/c3.ts
  packages/create-cloudflare/templates/pre-existing/js/wrangler.jsonc
Labels: e2e, c3-e2e

#8284 Add dist-tag input to hotfix action
  .github/workflows/hotfix-release.yml
  CONTRIBUTING.md
Labels: skip-pr-description-validation

#8285 No more `--dry-run`
  .github/workflows/hotfix-release.yml
Labels: skip-pr-description-validation

#8294 Provide publish token to hotfix action
  .github/workflows/hotfix-release.yml
Labels: skip-pr-description-validation

#8205 Use today's date as the default starter playground compat date
  .changeset/brown-tools-dream.md
  packages/workers-playground/generate-default-hashes.ts
  packages/workers-playground/src/QuickEditor/QuickEditor.tsx
  packages/workers-playground/src/QuickEditor/defaultHashes.ts
  packages/workers-playground/src/QuickEditor/useDraftWorker.ts
Labels: preview:workers-playground

#8290 C3: ensure that git commits are generated
  .changeset/five-streets-act.md
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/src/__tests__/git.test.ts
  packages/create-cloudflare/src/git.ts
Labels: c3-e2e

#8197 create-cloudflare: add types/autocomplete for Python projects
  .changeset/salty-bugs-begin.md
  packages/create-cloudflare/templates/hello-world/c3.ts
  packages/create-cloudflare/templates/hello-world/py/.python-version
  packages/create-cloudflare/templates/hello-world/py/README.md
  packages/create-cloudflare/templates/hello-world/py/pyproject.toml
  packages/create-cloudflare/templates/hello-world/py/uv.lock
Labels: c3-e2e

#8201 fix: interactively list Cloudchamber deployments using labels
  .changeset/public-groups-thank.md
  packages/wrangler/src/cloudchamber/cli/deployments.ts
Labels: e2e

#8302 chore: include `templates` directory in wrangler"s `check:type` script
  packages/wrangler/package.json
  packages/wrangler/templates/pages-dev-pipeline.ts
  packages/wrangler/templates/tsconfig.json
Labels: no-changeset-required

#8305 fix(unenv-preset) add missing json import type
  .prettierignore
  packages/unenv-preset/src/preset.ts
Labels: no-changeset-required

#8306 chore: cleanup e2e hyperdrive configs
  packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
  tools/e2e/common.ts
  tools/e2e/e2eCleanup.ts
Labels: e2e, no-changeset-required

#8013 C3: add vite+react templates with tests
  .changeset/nine-states-call.md
  packages/create-cloudflare/e2e-tests/frameworks.test.ts
  packages/create-cloudflare/e2e-tests/helpers.ts
  packages/create-cloudflare/e2e-tests/workers.test.ts
  packages/create-cloudflare/package.json
  packages/create-cloudflare/src/frameworks/__tests__/index.test.ts
  packages/create-cloudflare/src/frameworks/index.ts
  packages/create-cloudflare/src/helpers/files.ts
  packages/create-cloudflare/src/helpers/packageManagers.ts
  packages/create-cloudflare/src/templates.ts
  packages/create-cloudflare/templates-experimental/angular/c3.ts
  packages/create-cloudflare/templates-experimental/docusaurus/c3.ts
  packages/create-cloudflare/templates-experimental/hono/c3.ts
  packages/create-cloudflare/templates-experimental/qwik/c3.ts
  packages/create-cloudflare/templates-experimental/react/c3.ts
  packages/create-cloudflare/templates-experimental/react/js/api/index.js
  packages/create-cloudflare/templates-experimental/react/js/src/App.jsx
  packages/create-cloudflare/templates-experimental/react/js/src/assets/Cloudflare_Logo.svg
  packages/create-cloudflare/templates-experimental/react/js/wrangler.json
  packages/create-cloudflare/templates-experimental/react/ts/api/index.ts
  packages/create-cloudflare/templates-experimental/react/ts/src/App.tsx
  packages/create-cloudflare/templates-experimental/react/ts/src/assets/Cloudflare_Logo.svg
  packages/create-cloudflare/templates-experimental/react/ts/tsconfig.worker.json
  packages/create-cloudflare/templates-experimental/react/ts/wrangler.json
  packages/create-cloudflare/templates/angular/c3.ts
  packages/create-cloudflare/templates/docusaurus/c3.ts
  packages/create-cloudflare/templates/hono/c3.ts
  packages/create-cloudflare/templates/next/c3.ts
  packages/create-cloudflare/templates/qwik/c3.ts
  packages/create-cloudflare/turbo.json
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  pnpm-lock.yaml
Labels: c3-e2e

#8307 fix(unenv-preset): bundle index.mjs
  packages/unenv-preset/build.config.ts
Labels: no-changeset-required
