Repository cloudflare/workers-sdk, pull requests merged in 2025-08, with the labels that each got.

#9556 fix(vite-plugin-cloudflare): ensure cross-process service bindings route through asset worker
  .changeset/eight-buckets-bathe.md
  .changeset/icy-lands-build.md
  fixtures/dev-registry/assets/example.txt
  fixtures/dev-registry/tests/dev-registry.test.ts
  fixtures/dev-registry/vite.worker-entrypoint-b.config.ts
  fixtures/dev-registry/wrangler.service-worker.jsonc
  fixtures/dev-registry/wrangler.worker-entrypoint-a.jsonc
  fixtures/dev-registry/wrangler.worker-entrypoint-b.jsonc
  packages/miniflare/src/index.ts
  packages/miniflare/src/plugins/core/index.ts
  packages/vite-plugin-cloudflare/src/constants.ts
  packages/vite-plugin-cloudflare/src/miniflare-options.ts
  packages/vite-plugin-cloudflare/src/vite-proxy-worker/index.ts
  packages/vite-plugin-cloudflare/tsup.config.ts
Labels: e2e

#10174 make sure we run wrangler e2e tests in nested folders
  pnpm-lock.yaml
  tools/e2e/runIndividualE2EFiles.ts
  tools/package.json
Labels: no-changeset-required

#10218 fix changeset
  .changeset/silly-things-walk.md
Labels: skip-pr-description-validation, skip-v3-pr

#10122 fix `startWorker` not respecting `auth` options for remote bindings
  .changeset/sdw-auth.md
  .changeset/whole-masks-sniff.md
  packages/wrangler/e2e/dev-env.test.ts
  packages/wrangler/e2e/start-worker-auth-opts.test.ts
  packages/wrangler/src/api/remoteBindings/index.ts
  packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
  packages/wrangler/src/api/startDevWorker/types.ts
  packages/wrangler/src/cfetch/index.ts
  packages/wrangler/src/cfetch/internal.ts
  packages/wrangler/src/dev/create-worker-preview.ts
  packages/wrangler/src/dev/remote.ts
Labels: skip-v3-pr

#10250 Revert "chore: implement local browser rendering /v1/session endpoint"
  .changeset/petite-paws-allow.md
  fixtures/browser-rendering/src/playwright.ts
  fixtures/browser-rendering/src/puppeteer.ts
  fixtures/browser-rendering/test/index.spec.ts
  packages/miniflare/package.json
  packages/miniflare/src/index.ts
  packages/miniflare/src/workers/browser-rendering/binding.worker.ts
  packages/miniflare/test/plugins/browser/index.spec.ts
  pnpm-lock.yaml
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10232 validate id in `wrangler containers delete` and also include container API calls in WRANGLER_LOG=debug
  .changeset/blue-seas-visit.md
  .changeset/pink-heads-help.md
  packages/containers-shared/src/client/core/OpenAPI.ts
  packages/containers-shared/src/client/core/request.ts
  packages/containers-shared/src/types.ts
  packages/wrangler/src/__tests__/containers/delete.test.ts
  packages/wrangler/src/cloudchamber/common.ts
  packages/wrangler/src/containers/containers.ts
Labels: skip-v3-pr

#10259 ensure that `maybeStartOrUpdateRemoteProxySession` considers the potential account_id from the users' wrangler config
  .changeset/calm-gifts-hear.md
  fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
  packages/wrangler/e2e/dev.test.ts
  packages/wrangler/e2e/helpers/fetch-text.ts
  packages/wrangler/e2e/remote-binding/wrangler-remote-resources.test.ts
  packages/wrangler/src/api/remoteBindings/index.ts
Labels: skip-v3-pr

#10258 containers: add option to allow all tiers
  .changeset/famous-coats-chew.md
  packages/containers-shared/src/types.ts
  packages/wrangler/src/__tests__/containers/config.test.ts
  packages/wrangler/src/containers/config.ts
Labels: skip-v3-pr

#10060 refactor(wrangler): switch `getPlatformProxy()` to use Miniflare's dev registry implementation
  .changeset/short-humans-nail.md
  fixtures/dev-registry/tests/dev-registry.test.ts
  fixtures/dev-registry/tests/tsconfig.json
  fixtures/dev-registry/vite.worker-entrypoint-a.config.ts
  fixtures/dev-registry/vite.worker-entrypoint-b.config.ts
  fixtures/dev-registry/workers/worker-entrypoint.ts
  fixtures/dev-registry/wrangler.durable-object.jsonc
  fixtures/dev-registry/wrangler.external-durable-object.jsonc
  fixtures/dev-registry/wrangler.internal-durable-object.jsonc
  fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
  packages/wrangler/src/api/integrations/platform/index.ts
  packages/wrangler/src/api/integrations/platform/services.ts
Labels: skip-v3-pr

#10270 fix security alerts to avoid being in the same notification thread
  .changeset/crazy-experts-wonder.md
  packages/devprod-status-bot/src/index.ts
Labels: skip-v3-pr, status-bot

#10279 test: relax the pretty-print error test
  packages/miniflare/test/plugins/core/errors/index.spec.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10283 feat(wrangler): support long branch names in preview alias generation
  .changeset/lucky-hornets-listen.md
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-v3-pr

#10280 test: reduce flakes on pages-dev e2e tests
  packages/wrangler/e2e/pages-dev.test.ts
Labels: no-changeset-required

#9940 Add the nodejs_als flag for the svelte template
  .changeset/bright-snails-knock.md
  packages/create-cloudflare/templates/svelte/pages/templates/wrangler.jsonc
  packages/create-cloudflare/templates/svelte/workers/templates/wrangler.jsonc
Labels: skip-v3-pr

#10139 Remove mention of cf-requirements when Python Worker is enabled
  .changeset/brown-knives-sort.md
  packages/wrangler/src/deployment-bundle/guess-worker-format.ts
Labels: skip-v3-pr

#10311 skip flaky browser render test on Windows
  packages/miniflare/test/plugins/browser/index.spec.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10288 fix(wrangler) remove putQueue call when deploying a worker with queue producer binding
  .changeset/chatty-pens-sniff.md
  .github/workflows/c3-e2e.yml
  packages/miniflare/test/plugins/email/index.spec.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/triggers/deploy.ts
Labels: skip-v3-pr

#10332 Update cold-wasps-tease.md
  .changeset/cold-wasps-tease.md
Labels: skip-pr-description-validation, skip-v3-pr

#10347 run changeset versioning and release on Node 22
  .changeset/salty-bats-drop.md
  .github/workflows/changesets.yml
Labels: skip-pr-description-validation, skip-v3-pr

#10315 add rollout_active_grace_period to container config
  .changeset/poor-hoops-cover.md
  packages/containers-shared/src/client/index.ts
  packages/containers-shared/src/client/models/Application.ts
  packages/containers-shared/src/client/models/ApplicationRolloutActiveGracePeriod.ts
  packages/containers-shared/src/client/models/CreateApplicationRequest.ts
  packages/containers-shared/src/client/models/ModifyApplicationRequestBody.ts
  packages/containers-shared/src/types.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/containers/config.test.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/config/environment.ts
  packages/wrangler/src/config/validation.ts
  packages/wrangler/src/containers/config.ts
  packages/wrangler/src/containers/deploy.ts
Labels: skip-v3-pr

#10356 Bugfix: Update regex for valid branch names
  .changeset/giant-ghosts-flow.md
  packages/wrangler/src/__tests__/versions/versions.upload.test.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-v3-pr

#10244 Add e2e tests for programmatic remote bindings api
  packages/wrangler/e2e/remote-binding/remote-bindings-api.test.ts
  packages/wrangler/src/api/remoteBindings/index.ts
Labels: no-changeset-required

#9652 re-enable vite-plugin remote bindings e2e tests for dev mode
  packages/vite-plugin-cloudflare/e2e/basic.test.ts
  packages/vite-plugin-cloudflare/e2e/helpers.ts
  packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts
Labels: e2e, no-changeset-required, skip-v3-pr

#10314 add information about dashboard configuration differences on deploys
  .changeset/solid-sloths-drop.md
  fixtures/get-platform-proxy/custom-toml/path/test.toml
  fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
  packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
  packages/wrangler/src/__tests__/config/configuration.test.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/__tests__/deploy.test.ts
  packages/wrangler/src/__tests__/deploy/config-diffs.test.ts
  packages/wrangler/src/__tests__/helpers/write-wrangler-config.ts
  packages/wrangler/src/__tests__/pages/__snapshots__/deploy.test.ts.snap
  packages/wrangler/src/api/dev.ts
  packages/wrangler/src/cloudchamber/helpers/diff.ts
  packages/wrangler/src/config/index.ts
  packages/wrangler/src/core/register-yargs-command.ts
  packages/wrangler/src/deploy/config-diffs.ts
  packages/wrangler/src/deploy/deploy.ts
  packages/wrangler/src/deploy/index.ts
  packages/wrangler/src/dev.ts
  packages/wrangler/src/experimental-flags.ts
  packages/wrangler/src/init.ts
  packages/wrangler/src/pages/dev.ts
  packages/wrangler/src/versions/upload.ts
Labels: skip-v3-pr

#10284 Backport of 10280 - test: reduce flakes on pages-dev e2e tests
  packages/wrangler/e2e/pages-dev.test.ts
Labels: e2e, skip-pr-description-validation, no-changeset-required, v3-backport

#10407 set default for rollout_active_grace_period
  .changeset/hungry-falcons-brush.md
  packages/containers-shared/src/types.ts
  packages/wrangler/src/__tests__/containers/deploy.test.ts
  packages/wrangler/src/containers/config.ts
Labels: skip-v3-pr

#10409 update codeowners for containers-shared
  CODEOWNERS
Labels: no-changeset-required

#10398 v3 backport for #10396
  packages/wrangler/src/config/environment.ts
Labels: skip-pr-description-validation, no-changeset-required, skip-v3-pr

#10396 hide and mark `service.environments` as deprecated
  packages/wrangler/src/config/environment.ts
Labels: no-changeset-required

#10355 v3 Maintenance Release
  .changeset/chatty-pens-sniff.md
  .changeset/fifty-tires-kiss.md
  .changeset/shy-coats-drum.md
  packages/workflows-shared/CHANGELOG.md
  packages/workflows-shared/package.json
  packages/wrangler/CHANGELOG.md
  packages/wrangler/package.json
Labels: e2e, c3-e2e

#9991 V3 Backport [#9990]: Fix startup profiling with sourcemaps enabled
  .changeset/yummy-parents-remain.md
  packages/wrangler/src/__tests__/startup-profiling.test.ts
  packages/wrangler/src/check/commands.ts
Labels: skip-pr-description-validation, skip-v3-pr, v3-backport

#10424 Expose global flags from `experimental_getWranglerCommands()`
  .changeset/dirty-students-scream.md
  .changeset/nervous-goats-sniff.md
  packages/playground-preview-worker/package.json
  packages/turbo-r2-archive/package.json
  packages/wrangler/src/__tests__/experimental-commands-api.test.ts
  packages/wrangler/src/__tests__/metrics.test.ts
  packages/wrangler/src/experimental-commands-api.ts
  packages/wrangler/src/index.ts
Labels: skip-v3-pr

#10461 make dns test more robust
  packages/wrangler/e2e/unenv-preset/worker/index.ts
Labels: no-changeset-required

#10433 Update curvy-feet-swim.md
  .changeset/curvy-feet-swim.md
Labels: skip-pr-description-validation, skip-v3-pr

#10427 Simplify ENOENT debug logs for `.env` files
  .changeset/green-bugs-shout.md
  packages/wrangler/src/__tests__/dev.test.ts
  packages/wrangler/src/config/dot-env.ts
Labels: skip-v3-pr

#10477 fix outdated Remix template url being used
  .changeset/shiny-maps-type.md
  packages/create-cloudflare/templates/remix/pages/c3.ts
  packages/create-cloudflare/templates/remix/workers/c3.ts
Labels: skip-v3-pr

#10482 Pass the `compatibility_date` and `compatibility_flags` to the `unenv` preset
  .changeset/shaky-melons-help.md
  packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-https/https.spec.ts
  packages/vite-plugin-cloudflare/playground/node-compat/package.json
  packages/vite-plugin-cloudflare/playground/node-compat/tsconfig.worker.json
  packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-https.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-https/index.ts
  packages/vite-plugin-cloudflare/playground/node-compat/worker-https/wrangler.jsonc
  packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
  packages/vite-plugin-cloudflare/src/index.ts
  packages/vite-plugin-cloudflare/src/node-js-compat.ts
  packages/vite-plugin-cloudflare/src/nodejs-compat.ts
  packages/vite-plugin-cloudflare/src/plugin-config.ts
Labels: vite-plugin

#10431 remove node:module polyfills
  .changeset/cruel-terms-smell.md
  packages/unenv-preset/package.json
  packages/unenv-preset/src/preset.ts
  packages/unenv-preset/src/runtime/node/module.ts
  packages/wrangler/e2e/unenv-preset/worker/index.ts
  pnpm-lock.yaml
Labels: skip-v3-pr
